### ISSUE TITLE
Pie Chart crashes

### ISSUE THREAD

**Issue by mbch** [visualize-admin/visualization-tool#100]
Example:
Cube markusb010
(Next)
On Step 2 a columns chart is displayed. 
If you switch to Pie it crashes

I guess there is to many data to be displayed in the Pie Chart – but in this case it might be better to make the Pie Chart Selection “unselectable”

**Comment by herrstucki** [comment]
This is the same kind of error as in #97. I'm closing this issue since it's described in sufficient detail there.
