### ISSUE TITLE
Show Dataloading Spinner earlier when Loading Larger Datasets

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1000]
**Is your enhancement related to a problem? Please describe.**
Larger data sets take a while to load. To ensure that users do not leave the page, we would like to show the data loading spinner right away. Currently there is a ca. 10 second delay. Also see: https://github.com/visualize-admin/visualization-tool/discussions/996#discussioncomment-5288393

**Describe the solution you'd like**
Show the Data Loading Spinner as soon as the user selects the data set. 

**Describe alternatives you've considered**
Showing a banner or adjusting the text below the spinner to inform users that longer data sets may require more time to load

**Usecases and impact**
This would be beneficial as users are actively informed that something is happening on the page right away. At the moment it is assumed that users think their interactions have no affect. 

**Additional context**
See discussion here: https://github.com/visualize-admin/visualization-tool/discussions/996

**Comment by ptbrowne** [comment]
@sosiology Could you add an example of dataset causing a problem ?

**Comment by sosiology** [comment]
The "Stapfer-Enquête" data set is a good example. I guess the issue is more noticable, after the table preview when the user clicks "start a visualization" after the table preview loads

**Comment by sosiology** [comment]
Thanks for implementing this @bprusinowski. 
I had a look and it feels as if the spinner is shown earlier when the user selects "start a visualization". In addition, you added the text "large datasets may take more than 30seconds to load", are these assumptions correct? or were additional changes implement in the background? thanks in advance for your feedback

**Comment by bprusinowski** [comment]
Yes, the spinner is shown when we switch from dataset preview to chart editing page which wasn't the case before. Also as mentioned there is an additional text showing after 7.5s to mention that it might take longer for large datasets to be fetched.
