### ISSUE TITLE
Support Ordinal Dimension Values

### ISSUE THREAD

**Issue by herrstucki** [visualize-admin/visualization-tool#101]
We should support pre-defined ordering of dimension values in Ordinal Dimensions. These are expressed with `schema:position` as defined in https://github.com/zazuko/rdf-cube-schema/blob/master/documentation/visualization.md#qudtscaletype

To do: find all places where this is relevant.

**Comment by ortnever** [comment]
We also should have a solution to display nominal values in an other order than alphabetical order. For example, it should be possible to display the cantons according to their official ID (BFS list). 1 = Zürich, 2 = Bern etc.
https://www.bfs.admin.ch/bfs/fr/home/statistiques/catalogues-banques-donnees/cartes.assetdetail.453856.html

Maybe a quickly solution for ordinal values: If ordinal values cannot be processed via schema:position in a first instance, would it be possible to work around the problem by assigning IDs in the expected order (e.g. 1. Excellent, 2. Very good. 3. Good etc.).

**Comment by herrstucki** [comment]
In my opinion, if a dimension is supposed to be ordered (like cantons, ratings, age groups etc.), it must be declared as ordinal and schema:position needs to be present.

1. Ordering by ID alone is not very reliable and can't be explained to the user well because the IDs never show up.
2. Alphabetical ordering does not work for ordinal values like "< 5%", "5 – 10%", "> 10%" or even something like where we have IDs as "1", "2", "10" (the order would be 1, 10, 2 because lexical ordering doesn't "understand" numbers – and we can't treat IDs as numbers because they might not be numbers).

**Comment by ortnever** [comment]
If we declare the list of cantons as ordinal values with a predefined order (schema:position). Will we be able to choose in Visualize to display the list either in the pre-defined ordering or in alphabetical ordering?

**Comment by ptbrowne** [comment]
> To do: find all places where this is relevant.

At first glance, before diving in more :

- Editor
  - Filters on the left during creation
  - Filters on the right during creation
- Published chart
  - Legend
  - Interactive filters

@ortnever Do you see other places where the ordering could be relevant for you ?

> Will we be able to choose in Visualize to display the list either in the pre-defined ordering or in alphabetical ordering?

I think the question from our side is "Do you need visualize to be able to do this ?". Personally I think that as a user it would help to be able to re-order the values according to alphabetical order, particularly for cantons.  It seems to me that for Cantons, the id ordering is a bit difficult to navigate around from a user perspective (I am not Swiss so maybe this is just that I am not accustomed to this ordering).

**Comment by herrstucki** [comment]
I agree: if there's a defined order in a dimension it should be used as default but users should be able to override it.

I.e. here there could be another option to select:

![image](https://user-images.githubusercontent.com/70969/142390788-5a98038e-fa51-4705-bac0-fef082d0026d.png)

**Comment by ortnever** [comment]
@ptbrowne 
Ordinal dimensions should be displayed by default in the order defined via schema:position, wherever they appear. I'm not sure I can make an exhaustive list. I think you mentionned the right places. Don't forget pie chart and tables -> where the "Sort" function is used, the sorting should be done according to this predefined order.
Regarding the second question. Yes, the user should be able to choose the logic he wants to order the values. For example, for the cantons, it must be possible to choose between alphabetical order and the official order according to the Federal statistical Office (position).

It would also be useful/nice to have 2-3 specific colour palettes for ordinal dimensions. It's not required as the colours can be changed manually, but it would be useful. I.e from dark green to dark red, through light green and light red, or from green to blue, through yellow and orange, or a gradient from light to dark in a colour.
![image](https://user-images.githubusercontent.com/79834090/142449866-299d9896-f645-4d90-bba4-d97b80f82243.png)

**Comment by herrstucki** [comment]
@ortnever Is there a cube that currently has at least one dimension with ordinal scaleType?

**Comment by ortnever** [comment]
Yes, the red List, see here 
![image](https://user-images.githubusercontent.com/79834090/145356004-399303b0-2a5f-41c4-8a5d-dd7045202ddc.png)

**Comment by ortnever** [comment]
https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fabian-red-list-test-1-b7aqog24r6n/metadata

**Comment by herrstucki** [comment]
Has this cube been published? I can't find it on test.visualize.admin.ch (which should show all the LINDAS INT cubes).

**Comment by ortnever** [comment]
yes, as draft in test.visualize. Search "Red list" in english Interface or "Rote Liste" in German interface:

https://test.visualize.admin.ch/en/browse?includeDrafts=true&order=TITLE_ASC&search=red+list

![image](https://user-images.githubusercontent.com/79834090/145376178-6f4ba567-4385-4440-a322-864444dcbcbe.png)

**Comment by herrstucki** [comment]
Ah yes, I searched for "red list" in German … 🤦 Sorry!

**Comment by FabianCretton** [comment]
The dataset to use is "Red List (from INT) tst"

I do have a maybe naïve question about: "Ordinal dimensions should be displayed by default in the order defined via schema:position, wherever they appear. I'm not sure I can make an exhaustive list. " (from @ptbrowne )
I guess that everything displayed on screen comes from one or more SPARQL queries. 
And I suppose that taking care of the ordering, directly in those queries, could solve the problem "everywhere", no ?
That is: the query does an alphabetical ordering if no schema:position is specified, otherwise an ordering on schema:position.

**Comment by sosiology** [comment]
@ptbrowne can this issue be closed?

**Comment by ortnever** [comment]
There is always a problem for Pie Chart but there is a new issue. for that 
https://github.com/visualize-admin/visualization-tool/issues/580

**Comment by ptbrowne** [comment]
Closed in favour of #580
