### ISSUE TITLE
Temporal values not being displayed correctly on x-axis on INT

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1024]
When displaying temporal values on the x-axis on INT the values are (at least for one value) not shown correctly. Instead of the the expected values (e.g. year) _**0NaN**_ is shown. Also for some cubes not all the possible temporal values are shown in the bar chart and neither are only the valid values shown when in this case year is selected as a filter option (all years show up for selection instead).

[Heavy Metal Soil Contamination](https://int.visualize.admin.ch/create/QvP0Mlp8zd8H?dataSource=Int)
![Tempaxis_bug_20230425](https://user-images.githubusercontent.com/111350367/234262704-dd19b006-082a-40ef-af1a-17e3566bfa45.PNG)

[Another example for the airpollution along the A2 and A13](https://int.visualize.admin.ch/fr/v/yjzYpOegXJIJ)

On PROD I did not encounter this issue

**Comment by bprusinowski** [comment]
Hi @tboeni, thanks for reporting! This should be fixed once we merge #1025.
