### ISSUE TITLE
Adjust Text Below Spinner

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1027]
**Is your enhancement related to a problem? Please describe.**
In the last version we implemeted a change to make the spinner appear sooner and added a clarification text: _Bei grossen Datensätzen kann dies mehr als 30 Sekunden dauern_. The text should be refined to inform the user that we are working on optimizing the applications performance.

**Describe the solution you'd like**
This text should be changed to **_Bei grossen Datensätzen kann dies zur Zeit länger dauern, die Performance wird noch optimiert._**

**Comment by sosiology** [comment]
@bprusinowski can you implement this change next week? Thank you
cc: @adintegra

**Comment by bprusinowski** [comment]
Sure, I'll implement this on Monday 👍
