### ISSUE TITLE
Slow performance on loading published charts

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1028]
_Issue Shared by Thomas per Email on 09.05.2023_

**Describe the bug**
Slow performance on loading published charts with LFI dataset
 
**To Reproduce**
 
1. Open https://int.visualize.admin.ch/v/hKkUyBpGpWPl?dataSource=Int
2. Observe long loading times (up to 12s)
 
**Expected behavior**
Shorter loading time (preferably <1s) given that the filter values are available from slug (postgres) and
SPARQL query is really quick (i.e. 0.2s see https://s.zazuko.com/PCAa4k)
 
**Environment (please complete the following information):**
INT v3.19.14 ([e804d90](https://github.com/visualize-admin/visualization-tool/commit/e804d90b07922d0ffda7fd2ebedb50bcf4038b78))
 
**Additional context**
![image](https://github.com/visualize-admin/visualization-tool/assets/26090254/628739dc-14f0-4f66-b959-f37c644c786d)

**Comment by sosiology** [comment]
Hi @bprusinowski 
This is a new Issue from Thomas, that has the highest prio at the moment. Could you have a look at it this week please?
cc: @adintegra

**Comment by adintegra** [comment]
For reference: (Initial) retrieval of the test URL now returns in ~3.5s

<img width="865" alt="image" src="https://github.com/visualize-admin/visualization-tool/assets/6533245/51c1313c-4cc8-427a-897f-d3d316d7a6d5">
