### ISSUE TITLE
initially prefer map view over table view

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1038]
**Is your enhancement related to a problem? Please describe.**
initially prefer map view over table view

**Describe the solution you'd like**
New charts shall prefer map view over table view
i.e. https://visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1 shall open a map view

**Describe alternatives you've considered**
Explain to all the users how to switch :-)

**Usecases and impact**
users of would like to simply get a map view for https://visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1 to quickly share a map view

**Comment by sosiology** [comment]
@bprusinowski works on test 🎉
