### ISSUE TITLE
Graph Error for the Columns Chart Type

### ISSUE THREAD

**Issue by NoelLeber** [visualize-admin/visualization-tool#1044]
**Describe the bug**
Die Messwerte sind korrekt, jedoch werden sie zuweit unten angezeitgt. Der Grafische Startpunkt der Messwerte ist am Endpunkt.
https://int.[visualize.admin.ch](https://int.visualize.admin.ch/v/CXiHiKU4EoAh?dataSource=Prod)/v/CXiHiKU4EoAh?dataSource=Prod

**To Reproduce**

1. Go to ' Datenset: Treibhausgasemissionen nach Sektor und Gas, Neuestes Update: 24.05.2023 14:10'
2. Click on 'Säulendiagramm auswählen, Vertikale Achse: Emmisionen in Co2-äquivalenten, Horizontale Achse: Jahr
Filter: alle Treibhausgase + Bilanz der Landnuztung'
4. Scroll down to 'Grafische Darstellung'
5. See error

**Expected behavior**
Säulengrafik beginnt und endet danach auf Messpunkt. Länge der Säule Korrekt.

**Screenshots or video**
![Unbenannt](https://github.com/visualize-admin/visualization-tool/assets/113584933/cf0188f9-ed21-494e-9547-d7d9354d94a2)

**Environment (please complete the following information):**

- INT v3.19.18
- Firefox

**Comment by sosiology** [comment]
@NoelLeber a change has been deployed to TEST that fixes this issue. Could you test it on test.visualize.com and confirm this meets your expectation?
