### ISSUE TITLE
download full data set doensn't deliver full data set

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1046]
**Describe the bug**
download *full dataset* doensn't deliver *full dataset*

**To Reproduce**

1. Go to https://int.visualize.admin.ch/en/v/676MjZnpt6wR?dataSource=Int
2. Click on download data > full dataset
3. open dataset (csv)
4. See only *volume* is present

**Expected behavior**
receive the the *full dataset* with all the measure dimensions on click on *full dataset*

**Screenshots or video**
If applicable, add screenshots or a short video to help put your problem into a context.

**Environment (please complete the following information):**

- Visualize environment and version: v3.19.18 ([bea31bb](https://github.com/visualize-admin/visualization-tool/commit/bea31bb26f116fe321b43ff823f53e20293c9177))

**Comment by ortnever** [comment]
Note also that this concerns not only Measure Dimensions, but all dimensions which are not Key Dimensions -> If these are not used in the filters, they are not exported.
See : https://int.visualize.admin.ch/fr/create/Bj71FAgJgcCc?dataSource=Int
Thank you Thomas to have reported the bug.

**Comment by ortnever** [comment]
...I see now that the bug is closed and already ok on Test ! I had a look on test. That's fine for the "none" key dimensions !
