### ISSUE TITLE
Search full words

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#105]
The actual feature searches by individual characters, not by words, with unexpected results:
![image](https://user-images.githubusercontent.com/35593772/121002751-f71aa700-c78c-11eb-9ed6-049340e3154d.png)
![image](https://user-images.githubusercontent.com/35593772/121002894-25988200-c78d-11eb-867a-dad55ff00507.png)

**Comment by ortnever** [comment]
see #96

**Comment by ortnever** [comment]
The search Feature should also consider the Opendata.swiss Keywords entered via the Cube Creator
