### ISSUE TITLE
Sorting dimensions does not return the expected order in table view

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1053]
When sorting for dimensions (other than cantons), the function sorts the table but not in the expected way. The order seems to be all over the place even for a temporal dimension like "Year"

[Treibhausgas Emmisionen](https://int.visualize.admin.ch/create/Ip_fe7P33ZaU?dataSource=Prod)
![Jahrsortierung_BUG](https://github.com/visualize-admin/visualization-tool/assets/111350367/9dc46861-9ab5-417d-8ac9-55fe942b7811)

**Comment by ortnever** [comment]
Checked by OV. Ok for sorting by "Year". 
Dimensions with schema:name and schema:ID (like Emissionsquelle or Treibhausgas" are sorted by ID. This is confusing for users who think they are sorting alphabetically (A -> Z). The various sorting options should be added here, as for graphics. See: .#981
