### ISSUE TITLE
Sorting in reverse alphabetical order does not affect the legend in lines plot

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1054]
Sorting in reverse alphabetical order does not affect the legend in lines plot. The same works in the bar plot without any issue. Just the button press from **A -> Z** to **Z -> A** does not affect the legend to display Jura first instead of Zurich (which would be index number 1)

[Photovoltaiv](https://int.visualize.admin.ch/create/KBkqret2PzUU?dataSource=Prod)
![Sorting Bug Lines](https://github.com/visualize-admin/visualization-tool/assets/111350367/ad163dc0-bb26-4aa6-ac03-601b532d6957)

**Comment by ortnever** [comment]
Checked by OV. OK. Thank you !
