### ISSUE TITLE
Display Error for LFI Data

### ISSUE THREAD

**Issue by NoelLeber** [visualize-admin/visualization-tool#1057]
**Describe the bug**
Die Sortierung der ausgewählten Filter der LFI Daten stimmt nicht. Bei Auswahl nach Name oder ID ist die Sortierung durcheinander nach Grösse funktioniert es.
https://int.visualize.admin.ch/create/_c7u1xUqt929?dataSource=Int

**To Reproduce**

1. Go to 'Säulendieagramm -> Horizontal Gesamtvolumen -> Vertikal Region'
2. Click on 'Farbe -> inventur -> Sortierung nach ID oder NAME'

**Expected behavior**
Anzeige: LFI2 , LFI3 , LFI 4

**Screenshots or video**
![lfi](https://github.com/visualize-admin/visualization-tool/assets/113584933/2fee6701-7411-4646-812d-2fef136222bc)

- Visualize environment and version: [v3.19.18]
- Browser and version [Firefox]

**Comment by ortnever** [comment]
Checked by OV. ok. Thank you !
