### ISSUE TITLE
wrong sort order in time series

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1061]
**Describe the bug**
There is a wrong sort order in some time series applied.

**To Reproduce**
1. https://test.visualize.admin.ch/v/kSH3lpmO-vS2?dataSource=Test
2. See sort order in time series (1988, 2021, 1989, ...)

**Expected behavior**
Ascending sort order

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/26090254/31f6825a-1c75-4cfc-adc6-7a5d4dee1a15)

**Environment (please complete the following information):**
- Visualize environment and version: TEST v3.19.19 ([7dc9228](https://github.com/visualize-admin/visualization-tool/commit/7dc922825a61ec75c1d6b6878d3b13b057806628))
- Browser and version: Edge 113.0.1774.50

@bprusinowski @sosiology rapid fix needed for ongoing deploy ! THX
cc @zellersabine @ortnever

**Comment by ortnever** [comment]
Checked by OV. Ok. Thank you !
