### ISSUE TITLE
Lines chart : Interactive Filter does not work on temporal dimension "Year"

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1065]
Open this chart : https://int.visualize.admin.ch/fr/v/Vyk7FZURPfb-
Try the interactive Filter on horizontal axis "Year".

Strangely, the "Year" dimension also appears when you display interactive filters with the + key, even though this dimension is used on the horizontal axis? I don't know how I managed to configure this?

![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/f86be1e5-0b4a-4eeb-8a3a-901b269af9c5)

- Visualize environment and version: Viztuzalize INT, Datenquelle : PROD, v3.19.20 ([4122b66]

**Additional context**

**Comment by bprusinowski** [comment]
Hi @ortnever, thank you for the hint, I was just trying to replicate this behavior :) I think it should cancel the interactive filter in such case, I'll take a look into it 👀

**Comment by bprusinowski** [comment]
Hi @ortnever, the fix is available on TEST – could you take a look and let me know if it works as expected now?

**Comment by ortnever** [comment]
It works good on test. Thank you for the correction Bartosz. You can take it on INT.
