### ISSUE TITLE
wrong color in chart

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1068]
**Describe the bug**
in the chart not the selected color is used

**To Reproduce**

1. Go to https://int.visualize.admin.ch/create/new?from=VUSAeguRbG3t
1. See error

**Expected behavior**
use the very same color as selected

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/26090254/c74d4e4b-f583-4acc-96df-9c415369bd80)

**Environment (please complete the following information):**
- Visualize environment and version: INT v3.20.0 ([84a65f2](https://github.com/visualize-admin/visualization-tool/commit/84a65f237af007eb6147785107d9d865fd915e82))

@bprusinowski can you hot fix this asap / before PROD (will be next wednesday) ?
cc @zellersabine @sosiology @adintegra

**Comment by bprusinowski** [comment]
Hi @Rdataflow, yes, I am taking a look now 👀

**Comment by bprusinowski** [comment]
The fix is ready in #1069 – the root cause of the problem was that we were showing values that shouldn't be shown, because they were not present in the chart. If the chart actually used the "Keine Angabe" value, it would have the correct color 👍
