### ISSUE TITLE
Misinterpretation of the dimension Year

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#107]
In the dataset "States Accounts", there is a Dimension "Year":
- Data type : Integer
- Dimension type : Key Dimension
- Scale of measure : Interval (States Accounts - Category) or no Scale of measure (States Accounts - Domain)
- Data kind : Temporal - Year

This Year dimension cannot be used in many chart type as it is considered by Visualize as a measure, not a Key Dimension
There is also no mandatory filter for this dimension. [Sample](https://test.visualize.admin.ch/en/v/63josexK_Xl1)

![Year-Dimension-1](https://user-images.githubusercontent.com/35593772/121008932-d144d080-c793-11eb-9f03-8cb1ee6c93ea.PNG)

A Key Dimension must always be defined as an **axis** (X or Y), a **color** or a **filter**.  No matter it is a text, a number, a date, a geographical object or something else.

**Comment by herrstucki** [comment]
The datatype should be `xsd:gYear`, no?

**Comment by PDumasBAR** [comment]
Yes it is.

**Comment by PDumasBAR** [comment]
Sorry, the data type is Integer.
xsd:gYear is the property used.
Perhaps there is a contradction here.

**Comment by PDumasBAR** [comment]
You are right.
The problem is in the data type. Selecting xsd:gYear is not enough. Selecting the data type xsd:gYear is important too :

![image](https://user-images.githubusercontent.com/35593772/121211557-dfbae700-c87c-11eb-8e61-e2bc8d6f3ec8.png)

I close this issue now and verify in the related issue if they are solved.

**Comment by herrstucki** [comment]
Ah, I think the **target property** could also just be just `year` (no need for it to be `xsd:gYear`, in fact it's probably not correct since this is the **precicate** of the triple?) but the relevant **data type** has to be selected, yes.
