### ISSUE TITLE
Optimise the X-axis boundaries

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#108]
The Year dimension (as an integer, see [107](https://github.com/visualize-admin/visualization-tool/issues/107)) can be used in a scatterplot chart, but the result is not optimal, because the X-Axis minimum is not set to the min value of the dimension. In this [Sample](https://test.visualize.admin.ch/en/v/63josexK_Xl1), an X-Axis from 1850 to 2025 is expected, or at least 1800 to 2100.

![Year-Dimension-2](https://user-images.githubusercontent.com/35593772/121009351-592ada80-c794-11eb-9317-42f16f286249.jpg)

**Comment by herrstucki** [comment]
I would categorize this for a future iteration when we address scatterplots with time axes #127
