### ISSUE TITLE
Erratic chart behaviour

### ISSUE THREAD

**Issue by AFoletti** [visualize-admin/visualization-tool#1088]
**Describe the bug**
A cube **without any empty values** in the measure dimension behaves a little erratically when switching from one plotted key dimension to another.
See the following video, and pay attention at how the "_Endverbrauch - Total_" plot changes from time to time.

https://github.com/visualize-admin/visualization-tool/assets/691243/2e1dc469-1c34-4d11-af81-4880bd7d7a1a

**To Reproduce**

1. Go to visualize INT
2. Search for the "(Long) Schweizerische Gesamtenergiestatistik" cube (from SFOE) and try to create a visualization for it
3. Pick the column graph, and activate the coloring by "Energy carrier"
4. Change multiple times the displayed value for the "Rubrik" key dimension. Observe how the resulting plot is not constant

**Expected behavior**
Same data, same plot, same configuration == same results, every time!

**Screenshots or video**
See above

**Environment (please complete the following information):**

- Visualize environment and version: (https://github.com/visualize-admin/visualization-tool/commit/91b2d00e38067535f2b9b15bb6a645621a6a54dc)

**Additional context**
A couple of probably important points:

1. V13 of this cube (the last version where the issue described here is present) does not have any missing values for the measure dimension. V12 of the cube on the other hands has missing values (just so you know you have this version at your disposal for tests should you need it). I would have suspected another "missing imputation" issue, but since I see the problem with "always full" data it should be something else...
2. The cube uses **a hierarchy** on the Energy Carrier key dimension used for colorizing. Maybe has an influence?
3. This is the very same **high prio cube** as earlier today. I would appreciate a quick signal from your side @bprusinowski 

Tagging @Rdataflow and @aresssera FYI

**Comment by bprusinowski** [comment]
Hi @AFoletti, thanks for reporting the issue!

In fact it's related to the imputation issue, as we use the same method to compute the coordinates of the stacked bars, as in the area chart. It seems that some values inside the cube are only present for some years, and not for all.

For example, it seems that when filtering by "Import", values from the period of 1980-1996 do not have any value assigned for `https://ld.admin.ch/cube/dimension/gest_energietraeger/113` (Other renewable energies), while values for the following years are there.

This leads to the problems with inconsistency and broken bar charts – but this should be fixed by #1089.

**Comment by AFoletti** [comment]
Hey @bprusinowski many thanks for the update!
I think the reasoning in the mentioned PR makes sense.

Now, 2 questions:

1. I did not test other plot types (area, lines and whatnot). Will the fix solve the issue in every plot type?
2. Is there any hope to see the fix on prod next week?

**Comment by bprusinowski** [comment]
Yes, I checked area and line, and they both work fine (but area chart requires a user action to select the imputation type, so initially it might look broken in some cases).

For the production deployment, I personally don't see any contraindications, but I'll loop @sosiology and @adintegra here :)

**Comment by AFoletti** [comment]
> Yes, I checked area and line, and they both work fine (but area chart requires a user action to select the imputation type, so initially it might look broken in some cases).

Yes, already fallen into that trap once again. All good!

> For the production deployment, I personally don't see any contraindications, but I'll loop @sosiology and @adintegra here :)

It would be greatly appreciated. But I do not want to put any stress on your processes. We will publish the data and make visualizations as soon as the app is ready

**Comment by sosiology** [comment]
@AFoletti we will need to clarify with BAFU if we can deploy the fix to PROD next week and check with Abraxas to ensure they have availability to support. I have added this to the weekly call agenda for next Tuesday to discuss with BAFU. 

cc: @adintegra @bprusinowski

**Comment by AFoletti** [comment]
@bprusinowski Sorry for tagging you in this closed ticket, but I was thinking about temporarily solving the issue at the data level, so that we can go live this friday with some visualize plots even if the fix is not in PROD.
What's in your opinion the best way to "fix" the data in a neutral way but enough to ensure that today's version of visualize can handle it correctly?

I hope the question is clear enough... if not, do not hesitate to ask. And many thanks for whichever hint you may give me!

**Comment by Rdataflow** [comment]
@AFoletti maybe you can tweak this by setting *default value* in cc csv mapping?

**Comment by AFoletti** [comment]
> @AFoletti maybe you can tweak this by setting _default value_ in cc csv mapping?

Yes, that works of course very well and is the same as putting "0" in my CSV original data wherever a measure is missing (and actually better since I do not habe to hack my data production process).
This data hack (either on the CSV and CC) has however the negative effect to fill the mouseover tooltip with a lot of unneeded entries with value 0.
In this respect is IMHO the visualize fix proposed in #1089 a superior solution

**Comment by bprusinowski** [comment]
@AFoletti it seems that this is the case, the values with missing values are not fetched – yes, this is what's being solved by using imputation.

I would say it's different and more important in area charts, as there we also draw the connections between the values – the decision to impute missing values using 0s or e.g. linearly interpolated values heavily influences how the chart look like (at what story it says). In area chart we anyway assume a linear relationship between the current and next value, as we connect them with a straight line, so adding an option to do linear interpolation for this chart type seemed to make sense.

For stacked bar chart it's "easier", as if we treat missing values as 0s, we just do not see that value in the chart at all (contrary to area chart, where we would see the connection to preceding and next value). We also do not show the interpolated value in the tooltip, so I think it makes sense to just treat them as zeros.

The other thing is if we'd like to also offer options to impute missing values in some other ways when working with bar charts – but I feel that this would be "too much". What do you think?

**Comment by AFoletti** [comment]
Dear @bprusinowski many thanks for the explanations!
This makes, once again, perfect sense. And I agree with you that the imputation question for barcharts can be solved by defaulting to "0" without asking the user, which has a problem less to solve by himself.
As I said, the PR you posted is in my opinion great.
