### ISSUE TITLE
Missing chart with temporal dimension

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#109]
In the dataset "States Accounts", there is a temporal dimension (Year) and a measure dimension (Value), but both chart types "Lines" and "Areas" are not available. Probably because the Year dimension is not interpreted as a temporal dimension (see [107](https://github.com/visualize-admin/visualization-tool/issues/107)).

And for the "Scatterplot" chart type, the rules must say : 2 or more Measures or Temporal Dimensions
A scatterplot with a temporal dimension as an axis (X or Y) is sure interesting to produce ([sample](https://test.visualize.admin.ch/en/v/63josexK_Xl1))

**Comment by PDumasBAR** [comment]
See the resolution of #107

Yet the available charts follow the defined rules in the documentation.
"Lines" and "Areas" are available.

But scatterplot is no more available and it should be.
The [rules](https://dev.visualize.admin.ch/docs#/charts/types) must be changed to allow a scatterplot chart with a temporal dimension and a measure dimension.

**Comment by herrstucki** [comment]
Since the data issue was addressed in #107, I'm closing this and opening a new issue for the scatter plot discussion in #127.
