### ISSUE TITLE
Animated Charts: Finalize First Iteration

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1091]
**Design**
- [x] Define Placement in UI
- [x] Design the Slider

**Development**
- [x] Implement design of time slider
- [x] Fix chart container size to avoid "jumps"
- [x] Application to the following chart types **only** (for first iteration): Scatter, Bar, Pie (Maps, lines, areas and tables are out of scope for the first iteration)

**User Stories**

* [x] as a data provider I'd like to provide multitemporal data (with ordinal or interval temporal scale) for animated charts.
  * [x] as a data provider I excpect ordinal time dimensions to be interpreted as a abstract time concept wich can't be shown as line chart nor area chart.
  * example data:
    * ordinal: [WSL-NFI](https://test.visualize.admin.ch/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-19-None-None-44_ordinal_2%2Fcube%2F1) - allow only bar chart (and pie chart)
    * interval: [BFE-EIV](https://test.visualize.admin.ch/browse/dataset/https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen) - allow all chart types (bar, line, area)
* [x] as a publisher I'd like to publish & share an animated chart for any multitemporal dataset
* [x] as an end user I'd like to start / stop the animation of a multitemporal dataset
* [x] as an end user I'd like browse the time by interactively dragging a time slider for a multitemporal dataset (equally applies to publisher)
* [ ] as a developer I'd like have the chart-config docs up to date https://visualize.admin.ch/docs/chart-config

**UX examples for animations**

1. [gapminder charts](https://www.gapminder.org/tools/#%24model%24markers%24bubble%24encoding%24y%24data%24concept=energy_production_per_person&space@=country&=time;;&scale%24domain:null&zoomed:null&type:null;;&frame%24value=1989;;;;;&chart-type=bubbles&url=v1)
1. [map.geo.admin.ch maps](https://s.geo.admin.ch/9a81233ee5)

See also:

* https://github.com/visualize-admin/visualization-tool/issues/451
* https://github.com/visualize-admin/visualization-tool/issues/802

**Comment by Rdataflow** [comment]
@bprusinowski cube with ordinal time is available here https://test.visualize.admin.ch/de/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_ordinal_time%2Fcube%2F2023-1&dataSource=Test

cc @kronmar THX for providing

**Comment by kronmar** [comment]
Please let me know, should you need more

**Comment by sosiology** [comment]
ready for internal review, @bprusinowski will post the PR link

**Comment by bprusinowski** [comment]
The link to the PR: https://visualization-tool-git-feat-normalized-charts-2-ixt1.vercel.app/en?dataSource=Prod

**Comment by sosiology** [comment]
@bprusinowski I took a look and it looks very nice :) 

I tried to test for the use case "I want to animate the chart and change the bar colors from blue to green". I noticed that when I go to segmentation and select Air Pollutant as a dimension, the x-axis values significantly increase making the bars very small and the changes hardly noticible as the animation runs:

Example published chart blue (no segmentation): https://test.visualize.admin.ch/en/v/V9tWGyRMgJrI?dataSource=Int
Example published chart green (segmentation on Air Pollution): https://test.visualize.admin.ch/en/v/50IxnfrqWLC7?dataSource=Int

**Comment by bprusinowski** [comment]
Thanks for the review and testing @sosiology 🙇  I fixed this in #1116. There was also an issue with 100% charts when animating, but that also should be fixed by the PR 👀
