### ISSUE TITLE
Barcharts in Percent based on Absolute Values

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1092]
**User Stories**
- [x] As a user, I would like to visualize my data as bar chart in percentages based on absolute values (in the same way as a pie chart) when a breakdown by category is available, but the data only avalaible as "Absolute Value".

Use case :
- Umweltpanel : https://int.visualize.admin.ch/fr/v/Y8ksokwM5-ub
- Redlists : https://int.visualize.admin.ch/fr/v/VlugF2BJBF_Y 

**Additional Information**
- Also see comment from Véronique: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/375#note_7791

**Examples**

![Image](https://user-images.githubusercontent.com/29289679/250526419-875190cd-c13b-42a1-80b1-478f7fe9f3af.png)

**Comment by sosiology** [comment]
Hey @bprusinowski I noticed when comparing the values in a barchart and piechart with the same data, we round up the decimals in the barchart. I was wondering why as I would expect the same values. Example charts and screenshot below:

Pie Chart: https://test.visualize.admin.ch/en/v/gTW3-0FLnmZb?dataSource=Int
Bar Chart: https://test.visualize.admin.ch/en/v/SCTo4k-xJKUz?dataSource=Int



![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/aec89e13-eca1-4469-8a57-4603045956fe)

**Comment by bprusinowski** [comment]
Both should be fixed in #1116 :)

**Comment by sosiology** [comment]
Checked the PR you shared and LGTM. Im not sure if we should be rounding 🤔 or leaving the values as is. Let's discuss this afternoon

**Comment by bprusinowski** [comment]
Just to clarify: we are calculating the percentages on our own they do not come from the data – and there we need to round them somehow. I think the decision we need to make if whether it makes sense to round to whole percentage, or rather to e.g. one decimal place – but in the design we had whole percentages.
