### ISSUE TITLE
Tooltips: Display absolute values + percentages

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1093]
As a user viewing a percentage chart based on absolute values, e.g. pie chart or bar chart (issue [#1092](https://github.com/bafu/umweltdatenkiosk-planning/-/issues/509)), I would like the tooltip to show me not only the absolute values but also the % values.

![Image](https://user-images.githubusercontent.com/29289679/250526945-836782e6-e726-4181-9851-5383b1a7cb5a.png)

**Comment by KerstinFaye** [comment]
[Notion Documentation](https://www.notion.so/interactivethings/Charts-percent-based-on-absolut-values-6046643c09654dfdaad54039be4e82e3?pvs=4)


[Figma Link](https://www.figma.com/file/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---4.0---design?type=design&node-id=102-78282&mode=design&t=Nl7Rs4olVPDlQcyb-4)
