### ISSUE TITLE
Use Parameters to call up a Chart (Diagramms via API)

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1095]
Userstory:
- [ ] As a machine I'd like to use parameters to call up a *published chart view* (without manually clicking through the publishing process)
- [ ] As a data provider I'd like to use parameters to call up a *edit chart view* with predefined settings (i.e. similar to copy&edit a published chart)

DoD:
- [ ] Exposed and documented parameters (API) for *published chart view*
- [ ] Exposed and documented parameters (API) for *edit chart view*

Analog use case for maps:
- https://help.geo.admin.ch/?ids=54&lang=en

![Image](https://user-images.githubusercontent.com/29289679/250527925-d4e722ec-5788-49d9-ac28-73b8f73f8251.png)

It would be a good thing, if a visualization could be generated, even if the cube is hidden on visualize.

Use case: we would like to include a visualization for each table on the nfi [webpage](https://lfi.ch/resultate/resultateliste.php?fldSearch=&p=search&pg=1). But not all tables could be merged into the existing cubes, as it would have led to too many NA values (think of the nfi as a very sparse matrix). We would still like to include a visualization for all those tables left out, but publishing them would lead to an additional ~1000 cubes, all of which include a very limited amount of tables and leading to an absolute overkill of tables on [visualize.admin.ch](http://visualize.admin.ch/) landing page.

**Comment by sosiology** [comment]
A call will take place on 11.07.2023 (during the weekly call slot) get an overview of the task from Thomas and Marko
cc: @bprusinowski @adintegra

**Comment by sosiology** [comment]
Notes from Discussion with Thomas and Marco on 11.07.2023: https://www.notion.so/interactivethings/230711-Weekly-Call-c2f104dc802545329dd24ab781a4dd24?pvs=4#680d3579730f412999f2e792bcaf4f8a

**Comment by adintegra** [comment]
An initial implementation of the ideas collected as part of this discussion is in [this PR](https://github.com/visualize-admin/visualization-tool/pull/1152).
