### ISSUE TITLE
Visualize interprets some texts

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#110]
In the dataset "Peaks Bundesratsgeschäfte", there is a key dimension "Woche" represented by a string containing the year and the number of the week separated by a dash. Example: "2019-01".

In step 2, chart type selection, Visualize interprets this dimension and shows it as a date with month and year separated by a dot:

![image](https://user-images.githubusercontent.com/35593772/121026585-9009ec00-c7a6-11eb-820c-5490864d3fc5.png)
The dataset contains only data from years 2019 and 2020, so the representation of the x-axis is clearly false.

In the next steps, I define a color and this dimension is no more interpreted. The values on the x-axis are now correct:

![image](https://user-images.githubusercontent.com/35593772/121027198-10305180-c7a7-11eb-981f-ee2e8c8558c2.png)

**Comment by herrstucki** [comment]
I've never seen this notation 😄 – I don't think it's a valid ISO date and has no representation as XSD datatype?

**Comment by PDumasBAR** [comment]
That's a string. 
As I don't know how to represent a week of the year in RDF, I decided to publish it as a string.
Just defined as a Key Dimension, but not temporal, not Interval or something else.
In the second snapshot it is correct, in the first, it is interpreted.

The goal is exactly what Visualize produce at the end. A column chart with 3 "categories", so it's really a very small thing.
