### ISSUE TITLE
Display Inconsitency When Selecting Colors For Bar Charts

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1100]
This bug was discovered when looking at [Qualität der Badegewässer](https://visualize.admin.ch/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd0104%2F6&dataSource=Prod) on PROD and also INT.

When selecting Concentration for the Y axis, Date for the X axis and Badeplatz for the color filter, the following error occurs and nothing else is displayed:

![BAQUA Badeplatz bug](https://github.com/visualize-admin/visualization-tool/assets/111350367/8448b26f-8871-4293-9688-e2adfa48ae72)
![BAQUA Badeplatz bug all select](https://github.com/visualize-admin/visualization-tool/assets/111350367/c4475e1c-a7bd-4b73-8131-4faf59ad4638)

However, when deselecting all of the "Badeplätze" and just selecting a few random ones. Visualize is able to display the desired bar chart: 

![BAQUA Badeplatz bug one select](https://github.com/visualize-admin/visualization-tool/assets/111350367/b8e4b572-050d-41f5-a111-d26ed17ea19f)

Is this because the number of selected colours exceeds the maximum number of displayable bars in a bar chart?

**Comment by bprusinowski** [comment]
Hi @tboeni, thanks for reporting the bug!

I believe it should be already fixed on TEST, could you take a look and close the issue if it works there? See https://github.com/visualize-admin/visualization-tool/pull/1098 for reference 👀
