### ISSUE TITLE
After language switch the language in interactive filters is wrong

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1104]
**Describe the bug**
After opening https://visualize.admin.ch/de/v/IYdcAI0tH0Io?dataSource=Prod and switching to another language (i.e. FR) the interactive filter (tree species) is displayed in the wrong language.

**To Reproduce**

1. Go to https://visualize.admin.ch/de/v/IYdcAI0tH0Io?dataSource=Prod
2. Click on 'FR'
3. Open Filter (tree species)
4. See error: list displayed in previous language (DE)

**Expected behavior**
Switching the language reloading the filter in the chosen language
i.e. same behaviour as opening https://visualize.admin.ch/fr/v/IYdcAI0tH0Io?dataSource=Prod

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/26090254/8e0ead49-a8bc-405d-afe0-6bbc7860b31e)

**Environment (please complete the following information):**
- Visualize environment and version: [e.g. INT v3.20.2]

**Comment by sosiology** [comment]
Additional Note: If the page is reloaded after the language is switched, the filters shows up correctly.

**Comment by sosiology** [comment]
LGTM thanks for fixing this @bprusinowski
