### ISSUE TITLE
Export UI Text

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1107]
We would like to have an overview of all the UI texts so that we can align and optimize them where needed to ensure consistent language and clarity.

**Comment by bprusinowski** [comment]
Hi @sosiology, we keep all the strings [here](https://github.com/visualize-admin/visualization-tool/tree/main/app/locales), in respective `.po` files inside the folders. Let me know if this format works, or if there is a need to consolidate them in some way 👀

**Comment by sosiology** [comment]
Hi @bprusinowski thanks for pointing me in the direction of the PO files. The format works. 
@KerstinFaye you can find the German UI text here in notion: https://www.notion.so/interactivethings/UI-Texts-ab8711a44452495a8662162700e30717
We should probably quickly align on the best way to document changes / optimizations
https://www.notion.so/interactivethings/UI-Texts-ab8711a44452495a8662162700e30717

**Comment by sosiology** [comment]
Solange will add the EN strings to the notion doc. The notion doc is a temporary solution to beable to view the strings in a more digestible format but is not a sustainable solution. Mark will talk to the devs about potential solutions that can be applied to other projects, and Kerstin will reach out to the designers about UI copy writing best practices.
