### ISSUE TITLE
Add Storybook

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#1109]
To improve documentation and be able to more easily test some functional changes to particular components, we should think about adding Storybook.

Also see https://github.com/visualize-admin/visualization-tool/pull/1103#pullrequestreview-1558786496.

**Comment by sosiology** [comment]
@bprusinowski can this be closed?

**Comment by bprusinowski** [comment]
Yes, thanks for catching this @sosiology :)
