### ISSUE TITLE
Tooltip units for figures with relative measurements

### ISSUE THREAD

**Issue by kronmar** [visualize-admin/visualization-tool#1111]
**Describe the bug**
If a barplot is normalized, the measurement's tooltip inherit the absolute value's unit. 

**To Reproduce**
See for example [here](https://test.visualize.admin.ch/en/v/esoDl7HPVFwK). Hovering over displays the bars shows the unit in cubic meters (and with arguably way too many digits)

**Expected behavior**
Units should either change to %, or the original values should be displayed. Maybe even both?

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/95312586/414eeea8-bf81-4997-b1ad-7af64260ed26)

**Environment (please complete the following information):**

- Visualize environment and version: v3.20.3 ([99cea84](https://github.com/visualize-admin/visualization-tool/commit/99cea84a75bd78e59eea0124d134d21fe37d7c7b))
- Browser and version: Edge Version 115.0.1901.188 (Official build) (64-bit), but the same behavior is seen in Chrome Version 115.0.5790.171 (Offizieller Build) (64-Bit)

**Comment by bprusinowski** [comment]
Hi @kronmar, thanks for reporting this!

As we treated the two features separately (normalisation of charts and dual-value tooltip), the percentages inside the tooltip are not yet implemented (but should be ready soon) – see #1092 #1093.

I'll mention a pull request in this issue and close once it's merged to main.
