### ISSUE TITLE
Align Sentry environments with Visualize deployment environments

### ISSUE THREAD

**Issue by adintegra** [visualize-admin/visualization-tool#1118]
Currently, the Visualize TEST, INT and PROD environments aren't fully reflected in Sentry. While "Production" appears to be correctly configured, there is no differentiation between TEST (i.e. the development environment) and INT (integration/test environment).

<img width="465" alt="image" src="https://github.com/visualize-admin/visualization-tool/assets/6533245/d665a8fc-e0c6-406c-bac4-1e9749ce39b4">

While not critical, it could be useful to have the three environments (along with the Vercel environments) show up correctly in Sentry so that the differentiation of metrics in TEST and INT is clear.

**Comment by bprusinowski** [comment]
We need to add new environmental variables to Test, Int and Prod to align them correctly (current logic with PUBLIC_URL doesn't work, as we need to use build-time env variables). We need support from Jan from Abraxas who is on holiday until 08.09.2023.
