### ISSUE TITLE
Search in table works only with text

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#112]
It's not possible to find a date, a year or a value with the search functionality in table.
Bug or feature ?

**Comment by herrstucki** [comment]
I cannot reproduce this issue in the latest version on dev.visualize.admin.ch anymore.

<img width="926" alt="Bildschirmfoto 2021-07-05 um 17 12 11" src="https://user-images.githubusercontent.com/70969/124492091-48ca4780-ddb4-11eb-989f-5724f0bf0e86.png">

**Comment by PDumasBAR** [comment]
Another sample [here](https://www.dev.visualize.admin.ch/en/create/eUcsnuAUnjkG)

**The table**
![image](https://user-images.githubusercontent.com/35593772/124497799-b8900080-ddbb-11eb-8dc0-b3ac5642ce35.png)

**Search 326 (or 326,9 or 326.9)**

![image](https://user-images.githubusercontent.com/35593772/124498114-26d4c300-ddbc-11eb-853c-84bddbef7045.png)

If there is a 326 in a text (in the Text ID) it will find it, but not in a numeric or date value.

**Comment by herrstucki** [comment]
Dates should work but numbers not. This is intentional since the table search index would potentially get too big.

**Comment by PDumasBAR** [comment]
OK
