### ISSUE TITLE
URLs to visualize no longer work from opendata.swiss for datasets published from the Cube Creator. 

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1125]
URLs to visualize no longer work from opendata.swiss for datasets published from the Cube Creator. 
The bug has also been announced to zazuko. See more Infos here : https://github.com/zazuko/cube-creator/issues/1456

**To Reproduce**
- open https://opendata.swiss/dataset/stapfer-enquete-schule-in-der-schweiz-17991/resource/5917b51c-e172-4434-bfac-928cb81ab7f4
- test the link to visualize.

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/945e27b2-a0c0-40a5-aac4-8a56d9251f46)

- Visualize environment and version: v3.20.2 ([91b2d00]
- Browser and version: edge

**Additional context**

**Comment by tpluscode** [comment]
Does IXT confirm it's a problem on our end?

**Comment by bprusinowski** [comment]
@tpluscode it looks like this was on us :) Should be fixed in #1151.

**Comment by sosiology** [comment]
tested using testing steps in PR and it worked as expected for me. Thanks @bprusinowski
