### ISSUE TITLE
Do not completely hide the chart when the data is loading

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#1126]
Right now, we completely hide the chart when the data is loading (both in editor mode and when using interactive filters in published mode). As we introduced animations, we are missing the movement between previous values and current values, as everything jumps when the data is loading. I wonder if it wouldn't make sense to indicate this state is some different way, e.g. by applying an loading overlay with reduced opacity, but not remove the chart from the DOM.

**Comment by sosiology** [comment]
Really nice improvement @bprusinowski 👏 works as expected. Wondering if we should make the loading icon a bit smaller for the filters on the published chart. Could we for example keep the outline of the dropdown and have the loading icon in there? All the big loading symbols are a bit overwhelming 😅 



![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/d163b4c4-d3e6-4f26-bd51-997d905c281f)

**Comment by bprusinowski** [comment]
😱 this shouldn't look like this, thanks for catching this @sosiology – I'll take a look 👍

**Comment by sosiology** [comment]
LGTM. Awesome, thanks for the prompt fix @bprusinowski 🚀
