### ISSUE TITLE
It should not be possible to hide a key dimension

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#114]
This problem is surely related to #109 and #107 as it concern again the year dimension in the dataset "State Accounts".
But in all case it should not be possible to hide a key dimension in a table, otherwise the table become unreadable :

![HideYear-1](https://user-images.githubusercontent.com/35593772/121036231-e549fb80-c7ae-11eb-801b-4d68bb3bab05.PNG)

![HideYear-2](https://user-images.githubusercontent.com/35593772/121036239-e7ac5580-c7ae-11eb-931e-85805361ed55.PNG)

**Comment by PDumasBAR** [comment]
Solved, at least for the hidding of a key dimension :

![image](https://user-images.githubusercontent.com/35593772/121210409-f0b72880-c87b-11eb-9bb2-f9ab35c7f3b5.png)

The initial problem was in the cube creator, not defining the right data type for the Year.

However, the proposed filter is incomplete. It shows only the first and last years, not the intermediate years. 
I've already seen the comment in another issue.

**Comment by herrstucki** [comment]
Yes, the filter issue is described in #95
