### ISSUE TITLE
Dashboards Concept

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1141]
Initial Concept / Suggestions for the Dashboard Feature.

**Comment by KerstinFaye** [comment]
**Figma Design Link:**
https://www.figma.com/file/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?type=design&node-id=720-78420&mode=design&t=dxenv9i4JznVudxM-4

**Notion Dokumentation:**
https://www.notion.so/interactivethings/Dashboards-f8e103a690a040758801846fad390686?pvs=4

**Presentation 10-09-2023:**
https://www.figma.com/proto/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?page-id=904%3A81373&type=design&node-id=904-81378&viewport=129%2C733%2C0.15&t=RScktgR4fZIlKz6u-1&scaling=min-zoom&starting-point-node-id=904%3A81378&mode=design


PDF:

[Dashboards_Entwurf_19092023.pdf](https://github.com/visualize-admin/visualization-tool/files/12659457/Dashboards_Entwurf_19092023.pdf)

**Comment by sosiology** [comment]
Figma link shared with the client in Gitlab see comment here: https://gitlab.ldbar.ch/bafu/visualize/-/issues/373#note_12696
unfortunately the PDF was too large to share in Gitlab (max 10mb) just something to be aware of for next time ;)
