### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1144]
Comment from Thomas in Gitlab:  can you update the docs, especially clarify that time can also be of ordinal nature... THX

source: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/444#note_12097

**Comment by bprusinowski** [comment]
@sosiology I updated the docs on dimension types and how we retrieve them (and fixed some not working pages).

I've noticed that our design docs are quite outdated – I didn't update them, as I wasn't sure if I should (and this looks like a bigger task). Let me know if we should update `all` docs to be up-to-date, or maybe create another issue for that.

**Comment by sosiology** [comment]
Hi @bprusinowski thanks for your comment. I assume you are referring to the catalog documentation: https://visualize.admin.ch/docs/components/intro. if so, yes, it is out of date and maybe we should update it. As it is a bigger task I would propose we track it separately, and possibly wait until there is more clarity around the new CI / CD? I will create a new task so we have it in our backlog, but defintely something I would want to discuss with you, @adintegra and @KerstinFaye before investing too much time in.

**Comment by bprusinowski** [comment]
Yes, I meant Catalog docs – I'll then close this issue then :)
