### ISSUE TITLE
Display of absolute values in % in a bar chart - Small error in the display of the vertical axis

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1149]
When using the "Display absolute values in % in a bar chart" function, 100% is not displayed correctly on the y axis (00% instead of 100%).
See the chart :  https://int.visualize.admin.ch/fr/v/JEOzXRikOWZy
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/099ca755-a26e-4f0e-9119-bd29c0f55f52)

**Comment by bprusinowski** [comment]
Hi @ortnever, thanks for reporting! I've also noticed and fixed this in #1130 (try to make the same chart using [this link](https://visualization-tool-git-feat-cascading-interactive-f-0036c3-ixt1.vercel.app/en/create/new?cube=https://environment.ld.admin.ch/foen/ubd000502_sad_01/13)). It should be soon merged to TEST (and if not, I'll keep it on my radar to have this fix in the next PROD release) 👀

**Comment by ortnever** [comment]
Thank you @bprusinowski, the 100% on the y axis is ok in your Link.
Concerning Cascading Filters I add a new exemple in GitLab https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/511
