### ISSUE TITLE
Error loading data for bar chart visualization

### ISSUE THREAD

**Issue by AdMSilvan** [visualize-admin/visualization-tool#1168]
**Describe the bug**
When attempting a barchart visualization of a simple datacube, the data does not load and produces an error. The query is able to retrieve the data but it cannot be loaded in the visualization tool (https://s.zazuko.com/qon2Zo) 

**To Reproduce**
Go to https://int.visualize.admin.ch/create/22Sv3bKjVQGL?dataSource=Int

**Expected behavior**
A bar chart which can either be filtered by revenue type or represented as a segmented bar chart, stacking the different revenue types

**Environment:**
- Visualize INT v3.22.4 (211d0fb)

**Comment by sosiology** [comment]
@AdMSilvan thank you for reporting this we will look into it.

Link to example showing error: https://int.visualize.admin.ch/v/zGNXrwP6aWs7?dataSource=Int

![image](https://github.com/visualize-admin/visualization-tool/assets/29289679/342112b2-f7bc-40bd-9a18-e1222e920747)

cc @bprusinowski @adintegra

**Comment by bprusinowski** [comment]
Hi @AdMSilvan, it looks like the `https://culture.ld.admin.ch/sfa/PolitikfinanzierungParteien2023/einnahmequelle` dimension has a `langString` data type, which Visualize does not support. Would it be possible to change the data type to `string`? This should fix the issue.

From our side @sosiology, I think we could improve the error message to make it more clear what needs to be done, right now it's not very helpful 👀 

Also see #319.
