### ISSUE TITLE
Cascading Filter does not work correctly with hierarchies

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1176]
**Describe the bug**
In Edit mode, when I select a value in a filter, the content of the other filters automatically adapts according to the available values. This is not the case in 'publish' mode, at least not if the dimensions are hierarchical as in the example below.

**To Reproduce**
1. Open the following dataset: https://int.visualize.admin.ch/fr/v/64x2xjnhE__Q
2. copy and edit
3. In the "Source of Emission" filter, open "Balance of Lande use" and select "Leaching (N2O)"
4. Consult the "Greenhouse Gas" filter -> only the values "all greenhouse gas" and "Nitrous Oxide" are proposed. This is correct.
5. Select "Nitrous oxide" 
6. Activate the interactive filters for the 2 dimensions.
7. Publish the graph
6. Display the interactive filters -> the "Grennhouse gas" filter displays all the gases.

**Expected behavior**
Only the gases "all greenhouse gas" and "Nitrous Oxide" should appear in the list.

**Screenshots or video**
Mode Edition
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/956b4731-a5d5-4067-a7ed-2ae9304985e4)
Mode publish
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/bb04a3ba-b30b-427f-ae41-1cf711eaa9ad)

**Environment (please complete the following information):**

- Visualize environment and version: v3.22.5 [615675d]

**Additional context**

**Comment by bprusinowski** [comment]
Hi @ortnever, thanks for reporting the bug – I'll take a look at it tomorrow 👀
