### ISSUE TITLE
Y-axis scale error

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1183]
In some cases, the y-axis scale is not displayed correctly in terms of the numbers shown and the layout.

**To Reproduce**
1) https://int.visualize.admin.ch/de/v/a5Jjfyd4-hAy
2) compare values in mouse-over with values indicated on the scale.
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/4cebd89c-75d7-4801-85fc-5b7d10f9c802)

**Expected behavior**
Like on PROD 
open https://www.visualize.admin.ch/de/v/4OFt2R6jxnyr
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/3df2a4da-f67e-4416-97c4-ba2e06aa4fa0)

**Environment (please complete the following information):**

- Visualize INT : v3.22.5 ([615675d]
- edge

**Comment by ortnever** [comment]
and the layout Problem : the left side is cutoff.
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/d7d5298f-623f-4113-8a57-bcd12c020ea9)

**Comment by bprusinowski** [comment]
Hi @ortnever, thanks for reporting the bug 🙇 

After the initial investigation, I believe the numbers are shown correctly, but the Y axis tick values are cut off, which leads to the impression they're wrong – I'll fix the layout problem and hopefully it will be fine then 🤞

**Comment by ortnever** [comment]
exactly...I discovered the layout problem later ;-) !

**Comment by ortnever** [comment]
Hi Bartosz, I did a test on test.visualize and everything was fine. But not on INT. Is trhe last release installed?
Could check the problem with y-Axis. I tried with line chart. Could it be the reason?
https://int.visualize.admin.ch/de/v/fk-ItSBbitF1
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/5a915391-9449-4ff8-9a4e-ab6bf84e4dfc)

**Comment by ortnever** [comment]
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/20e5c434-422f-4f6b-9ae2-d9670b6b4793)
