### ISSUE TITLE
Compositions

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1191]

**Comment by bprusinowski** [comment]
Preview link: https://visualization-tool-git-feat-dashboards-1-ixt1.vercel.app/en?dataSource=Prod

**Comment by sosiology** [comment]
- Tab Layout is done, but other layouts are not yet implemented
- Only one URL and the possibility to switch to the tab to have dedicated URLs the additional effort is estimated to be a bigger efffort: ca. 1-2days.
