### ISSUE TITLE
Minor alignment issue on interactive filters

### ISSUE THREAD

**Issue by adintegra** [visualize-admin/visualization-tool#1197]
**Describe the bug**
There's a minor alignment issue for interactive filters when adding more than two, potentially related to whether the filter titles have capital letters (see video). Tested against current deployment on INT (v3.22.7). 

**Expected behavior**
Filter dropdowns are aligned horizontally.

https://github.com/visualize-admin/visualization-tool/assets/6533245/4e226fba-f739-4fda-b992-0a2353ce7613

**Comment by sosiology** [comment]
@bprusinowski i tested this with the following chart https://int.visualize.admin.ch/en/v/cW5M0Qj8roKO?dataSource=Prod and it seems there is still some misalignment (also in the published chart)

**Comment by bprusinowski** [comment]
Hi @sosiology, the fix is currently available on TEST – let me know if I should deploy the changes to INT. I thought I'll wait with the deployment until it's "approved" on TEST 😅

**Comment by sosiology** [comment]
Sorry about that @bprusinowski on test it looks wonderful 🎉 
https://test.visualize.admin.ch/en/v/OktUL-a8JEGs?dataSource=Prod
