### ISSUE TITLE
Some dates are not displayed correctly

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#121]
Some dates are not displayed correctly in Visualize, although they are stored correctly in LINDAS.
See example below
Qualität der Badegewässer, Station : Curtinaux, la Vaudaire, le Pont etc., le 1.07.2008.
![image](https://user-images.githubusercontent.com/79834090/121163681-4a552e00-c84f-11eb-892d-5d7aeb9e7c06.png)
![image](https://user-images.githubusercontent.com/79834090/121164346-cf404780-c84f-11eb-8802-22f6ce8c14cc.png)

**Comment by herrstucki** [comment]
This is now improved (currently on dev)
