### ISSUE TITLE
perf: also consider dimensions with `{min,max}Inclusive` according to new solution provided by zazuko

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1219]
*Userstory*
 - As a data provider I'd like visualize to reuse conforming `{min,max}Inclusive` values from the shape (instead of firing another slow query per dimension to lindas)

*DoD*
- [ ] visualize also considers `{min,max}Inclusive` values also according to the new solution (within `rdf:List` behind `sh:or`)

see solution described in https://gitlab.ldbar.ch/bafu/visualize/-/issues/537#note_13077

thus there exist two official places where sh:{min,max}Inclusive is to expect:
1. directly on the dimension (implemented in visualize)
    ```
    <dim> sh:minInclusive ?min .
    ```
2. behind sh:or packed in a rdf:List (to be implemented yet in visualize)
    ```
    <dim> sh:or ( [..., sh:minInclusive ?min, ...] )
    ```

the second case can thus be queried traversing the properties:
```
<dim> sh:or/rdf:rest*/rdf:first/sh:minInclusive ?min .
```

see also code at https://github.com/visualize-admin/visualization-tool/blob/598b756ef7a9365f6d231b332aef2a8a93738f7b/app/rdf/queries.ts#L227-L228

see data samples at https://s.zazuko.com/phdBiS

cc  @kronmar

**Comment by sosiology** [comment]
Thank you for reporting @Rdataflow. I have added this issue to [gitlab](https://gitlab.ldbar.ch/bafu/visualize/-/issues/553), so it can be considered during sprint planning 
@bprusinowski could you please provide an estimate for the requested change? Thanks in advance!

**Comment by bprusinowski** [comment]
@sosiology I've added an estimate 👍 

@Rdataflow do you know what datasets / dimensions use the "new" way of specifying min / max values (maybe NFI ones)?

**Comment by kronmar** [comment]
The NFI ones will have it implemented by tomorrow (on INT and TEST) by tomorrow I reckon. I'll give you an update on zulip once they're up.

**Comment by bprusinowski** [comment]
Fantastic, thank you @kronmar!
