### ISSUE TITLE
drop `meta:hasHierarchy` in favor of `meta:inHierarchy`

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1224]
**context**
`meta:inHierarchy` is now settled and present in all the current cubes on all the environments. (in some cases both variants are present, but never deprecated `meta:hasHierarchy` alone.)

**DoD**
- [ ]  deprecated `meta:hasHierarchy` is removed from code

**Additional Information**
- codebase https://github.com/search?q=repo%3Avisualize-admin%2Fvisualization-tool%20hasHierarchy&type=code
- no cubes w/hasHierarchy w/o inHierarchy https://s.zazuko.com/g621bR

**Comment by bprusinowski** [comment]
This is already the case since some time 👍
