### ISSUE TITLE
Cube checker do not recognize that a cube is not found (or do not exist)

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#1226]
**Describe the bug**
Entering a dummy url in the cube checker gives the false feeling that the cube is found, with some valid an some invalid checks. See the screenshot about 'https://blabla'

This was annoying when I was trying to debug a new cube, I thought the remarks where helping me to understand why it does not show up in Visualize, but I finally find out that the cube was actually not found.

**Expected behavior**
When a cube is not found:
- have a check that says it is not found
- have no other check or at least all checks to "wrong"

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/6167669/0082981e-f7f4-4966-9635-e30c3fe2fc99)

**Comment by bprusinowski** [comment]
Closing, as Visualize now links to Zazuko's Cube Validator and Cube Checker has been removed.
