### ISSUE TITLE
Cube checker - changing the Data Source option is not taken into account

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#1227]
**Describe the bug**
If I change the Data source, for instance from 'int' to 'test', with the drop down menu
When clicking "Check" -> it comes back to the former data source.
If I change it in the URL, then it works

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/6167669/2514ec4d-2f09-4899-93b9-3029eeedb6e7)

**Comment by bprusinowski** [comment]
Closing, as Visualize now links to Zazuko's Cube Validator, and Cube Checker has been removed.
