### ISSUE TITLE
Support of time:TemporalEntity

### ISSUE THREAD

**Issue by tpluscode** [visualize-admin/visualization-tool#1234]
**Is your enhancement related to a problem? Please describe.**

For the Agro Market Data cubes we could benefit from supporting complex description of time. We would like to have time expressed as [time:TemporalEntity](https://prefix.zazuko.com/time:TemporalEntity), reusing the [Lindas core entities](https://lindas.admin.ch/governance/core-entities/), such as https://ld.admin.ch/time/year/1972

The problem is that Visualize only supports simple `xsd:date(Time)` for temporal dimensions. 

**Describe the solution you'd like**

It should be possible for a dimension to link to URIs of specific temporal entities and have that dimension annotated as time description with an appropriate `time:unitType`.

**Describe alternatives you've considered**

The OWL-Time ontology is one possible option. Others could be considered. I would, however stick to s single structure to support.

**Usecases and impact**

The necessity for more complex patterns will likely have an impact on query performance.

By referencing instances of [`time:TemporalEntity`](https://prefix.zazuko.com/time:TemporalEntity) it would be possible to form hierarchies of date periods, such as `Month -> Quarter -> Semester -> Year`

**Comment by sosiology** [comment]
Related WAM issue: https://blw-ofag-ufag.atlassian.net/browse/WAM-299

**Comment by sosiology** [comment]
@ptbrowne @bprusinowski would it be possible to isolate this change and deploy it to PROD without the other changes currently in review / in progress? Once we have this we can publish the BLW data on PROD.

**Comment by bprusinowski** [comment]
It looks like one "risky" thing is that 4.1.0 introduces a switch to a cached LINDAS endpoint 🤔

**Comment by ptbrowne** [comment]
@sosiology This change we could revert the particular change about change of endpoint from 4.1.0 = create a new version like 4.1.0 but without the change to the cached lindas endpoint.

@bprusinowski It's @Rdataflow who would know if the lindas cached endpoint is safe enough to use in production ?

**Comment by bprusinowski** [comment]
@ptbrowne yes, I think so. I am also not sure if we'd actually need to reach out to Abraxas to update the ENDPOINT env variable, would need to check how we retrieve the URL currently 🤔

**Comment by Rdataflow** [comment]
@ptbrowne AFACIT cached endpoint LGTM - unless @CDiGallo you see any objection?

cc @ludovicm67

**Comment by sosiology** [comment]
Thanks for the feedback @bprusinowski @ptbrowne @Rdataflow.  Based on the inputs, going for a deployment to PROD with the current int version asap seems like the safer approach. I have added the topic of deployment to PROD to the weekly call agenda for 28.05 to be discussed and decided how to proceed.
