### ISSUE TITLE
Next button not available on the first step, but no "error" message to the user

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#125]
When selecting the dataset, the first page does display the data, but the "Next" button is inaccessible (see printscreen)
![image](https://user-images.githubusercontent.com/6167669/121636345-11ec6480-ca88-11eb-9767-671d61abe78a.png)

As the button is inaccessible, I guess the tools "knows" what is incorrect, and could display a message to the user.
We are currently investigating this with Jeremy, it could be that the values do not have a numeric type, but only Jeremy new about that, seeing the left alignement of the values.

**Comment by FabianCretton** [comment]
It seems that this is working now, the values are right-aligned, next button is available.
@herrstucki  Was it finally a bug in the visualization tool, or in the data ? (important for me for those px cubes transformations).

**Comment by herrstucki** [comment]
It could have been fixed by https://github.com/visualize-admin/visualization-tool/commit/35379f0ccbde60f5957f51ad9c714295038c3c34. If I recall correctly, some of the non-Cube Creator cubes had double/float as datatype which we initially didn't support.

I will close the issue then!
