### ISSUE TITLE
Do not Always Start y-Axis at Zero

### ISSUE THREAD

**Issue by bequrios** [visualize-admin/visualization-tool#1255]
**Is your feature request related to a problem? Please describe.**
If there is a visualization, where the relevant y-axis values are in a limited range of values that is far from zero, letting the y-axis start at zero is not helpful for the visualization. See screenshot: 
![grafik](https://github.com/visualize-admin/visualization-tool/assets/22146779/afe32495-e49c-485c-8c07-92a0ab65120f)

**Describe the solution you'd like**
There should be a possibility to let the y-axis start at values different from zero. There could be a "auto-tune" function to choose the right values for the y-axis depending on the data that would be displayed. But this function should be optional, because sometimes, it is very important that the y-axis starts exactly at zero no matter what the data is.

**Usecases and impact**
I think there must be tons of visualizations that would benefit from such a behaviour.

**Comment by sosiology** [comment]
Completed in Sprint 5.8 tracked here: https://gitlab.ldbar.ch/bafu/visualize/-/issues/599
