### ISSUE TITLE
Error by editing Published Chart

### ISSUE THREAD

**Issue by LiamBAFU** [visualize-admin/visualization-tool#1259]
I got a completed Visualization from someone. I wanted to Edit the Visualization again to see what filters and settings they put in.
When i clicked on the Horizontal axis which is Geburtsjahr in this Visualization i get a black screen with the message: "Application error: a client-side exception has occurred (see the browser console for more information)."
I first thougt i probably am the only one who gets this Issue because it says client side but i made someone else do the same thing as i did with the same Published Visualization and she got the same error message as me when she clicked on the horizontal axis.

When i open the same Data set by myself and click on the horizontal axis i havent gotten this error message.

**To Reproduce**

1. Open up the Link to the published chart: https://int.[visualize.admin.ch](https://int.visualize.admin.ch/de/v/xnf88WuNFK_L?dataSource=Int)/de/v/xnf88WuNFK_L?dataSource=Int
2. click on "open and edit this visualization"
3. Click on the horizontal axis

**Expected behavior**
It should open up the horizontal axis settings

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/145760304/3d133a86-7c0d-48ea-8096-3c71cc001f91)

**Environment (please complete the following information):**

- Visualize environment and version: v3.24.0 ([35dd61f](https://github.com/visualize-admin/visualization-tool/commit/35dd61f26a145be20f83da317a9e9835793f6818))
- Microsoft Edge Version 119.0.2151.44 (Offizielles Build) (64-Bit)

**Comment by sosiology** [comment]
thanks for reporting this @LiamBAFU we will investigate.

**Comment by sosiology** [comment]
@bprusinowski i tested this and could reproduce the error. However when I recreate the exact chart (see: https://int.visualize.admin.ch/v/FTFqAgg2vKCP?dataSource=Int) i cannot reproduce the error. I am wondering if the data changed, causing the error Liam reported.

**Comment by Rdataflow** [comment]
@sosiology fyi: cannot reproduce here on firefox. related to browser?

**Comment by sosiology** [comment]
Thank you for the hint @Rdataflow. I will test on different browsers and report the results.

**Comment by sosiology** [comment]
@LiamBAFU I retested the reported bug (using this link: https://int.visualize.admin.ch/de/v/xnf88WuNFK_L?dataSource=Int)  this morning on various browsers including: Firefox, Safari, Chrome and Edge and couldn't reproduce the error anymore (thanks for the hint @Rdataflow). Could you retry and let me know if the error persists on your side? Thank you.

**Comment by LiamBAFU** [comment]
I don't get the error message anymore. Thanks for looking at the problem :)
