### ISSUE TITLE
Regression on INT : Filter problem by Pie Chart 

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1277]
On Int it is no longer possible to configure a Pie Chart correctly because the Key dimension filters no longer appear automatically and cannot even be added. 

**To Reproduce**

1. Open https://int.visualize.admin.ch/en/v/WZTTkoX3IauM
2. Copy and Edit this Visualization
3. Select "Pie Chart"
4. Edit Segmentation
5. Select Dimension "Art der Bewegungen" as segmentation
6. Back to main
8. See error : "Jahr" isn'tautomatically selected as Filter.

**Expected behavior**
 The Dimension "Jahr" should appear as Filter like on PROD Version : https://www.visualize.admin.ch/en/v/u3kJefbrNYCZ

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/9fdf83a3-e2d5-441a-a569-716db253169b)

**Environment (please complete the following information):**

- Visualize environment and version: v3.24.1 ([e60bae8]
- Browser and version : Edge

**Additional context**

**Comment by bprusinowski** [comment]
Hi @ortnever, thank you for reporting the bug!

We also identified and fixed it already in the latest TEST release. I double checked your example on TEST and it works correctly there (see https://test.visualize.admin.ch/en/v/1rRMW3H5PejZ).

I'll close the issue, let me know if the problem still appears for you.
