### ISSUE TITLE
unstable scrollbar layout makes chart width flickering

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#130]
due to some unstable CSS layout some charts happen to flicker (>30Hz) between two unstable states.

currently observed at step3 (i.e. starting with https://dev.visualize.admin.ch/create/new?from=IcScLx63qIuO at certain browser width i.e. 1570px)

* state A (with scrollbar)
![image](https://user-images.githubusercontent.com/26090254/132335536-00f011cf-62b1-4bdb-b7b8-d9f2867b5626.png)

* state B (w/o scrollbar)
![image](https://user-images.githubusercontent.com/26090254/132335120-5f394f65-96f8-4f3a-a70c-85bdda0179c0.png)

**Comment by herrstucki** [comment]
Yes this is because of automatic resizing and the scrollbar appearing and disappearing. Will investigate how to fix this.

**Comment by Rdataflow** [comment]
did you deploy this change already?
nb: it still flickers in some cases as of now 😢

**Comment by herrstucki** [comment]
It should be fixed on dev already … maybe there is an additional issue like described here: https://bugs.chromium.org/p/chromium/issues/detail?id=1206298

@Rdataflow is the zoom level in your browser 100%? Are you using Edge?

Possible fix: https://github.com/adazzle/react-data-grid/pull/2389/files

**Comment by Rdataflow** [comment]
https://dev.visualize.admin.ch/create/new?from=IcScLx63qIuO
above situation reproduces at 100% zoom level 
using chromium edge versions (v91 and v92)
- i.e. @body size: 1989 x 1110
and firefox (v78.3.0esr) as well
- i.e. @body size: 2027×1108
other browsers have not been tested
