### ISSUE TITLE
Big cube testing: Error on the first page after DataSet selection 

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#1304]
As discussed recently, I am trying out a cube with millions of observations.

Lindas: TEST
Cube name: "Exp/Imp by commodity group (pipeline)" 
Status: Draft

The total is 10 millions observations, but I am loading the observations by chunks of 2 millions.

I did successfully visualize the cube with the first 2 millions observations.
The slow part was not the display of a graph when "Starting a Visualization", but the very first screen after the selection of the dataset, but it worked and the performance to display the graph was fine.

Now that I have uploaded the second part (thus with a total of 4 millions observations), the first screen after the dataset selection does give an error - after more than 10 minutes of "Loading data...":
![image](https://github.com/visualize-admin/visualization-tool/assets/6167669/06974b9a-2770-4756-b525-e19e8cc5ce50)

[Link to open that page](https://test.visualize.admin.ch/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22waren%22%2C%22includeDrafts%22%3Atrue%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_ahst_exp_imp_pipeline%2F1&dataSource=Test).

Is it possible to explain why the very first page fails to load ?

For information: there are 5 key dimensions. 4 of them are "NominalScale" with the list of URIs specified with sh:in.
But the 5th one is IntervalScale and I did not yet add the min/max values as I do not have them yet. Could this be the problem ?

If we can pass this first page, than we can try the graphs:
We already suspect that the Table view, with no paging, will cause problems as it would try to display all observations.
However, the other graphs might work fine.

**Comment by Rdataflow** [comment]
it appears the timeout happens in some sparql query - just guessing it could be a select distinct

@FabianCretton may I suggest you try
- [ ] add `sh:nodeKind sh:Literal` to literal dimensions
- [ ] add `sh:minInclusive` and `sh:maxInclusive` values (the real ones or at least some fake values)

then let me question
- [ ] is there a reason to have IntevalScale or can you pass to RatioScale for the measure dimensions?
- [ ] is there a reason to have Land with IntervalScale or can you pass to NominalScale?

in case you still get similar issues I suggest you furthermore
- [ ] reduce the uploaded data back to 2M obs - so you still visualize it
- [ ] ensure the shape is completely uploaded
- [ ] debug from the reduced set in visualize debug panel to detect which of the queries run but run slow...

**Comment by FabianCretton** [comment]
Thank you @Rdataflow for your input. Yes, I will do as you say with corrections and improvements. Hope I can do it asap, I will then update the information here.

**Comment by FabianCretton** [comment]
Here are the last news, the cube can now be displayed:
[Link to open the cube's preview](https://test.visualize.admin.ch/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22waren%22%2C%22includeDrafts%22%3Atrue%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_ahst_exp_imp_pipeline%2F1&dataSource=Test).

It is not yet the full cube with 10 millions observations, but 6.5 millions ([query the number of observations](https://s.zazuko.com/ht8yVF))
As the filters take some time to update, I did stop the data upload so that we still have a "usable" cube.

The corrections to allow the display of the preview page were the proposal of Thomas:
- change the Land dimension to NominalScale, also creating "fake" labels for the display ("land" + ID)
- add sh:nodeKind sh:Literal to literal dimensions
- RatioScale for the measure dimensions

After those first corrections, the preview was still failing (certainly the DataCubeComponents() graphQL query).
This was solved by adding for the 4 measure dimensions:
- dataKind xsd:decimal
- min/max values
As querying the min/max values for all 4 dimensions takes around 1 minute, I guess some optimisation is possible (the data preview should not fail after a few minutes if min/max are not specified).

Currently the Columns graph can be displayed with "Country" on the X axe.
Changing the value of a filter does take a little while to update the graph, but much more time to update the filters themselves.

**Comment by FabianCretton** [comment]
En complément: 
I did sometimes create cubes with named nodes for dimensions metadata.
It was the case for instance for a template pipeline used to learn how to create a pipeline.
But Visualize seems to no more accept Named Nodes here -> [my question to IXT](https://zulip.zazuko.com/#narrow/stream/40-bafu-ext/topic/Visualize.20dimension.20metadata.20as.20named.20nodes.20.3F/near/382433)

**Comment by bprusinowski** [comment]
Hi @FabianCretton, am I right in assuming that we can close the issue (based on our conversation on Zulip)?

PS. Thanks @Rdataflow for suggesting the fixes on the data side 💯

**Comment by FabianCretton** [comment]
yes, thanks
