### ISSUE TITLE
Visualize Displaying a GraphQL error, while SPARQL queries find the data

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1305]
**Bug Description**

While working on a cube **[UBD01041 Qualität der Badegewässer Schweiz (Test 2)](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd01041-qualitat-der-badegewasser-schweiz-test-2-mvx7ne1xneq/csv-mapping)** I suddenly got this error below when I was trying to check the result in Visualize:
![GraphQL Error ](https://github.com/visualize-admin/visualization-tool/assets/111350367/daf6421e-635d-4f88-a5eb-ee206c965190)

This error only occured when I went to replace the small csv file with the big counterpart of this cube **[UBD01041 Badegewässer_LODFIX](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd0141badegewasserlodfix-xvgp4ovrwy8/csv-mapping)**
The cubes have the same dimensions and I created the project from an exported trig-file of **UBD01041 Badegewässer_LODFIX**.

Also when replacing the file again with the oneliner file of the **UBD01041 Qualität der Badegewässer Schweiz (Test 2)** the error persists for visualize despite it working before and the data being fetchable with [SPARQL queries](https://s.zazuko.com/2gAPN6C)

**To Reproduce**

1.  Export trig-file from [UBD01041 Qualität der Badegewässer Schweiz (Test 2)](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd01041-qualitat-der-badegewasser-schweiz-test-2-mvx7ne1xneq/csv-mapping) and create new Project
2.  Import the csv-file from [UBD01041 Qualität der Badegewässer Schweiz (Test 2)](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd01041-qualitat-der-badegewasser-schweiz-test-2-mvx7ne1xneq/csv-mapping) and run both transformation and publish. Visualize should work fine
3. Replace the csv with the one from [UBD01041 Badegewässer_LODFIX](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd0141badegewasserlodfix-xvgp4ovrwy8/csv-mapping) and retransform and republish
4. Error should be visible when opening the cube in Visualize 
5. Replace the csv with the original from [UBD01041 Qualität der Badegewässer Schweiz (Test 2)](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd01041-qualitat-der-badegewasser-schweiz-test-2-mvx7ne1xneq/csv-mapping) and repeat transformation and publish
6. See the error still when opening the cube in Visualize

**Comment by tboeni** [comment]
As of today, I tried to republish the above mentioned cubes without any changes and now Visualize is fetching them properly.
I will still leave this issue up, since I do not know if there was anything changed or if this might have further impacts in the future

**Comment by bprusinowski** [comment]
Hi @tboeni,

thanks for reporting the problem. It looks like it's connected to backend / Stardog infrastructure failing from time to time, we also monitor the status of LINDAS endpoints internally, and this problem (code 502) appears quite often.

You can also see our public status page here: https://visualization-tool.status.interactivethings.io, here we monitor PROD endpoints. It looks like your cube was present on INT, so this link might not be super-helpful for this case, but just FYI :)

Maybe we should bring this topic up and let the LINDAS team know about it @adintegra @sosiology?

**Comment by tboeni** [comment]
Hi @bprusinowski,

Thanks for your comment on the matter!
I did check the status then at everything was green-lit which did confuse me a little and that's why I decided to report it as an issue, as there might be something more unusual involved :-)
