### ISSUE TITLE
Title is not displayed on the charts

### ISSUE THREAD

**Issue by leticiapr** [visualize-admin/visualization-tool#1307]
If the diagrams are displayed in Visualize, you cannot specify a title. Even if you want to edit it, the function is not available. 

You should be able to enter a title so that you know where you are. 

**Below is the screenshot of the problem:**

The red box should contain the title above the diagram

<img width="826" alt="issue_title" src="https://github.com/visualize-admin/visualization-tool/assets/157011391/926523f5-1f9d-4df7-bd4f-34cd4ffca77e">

Microsoft Edge
Version 120.0.2210.121 (Offizielles Build) (64-Bit)

Visualize v3.25.0 (1b7a837)

**Comment by sosiology** [comment]
@leticiapr Thank you for your note. It is possible to enter a title for a composition, this however is done in the "Layout Option" step (after the charts are edited and before the visualization is published). 


![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/28c3dce8-61c0-4dbe-be1a-d5367729c0da)

**Comment by bprusinowski** [comment]
Note that the layout step feature is still behind a flag, so there is a need to go to https://test.visualize.admin.ch/en?flag__layoutStep=true to enable it 👀
