### ISSUE TITLE
"latest" not selectable

### ISSUE THREAD

**Issue by leticiapr** [visualize-admin/visualization-tool#1310]
"latest" is not yet selectable

**To Reproduce**

1. open this link: https://int.visualize.admin.ch/create/new?copy=AYYGahfke9Nh 
2.  here you cannot see "latest", should be displayed in the sidebar

**Expected behavior**
you should be able to select "latest" in the sidebar

**Screenshots or video**

![image](https://github.com/visualize-admin/visualization-tool/assets/157011391/3ff19359-608a-4b90-b987-2409b54bdcd3)

Visualize environment and version: [e.g. INT v3.25.0]
Microsoft Edge: Version 120.0.2210.121 (Offizielles Build) (64-Bit)

**Comment by ortnever** [comment]
I don't know if the description of the problem is vclear enough...

For ordinal time dimensions, such for LFI, the "use most recent date" option doesn't work yet.
https://int.visualize.admin.ch/create/new?copy=AYYGahfke9Nh

**Comment by bprusinowski** [comment]
Hi @ortnever, thanks for clarifying – this should be possible once we merge #1311 :)
