### ISSUE TITLE
Not working Datasets

### ISSUE THREAD

**Issue by LiamBAFU** [visualize-admin/visualization-tool#1313]
**Describe the bug**
There are a lot of Datasets on Prod that are not working for me. They all have the same Title: "Marktzahlen Milch und Milchprodukte"
If i open them there always is a error message.

![image](https://github.com/visualize-admin/visualization-tool/assets/145760304/4f34d63d-6f69-473b-8351-d3a0d96ed1e4)
![image](https://github.com/visualize-admin/visualization-tool/assets/145760304/44687f05-ab1a-4ffa-98a4-a4cde99f84b3)

**Environment (please complete the following information):**

Microsoft Edge
Version 120.0.2210.121 (Offizielles Build) (64-Bit)
v3.25.0 (1b7a837)

**Additional context**

**Comment by sosiology** [comment]
Closing this issue as it is upstream and the datasets are now on INT and appear to be working there as expected
