### ISSUE TITLE
Locations Defined Via Shared Dimension Not Visible On Map

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1314]
As described in the title when choosing to display the [map](https://int.visualize.admin.ch/en/v/y9ua75vp5N8-) for the [bathing wate quality](https://int.visualize.admin.ch/en/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd0141_lodfix%2F15&dataSource=Int) not a single point shows up. I tried replacing the Shared Dimension with a concept table and this works fine for the map graphic [here](https://int.visualize.admin.ch/en/v/QmB1AznheN6j). However, the strange part is that I created "Bathing Site" in this cube via a concept table and "Bathing Site new" via the shared Dimension and they both seem to work here. But for the original cube it does not. 

Could this be related to **https://github.com/visualize-admin/visualization-tool/pull/1311** in anyway?

**To Reproduce**

1. Simply click on the provided links and select the map display
2. See error

**Expected behavior**
See the dots on the map just as in the 2nd, smaller cube.

**Comment by ortnever** [comment]
Could we please solve this problem or tell us what is the problem with this cube because we have to publish the last update of the dataset on PROD.

**Comment by bprusinowski** [comment]
Hi @ortnever @tboeni, I am taking a look and will try to get back to you shortly 👀

**Comment by bprusinowski** [comment]
@tboeni @ortnever it should work correctly on TEST now 🤞

**Comment by ortnever** [comment]
thank you Bartosz. @tboeni : could you test please ! Thank you in advanced for your feed-Back.

**Comment by tboeni** [comment]
> @tboeni @ortnever it should work correctly on TEST now 🤞

@bprusinowski I tried it on TEST and for me it seems to be working fine [Bathing Water Qualitity](https://test.visualize.admin.ch/de/v/gr5AV6m0KA4u). Do you expect the fix to be released with the next sprint?

**Comment by bprusinowski** [comment]
Hi @tboeni, the fix should be deployed to INT by the end of this sprint at the latest. From what I've heard, we are aiming for a PROD deployment sometime in mid March – it for sure will be deployed along with all the other changes then 👍

**Comment by ortnever** [comment]
@bprusinowski : There are some strange rectangles on the map, depending on the zoom.
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/ed4b314f-c655-468e-95ed-de2778dcb3fc)

**Comment by bprusinowski** [comment]
@ortnever I am taking a look, thanks for reporting 👍

**Comment by bprusinowski** [comment]
@ortnever the problem should be fixed on TEST once it redeploys (up to 30 mins) :)
