### ISSUE TITLE
Bug with "use most recent" option

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1317]
To reproduce :

1. Copy and edit this visualisation : https://int.visualize.admin.ch/v/ozxDF5KXa3YU?dataSource=Prod
2. Disable  the "use most recent" option on the "Date" dimension filter.
3. Reactivate "use most recent" option
-> Data exists for this date (see table), but instead of displaying the data Visualize displays a message saying that there is no data for the selected filter combination.
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/0ee40d95-49be-4790-81cf-9301e19f07b4)

![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/bde63a8e-30cc-4146-b473-a012f6979613)

![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/cf9a0a53-a2fd-4b65-9f15-759ccd695d30)

- Visualize environment and version:v3.25.0 ([1b7a837]
-  Edge

**Comment by Rdataflow** [comment]
@bprusinowski very good this now also works for [ordinal time](https://test.visualize.admin.ch/v/RvcsU3PKuD6s?dataSource=Prod) 👍
