### ISSUE TITLE
Date 01.01.1970 01:00 displayed by default when "Date" Field is empty

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#132]
When the "Date" field is empty, the date 01.01.1970 01:00 is displayed by default.
Example : "Schwermetallbelastung des Bodens" (cube UBD0066 Bodenbelastung (final)". There are 7 stations for which sampling has been "rescheduled" to the next period. For these records the "reference date" (Probenahmedatum) and "value" fields are empty in the csv.
These records could be deleted (not interesting for the charts). It is nevertheless interesting to be able to display this information in a table.

**Comment by Rdataflow** [comment]
This seems quite unexpected, as those values `cube:Undefined` shall not be treated as `0` (a.k.a. `01.01.1970` for time)

**Comment by herrstucki** [comment]
I agree that this is can be considered a bug but as a sidenote I think that there should be no undefined values allowed in a key dimension (not sure if it is in fact one in this case).

**Comment by ortnever** [comment]
It isn't a key dimension in this case.

**Comment by herrstucki** [comment]
Implementation note: Concepts have URI `cube:Undefined`, literals have empty value `""^^cube:Undefined`

**Comment by ptbrowne** [comment]
Fixed in #146
