### ISSUE TITLE
Browser Tab Closes when chart is published

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1321]
See: https://int.visualize.admin.ch/v/EbXixKlDKslp?dataSource=Int 
To Reproduce: 
1. COpy edit VIsualization 
2. Publish visulisation 
3. see browser tab closes

**Comment by bprusinowski** [comment]
Hi @sosiology, I was taking a look and couldn't reproduce the issue. Could you check if the problem still persists? 🙏

**Comment by sosiology** [comment]
Hi @bprusinowski thanks for the note. I tested it again this morning, and could not reproduce. Closing this issue.

**Comment by tboeni** [comment]
Hi @sosiology @bprusinowski 
When trying to publish a visualization from this https://int.visualize.admin.ch/de/v/nkmHKm1hUznL cube, i experience the above mentioned crash / closure of the tab.

**Comment by bprusinowski** [comment]
Hi @tboeni, thanks for a hint, I'll take a look at this 👍

**Comment by sosiology** [comment]
@bprusinowski thanks for the fix. I tested it with the following chart https://test.visualize.admin.ch/v/K7XYdAcJtUJZ?dataSource=Prod (same cube as the above charts) and could not reproduce it. 

FYI: @tboeni the fix is curently on TEST.

**Comment by sosiology** [comment]
Rested on INT and worked as expected: https://int.visualize.admin.ch/v/P2XZZjyO_jZt?dataSource=Prod
