### ISSUE TITLE
perf: `DataCubeComponents` skip get values w/o filters

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1323]
**Is your enhancement related to a problem? Please describe.**
Currently the DataCubeComponents GQL query asks for distinct values on a dimension.

**Steps to reproduce**
1. goto https://test.visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1&dataSource=Test&flag__debug=true
2. open GQL debug tool
   <details>

   ```bash
   
   time curl 'https://test.visualize.admin.ch/api/graphql' -H 'x-visualize-debug: true' -H 'x-visualize-cache-control: no-cache' --data-raw '{"query":"query DataCubeComponents($sourceType: String!, $sourceUrl: String!, $locale: String!, $cubeFilter: DataCubeComponentFilter!) {\n  dataCubeComponents(\n    sourceType: $sourceType\n    sourceUrl: $sourceUrl\n    locale: $locale\n    cubeFilter: $cubeFilter\n  )\n}\n","operationName":"DataCubeComponents","variables":{"locale":"de","sourceType":"sparql","sourceUrl":"https://test.lindas.admin.ch/query","cubeFilter":{"iri":"https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1","componentIris":["https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/land","https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/verkehrsrichtung","https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/warenart","https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/wert_chf","https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/zeit","https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/zusatzmengencode"],"filters":{"https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/verkehrsrichtung":{"type":"single","value":"https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/verkehrsrichtung/1"},"https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/zeit":{"type":"single","value":"https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/zeit/198801"},"https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/land":{"type":"single","value":"https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/land/1"},"https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/zusatzmengencode":{"type":"single","value":"https://environment.ld.admin.ch/foen/fab_ahst_exp_imp_pipeline/1/zusatzmengencode/104"}}}}}'
   ```
   </details>
4. observe unnecessary query happening https://s.zazuko.com/LzpvWK (~20s)

**Describe the solution you'd like**
The first of those queries happens w/o any FILTER and can be skipped. Instead rely on the values given in the shape per `sh:in` as it's already fetched in another query beforehand https://s.zazuko.com/ti27Ay see spec at https://cube.link/#usage-of-code-lists

**Describe alternatives you've considered**
stick with bad performance :upside_down_face: 

**Usecases and impact**
vastly speed up all the similar cases (up to -20 s)

**Additional context**
called function with empty filterList https://github.com/visualize-admin/visualization-tool/blob/060ddf17e29b05cdda4a4c0a756f402f5134908e/app/rdf/query-dimension-values.ts#L152-L157 

@bprusinowski yet another quick performance win :smile:

**Comment by bprusinowski** [comment]
Hi @Rdataflow, thank you for reporting the issue.

I am not sure if I can identify the problem – when going to the link shared in the issue and opening the debug panel, the `DataCubeComponents` query takes 1.6s and I can't find the unnecessary query that asks for dimension values without filters applied. Am I missing something obvious? 🤔

**Comment by Rdataflow** [comment]
@bprusinowski sorry it was the wrong link - we need to look at /create

**Comment by sosiology** [comment]
Hi @Rdataflow 
As we already have quite a few open issues to finalize before the 20.02, and this is an enhancement, I will plan it in to be tackled it in the next sprint (v_5.6 starting on 21.02.2024).
cc: @bprusinowski @adintegra

**Comment by bprusinowski** [comment]
Fixed by https://github.com/visualize-admin/visualization-tool/pull/1360.
