### ISSUE TITLE
Data loading failure -Time interval as temporal dimension?

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#133]
Since I made a small modification to my "Bodenbeladtung (final)" cube, the data is no longer displayed in Visualize (see Schwermetallbelastung des Bodens, Versions 15 and 16, version 14 was published before the modification).
For this cube I used the column "Beprobungszeitraum" (1985-1989, 1990-1994 etc.) as key Dimension because this is the one usually used in the graphs, and I don't want the sampling date as mandatory Filter. So I had to define the Datatype as a string and not a date.
However, in Visualize, if I want to make a line chart using this dimension on the x-axis, following conditions are required : Temporal type (Dimension of Continuous/Interval type that is marked as Temporal and contains Date/DateTime values).
So I modified my cube in the following way:
- I replaced the ID of the "samplingperiod" table with a year and set the Datatype "Year".
- I set the metadata of the "SamplingPeriod" dimension as below:
![image](https://user-images.githubusercontent.com/79834090/135818962-ed627033-c739-471e-a2dd-df26b4d7b0f2.png)
The transformation was successful but the data can't be loaded in Visualize.
I saw an issue in GitHub to treat these "survey periods" as time dimensions (#128) but I'm looking for an immediate solution and furthermore my original data aren't entered as "Start date" and "End date".

**Comment by herrstucki** [comment]
@ortnever I'm also adding this to the release project, so we can investigate. I think the tool is now getting confused by a temporal dataKind which is in fact a concept (the "Beprobungszeitraum").

I would probably just treat it as an ordinal dimension without time semantics. That way you can at least use it in a bar chart which appears to me to be the correct visualization type anyway. In a line chart, I wouldn't know where on the x-axis to place the point (at the beginning or end of the interval? The middle?).

To do this correctly it very much looks like the same issue as described in #128.
