### ISSUE TITLE
Feedback Chart creation

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#1332]
Some feedback after some time away from the project. Feedback is mostly concerning the chart creation, and the options in the left panel.

### Comparison

I see the new comparison feature and wonder how to compare here. All the options are grey and not clickable interactive.

- [ ] Add a tooltip to comparison section explaining why can't I add a chart from here ?
- [ ] Why is there a "!" next to comparison ? Shouldn't it be a "?", I am not sure it should be this prominent.
- [ ] Provide a way to solve the situation (Add a new cube button ?)

### Scatterplot

- [ ] Add a tooltip explaning why I cannot make a scatterplot

### Title & description

- [ ] Add "OK" to description & title panels (same as back), I think it fluidifies and does not require the user to think "to accept, I need to press 'back'"

### Interactive filters

- [ ] Why has the "!" icon as the warning color in "Interactive filters", it is merely an information ?

**Comment by ptbrowne** [comment]
@KerstinFaye I think this issue would be interesting to take a look at.

**Comment by sosiology** [comment]
@KerstinFaye could you please review this on INT and move to the next lane if good for you?
