### ISSUE TITLE
"Multiple cubes found for ..." Error

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1341]
In light of the issue #1314 I tried to test wether it is possible to use PROD as the data source for the new changes to see the datapoints in the map display. However, when I try to load this particular cube in either the TEST or INT environment. I receive this error: 
![Mulitple Cubes Error](https://github.com/visualize-admin/visualization-tool/assets/111350367/935317bd-2002-4443-a79b-361d33d58eb7)

 [Environment TEST Source PROD](https://test.visualize.admin.ch/browse?previous=%7B%22includeDrafts%22%3Atrue%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd01041prod%2F1&dataSource=Prod)
Nothing is displayed, no way of creating a visualization

[Environment INT Source PROD](https://int.visualize.admin.ch/browse?previous=%7B%22includeDrafts%22%3Atrue%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd01041prod%2F1&dataSource=Prod)
Possible to start a visualization, but the error will be displayed instead of a graphic

[Environment PROD](https://visualize.admin.ch/browse?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22qual%22%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd01041prod%2F1&dataSource=Prod)
Visualize works as intended and there are no errors whatsoever

However, i checked multiple times via the Cube Creator, [SPARQL queries](https://s.zazuko.com/2B5GVJb) and the LINDAS webpage (https://environment.ld.admin.ch/foen/ubd01041prod/1) to see if the identifier is not unique. Though I did not find anything out of place. I only find one version of the cube (version 1) and only a single entry of this identifier.

Strangely, the outcome of using the PROD source is different for each of the 3 environments

**To Reproduce**

1. Click the provided links
2. See the differing behaviours of environments

**Expected behavior**
That each of the visualize environments behave the same or at least similar if the source is the same

**Comment by bprusinowski** [comment]
Hi @tboeni, thanks for reporting the issue. When investigating the results of the cube metadata query (https://s.zazuko.com/NNYbb8) I've noticed that there are two entries with different date published (2023-07-07 and 2024-02-15) but the same version (1) – in order to fix the errors, you'd need to bump the version of newer cube to 2 (or remove one of the published date properties, so we have only one combination of `cube version – date published`).

Let me know if this is possible 🤞

**Comment by tboeni** [comment]
Hi @bprusinowski, thanks for your inputs already!
I did republish the cube and it now works for INT, however there is still a problem that I cannot get the source of for TEST 
![Screenshot 2024-02-16 113404](https://github.com/visualize-admin/visualization-tool/assets/111350367/b8453a76-a324-434c-8341-5587e79285ec)

This happens for the new Cube -> [Link](https://test.visualize.admin.ch/browse?previous=%7B%22includeDrafts%22%3Atrue%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd01041prod%2F3&dataSource=Prod)

**Comment by bprusinowski** [comment]
@tboeni thanks for republishing the cube! The problem with TEST should be fixed once we merge #1345 🤞
