### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1359]
**Describe the bug**
Application crash

**To Reproduce**

1. Go to https://int.visualize.admin.ch/create/KkTeV9xmkrjW?dataSource=Prod

**Expected behavior**
no crash

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/26090254/9bcebbc1-e861-4225-831b-a93f7d7cb04f)

**Environment (please complete the following information):**
- Visualize environment and version: INT v3.26.1
- Browser and version: Firefox as well as Edge

**Comment by sosiology** [comment]
@Rdataflow thanks for reporting. We deployed a new version to INT shortly before you reported this bug, i wonder if this error happened becuase the application was not fully deployed yet. cc @ptbrowne @bprusinowski 

Could you also provide the name of the data set you used when the bug occured so I can try to reproduce the error? The link you shared takes me to the dataset overview. Thanks!

**Comment by Rdataflow** [comment]
@sosiology i observed this after the version 3.26.1 was deployed to INT. You can reproduce using the link wnich contains the IRI of the dataset or open it manually, Strompreis...

**Comment by Rdataflow** [comment]
Sorry here the relevan link https://int.visualize.admin.ch/create/new?cube=https://energy.ld.admin.ch/elcom/electricityprice&dataSource=Prod
