### ISSUE TITLE
Load single value per filter when entering the edit mode first and load unique values afterwards

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1372]
Currently, we need to wait for the filter panel values to load before a chart is shown. This happens due to fetching unique values per each filter – we could speed up showing of the chart by only loading one value per filter initially and then loading all unique values afterwards, so that the loading would be scoped purely to the filter panel, and not the whole application.

**User story**

I want the chart to not be waiting for the filter values to be loaded.

**Definition of Done**

When initially entering editing mode, filters are loaded with single values – so the chart doesn’t need to wait for them – and only then begin to fetch all available values.

**Comment by sosiology** [comment]
Thanks for preparing this @bprusinowski I tested on TEST and compared it to INT. It definitely _feels_ like the charts load faster with this change. Is there a way to test it more reliably?

**Comment by bprusinowski** [comment]
Thanks @sosiology! I think testing here should be mainly about going to several "random" datasets and see if they load correctly (filter values, observations, etc) – like on INT. The performance gain will be hard to put to numbers and reliably test, as it depends on many things, like size of the dimension, number of dimensions in cube, ... 👀 

I think the cube that benefits from this change most is this one: https://test.visualize.admin.ch/en/browse?previous=%7B%22order%22%3A%22SCORE%22%2C%22search%22%3A%22pipeline%22%2C%22includeDrafts%22%3Atrue%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_ahst_exp_imp_pipeline%2F1&dataSource=Test (previously it took around 30-50s for the chart to show).

**Comment by sosiology** [comment]
Thanks @bprusinowski got it! Assigning this issue to myself and @KerstinFaye for testing

**Comment by KerstinFaye** [comment]
I also tested it. Looks good. As you said, with some dataset it's more obvious, like the one you shared. 

Would it be possible to show the selected default filters greyed out, even though the filters are not loaded and selectable yet? I think it could benefit the user to at least see the default filters in a disabled state until they are all loaded to inform them of what they see?

![Screenshot 2024-03-04 at 16 01 03](https://github.com/visualize-admin/visualization-tool/assets/127507692/6758c67a-fc8a-4d0f-a36d-0dbd844303af)

**Comment by bprusinowski** [comment]
@KerstinFaye will do!

**Comment by sosiology** [comment]
@bprusinowski Reopening this issue for the UI Refinements mentioned by @KerstinFaye above, please let me know if you would prefer a separate issue.

**Comment by bprusinowski** [comment]
@sosiology closing after a discussion with @KerstinFaye, at this point we can't yet show a default value as we need to wait until its label is fetched (in the chart config we store "ids" of values, without labels).

**Comment by sosiology** [comment]
FYI @KerstinFaye @bprusinowski i documented this in the decision log. https://www.notion.so/interactivethings/Selected-default-filters-are-not-greyed-out-while-loading-this-is-due-to-the-fact-that-we-can-t-ye-748bc7d3fa3149fa83c9f134f70a0479?pvs=4 j
