### ISSUE TITLE
Ordinal time as default choice for x-axis

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1373]
**DoD**
- [ ] ordinal time is by default chosen as x-axis (like it's already default for interval time)

**Comment by sosiology** [comment]
@ptbrowne as mentioned in the comment from Thomas here: https://gitlab.ldbar.ch/bafu/visualize/-/issues/630#note_15105 they would like to have this enhancement in the upcoming release in March. Do you think that is feasible? Concretely it would need to be completed by the end of the week 29.02.2024

**Comment by bprusinowski** [comment]
Just to explain the estimate and user story (I think I was the one who added the estimate, and talked about this issue with Thomas during our sync): the need here is that we also consider ordinal temporal dimensions when finding preferred dimensions for a given chart type. In detail, we need to modify `findPreferredDimension` function to accept an array or dimension types, and have temporal dimension as first preferred choice, if such type is not present in a dataset, we would look for temporal ordinal dimension (this is only applicable for column charts). https://github.com/visualize-admin/visualization-tool/blob/41b2c353d3d573a11bfa795e45fd180c2b05ccec/app/charts/index.ts#L134-L156

**Comment by ptbrowne** [comment]
Thanks for the context @bprusinowski, yes @sosiology I think this would be feasible.

**Comment by sosiology** [comment]
Tested with Various NFI cubes and "Inventory" was shown by default for the x-axis. Approved from my side.
