### ISSUE TITLE
UI Improvements and Enhancements

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1374]
Issues that could be tackled: 
https://github.com/visualize-admin/visualization-tool/issues/1332

- Overlay alignment across the tool: Defined 3 sizes, define text styles for overlays
- UX Writing in the tool in the English language: Alignment of sentence-case across the tool
- [Feedback on Patricks finding](https://github.com/visualize-admin/visualization-tool/issues/1332) #1332
-  Tooltips: informing/warning the user when something is disabled: Alignment across the tool: Defining the way we inform the user (UX writing) https://www.figma.com/file/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?type=design&node-id=3284-65513&mode=design&t=9gzt3oOH14YJikTB-4
- Adding a save button after editing the title&description:
https://www.figma.com/file/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?type=design&node-id=3483-234001&mode=design&t=NoKQuqtCOulXJizj-4

**Comment by KerstinFaye** [comment]
- Overlay alignment across the tool: Defined 3 sizes, define text styles for overlays
- UX Writing in the tool in the English language (Aligning title case in the English language across the tool)
- Feedback on Patricks finding: https://github.com/orgs/visualize-admin/projects/1/views/20?pane=issue&itemId=53270412
- Warnings & alerts system: How and when do we inform the user if something is not working or not functioning
-  Tooltips: informing/warning the user when something is disabled: Alignment across the tool: Defining the way we inform the user (UX writing) https://www.figma.com/file/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?type=design&node-id=3284-65513&mode=design&t=9gzt3oOH14YJikTB-4

**Comment by sosiology** [comment]
@KerstinFaye could you check this in on INT and move it to the next lane (Ready for client review) if it looks good to you.

**Comment by KerstinFaye** [comment]
@sosiology 
These improvements seem to be implemented:
- Alignment of overlays
- Sentence-case for the English language

These improvements are not yet implemented (from the ticket #1332): 
- Tooltip for disabled chart-types
- Save button for Title & Descriptions
- Info icon instead of !-icon for Comparison charts

**Comment by sosiology** [comment]
@KerstinFaye for the "Save Button" i have added a ticket to the backlog https://github.com/visualize-admin/visualization-tool/issues/1427

could you create new tickets for the other 2 issues and add them to the to do list. Thank you

**Comment by sosiology** [comment]
Closing this issue. New issues created for the outstanding tasks. 
 
- Info icon instead of !-icon for Comparison charts #1449
- Tooltip for disabled chart-types #1448
- Add "Save" button to the title and description overlay #1427
