### ISSUE TITLE
Unable to select entire sub-categories for filter options with hierachies 

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1380]
Clicking on a sub-category in the filter options does not select or deselect the chosen sub-category. For example in [LFI: Themen nach Nadel- und Laubholz](https://int.visualize.admin.ch/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-96%2Fcube%2F2023-1&dataSource=Prod).
When editing the filter **region** the parent "Schweiz" can be selected and deselected and as well als the inidividual cantons under the sub-category "Schweiz - Kantone". However, it is not possible to select or deselect "Schweiz - Kantone" as a whole.

![sub-catergory-filter-bug-20240229](https://github.com/visualize-admin/visualization-tool/assets/111350367/0d005c01-429a-4e38-9cd5-0d6b9624df0b)

**Steps to reproduce the behavior:**

1. Click on the link [LFI: Themen nach Nadel- und Laubholz](https://int.visualize.admin.ch/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-96%2Fcube%2F2023-1&dataSource=Prod)
2. Edit the horziontal axis and choose "Region"
3. Click on "Edit Filter", deselect all and try to select "Schweiz - Kantone"
4. See error (Nothing happens)

**Expected behavior**
I would expect that all of the elements contained in this sub-category would be either selected or deselected, as it happens for the parent category

**Environment (please complete the following information):**

- Visualize environment and version: [INT v3.26.2 ([a9b1c44](https://github.com/visualize-admin/visualization-tool/commit/a9b1c4426494a0e945afbc3e1a2b696fd35541f6))]
- Browser and version [Microsoft Edge Version 120.0.2210.144 (Offizielles Build) (64-Bit)]

**Comment by Rdataflow** [comment]
@tboeni this was most probably an issue in the data which meanwhile has been fixed. Can you retry and report back? THX

**Comment by tboeni** [comment]
Closed this issue after discussing with @Rdataflow
