### ISSUE TITLE
After publishing a chart with separate URLs the layout option screen is still shown without any options

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1384]
**Steps to Reproduce**
1. go to https://test.visualize.admin.ch/en/v/BV8Nql433j1R?dataSource=Int
2. click on "Copy and edit this visualization" 
3. Republish the same visualizations but with the option "separate URLs" (select all visualizations to publish)
4. 3 new tabs open each with a visualization as expected. 
5. The penultimate screen before the visualization is published is still shown but with no options to go back or edit the visualizations

![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/fa06d748-589a-4f27-8a26-695485949ce1)

Additional context: 
When the page is reloaded the options are shown and the user can go back to the editor 

![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/232e58bd-9084-4afb-90a4-68d5c8e85e58)

Tested in Chrome and Safari.

**Comment by ptbrowne** [comment]
I guess this could be related to some refactors done while doing the draft feature. @bprusinowski I would have a look after I have move forward a bit with the "merging cubes" functionality.

**Comment by bprusinowski** [comment]
Thanks @ptbrowne, I'll take a look with this in mind 👍

**Comment by tboeni** [comment]
@sosiology @bprusinowski The being "stuck" on the penultimate screen which is still being shown looks a lot like what happened previously in issue #1379 :-)

**Comment by sosiology** [comment]
@bprusinowski i retested on Test, and now only 2 of the 3 charts open in a new tab (the map was not shown)


I used the same link as above to test  https://test.visualize.admin.ch/en/v/BV8Nql433j1R?dataSource=Int

**Comment by sosiology** [comment]
LGTM, thanks @bprusinowski

**Comment by sosiology** [comment]
Tested on INT, LGTM
