### ISSUE TITLE
Can't preview an old version of a cube

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#1390]
**Describe the bug**
It's not possible to preview an old version of a cube (cube not found error).

**To Reproduce**
1. Go to https://test.visualize.admin.ch/en/browse?dataset=https://environment.ld.admin.ch/foen/nfi/nfi_C-20/cube/2023-2&dataSource=Prod
2. See error (cube not found).
3. Go to https://test.visualize.admin.ch/_cube-checker?cubeIri=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-20%2Fcube%2F2023-2&dataSource=Prod
4. See that cube exists.

**Expected behavior**
A latest version of the cube should be loaded (2023-03), instead of throwing an error.

**Environment (please complete the following information):**
- Visualize environment and version: TEST v3.26.3 (9de2204)
- Browser and version: Safari 17.3 (19617.2.4.11.8)

**Comment by bprusinowski** [comment]
cc @Rdataflow

**Comment by sosiology** [comment]
Tested on INT, LGTM
