### ISSUE TITLE
Electricity price crashes

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1395]
**Describe the bug**
Electricity price cube crashes

**To Reproduce**

1. Go to https://test.visualize.admin.ch/en/browse?dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Felcom%2Felectricityprice&dataSource=Prod
2. Click on 'start visualization'
3. Wait & see nothing happens for a long while
4. See app reloads unexpectedly

**Expected behavior**
after a while display of a chart as on https://visualize.admin.ch/en/browse?dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Felcom%2Felectricityprice&dataSource=Prod

**Environment (please complete the following information):**
- Visualize environment and version: INT v3.26.3 and later

**Additional context**
- cannot reproduce on self hosted instance v3.26.3
- maybe OOM related (domain no longer responds for a while)
- AFAICT introduced by https://github.com/visualize-admin/visualization-tool/pull/1378/commits
- triggered by
   ```sh
    curl https://test.visualize.admin.ch/api/graphql -X POST -H 'content-type: application/json' -H 'x-visualize-debug: true' -H 'x-visualize-cache-control: no-cache ' --data-raw '{"query":"query DataCubeComponents($sourceType: String!, $sourceUrl: String!, $locale: String!, $cubeFilter: DataCubeComponentFilter!) {\n  dataCubeComponents(\n    sourceType: $sourceType\n    sourceUrl: $sourceUrl\n    locale: $locale\n    cubeFilter: $cubeFilter\n  )\n}\n","operationName":"DataCubeComponents","variables":{"locale":"en","sourceType":"sparql","sourceUrl":"https://lindas.admin.ch/query","cubeFilter":{"iri":"https://energy.ld.admin.ch/elcom/electricityprice","loadValues":true}}}'
   ```
- the generated SPARQL queries look fine and get a quick response each

cc @bprusinowski

**Comment by Rdataflow** [comment]
@bprusinowski @ptbrowne agreed 100% that having multiple datatypes is nonsense. IIRC it is not allowed with latest validation profile. 

Please retry with electricity price from LINDAS TEST which has correct datatypes... curious if this still reproduces the issue.

**Comment by sosiology** [comment]
@bprusinowski I just tested on test.visualize.admin.ch with data sources PROD and TEST - in both cases a chart is displayed after intial loading.
