### ISSUE TITLE
Dimension missing data type results in filters not working

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1404]
1. Go to: https://int.visualize.admin.ch/en/v/pkxj9BlxaM1L?dataSource=Prod
2. Copy and edit visualization
3. Add a filter
4. see error

Issue: The `Active Since` dimension misses a data type, which means that we can't properly filter the observations when checking for possible filters. It would be best to reach out to the maintainer of the cube to add a data type to this dimension 👀

_Originally posted by @bprusinowski in https://github.com/visualize-admin/visualization-tool/issues/1402#issuecomment-1991397373_

**Comment by Rdataflow** [comment]
@sosiology a situation we are well aware of 👍 

FYI: we prepared the new data on TEST and INT. The deployment to PROD is on hold because it depends on the new visualize version - otherwise it would break for other issues...

cc @bprusinowski

**Comment by Rdataflow** [comment]
@sosiology should be fixed now on prod👍️
