### ISSUE TITLE
error with possible filters after check `last date`

### ISSUE THREAD

**Issue by t0b3** [visualize-admin/visualization-tool#1415]
**Describe the bug**
after checking [x] `use last date` an error appears

**To Reproduce**

1. Go to https://test.visualize.admin.ch/create/new?copy=rvMNgJBlH4he
2. Click on use last date

**Expected behavior**
no error message

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/5751047/651bec6f-eb53-4c03-8345-f151ddd27053)

**Environment (please complete the following information):**

- Visualize environment and version: v3.27.1 aae7eec

**Comment by bprusinowski** [comment]
Hi @t0b3, thanks for reporting! Should be fixed on TEST :)

**Comment by sosiology** [comment]
Tested on INT LGTM. Tested with: https://int.visualize.admin.ch/v/diAWUz0rO_uM?dataSource=Prod
