### ISSUE TITLE
Download Full xls : Dimensions are missing

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1416]
Some Dimensions (dimensions that are not Key dimensions) are missing by download Full dataset on Visualize INT 

**To Reproduce**
1. Open https://www.visualize.admin.ch/en/v/t6ee4XGN_Ofz
2. Download Full datset in csv and in xls
3. look at Columns : They are 8 Columns
4. Opne same cube on INT : https://int.visualize.admin.ch/en/v/8m_Dl0WtYvjx
5. Download Full datset in csv and in xls
6. look at Columns : 4 columns are missing

**Expected behavior**
By Download "Full Dataset" all Dimensions which are integreted in the cube must be downloaded. See Behaviour on PROD with same Cube. 

**Screenshots or video**
Download with PROD :
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/1dc03a8f-ad1d-463b-aee6-1004cbd001c2)

Download same Cube with INT
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/12b78b7d-81c2-4115-9214-857c903fc538)

**Environment (please complete the following information):**

- Visualize environment and version:v3.27.1 [8c3e7f9]
- Browser and version : Edge

**Additional context**

**Comment by sosiology** [comment]
Tested on TEST and it looks good to me @bprusinowski. Can we deploy to INT?

**Comment by bprusinowski** [comment]
Thanks for testing @sosiology, I will deploy to INT :)

**Comment by sosiology** [comment]
@bprusinowski when testing on INT - the full data set with all columns works in the preview - but in the chart editor mode and published mode, i only get the 4 columns

**Comment by bprusinowski** [comment]
@sosiology it looks like the INT deployment still doesn't work 😭
