### ISSUE TITLE
eIAM Integration

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1422]
Enhance Visualize such that users can log in using an OIDC Identity Provider – in this case a [Swiss federal login](https://www.eiam.swiss/). Furthermore, they should be able to save visualizations as drafts and resume these at a later point in time.

DoD:
- [x] eIAM login is available in Visualize on TEST
- [x] eIAM login is available in Visualize on INT
- [x] eIAM login is available in Visualize on PROD
- [ ] A user can log in with his eIAM credentials in each of these environments and create visualisations.

**Comment by sosiology** [comment]
OIDC metadata for the connection to eIAM REF environment -> Info received Rene Kreidemacher

**Comment by adintegra** [comment]
Followed up on PKCE settings with BIT today – awaiting answer.

**Comment by sosiology** [comment]
Feedback BIT: Reduce request of the scope down to Open ID

**Comment by bprusinowski** [comment]
Might be solved with #1471

**Comment by sosiology** [comment]
can i support with testing anything?

**Comment by bprusinowski** [comment]
@sosiology not yet, we need to merge #1471 first (cc @ptbrowne)

**Comment by adintegra** [comment]
After merging #1471, looks like the Sign In currently takes the user to the Keycloak Login screen. IIRC we had this once before. Maybe a configuration issue somewhere @bprusinowski? 

<img width="487" alt="image" src="https://github.com/visualize-admin/visualization-tool/assets/6533245/e0c95c29-1bd0-4be3-8a5a-3f69ccbcfe08">

**Comment by bprusinowski** [comment]
@adintegra I am taking a look 👍

**Comment by bprusinowski** [comment]
I think that we get the correct information from Keycloak back, but have some problem with dealing with it afterwards. After a quick investigation it turns out it might [be related to Prisma](https://github.com/nextauthjs/next-auth/issues/3830), and e.g. a different type of `id` we get from Keycloak now.

It's hard for me to debug this without having access to logs – I pushed [a commit](https://github.com/visualize-admin/visualization-tool/commit/0609345311fd43050d8410fad0414a99a4fb76f7) with a debug `KeycloakProvider` flag set to true – once it deploys on TEST, we can do several attempts to log in, and then ask Abraxas for server logs to check what's the exact problem.

**Comment by ptbrowne** [comment]
Maybe it'd be good to try and connect to [abraxas servers](https://www.notion.so/interactivethings/Hosting-Abraxas-daf7c8df5fb5478fadf2b46da8164ec0?pvs=4) ?

**Comment by bprusinowski** [comment]
@ptbrowne it's a good idea, I can try to do it tomorrow 👍

**Comment by adintegra** [comment]
**Quick update:** After trying out various configurations (primarily around using Keycloak as an Authentication Bridge), I believe we may not need a Keycloak instance at all, but could connect directly to the BIT OIDC trust broker. This would simplify our architecture substantially.
BIT has provided the information that their trust broker/IdP is a custom implementation of Microsoft ADFS (Active Directory FS). While there is no built-in provider for this in `next-auth`, there is a [discussion here](https://github.com/nextauthjs/next-auth/discussions/6130) on how to go about implementing this. Thus, the next step would be to adjust our current implementation in line with this and test it.
/cc @bprusinowski

**Comment by bprusinowski** [comment]
I will try to change the implementation @adintegra and deploy to TEST to see if it works 👍 Thanks for the investigation 🙇‍♂️

**Comment by ptbrowne** [comment]
I could login in test.visualize.admin.ch with eIAM credentials, save a chart to draft then publish it 🎉 . @sosiology

**Comment by sosiology** [comment]
Closing this issue as the login is available on PROD now, please re-open if i missed something @adintegra
