### ISSUE TITLE
Rewrite GeoShapesByDimensionIri and GeoCoordinatesByDimensionIri queries

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1424]
From Gitlab Issue: Please check [there](https://gitlab.ldbar.ch/bafu/visualize/-/issues/644) before tackling the issues incase Thomas adds additional feedback or input

Currently, `GeoShapesByDimensionIri` **and** `GeoCoordinatesByDimensionIri` can be optimized

| Attribute | Localized |
| --- | --- |
| name | yes |
| geometry | no |
| wkt coordinates (for geo shapes) | no |
| latitude, longitude (for geo coordinates) | no |

**User story**

I would like the `GeoShapesByDimensionIri` and `GeoCoordinatesByDimensionIri` queries to be aligned with the new query pattern and optimized.

**Definition of Done**

`GeoShapesByDimensionIri` and `GeoCoordinatesByDimensionIri` queries are written from scratch and use `CONSTRUCT` approach, which should result in improved performance of fetching geographical entities.

**Comment by sosiology** [comment]
@bprusinowski this is on INT now correct?

**Comment by bprusinowski** [comment]
@sosiology yes 👍

**Comment by sosiology** [comment]
Wonderful. Thanks @bprusinowski - Informed Thomas via Gitlab

**Comment by sosiology** [comment]
Approved in Gitlab
