### ISSUE TITLE
Filter Issue in graph

### ISSUE THREAD

**Issue by nickeichmann** [visualize-admin/visualization-tool#1430]
**Description of the bug**
When I'm visualizing a graph, an error message appears. I already checked the quality of my cube design, I guess it is fine.

**To Reproduce**
Steps to reproduce the behaviour:

Link to the Cube (int): [Link](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!konzessionierte-tv-karte-9kaxawdkyy3/edit)
Link to the Visualization (int): [Link](https://int.visualize.admin.ch/en/browse?dataSource=Int&dataset=https%3A%2F%2Fcommunication.ld.admin.ch%2Fofcom%2Fmap_tv_konz)

1. I want to visualize my above linked cube. So I click on the according button on the Cube Creator Tool to get to the above-mentioned Visualize visualization. 
2. At Visualize, I click on the "Start a visualization" button.
3. I get a pretty bar plot, but at the filter menu I get an error statement: "An error happened while fetching possible filters, please retry later or reload the page." (see picture)
<img width="891" alt="image" src="https://github.com/visualize-admin/visualization-tool/assets/73659892/6c471a2e-9211-4cdc-a21a-a2b908ae5dc4">

4. According to the SparQL-[request ](https://s.zazuko.com/Gffv6T) it does some strange type of filtering.

**Expected behavior**
The error shouldn't be displayed.

**Environment (please complete the following information):**

- Visualize environment and version: INT 4.0.0
- Browser and version: Microsoft Edge Version 122.0.2365.92

**Additional context**
Maybe this issue corresponds to the bug #1431 .

**Comment by ptbrowne** [comment]
Hey Nick, and thanks for the bug report. We have put in place a basic checker for cubes and it seems like the cube you're linking does not respect some of the constraints. I can't say now if the bug you're experiencing surely comes from this, but I think first the checks should be green before we start investigating. Can you please check if everything is correct ?

- Cube checker against your cube: https://visualize.admin.ch/_cube-checker?cubeIri=https%3A%2F%2Fcommunication.ld.admin.ch%2Fofcom%2Fmap_tv_konz%2F8&dataSource=Prod
- Cube checker against a NFI cube: https://visualize.admin.ch/_cube-checker?cubeIri=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_C-94%2Fcube%2F2023-1&dataSource=Prod

(I noticed that we have a check that seems incorrect in reporting the number of dimensions)

**Comment by Rdataflow** [comment]
@ptbrowne thanks for checking - though I assume the correct cube check would rather be https://int.visualize.admin.ch/_cube-checker?cubeIri=https%3A%2F%2Fcommunication.ld.admin.ch%2Fofcom%2Fmap_tv_konz%2F8&dataSource=Int 
can you double check what else might be the cause? Thank you

**Comment by ptbrowne** [comment]
Ah yes thanks @Rdataflow , I missed the int, I will have a look.

**Comment by Rdataflow** [comment]
the same issue also happens with ForestFireWarnings
https://visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1&dataSource=Prod

interesting commonality: only 1 key dimension

**Comment by Rdataflow** [comment]
@ptbrowne this line probably should not be here in case `dimensionIris[]` is empty
https://github.com/visualize-admin/visualization-tool/blob/3199e340e36d54ca28ffecd81a938acf5875ebc8/app/rdf/query-possible-filters.ts#L64

**Comment by sosiology** [comment]
Tested on INT. 
See: https://int.visualize.admin.ch/en/v/r7BTlfGgGXXj?dataSource=Prod (Copy and edit published visualization, see the error no longer appears in the filter section)
