### ISSUE TITLE
New legend, better supporting Joined cubes, responsive mode and Dashboards

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#1440]
We adjust the legend to gain more space and optimize for responsive behavior and dashboards. The user will be able to focus better on the content of the chart due to [minimizing cognitive load](https://www.nngroup.com/articles/minimize-cognitive-load/)

- SparQL, Download Data and table view will be in the more option button
- Information about the Dataset will be reachable through the metadata button

[Figma Design Section](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=4851-203884&t=vxYfrWOhfqCTP31a-4)

**Comment by KerstinFaye** [comment]
Thanks @ptbrowne. I would also like to discuss the published view for mobile when we are tackling in the legend: 
https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=3427-71385&t=yLY0m7rJlCWi1o1S-4
