### ISSUE TITLE
✓ Tooltip for disabled chart-types

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1448]
add tooltip to inform user why charts are disabled.

Design: https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5767-77161&t=uwHkLPIGgEcHOn4s-4

Related Issue: https://github.com/visualize-admin/visualization-tool/issues/1374

To help the user understand why certain chart types are disable we can implement a tooltip with an explanation why certain chart types are disabled:
E.g. for comparison chart types:
![Image](https://github.com/user-attachments/assets/5c58d20f-48c4-41c9-8e4a-ed93ce6f1702)

Notion: https://www.notion.so/interactivethings/Tooltip-for-disabled-chart-types-13d30da5430280d7b275f9bb94328c4c?pvs=4

**Comment by KerstinFaye** [comment]
@bprusinowski The above example has a generic part "Chart-type is not suitable for the selected dataset" and a specific part "Incompatible Format: Datasets don’t share two dimensions with the same unit or resolution." 
I wonder if we can come up with a set of specific strings that are show for different situations when a chart-type is disabled?
