### ISSUE TITLE
Adding a second chart when the current one has segmentation doesn't correctly apply the filter

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#1462]
**To Reproduce**

1. Go to [this link](https://test.visualize.admin.ch/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/2&dataSource=Test).
2. Enable segmentation by Kanton.
3. Add a new Line chart.
4. See that the Kanton filter is not applied.

**Expected behavior**
Kanton filter should be automatically applied.

**Screenshots or video**

<img width="1920" alt="Screenshot 2024-04-19 at 09 42 34" src="https://github.com/visualize-admin/visualization-tool/assets/52032047/685176ed-2b0e-4e84-bb40-c2dbc3889896">

**Environment**

- Visualize environment and version: TEST v4.1.0 (35ef533)
- Browser and version: Safari 17.4.1 (19618.1.15.11.14)

**Comment by sosiology** [comment]
@bprusinowski not sure if they are related, but when trying to copy the chart i discovered this issue https://github.com/visualize-admin/visualization-tool/issues/1466

**Comment by sosiology** [comment]
Works as expected 👍
