### ISSUE TITLE
Duplicating a chart leads to an application error

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1466]
**Describe the bug**
In editor mode, when copying a chart, an application error is shown

![image](https://github.com/visualize-admin/visualization-tool/assets/29289679/cf66f26c-6c20-4e2d-bf21-d359f5b10507)

**To Reproduce**

1. Go to https://test.visualize.admin.ch/en/v/g00DSr22kUJ7?dataSource=Prod
2. Click on Copy and edit thsi visualization
3. in the editor mode, duplicate the chart (by using the option on the tab) 

**Expected behavior**
the chart can be copied. 

**Screenshots or video**
https://github.com/visualize-admin/visualization-tool/assets/29289679/125e9a92-f6e6-4785-a4e1-9333fb64df89

**Environment (please complete the following information):**

- Visualize environment and version:  Test v4.1
- Browser and version Chrome

**Additional context**

**Comment by bprusinowski** [comment]
@sosiology should be fixed on TEST :)

**Comment by sosiology** [comment]
Can't reproduce anymore. Looks good to me 💯
