### ISSUE TITLE
Broken chart layout in dashboard mode when interactive filters are applied

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#1468]
If there are interactive filters applied, chart's layout is broken in dashboard layout.

<img width="1189" alt="Screenshot 2024-04-19 at 16 59 23" src="https://github.com/visualize-admin/visualization-tool/assets/52032047/e2f51451-2f7a-4b6c-8527-70bc0ccc63bf">

**Comment by sosiology** [comment]
Tested on INT and could not reproduce the reported bug. 

Test chart: https://int.visualize.admin.ch/en/v/EWtvIw_ZWc45?dataSource=Prod
