### ISSUE TITLE
Upgrade cube version initially and once only on client-side

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#1472]
**Situation**
- Each GQL query re-initiates the version upgrade on it's own, even after the version information is already known at the client
- Version upgrade is not streamlined across all the different GQL queries (i.e. some use LightCube, others won't)

**Motivation**
- Firing less queries to the SPARQL endpoint helps to improve the general performance. Therefore omitting double queries (i.e. for version upgrade) will help to improve.

**DoD**

- [ ] The cube version information initially queried by the client is reused - suceeding GQL queries rely on that dynamically queried information, therefore no need to re-query for version upgrades.
- [ ] The version upgrade functionality is streamlined among all the GQL queries. The recent improved query pattern from getLatestCubeIriQuery is reused therefore.

**Comment by Rdataflow** [comment]
LGTM 👍
