### ISSUE TITLE
join by not found in cube

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1475]
**Describe the bug**
merging cubes works pretty fine. but then using that as published chart looks broken atm

**To Reproduce**

1. Go to https://test.visualize.admin.ch/v/psNkz4rQWqvH?dataSource=Test
2. See error

**Expected behavior**
A chart as shown in edit mode https://test.visualize.admin.ch/create/new?copy=psNkz4rQWqvH

**Screenshots or video**
```
Unexpected error
An unexpected error occurred while displaying this chart.
No dimension <joinBy> in cube!
```

**Environment (please complete the following information):**
- Visualize environment and version: TEST v4.2.0 ([687874d](https://github.com/visualize-admin/visualization-tool/commit/687874d28e52179c27cfff4957ec00febdd4c74e))

**Comment by sosiology** [comment]
Thanks for the feedback @Rdataflow. 
@ptbrowne assigned to you incase it's not yet on your radar

**Comment by sosiology** [comment]
LGTM- Was able to successfully create a chart with the same parameters on TEST. The error described above did not show up.

test chart: https://test.visualize.admin.ch/en/v/cwiHCcmWVyTi?dataSource=Test
