### ISSUE TITLE
Legend: Only display data points relevant to the visualization

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1476]
While testing the improvements to the legends and symbols (issue https://github.com/visualize-admin/visualization-tool/issues/1425), the question arose from Tobi B. if it is possible to only show the relevant items in the legend. 

see example here: https://int.visualize.admin.ch/de/v/Ne4JcJneHn8p

**Comment by sosiology** [comment]
@bprusinowski @ptbrowne @KerstinFaye would be interested in your opinion here. Based on the linked example, it seems reasonable to remove the non relevant legend items but i may be missing something.

**Comment by bprusinowski** [comment]
I also think it makes sense :)

**Comment by Rdataflow** [comment]
@sosiology @bprusinowski I agree with one exception: in case of ordinal scales (like forest fire warning) having the full scale helps to better understand the severity of some isolated level

**Comment by sosiology** [comment]
reviewed on test and LGTM
