### ISSUE TITLE
Dashboard Layout: Table exceeds width of component

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1481]
**Describe the bug**
When creating a dashboard that includes a table. The table element is to wide and overflows
https://int.visualize.admin.ch/en/v/0zt1xrUrfZG-?dataSource=Prod

**To Reproduce**
Steps to reproduce the behavior: go to https://int.visualize.admin.ch/en/v/0zt1xrUrfZG-?dataSource=Prod

**Expected behavior**
The table should be scrolable within the the frame

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/29289679/1ffc5e34-e2e8-4cc0-9925-6aaa5b8b87f1)

**Environment (please complete the following information):**
- Visualize environment and version: [e.g. INT v4.3.0]
- Browser and version: Chrome

**Comment by ptbrowne** [comment]
Could be fixed by https://github.com/visualize-admin/visualization-tool/pull/1480

**Comment by sosiology** [comment]
Thanks for the fix @bprusinowski , LGTM 🎉
