### ISSUE TITLE
filters contain wrong values

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1491]
**Describe the bug**
a valid cube shows an wrong values in filter list

**To Reproduce**

1. Go to https://test.visualize.admin.ch/en/create/new?copy=vp7DMJ1EUc5D
2. Open a filter dropdown (`evaluation area` or `grid` or `evaluation type`)
4. See unexpected list

**Expected behavior**
List of the actually ocurring elements within this dimension (as on PROD)

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/26090254/6093f6ee-ca58-43c1-a436-a1b68fef45ed)

**Environment (please complete the following information):**
- Visualize environment and version: TEST v4.3.0 ([36a4c93](https://github.com/visualize-admin/visualization-tool/commit/36a4c931cf5e833d87cbe5096c2a36d72cb7cf5f))

**Comment by sosiology** [comment]
Tested on INT and LGTM.
