### ISSUE TITLE
PROD :  Error happened while fetching possible filters

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1495]
**Describe the bug**
The "Expenditure of general government by function (COFOG)" cube can no longer be viewed on PROD -> An error happened while fetching possible filters, please retry later or reload the page.
This display has always worked before.
-> 

**To Reproduce**
1. Open visualize.admin.ch 
2. Search and select Dataset "Expenditure of general government by function (COFOG)"
3. Start a visualization
4. See error by Filter

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/79834090/964b267f-2209-43fa-b4d0-04023a5f2197)

**Environment (please complete the following information):**

- Visualize environment and version: v4.0.0 ([3199e34]
- Browser and version : Edge

**Additional context**

**Comment by ortnever** [comment]
Hi @sosiology : Can you ensure that this bug is dealt as quickly as possible. Thank you.

**Comment by Rdataflow** [comment]
@ortnever IIRC this should already be fixed on INT

**Comment by ortnever** [comment]
Thank you for your answer Bartosz. We will do the necessary in the data.

**Comment by bprusinowski** [comment]
That's great to hear @ortnever 🎉
