### ISSUE TITLE
demo charts disfunct

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1497]
**Describe the bug**
A clear and concise description of what the bug is. If it seems connected to some data problem (missing values, wrong parsing) please first check the cube in Cube Checker ([int](https://int.visualize.admin.ch/_cube-checker), [prod](https://visualize.admin.ch/_cube-checker)) to see if everything is fine there.

**To Reproduce**

1. Go to https://test.visualize.admin.ch/
2. Scroll to first chart
3. Click on Filters
5. See missing labels
6. see differing chart (compared to INT)
7. see unexpected warning (compared to INT)

**Expected behavior**
- labels in the filters
- same chart than INT
- no warning

**Environment (please complete the following information):**
- Visualize environment and version: TEST v4.3.0 ([b924518](https://github.com/visualize-admin/visualization-tool/commit/b9245187d2671a7e0cf0c1a6799a366272d4c967))

**Comment by sosiology** [comment]
fixed on test and INT
