### ISSUE TITLE
✅ Dashboards: Create Charts with Multiple Datasets (1. Iteration)

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1499]
**User Story**
As a user, I can create a dashboard consisting of multiple charts based on 2 different data sets and connect them with a global filter.

**Demarcation**
In this step we will work with the existing dashboard layouts (vertical and vertical) that are already available in visualize.

**DoD**
In Visualize, a dashboard consisting of multiple charts based on 2 different data sets can be created and linked to a global filter.

**Comment by KerstinFaye** [comment]
@ptbrowne I tested adding a chart based on a different dataset:
1.  Add chart
2. Select different dataset
3. Preview table
4. I closed the search overlay with the close-icon to cancel that process
5. I go again to add a chart based on a different dataset
6. The overlay shows the data preview table to the chart that I selected in the process before

---> Could we achieve that the process of selecting a dataset is canceled by closing the overlay, meaning when I selected the next time a dataset that I don't end up directly at the preview?

[Video of the problem ](https://www.dropbox.com/scl/fi/ewq17ham0k53vkw6e6jxp/Dashboard_based-in-different-dataset.mov?rlkey=byhh6c6w77bq5e2wu0v8vqhop&dl=0)

**Comment by ptbrowne** [comment]
Yes sure, I fix this in https://github.com/visualize-admin/visualization-tool/pull/1541, it should be there soon.

**Comment by KerstinFaye** [comment]
Ill move my feedback to that PR

**Comment by sosiology** [comment]
Thanks for the fix @ptbrowne and for suggesting the improvement @KerstinFaye 
Tested  the improved behaviour on TEST and it LGTM!
