### ISSUE TITLE
multiple std errors are displayed where only one is expected

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1504]
**Describe the bug**
multiple std errors are displayed where only one is expected

**To Reproduce**

1. Go to https://visualize.admin.ch/v/iyq3m4Ok43Re?dataSource=Prod
3. Scroll down to 3rd chart
4. See multiple std errors

**Expected behavior**
same amount of standard errors as bars - (in this case one)

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/26090254/3873fbc0-e315-4be7-81b5-4999ac45d92a)

**Environment (please complete the following information):**

- Visualize environment and version: PROD 4.0.0

**Comment by bprusinowski** [comment]
Hi @Rdataflow, thanks for reporting the issue. Could you also share some further reproduction steps on how to create such chart by not copying and editing the published one, but starting from a new cube?

The problem with the shared chart lies in the missing `Region` filter; however I was not able to remove it through interacting with the application itself (but could do so by going to the `localStorage` and manually removing the filter).

I believe that generally such cases should be prevented on a chart-creation level, inside the configurator, as after the wrong chart was published, we can't really back-add the missing filter, as it's impossible to automatically select the "right" value, without knowing creator's intentions.

I added a "safety net" in #1507 to add back these missing dimensions to the filter panel if for some reason the filters were not computed correctly – but I would be interested to learn if the wrong state achieved in the shared link was achieved in "non-hacky" way; then we'd need to fix that case.

**Comment by Rdataflow** [comment]
@bprusinowski IIRC this was by selecting chart then going back to chart, maybe?

**Comment by sosiology** [comment]
A similar issue identified while testing. The standard error bars show up at the top of the chart. 

![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/ed2bde2c-c1bb-46ef-bca3-71672250747a)

Link:https://test.visualize.admin.ch/v/GZ-0AyMnkDCB?dataSource=Test

**Comment by sosiology** [comment]
Tested on TEST with PROD data set - 

I noticed that sometime the standard error bar is not correctly positioned, sometimes it "jumps" into place but see examples below where it shows up on the y-axis labels 

![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/28f849b4-3956-4fd5-8ca9-87a2bade9300)
Link: https://test.visualize.admin.ch/v/W4mX7FK_UJEu?dataSource=Prod

![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/df9f9d14-e521-45da-adc8-58e227f728c3)
https://test.visualize.admin.ch/v/kUtR4TEUrn38?dataSource=Prod
