### ISSUE TITLE
Table Chart: Long values are cut off

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1505]
**Describe the bug**
In the table charts, when the values are long, they appear to be cut off 

**To Reproduce**
1. Go to: https://test.visualize.admin.ch/en/v/71WvmU9SA6F6?dataSource=Int
2. See in column "Product" -> "All forms of produc" instead of the expected "All forms of product" 

**Expected behavior**
The full text should appear, or is there a limitation to the number of characters?

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/29289679/0682b29d-5087-44f8-938a-b9c617ed4600)

**Environment (please complete the following information):**
- Visualize environment and version: TEST v4.3.0
- Browser and version Chrome

**Additional context**

**Comment by bprusinowski** [comment]
Hi @sosiology, thanks for reporting the bug. I investigated the "raw data" by checking directly in LINDAS, and it's a data issue (see the [actual object that represents "All forms of produc"](https://agriculture.ld.admin.ch/foag/product/81) – the translation is wrong there).
