### ISSUE TITLE
Time filter initialization to only 1 year

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#1517]
When testing, I noticed one issue (which is also there on TEST, so not a regression, but related to this area I think):
1. Go to https://visualization-tool-git-feat-preparation-dashboard-ixt1.vercel.app/en/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod
2. Add a second chart.
3. Go back to first chart.
4. Go to X axis.
5. Enable interactive filter.
6. Proceed to layout options.
7. See that the chart changes filter range to 2014-2014.

_Originally posted by @bprusinowski in https://github.com/visualize-admin/visualization-tool/pull/1516#pullrequestreview-2060222076_

**Comment by bprusinowski** [comment]
Fixed by https://github.com/visualize-admin/visualization-tool/pull/1644
