### ISSUE TITLE
Add note for published graphics that use deprecated data

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#152]
What happens to *published* graphics that reference an unlisted (ie expired) cube?
→ Graphic should still work but maybe display a message (if flag "deprecated" is set)

**Comment by ortnever** [comment]
Our point of view (BAR/BAFU) is described in the documentation (https://github.com/zazuko/cube-creator/wiki/3.-Publication#clarification-about-flags-expired-deprecated-and-actions-unlist-delete), as well as in GitLab : 
- issue #309 for the Cube Creator part (https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/309) and 
- Issue#310 for what concerns Visualize (https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/310)

**Comment by ortnever** [comment]
test @wts21
