### ISSUE TITLE
Map does not keep the default view when proceeding to layout options

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1526]
When the map graphic is chosen, in the dashboard layout option the whole world map will be shown instead of only Switzerland. If you continue without zooming in, the published version will be just Switzerland.

on int: https://int.visualize.admin.ch/create/bh2bT7INAWxb?dataSource=Prod
1. start chart from dataset [Einmalvergütung für Photovoltaikanlagen](https://int.visualize.admin.ch/create/new?cube=https://energy.ld.admin.ch/sfoe/bfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen/9&dataSource=Prod)
2. chose map as a chart-type (May view showed per default Switzerland)
3. added another chart for the dashboard
4. proceed to layout options: map shows the whole world
5. not zooming into the map but just click publish: chart with map shows zoom into Switzerland again

**Comment by ptbrowne** [comment]
I was able to reproduce once, but on my machine, most of the time it works. I switched from configurator view to layout view around 10 times.

**Comment by sosiology** [comment]
I can only reproduce on INT it appears the issue has been resolved on TEST.

**Comment by bprusinowski** [comment]
Should be fixed via https://github.com/visualize-admin/visualization-tool/pull/1673

**Comment by sosiology** [comment]
re-tested on TEST v4.8.0 ([d6a6ad5](https://github.com/visualize-admin/visualization-tool/commit/d6a6ad5c625da81c164fed1e37aaf15fceb9cee8)) and issue cannot be reproduced, the map maintains the zoom level (showing only CH and not the world in all steps: editor, layout, published)

**Comment by KerstinFaye** [comment]
Same. Thanks. I tried as well with multiple different datasets.
