### ISSUE TITLE
UI improvement: 'Metadata'- button and 'show filter'- button aligned underneath chart title

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1528]
The 'metadata' button and the 'show filters' button are aligned underneath the title, to give the title more space. The Metadata button is styled not as a secondary button anymore but as a ghost button (textcolor primary blue, no border)
[Figma Design Section](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=4481-154763&t=kfxyZOHAurgPBrCi-4)

Filters are hidden:
![Image](https://github.com/visualize-admin/visualization-tool/assets/127507692/0f937bb4-cbbc-432c-9e7a-6273a7dd659c)

Filters are shown:
![Image](https://github.com/visualize-admin/visualization-tool/assets/127507692/71eb2a9e-34a8-4405-a016-fce5a1c3d721)

**Comment by sosiology** [comment]
LGTM. Acknowledging that Metadata Button is not there anymore but rather "Details"

**Comment by KerstinFaye** [comment]
LGTM. And yes, meanwhile we renamed it to details.
