### ISSUE TITLE
Adding Chart from Different Dataset: Concept Filters not working

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1534]
**Description**
When adding a new chart with a new data set, the concept filters in the dataset selection page do not work. 

https://github.com/visualize-admin/visualization-tool/assets/29289679/91092948-ca40-4705-b4f9-17f014ac7a5c

**Comment by sosiology** [comment]
Thanks for the fix @bprusinowski - the concept filters are now clickable. I noticed though that the number of data sets shown in the chip, do not correspond to the actual number of data sets shown

Example
For Cantons - it appears i have 37 data sets


![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/60d36f67-7f5a-415b-a187-a3f5995de515)

but when I select it only 5 are shown


![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/948e11c3-1b66-4265-95c9-59cedeb0de1c)

Not sure if i a missing something, if it is in fact a bug, i will open a new issue for it.

**Comment by bprusinowski** [comment]
Hi @sosiology, if I remember correctly, I think we fetch all possible cubes in the Concepts section, but when it comes to filtering, we can't yet catch all the relevant cubes until we integrate new triples due to performance reasons. However I might be wrong, I think it's a good thing to add an issue so it's not forgotten 👍

**Comment by sosiology** [comment]
@bprusinowski thanks for your feedback - we have an issue for integrating the new triples here #1606 i will add a note in that issue so we don't forget to retest this once it is completed.
