### ISSUE TITLE
Separate URLs Layout: not all charts published

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1535]
**Description**
When the layout option "Separate URLs" is selected, only 2 charts are published. I would expect all charts to be published in separate tabs. 

**To Reproduce**
1. Create a chart, and duplicate 2x so there are at minimum 3 charts 
2. Go to the layout step and select "Separate Urls"
3. Publish the charts and see that only 2 are published. 

https://github.com/visualize-admin/visualization-tool/assets/29289679/0b5c4947-422f-4b07-b9b2-5a156945733d

Browser: Chrome 
Visualize Version: TEST v4.5.1 ([6f213e7](https://github.com/visualize-admin/visualization-tool/commit/6f213e79bc7b98194f5780494612f7822738ffb6))

**Comment by bprusinowski** [comment]
Hey @sosiology, I tested the feature both locally and on TEST and it seems to publish all charts; the logic is that the first chart is published in the current tab, where you click the "Publish" button – any extra charts are published in new tabs. So in case of three charts, there should only be two new tabs, and one "old" tab with the first chart.

If this causes confusion, I guess we could open as many new tabs as charts, but I am not sure what should be displayed in the original tab (main page? should it close?). Maybe we can discuss with @KerstinFaye?

**Comment by sosiology** [comment]
hey @bprusinowski you are right - i didnt notice the pop-up blocker blocking the 3rd chart - all good. closing this issue for now.

**Comment by bprusinowski** [comment]
Ah, this might also be an issue :/ Maybe we should have some information about this, so users are prepared 🤔
