### ISSUE TITLE
Enhance CI/CD

### ISSUE THREAD

**Issue by adintegra** [visualize-admin/visualization-tool#1544]
The CI/CD process needs to be enhanced to make configurations for different environments possible. This is mainly due to the integration of authentication and different parameters needing to be supplied for the various deployment environments.

**Describe the solution you'd like**
A build and deployment pipeline flexible enough to cater to different environments.

**Comment by sosiology** [comment]
@adintegra do we need to plan this in for the next sprint so we can proceed with the eIAM integration? Does this need to be done in collaboration with Abraxas/VSHN?

**Comment by adintegra** [comment]
Closed as variables are server-side and can be specified in the runtime environment.
