### ISSUE TITLE
Resize/adapt little duplicate icon in the menu for the more options for each chart

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1549]
1. Create dashboard
2. Continue to layout options
3. Each tap has a little chevron to call a menu that says duplicate or remove this chart
4. The duplicate icon is cut off

![Image](https://github.com/visualize-admin/visualization-tool/assets/127507692/7e4e2381-0a4c-47a8-b650-a84f08038fba)

**Comment by sosiology** [comment]
LGTM! Thanks for the fix @bprusinowski
