### ISSUE TITLE
Edit saved dashboard - jump to layout options

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1550]
After clicking edit on a saved dashboard in my profile arrive at the edit mode for all charts instead of the layout options step.

1. Create dashboard
2. Save dashboard
3. Click edit on the saved dashboard
4. I end up in the edit more of all charts instead of the layout options step. 

IArriving at the layout options step when revising a dashboard could enhance the comparison and decision-making process for chart revisions.

**Comment by sosiology** [comment]
Interesting input @KerstinFaye . When i was testing, the login and the feature it made sense to be that if you click on edit from your profile you are taken to the editor mode. But i see your point that for dashboards the layout step would be more intuitive. It would only apply to the Dashboards though, right?

**Comment by ptbrowne** [comment]
This is more a discussion than an issue at this point correct ? I think we could argue that for a user, always landing on the same view from the same link would make sense ? And we could add another action "Edit layout" only for configs that are in "dashboard" layout ?

**Comment by sosiology** [comment]
@ptbrowne i think so. Will add it to the agenda for Tuesday so we can decide the best approach

**Comment by sosiology** [comment]
Decision from Team Sync on 06.04.2024:
As soon as there is more than one chart config, we default to the layout page

**Comment by sosiology** [comment]
Tested on TEST with my eiam login, lgtm. Thanks @bprusinowski 🙇‍♀

**Comment by KerstinFaye** [comment]
Thanks a lot for implementing this. That's great. 
I would like to change one more thing: I assume it would be confusing for the user that when clicking on the draft title they end up in a published more with the banner that this is still a draft. But there they still have the option to publish and embed even though it is still a draft. I would like to disable the title for a draft. Then the only clear call to action is that they would click on edit to further work on the draft. @ptbrowne @bprusinowski @sosiology What do you think?

**Comment by sosiology** [comment]
LGMT tested on INT
