### ISSUE TITLE
Check if temporal entity dimension work with dashboard shared filter

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#1555]
> Wondering if `TemporalEntityDimension` wouldn't also work "out of the box", as it looks like it has a `timeUnit` just like `TemporalDimension`?

_Originally posted by @bprusinowski in https://github.com/visualize-admin/visualization-tool/pull/1545#discussion_r1624444483_

**Comment by sosiology** [comment]
@bprusinowski i tried to test on TEST and with the PR links
Time brush for temporal entity dimension based X axis -> works as expected on both the PR and on TEST
Temporal entity dimension in shared dashboard filters
- On the PR when I switch to the dashboard layout the shared filter option is not shown: ![Image](https://github.com/user-attachments/assets/164c4139-32ff-4f8a-bbc7-c3f6e3c5724e)
- On TEST i can activate the shared filter, however for the date i am only shown 01.1970, and cannot filter the chart with the time brush
 ![Image](https://github.com/user-attachments/assets/26e51480-3f17-44e9-97f6-3038e9c47fb4)

Tested with https://test.visualize.admin.ch/en/v/uVzl9tEGzs_E?dataSource=Int

**Comment by bprusinowski** [comment]
@sosiology should be fixed on TEST in ~20 mins :) Let me know if it still doesn't work as expected 👍
