### ISSUE TITLE
Unexpected Error when trying to create a table with BLW cubes

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1570]
**Describe the bug**
When trying to create a table (chart type) with the BLW cubes (milk, egg markets) an unexpected error occurs 
![image](https://github.com/visualize-admin/visualization-tool/assets/29289679/1b7b0b54-5019-4479-8522-d64fb6de591c)

**To Reproduce**

1. Go to test.visualize.admin.ch
2. Select a FOAG data set (for example 
Market figures milk and dairy products - Monthly consumption prices)
3. start creating a chart, select table 

**Expected behavior**
It should be possible to create a table chart with the BLW data sets. 

**Screenshots or video**
If applicable, add screenshots or a short video to help put your problem into a context.

**Environment (please complete the following information):**

- Visualize environment and version: TEST v4.6.1 ([4363e67](https://github.com/visualize-admin/visualization-tool/commit/4363e676cca9041f862ce52bc1ee720ce5de2a8c))
- Browser and version Chrome

**Additional context**
if another chart type is created, it is possible to switch to the table view using the "switch to table view" link below the chart.

**Comment by sosiology** [comment]
@bprusinowski i realized this was more of a general bug with the tables - can we deploy only this fix to INT so that the tables are not broken with the upcoming PROD release?

**Comment by bprusinowski** [comment]
Hey @sosiology, I think it would be possible, but I think we recently introduced a lot of feature flags, to be able to deploy to PROD without creating diverging branches / deployments. Would it be fine to deploy the current version from TEST, with all the "extra" bug fixed we already did there, among with new features hidden by flags?
