### ISSUE TITLE
Table Charts "data filters are not enabled for this chart"

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1579]
Very straight forward error report. When choosing the table chart, instead of the expected table, a error message shows up. 
![Table Fail 10 06 2024](https://github.com/visualize-admin/visualization-tool/assets/111350367/246df19f-59a4-4b58-b348-9e010bb58ba1)

This happened for this [cube](https://int.visualize.admin.ch/de/v/NoQtksf6wezx) but also any other I tested with PROD as its source

**To Reproduce**

1. Go to https://int.visualize.admin.ch/de/v/NoQtksf6wezx

**Environment (please complete the following information):**

- Visualize environment and version: [INT v4.6.1]
- Browser and version [e.g. Edge]

**Comment by bprusinowski** [comment]
Hi @tboeni, thanks for reporting the bug 🙇‍♂️ It should already be fixed on TEST 🤞

**Comment by bprusinowski** [comment]
Hi @tboeni, as we currently have a lot of new things on TEST (along with bug fixes), we wanted to first clarify with BAFU on how to proceed there – whether we push everything to INT, hiding some of the new features behind feature flags, or cherry-pick some of the bug fixes to only deploy them to INT. But the plan is to definitely not have a PROD deployment with broken table charts :)
