### ISSUE TITLE
Tabs have labels

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#1587]
After feedback from Matthias Brändli, we decided that tabs should have labels. The label is the title of the chart. The behavior of  the width of the tabs should mimick browser tabs.

**Comment by ptbrowne** [comment]
Was fixed in https://github.com/visualize-admin/visualization-tool/pull/1584

**Comment by KerstinFaye** [comment]
Thank you @sosiology. I didn't see this. I'll delete the other one. 
@ptbrowne Not sure yet, how we handle multiple languages? Only the on that the editor wrote I assume? That would work I think.

**Comment by sosiology** [comment]
@KerstinFaye seems like the translations and charts not having a title are already accounted for see examples below

Chart with labels in all languages: https://test.visualize.admin.ch/en/v/W6-T_gW3_6y3?dataSource=Prod
Chart with label only in EN: https://test.visualize.admin.ch/en/v/IkmUw2wTEwo9?dataSource=Prod

👏 thanks @ptbrowne

**Comment by KerstinFaye** [comment]
Thanks a lot. Looks good.
