### ISSUE TITLE
Tab titles in dashboard tab layout

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1590]
Giving the option to add a title for the tabs
To consider:
- how do we handle multiple languages
- how do we handle long titles
-

**Comment by sosiology** [comment]
@KerstinFaye there is already an issue for this here https://github.com/visualize-admin/visualization-tool/issues/1587

**Comment by bprusinowski** [comment]
Fixed via https://github.com/visualize-admin/visualization-tool/pull/1584
