### ISSUE TITLE
Managed Cached Endpoint

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1596]
DoD

- [ ] the cube specific queries are sent to a specific endpoint (basically appending the cube specific IRI to the endpoints URL) conforming the technical info (specific pattern to be shared by [@ludovic.muller](https://github.com/ludovic.muller))
      - nb: the queries spanning multiple cubes or listing cubes stay with the current pattern.

This Part of the issue is for VSHN to complete, not applicable to IXT.
- [ ] for the a) x% most recently published and b) y% most frequently opened published charts and c) custom cube list cron jobs are established to preload those published views (in varnish) during at a custom schedule (i.e. at night)

Current State as of 11.06.2024
* [x] Der Varnish Endpoint maintained by VSHN is active
* [x]The appropriate Trifid routing by zazuko is productive
* [x] Visualize already uses caching in visualize TEST/INT
* [ ] Visualize uses cache partitioning (everything is ready)
* [ ] follow-up 1:  zazuko & VSHN establish invalidation (independently possible)
* [ ] follow-up 2: VSHN increases the cache duration (independently possible)

**Comment by bprusinowski** [comment]
@sosiology thanks for adding the issue, one small note – the second part is not on us, but if I understood correctly, on VSHN's side 👀

**Comment by sosiology** [comment]
@bprusinowski thanks for clarifying i commented it out above. @adintegra i assume we should do the same in gitlab?

**Comment by Rdataflow** [comment]
@bprusinowski I can step in and explain how you may handle the second part. We need ITX to accomplish that step by simply loading the relevant published charts (i.e. by means of a [virtual] browser). Doing this you will trigger preloading of the cache without any additional effort.

cc @adintegra @sosiology

**Comment by bprusinowski** [comment]
Right, thanks for clarifying this @Rdataflow and sorry for the confusion.

For the a) and c) points, this should be pretty straightforward to do (we could potentially utilize preview charts via API feature there), I am however not sure about the b), as we don't really have analytics on chart views yet; but we could also explore a bit there to see if that's something realistic to implement in a short amount of time.
