### ISSUE TITLE
In the layout preview, the charts appear bigger than in the published view

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1597]
When testing on TEST. I noticed that the charts appear bigger in the layout preview than in the published view. Note in the screen recording, how in the layout steps, all charts are visible, whereas in the published view they are smaller and thus not readable, and in some cases even broken as labels seem to overlap: 

![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/cf972df6-651b-4844-bcd1-4b7c54b17195)

**Comment by sosiology** [comment]
See video here: https://www.notion.so/interactivethings/Testing-File-f5fb6a3566374bce9a731bbdf1734761?pvs=4#5b73cf523f6947a8bc5cb82f5df0567c

**Comment by bprusinowski** [comment]
@sosiology I wonder if the chart preview in different screen sizes (https://github.com/visualize-admin/visualization-tool/pull/1724) would solve this issue (so the users would be able to see how the chart would look like on smaller screens)?

**Comment by sosiology** [comment]
@bprusinowski thanks for the note. Yes, i think this will be resolved with the chart preview for different screen sized. Closing this issue. Thanks!
