### ISSUE TITLE
Dashboard title as a draft title in My Visualizations

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1600]
It would be good to use the Dashboard title for the draft in My Visualizations instead of the charts listed. 
For Tab Layout Option it might be good to simply truncate after 3 listed chart-titles.

[Link to Figma Design ](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=1500-69679&t=kN9yTBVprZWMGbgy-4)

Example Recording
https://www.dropbox.com/scl/fi/qln7yacahx2rg9ugb5qco/draftname-is-dashboard-name.mov?rlkey=4s0bse9v1t7oziv0bwl46jn5v&dl=0

![Image](https://github.com/visualize-admin/visualization-tool/assets/127507692/a4c47412-4ae6-472e-8e7f-bc8f441d6428)

**Comment by sosiology** [comment]
@KerstinFaye I agree with this proposal. Would be good to understand the technical effort to see if we include it in this sprint or the next

**Comment by sosiology** [comment]
LGTM thanks @ptbrowne
