### ISSUE TITLE
Integration of new triples on TEST

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1606]
**DoD**
- Use new triples that link the dimension to the shared dimension when searching for cubes matching shared dimension on TEST and provide feedback to zazuko

**Dependency**
- It is not possible to deploy to INT or PROD as it is not yet ready on zazuko's side
- [#661 (comment 15493)](https://gitlab.ldbar.ch/bafu/visualize/-/issues/661#note_15493)

**Testing note**
- Once this task is completed, test that the concept filter chips are showing the correct number of data sets (see comment here: https://github.com/visualize-admin/visualization-tool/issues/1534#issuecomment-2163710945

**Comment by sosiology** [comment]
@bprusinowski not sure if you saw it, but we got feedback from Thomas on this issue last week via gitlab https://gitlab.ldbar.ch/bafu/visualize/-/issues/684#note_16875

**Comment by bprusinowski** [comment]
Thanks @sosiology; btw, it looks like the triples are now available across every environment, so we don't have a dependency on Zazuko anymore when it comes to deploying to INT and PROD 👍
