### ISSUE TITLE
Label Dashboards as such on the profile page

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1608]
Currently in the login area, dashboards are displayed as "Type" -> Multi. I was wondering if there is a way to have them be labeled as "Dashboards". Thoughts @KerstinFaye @bprusinowski @ptbrowne ?

![Image](https://github.com/visualize-admin/visualization-tool/assets/29289679/403ce34b-aea6-494a-9e7d-bf8187d6658c)

**Comment by bprusinowski** [comment]
I think it would bring alignment, multi is not used anywhere else in the application 👍

**Comment by sosiology** [comment]
Thanks for your feedback @bprusinowski. @KerstinFaye if you agree, we can go ahead an implement the change, assuming the effort is reasonable (its not the highest priority :))

**Comment by KerstinFaye** [comment]
@sosiology @bprusinowski  Thanks for that. I only saw it now. Would Dashboard also fit to multiple charts in tabs? If so, then yes, I think it would make sense to rename it.

**Comment by sosiology** [comment]
LGTM. Tested on TEST and INT
