### ISSUE TITLE
Dashboard time filter's last option is not displayed correctly

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#1617]
See that the last option in dashboard shared time filter has less "padding" than it should have e.g. [here](https://test.visualize.admin.ch/en/v/6YW3HU5Tq2Q9?dataSource=Int). This is related to the incorrect `step` calculation, which could be fixed to make sure the spacing is consistent.

**Comment by sosiology** [comment]
cannot reproduce the issue - padding looks good to me on the time filter.
