### ISSUE TITLE
Show more button is not aligned on the right side

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1622]
Show more button is not aligned anymore on the right side next to the drag icon:

![Image](https://github.com/visualize-admin/visualization-tool/assets/127507692/6151bf17-ce40-4bae-9654-ff37ba4dc015)

**Comment by bprusinowski** [comment]
@KerstinFaye should be fixed on TEST 👍 Thanks for catching that!

**Comment by KerstinFaye** [comment]
Amazing. Thanks
