### ISSUE TITLE
Drafts - Only preview from more options button

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1623]
We should give the users a clear indication what they can do with a draft to only have in the more options buttons the action: preview.

- Take out the link to access the preview by clicking on the title of the draft
- Rename `View` to `Preview`
- Take out the actions: `Embed`  and `Share` from the Preview page
- Make the banner over the whole width of the chart underneath

![Image](https://github.com/visualize-admin/visualization-tool/assets/127507692/4ee8e8a3-eddc-47c9-832d-9bf7398b3ac3)

![Image](https://github.com/visualize-admin/visualization-tool/assets/127507692/20b789ed-1736-4edc-9723-f4e6ba6abf3d)

**Comment by sosiology** [comment]
Feedback based on testing on TEST:

- Take out the link to access the preview by clicking on the title of the draft
      - The link now leads to the editor, not the preview mode - I assume that is the expected behaviour @KerstinFaye ? 
- Rename View to Preview 
      - Works as expected ✅   
- Take out the actions: Embed and Share from the Preview page
     -  The actions are moved from the preview page, however, the "Share" option is still shown in the User Profile @bprusinowski @KerstinFaye 
     - ![Image](https://github.com/user-attachments/assets/1b640a3f-5efc-46a5-81ed-9dae946f35c9)
- Make the banner over the whole width of the chart underneath
      - Banner is across the entire width ✅

**Comment by KerstinFaye** [comment]
Thanks for your feedback @sosiology 

- The first point is the expected behaviour. Clicking on the draft title will bring the user to the editing mode.
- ✅
- Regarding the action buttons: 'Share' was not shown anymore when I tested.
- ✅
