### ISSUE TITLE
VisualizeAPI demo throws error

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1625]
**Describe the bug**
Clicking on those demo buttons throws an error

**To Reproduce**

1. Go to https://visualize.admin.ch/_preview_post
2. Click on either button

**Expected behavior**

**Screenshots or video**
```
Application error: a client-side exception has occurred (see the browser console for more information).
```

**Environment (please complete the following information):**

- Visualize environment and version: PROD v4.0.0 ([3199e34](https://github.com/visualize-admin/visualization-tool/commit/3199e340e36d54ca28ffecd81a938acf5875ebc8))

**Additional context**
consider: NFI cubes on PROD will be updated very soonish (before visualize relase) with what is live on INT now
```
Uncaught Error: You need an <ConfiguratorStateProvider> to useConfiguratorState
    at ew (configurator-state.tsx:1856:11)
    at z (chart-published.tsx:62:19)
    at ak (react-dom.production.min.js:167:135)
    at i (react-dom.production.min.js:290:335)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at ox (react-dom.production.min.js:268:166)
    at x (scheduler.production.min.js:13:197)
    at MessagePort.T (scheduler.production.min.js:14:126)
```

**Comment by bprusinowski** [comment]
Hi @Rdataflow, thanks for reporting the issue. The problem is already solved on TEST and INT, see e.g. https://int.visualize.admin.ch/_preview_post

If the fix needs to be deployed before the official Visualize release, then I think it would be good to coordinate with @adintegra, but from technical side the bug is fixed 👍

**Comment by Rdataflow** [comment]
THX - I wasn't aware anymore 👍
