### ISSUE TITLE
switch `/_cube-checker` to https://cube-validator.lindas.admin.ch

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1626]
**Is your enhancement related to a problem? Please describe.**
https://visualize.admin.ch/_cube-checker only checks for a small subset of the visualize requirements while the https://cube-validator.lindas.admin.ch is the new official tool provided by LINDAS.

**Describe the solution you'd like**
switch to cube-validator

**Describe alternatives you've considered**
stick with legacy cube-checker

**Usecases and impact**
easily check if datasource conforms with visualize requirements

**Additional context**
will be online soon once Ludovic is back at work
- see demo for the URL pattern https://cube-validator.zazuko.com/validate/https:%2F%2Flindas.admin.ch%2Fquery/https:%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd010701%2F8

**Comment by Rdataflow** [comment]
@bprusinowski @adintegra https://cube-validator.lindas.admin.ch/ is up now 👍

**Comment by adintegra** [comment]
Thanks for the info @Rdataflow. A question for consideration: At the moment the internal cube checker is just a URL which is essentially decoupled from the rest of the application. Because of this, do you think having a redirect (i.e. our understanding of this request) provides a real benefit for users (as they could just go there directly)?
Alternatively, we could retire this functionality and update the documentation to point users to the new cube checker.

What are your thoughts on this?

**Comment by Rdataflow** [comment]
@adintegra not sure I get you correctly... 

see currently upon opening an [invalid cubeIRI](https://test.visualize.admin.ch/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_T-changes%2Fcube%2F2077-1&dataSource=Test) a notification with the cube-checker appears... something I think still makes sense in the future even with cube-validator at lindas
![image](https://github.com/visualize-admin/visualization-tool/assets/26090254/7befa82e-d55b-45b9-96a2-edf7ce77c599)
linking to https://test.visualize.admin.ch/_cube-checker?cubeIri=https://environment.ld.admin.ch/foen/nfi/nfi_T-changes/cube/2077-1

therefore my question: what was your proposition what may happen if a user browses an invalid or non-existsing cube i.e. https://test.visualize.admin.ch/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2Fnfi_T-changes%2Fcube%2F2077-1&dataSource=Test

and sure: retiring and dropping cube-checker from codebase incl docs makes sense now that cube-validator is official

**Comment by adintegra** [comment]
Thanks for the added explanation @Rdataflow – all makes sense now!

**Comment by sosiology** [comment]
link points to cube Validator now on TEST
![Image](https://github.com/user-attachments/assets/9d649cf8-0c5d-4f6f-85b9-a531f140856d)
