### ISSUE TITLE
error whiskers placed in the off

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1627]
**Describe the bug**
the error whiskers are not where expected

**To Reproduce**

1. open https://int.visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/nfi/nfi_T-changes/cube/2024-1&dataSource=Int
2. See error

**Expected behavior**
error whiskers on top of the bars

**Screenshots or video**
![image](https://github.com/visualize-admin/visualization-tool/assets/26090254/249ac242-e0eb-43cf-8746-d24ce9449ab6)

**Environment (please complete the following information):**

- Visualize environment and version: INT v4.6.1 ([7b6ab2c](https://github.com/visualize-admin/visualization-tool/commit/7b6ab2c90a35e5a7a619f3c5e6dea279ebb172a5))
- Browser and version: edge Version 125.0.2535.92

**Additional context**
maybe already fixed on TEST?

**Comment by bprusinowski** [comment]
Thanks for reporting the issue @Rdataflow – it's already fixed on TEST 👍
