### ISSUE TITLE
Link new Cube Validator

### ISSUE THREAD

**Issue by adintegra** [visualize-admin/visualization-tool#1628]
The existing cube validation functionality in Visualize can be retired and replaced by linking to the forthcoming Cube Validator (expected to be published at https://cube-validator.lindas.admin.ch/). A development deployment of the new Cube Validator can be found [here](https://cube-validator.zazuko.com/select).

**DoD**
- [ ] Visualize links out to the new Cube Validator

**Comment by Rdataflow** [comment]
I guess this is a duplicate of #1626 ;-)

**Comment by adintegra** [comment]
Closed as duplicate :)
