### ISSUE TITLE
Name is not saved in Draft of a Visualization, even though the chart has a title

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1634]
https://test.visualize.admin.ch/de/create/new?edit=MR9kR2D9K1Q5

1. I made a chart and gave a chart title
2. I saved the chart
3. Went to my visualizations - Draft does not show chart title

[Screen recording](https://www.dropbox.com/scl/fi/qln7yacahx2rg9ugb5qco/draftname-is-dashboard-name.mov?rlkey=4s0bse9v1t7oziv0bwl46jn5v&dl=0)

**Comment by bprusinowski** [comment]
Hi @KerstinFaye, it looks like it's already fixed on TEST – could you take a look again and confirm if it's still an issue?

**Comment by KerstinFaye** [comment]
Looks perfect. Thanks for the fast fixing @bprusinowski

**Comment by sosiology** [comment]
Re-opening this issue as the issue seems to persist on TEST

https://github.com/user-attachments/assets/c9715675-2c09-4fc8-8f84-9e21d9084d7e

**Comment by sosiology** [comment]
LGTM thanks for the fix, works as expected now
