### ISSUE TITLE
Dashboard Layout Options - Switch option settings saved

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1635]
**Problem:** 
When users change a dashboard layout option and then return to the originally selected option, the dashboard settings are lost.

1. Layout option Dashboard: Did all settings for free canvas. Resized the charts and activated shared filters. 
2. Switch to Tab Layout on the top navigation.
3. Switch back to Dashboard Layout options. 
4. All my settings were deleted and set on default.

https://test.visualize.admin.ch/create/FoVVuE05GKHw?dataSource=Prod

**Improvement:**
Save layout settings so that users can switch between the options and the settings are retained.

**Comment by bprusinowski** [comment]
Ready on TEST :)

**Comment by sosiology** [comment]
Works for me on test. Tested with https://test.visualize.admin.ch/v/n0282fzAA7ge?dataSource=Test and https://test.visualize.admin.ch/en/v/jb1G_2a7xwLO?dataSource=Test

**Comment by KerstinFaye** [comment]
✅ Works on INT. 🎉
