### ISSUE TITLE
Minimum size graphs in Dashboard cards

### ISSUE THREAD

**Issue by adintegra** [visualize-admin/visualization-tool#1637]
The current layout of dashboard cards leaves little space for the graphs themselves – about 2/3s of the card is taken up by legend, titles, and various metadata. We should move the visual elements (e.g. download link, etc.) that can be moved to a menu to create more space for the graphs.

Related to #1440

**Comment by sosiology** [comment]
Resolved by adding a detail panel to the charts with information. Note: In Sprint 5.11 it was decided to reintroduce the legend to the bottom of the chart.
