### ISSUE TITLE
"Run SPARQL Query" missing on INT & TEST

### ISSUE THREAD

**Issue by nickeichmann** [visualize-admin/visualization-tool#1654]
At the INT and TEST Services of Visualize, the "Run SPARQL Query" at the bottom of charts is missing. At the PROD Page it still is available.

**To Reproduce** Steps to reproduce the behavior:

1. Go to [https://int.visualize.admin.ch/de/v/r8S32OoEOrOi](https://int.visualize.admin.ch/de/v/r8S32OoEOrOi) or [https://test.visualize.admin.ch/de/v/V2oNCw8K8N27](https://test.visualize.admin.ch/de/v/V2oNCw8K8N27) 

2. Compare it to [https://visualize.admin.ch/en/v/oyrIxiLKWMTE](https://visualize.admin.ch/en/v/oyrIxiLKWMTE)

**Expected behavior** 
At the INT and TEST page the button should also be available.

**Screenshots or video**
*INT*
<img width="623" alt="image" src="https://github.com/visualize-admin/visualization-tool/assets/73659892/8ef12042-6116-41ae-a8da-ab4c712c3f00">

*PROD*
<img width="766" alt="image" src="https://github.com/visualize-admin/visualization-tool/assets/73659892/22c66b86-a70b-4e53-bd4e-b7918c9cfd47">

**Environment (please complete the following information):**
TEST: v4.7.0
INT: v4.7.1
PROD: v4.0.0

**Comment by nickeichmann** [comment]
Danke @Rdataflow. So einfach löst sich ein Problem :)

**Comment by bprusinowski** [comment]
Yes, thanks for reporting the issue @nickeichmann and jumping in @Rdataflow!

Together with @KerstinFaye we decided to unclutter chart footnotes a bit, as they can take a lot of space when merging cubes or in the dashboard layouts. All of the previous information and features are still available either in "more options" button (three dots in the top right corner of a chart) or inside the Details panel :)
