### ISSUE TITLE
Display units next to map scale

### ISSUE THREAD

**Issue by ahlesphi-wsl** [visualize-admin/visualization-tool#1657]
While the units are visible when hovering over the map, it would be nice to see the units next to the scale too.

![map-chart-scale](https://github.com/visualize-admin/visualization-tool/assets/167202421/95c9d6d5-c52e-4304-a3fe-1993cec685d4)

**Comment by ortnever** [comment]
See https://gitlab.ldbar.ch/bafu/visualize/-/issues/692#note_16683

**Comment by ahlesphi-wsl** [comment]
Thank you

**Comment by ortnever** [comment]
Thank you @bprusinowski . It looks good !
