### ISSUE TITLE
Chart Duplication Button not aligned with Tab

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1660]
**Is your enhancement related to a problem? Please describe.**
When selecting the chart duplication option from the tab menu, the popover is not aligned with the tab 

![image](https://github.com/user-attachments/assets/db45fa74-9631-4b8c-978e-9fa10e55a74f)

**Describe the solution you'd like**
Align the box with the tab (this is the case if there are 2 or more tabs), but not for a single tab 
![image](https://github.com/user-attachments/assets/926fcb46-4a56-4112-9a88-a94635ff1517)

**Additional context**
Tested on TEST v4.7.0

**Comment by sosiology** [comment]
Works as expected in the PR linked in #1668 but on test i can still reproduce the issue

**Comment by bprusinowski** [comment]
@sosiology closing, as it looks correct on INT (and TEST is currently behind) 👍

**Comment by sosiology** [comment]
Thanks @bprusinowski reviewed and it now looks good on both TEST and INT, thanks!
