### ISSUE TITLE
Cube cannot be visualized

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1661]
@bprusinowski Here is a question rather as a bug, but it would help me a lot if if you could explain me why I have this problem with my cube.
Thanks in advanced !

I've re-published a cube on INT after doing a small change to the mapping of a shared Dimension. 
Since then, I've been unable to view the cube on INT.

The cube in Cube Creator INT (Lindas INT) is "[UBD006601 Bodenbelastung durch Schwermetalle](https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!ubd006601-bodenbelastung-durch-schwermetalle-r5zqggxxgl9)"

**Steps to reproduce the behavior:**
1. Open the dataset with name "[Heavy Metal Soil Contamination](https://int.visualize.admin.ch/en/browse?order=SCORE&search=Heavy+metal&includeDrafts=false&dataSource=Int-uncached#:~:text=31.05.2023-,Heavy%20Metal%20Soil%20Contamination,-The%20measurement%20data)", version dated 31.05.2023, Status Publish, on int.visualize.admin.ch 

2. Start the visualization
-> Visualize automatically returns to the results list.

![image](https://github.com/user-attachments/assets/bedca6c2-e427-454a-8870-b5e3271de221)

![image](https://github.com/user-attachments/assets/f4d1eaf0-7863-4f5d-8864-89609096de18)

Result 
![image](https://github.com/user-attachments/assets/0890b3e0-593b-4c69-8e4e-91a183b84683)

- Visualize environment and version: v4.7.2 ([dbe2b7e]
- Browser and version : Edge

**Comment by bprusinowski** [comment]
Hi @ortnever, thanks for reporting the bug! I took a look and it seems that the `stationid` dimension contains mixed literal and named node values, see https://s.zazuko.com/2RxqjSC. In Visualize we expect to have only one type at time, defined by `nodeKind` of a dimension. Is it possible to make the "WA_010" value also a node, not a literal value?

**Comment by Rdataflow** [comment]
@bprusinowski thanks for pointing to this - a fact which would be detected by the full cube validation (although not necessarily by the online cube-validator because it only inspects a first subset of the data)

FYI: Vero will soon update this dataset hence issue will be solved on the data side ...

**Comment by bprusinowski** [comment]
Great, thank you @Rdataflow for jumping in and @ortnever for updating the cube soon 🙇‍♂️ I will close the issue, let me know if you have any other questions.
