### ISSUE TITLE
Regression : Link "Created with Visualize"

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1664]
On PROD, the ‘Created with Visualize’ link leads directly to visualisation. On INT this link leads to the Visualize home page.

If it has not been expressly decided to modify this way for a good reason, please correct the link so that the user lands directly on the graph.

Please check and adapt the link in embeded URLs as well (AEM + iFrame).

**Comment by ortnever** [comment]
Oh thanks for the explanation @bprusinowski . I wouldn't have looked for this feature under Button "share" but the main thing is that we can edit the graphic from the publication.
You can close the issue.
Thank you very much.

**Comment by bprusinowski** [comment]
Thanks @ortnever! If it turns out to be confusing, we might need to revisit this with @KerstinFaye. But for now I will close the issue 👍
