### ISSUE TITLE
Display the bar chart when a label is very long

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1665]
When one of the labels is too long on the x axis, the height of the bar chart is shortened to the point where the graph is no longer visible.
@bprusinowski  : Do you see a solution to avoid this?
- Force a line break in the label text
and/or
- guarantee a minimum height for the chart
We could of course adapt the label text in the data, but this is sometimes difficult.
https://int.visualize.admin.ch/fr/v/YzDlIzcQKrT6

**Comment by bprusinowski** [comment]
@ortnever thanks for reporting the issue. We could guarantee a minimum height of a chart, or make it keep a certain aspect ratio, based on chart width. I don't think it should be a complex thing to do; and it would prevent cases like in the example link 👍

**Comment by ortnever** [comment]
Thank you @bprusinowski for your prompt reaction. 
guarantee a minimum height or make it keep a certain ratio will be fine.

**Comment by ortnever** [comment]
Hi @bprusinowski : I notice that the same graph is displayed correctly on PROD. We may therefore have the same problem with other published graphics when we move the current INT release to PROD. 
https://www.visualize.admin.ch/fr/v/R8H96ToID0FE
Is it possible to correct this before deployment?

@sosiology

**Comment by bprusinowski** [comment]
Hi @ortnever, we will include this fix in the upcoming release :)

**Comment by ortnever** [comment]
Wonderful. Thank you @bprusinowski
