### ISSUE TITLE
Categorical Shared Filters

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1669]
Add the possibility to include a global categorical filter in the dashboards similar to the temporal global filter.

**Comment by sosiology** [comment]
@bprusinowski thank you for implementing this. When testing, I noticed that all possible filters are shown as options. I would expect only filters to be shown that are applicable to all the charts in the dashboard, as oppose to also showing filters that only apply to a single chart. 

Example:  https://test.visualize.admin.ch/en/v/Rfy-32ugtXJk?dataSource=Prod
- If i interact with the date filter all charts are affected, as expected.
- If i change the "inventory" or "parameter" filters, only the charts with those dimensions are changed. I wouldn't expect those filters to be at the top of the dashboard, as it only affects some charts. I would expect the shared filters to impact all charts, respectively, only filters that can be applied to all charts are available to select in the layout step. 
- If i change the region filter to "both Basel" - no relevant data is shown, as I filtered out this region while creating the chart - so I would not expect this option to show up at all. 

Is this the expected behaviour?

**Comment by bprusinowski** [comment]
Hi @sosiology, I am able to filter by both Basel, see the below screenshot 👀 I think there's another bug that makes the NFI chart disappear when you use a date filter that is not there in this dataset 😱 

<img width="1325" alt="Screenshot 2024-09-25 at 10 01 16" src="https://github.com/user-attachments/assets/7e6ff774-2157-4754-9919-9d2a4b09fc26">

I think here, when we have one chart per different cube, it probably doesn't make sense to enable shared filters, except of date dimension 👍 But in case of having e.g. two charts from Bathing water quality, this would be different if we wanted to keep the filters in sync. Maybe we need to have some indication on filter-chart connection, to know what will change if we use a given filter?

We could discuss this in a sync, I don't remember having a discussion on this 😄 cc @KerstinFaye

**Comment by sosiology** [comment]
Thanks @bprusinowski can confirm the issue with the NFI cube is fixed and works as expected. Re the categorical global filters. Let's pick this up again when we resume the project. I created an issue for that here: https://github.com/visualize-admin/visualization-tool-private/issues/108 otherwise i fear it will get lost in notion 😅

**Comment by KerstinFaye** [comment]
Thank you, @sosiology and @bprusinowski, for bringing this up. I was also under the impression that only shared filters affecting all charts could be applied as shared filters. I thought individual filters would still remain for each chart. However, let's definitely discuss this again to clarify our understanding.
