### ISSUE TITLE
Versions number handling - question

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#167]
I talked yesterday in the meeting about the version number with Jeremy.
One thing looked "wrong", as the tool on dev (version 3.0.1 yesterday) seemed more recent than the tool on test (version 3.1.0).
One improvement that was available on dev, but not yet on test, is the fact that the date filters work on dev (the final user can display the filters, and change the date).
Today I see that both environmnent now have version 3.1.0, but I "guess" that they do not both use the same code, as the date filters are ok on dev (as expected), but still not ok on test.
My question: as I follow a few issues, and I would test if they are solved only if I see that the version has changed, could you handle those versions numbers more precisely ? Or am I wrong to rely on versions numbers ?
For instance, I fillow this issue: https://github.com/visualize-admin/visualization-tool/issues/162, and currently I can only create a new visualization and edit it to see if the fix is has been deployed or not.
Thank you for any feedback

**Comment by herrstucki** [comment]
I proposed a solution in #192
