### ISSUE TITLE
Enable site indexing in Production

### ISSUE THREAD

**Issue by adintegra** [visualize-admin/visualization-tool#1676]
**Describe the bug**
Currently, the Visualize production site includes meta directives which discourage it from being indexed by search engines.

**To Reproduce**

1. Go to https://visualize.admin.ch
2. Open Dev Tools and check the `X-Robots-Tag` HTTP header

![visualize_seo](https://github.com/user-attachments/assets/72904c42-dd32-4ffd-a1a8-e5dcc499de7b)

**Expected behavior**
In the production environment the [X-Robots-Tag](https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag#xrobotstag) header should not be set.

**Environment**

- Visualize environment and version: PROD 4.0.0

**Additional context**
The functionality for the correct behaviour is already implemented and is controlled by the presence of the environment variable `ALLOW_SEARCH_BOTS`. However, this doesn't appear to be correctly evaluated at runtime.

**Comment by sosiology** [comment]
no clue how to test this, tried to find the reference in the console but couldnt find it 🤷‍♀

**Comment by bprusinowski** [comment]
Sorry for not writing an instruction here; it can be tested by going to Visualize TEST and PROD, opening the Network panel and taking a look at an entry with a name of current locale (e.g. `en`).

### PROD
<img width="607" alt="Screenshot 2024-09-30 at 08 58 30" src="https://github.com/user-attachments/assets/1d32f7b4-860d-484d-bf6f-06f9ff19eef4">

### TEST
<img width="605" alt="Screenshot 2024-09-30 at 08 58 49" src="https://github.com/user-attachments/assets/73ff8599-4539-43f0-b9ec-e16d53a94538">

**Comment by sosiology** [comment]
Nice! Thanks for the instructions @bprusinowski can confirm on TEST the X-Robots Tag is gone ✅
