### ISSUE TITLE
Visualize TEST not displaying newest published versions

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1682]
I published another version of [Rodungstatistik](https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!rodungsstatistik-test-jk5p4n4mqma/publication) via test.cube-creator.admin.ch, however the newest version (5) does not show correctly in [Visualize](https://test.visualize.admin.ch/create/PMlFkdqY0uaW?dataSource=Test) TEST.
![TEST Published Error 2](https://github.com/user-attachments/assets/3efc1485-ca89-4c83-b7c9-4a544fce3ede)
![TEST Published Error](https://github.com/user-attachments/assets/8734f69d-ba2d-4e07-bbb2-14cbc8f09920)

This also happened after trying it with another cube ([Russkonzentration Cube Creator](https://test.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!russkonzentration-test-aonmzjbr29r/publication) / [Russkonzentration Visualize TEST](https://test.[visualize.admin.ch](https://test.visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/russkonz_test/1&dataSource=Test)/create/new?cube=https://environment.ld.admin.ch/foen/russkonz_test/1&dataSource=Test))

**Comment by sosiology** [comment]
Hi @tboeni thanks for reporting. Could you specify what is not showing up correctly? If i open the Rodungstatistik data set on TEST I see that Version 5 is there and there are values in the column "Rodungszweck", as oppose to URLs

![image](https://github.com/user-attachments/assets/da7409c3-0960-4768-bbed-8c4e0502de2e)

Thanks in advance!

**Comment by ptbrowne** [comment]
@tboeni How long did you wait after the publication. I wonder if this is not the caching from Lindas. On our end, waiting for 10m after publication should [suffice](https://github.com/visualize-admin/visualization-tool/blob/a0130d71f1d049b999ec7348e29ae09e6905a54a/app/graphql/context.tsx#L145).

**Comment by Rdataflow** [comment]
@tboeni you unluckily bumped into a 2h caching effect on TEST/INT which will be gone soon, once purging is operating as expected. the next time just go for Test-uncached 👍 or wait 2h...

**Comment by sosiology** [comment]
@Rdataflow thanks for the input. @tboeni do you have further questions, or can this ticket be closed?

**Comment by tboeni** [comment]
@ptbrowne I waited more than 10mins, but as @Rdataflow specified, I was probably unlucky and it confused me a bit so I opened this issue :-)
@sosiology I have no further questions regarding this Issue thanks!

**Comment by Rdataflow** [comment]
@tboeni this is expected to be fixed now with the changes @ludovicm67 deployed now - can you check and report back?

**Comment by tboeni** [comment]
@Rdataflow  @ludovicm67 I tested publishing on TEST a couple of times now this afternoon and I did not run into the same symptom again. Publishing was very fast, thanks!

**Comment by ludovicm67** [comment]
@tboeni thanks a lot for your feedback! 👍
