### ISSUE TITLE
Saved Charts cannot be deleted

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1686]
**Describe the bug** 
Published and draft charts cannot be deleted in the Login Area

**To Reproduce** 
 
1. Go to 'visualize.admin.ch'
2. Login with you eIAM login
3. Create a chart and save as draft or publish
4. See that nothing happens

**Expected behavior** 
When a chart is deleted, it should not appear in the list of my visualizations in the login area

**Screenshots or video** 
[If applicable, add screenshots or a short video to help
put your problem into a context.](https://github.com/user-attachments/assets/dcb0a753-ac2a-48ac-8572-33d1cb11c18c)

**Environment (please complete the following information):**

- Visualize environment and version: PROD v4.7.4 ([71758ed](https://github.com/visualize-admin/visualization-tool/commit/71758ed5983be7beb7b6bc0d4f39ab84668b2e57))
- Browser and version [e.g. Chrome 107]

**Additional context** 
-

**Comment by KerstinFaye** [comment]
Thanks for the description. Neither drafts nor published visualizations can be deleted.
https://github.com/user-attachments/assets/f4ef5334-96da-4b42-8ed1-9e5a50f5bbfa

**Comment by sosiology** [comment]
@bprusinowski maybe i am missing something, but i still cannot delete draft or published charts. Tested on TEST and also double checked on INT. 

I first tried to delete an chart i already had in my user profile. When that didn't work i created a new chart and tried to delete it without success. Lastly i tried to open a private browser window but that also didn't result in the chart being deleted. 

Is there something else I should try?

**Comment by bprusinowski** [comment]
@sosiology unfortunately it looks that TEST is still not deploying correctly, and I didn't deploy to INT, to technically it's not possible to test the change yet. I could do a minor INT deployment tomorrow so the recent changes could be tested, let me know if that makes sense.

**Comment by bprusinowski** [comment]
@lloydrichards TEST should work now going forward :)

**Comment by lloydrichards** [comment]
> @lloydrichards TEST should work now going forward :)

me? 🥺👈

**Comment by sosiology** [comment]
Tested on TEST and works as expected, thank you @bprusinowski
