### ISSUE TITLE
Cleanly terminate eIAM session

### ISSUE THREAD

**Issue by adintegra** [visualize-admin/visualization-tool#1691]
While logging out, the application currently makes a POST request to https://visualize.admin.ch/api/auth/signout. While this disconnects the session application-side, it doesn't initiate clean termination on the eIAM side. In order to ensure this, Visualize should call the SLO endpoint – this will terminate the eIAM session cleanly server-side.

Please use the official `end_session_endpoint` from the metadata:

- TEST: feds-r.eiam.admin.ch/realms/uvek_bafu-visualise/.well-known/openid-configuration
- INT: feds-a.eiam.admin.ch/realms/uvek_bafu-visualise/.well-known/openid-configuration
- PROD: feds.eiam.admin.ch/realms/uvek_bafu-visualise/.well-known/openid-configuration

For PROD then for example: https://identity-eiam.eiam.admin.ch/realms/uvek_bafu-visualize/protocol/openid-connect/logout

**Expected behavior**
The eIAM session is cleanly terminated.

**Comment by sosiology** [comment]
assume this cannot really be tested, so moving to the next lane (Client Review)

**Comment by bprusinowski** [comment]
Hi @sosiology, it could be tested by logging out from TEST, and seeing that you need to enter your credentials again when trying to log in after that (previously login occurred without a need to re-enter login and password) 👍

**Comment by sosiology** [comment]
Thanks @bprusinowski just tried on test, and can confirm that after signing out, i needed to enter my credentials again to login. 👍
