### ISSUE TITLE
Allow Dashboard Titles to be edited from User Profile

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1692]
**Is your enhancement related to a problem? Please describe.**
Currently, a dashboard title cannot be edited using the "rename" option in the user profile, only the individual chart titles can be changed. 

**Describe the solution you'd like**
I think it would be good to offer the user a way to change the title of the dashboard using the rename feature in the user profile, especially because this title is shown in user profile.

**Describe alternatives you've considered**
None

**Usecases and impact**
This enhancement would allow users to quickly add or edit dashboard titles directly from the User Login Landing page without having to navigate to the editor flow 

**Additional context**

https://github.com/user-attachments/assets/454c0a60-20cd-4280-9e07-155ff7a41e39

**Comment by bprusinowski** [comment]
Fixed via https://github.com/visualize-admin/visualization-tool/pull/1694
