### ISSUE TITLE
Example Charts on Home Page: Box appears above

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1700]
**Describe the bug** 
A box appears above the example charts on the home page on TEST. 

**To Reproduce** Steps to reproduce the behavior:
1. Go to test.visualize.admin.ch
2. Scroll down to the examples (Distribution of expenses and income by office) on the home / landing page 
3. See that the charts have an additional box on top of them 

**Expected behavior** 
The lines / box should not be there

**Screenshots or video** 

![Image](https://github.com/user-attachments/assets/e1ac78e4-e9b2-4847-9dd5-8246e3613eeb)

**Environment (please complete the following information):**

- Visualize environment and version: TEST v4.7.4
- Browser: Chrome, Safari

**Comment by bprusinowski** [comment]
@sosiology should be fixed on TEST :)

**Comment by sosiology** [comment]
LGTM - thanks for the quick fix @bprusinowski 🙇‍♀️
