### ISSUE TITLE
Sidebar Layout Regression

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1705]
**Description**
On test, it appears as the layout in the sidebar has changed, the options are now not seen when initially opened, and the user needs to scroll. 

**To Reproduce** 
1. go to test.visualize.admin.ch
2. Create a chart 
3. Select horizontal axis to see sidebar layout  has changed. 

**Screenshots**
![Image](https://github.com/user-attachments/assets/d4fa7fe4-18cc-45ab-800b-ec2db8d0c321)

https://github.com/user-attachments/assets/6f00430d-f664-4930-9bfb-393cc93d2fa0

**Version**
v4.7.4 ([99eb19f](https://github.com/visualize-admin/visualization-tool/commit/99eb19f12af6920f27d9b7475e6ff74b6501ab98)
Tested on Chrome on Mac

**Comment by bprusinowski** [comment]
Should be fixed on TEST 👍
