### ISSUE TITLE
Improving the visibility of the function "Add a chart"

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1709]
**Problem:**
Users did not find the add chart button easily. 

**Improvement:**
- Emphasize the "+" add chart button to create a new chart.
- Clarify the difference with UX text (‘Add chart’ with plus icon).
- Align layout of editing mode to the layout options mode. 

**Design:**
https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5240-100263&t=wu12MGupEtSjHuVC-4

![Image](https://github.com/user-attachments/assets/df959cb7-e9ce-4121-bda4-26bcfe16799a)

**Comment by bprusinowski** [comment]
Ready on TEST 🧑‍💻

**Comment by sosiology** [comment]
LGTM. Would be good if Kerstin could also test next week.

**Comment by KerstinFaye** [comment]
✅ LGTM. Tested it on INT. 🎉
