### ISSUE TITLE
Line colour does not match the legend colour

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#171]
I have noticed several times that for line diagrams, the line colour does not match the legend colour.
This seems to be the case only when there is only one category.
![image](https://user-images.githubusercontent.com/79834090/139840619-31f1b3fe-5f15-4434-a632-8b9fdfda3baf.png)

**Comment by bprusinowski** [comment]
Hi @ortnever, it should be fixed on DEV :)

Thanks for raising this issue!
