### ISSUE TITLE
Free Canvas Layout: Quickly identify the minimum size of the canvas

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1710]
**Problem:** 
The minimum width of the diagrams in the canvas is difficult to understand. It varies depending on the screen size. Usually only two diagrams fit next to each other. Users are confused that the layout looks different in edit mode than in the published status (more diagrams next to each other). 

**Improvement:**
- Option to ‘Preview the published view’.
- Additional breakpoint so that 3 charts can also be placed next to each other.

Design:
[Interactive prototype](https://www.figma.com/proto/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?page-id=8%3A145669&node-id=5235-123489&node-type=FRAME&viewport=1199%2C369%2C0.13&t=V5EtBLKMUERyDo6g-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5235%3A123489&show-proto-sidebar=1)

![Image](https://github.com/user-attachments/assets/ae661438-0b5b-45e0-bdd6-97b610a910f3)

![Image](https://github.com/user-attachments/assets/e4b78801-0104-4974-9da1-b13d6cab8761)

**Comment by sosiology** [comment]
LGTM!

**Comment by KerstinFaye** [comment]
Works well on INT!  ✅
