### ISSUE TITLE
Layout options: Layout settings are preserved when the user changes to another option

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1711]
**Problem:** 
When users change a dashboard layout option and then return to the originally selected option, the dashboard settings are lost.

**Improvement:**
Save layout settings so that users can switch between the options and the settings are retained.

**Comment by bprusinowski** [comment]
Ready to check on TEST. The previous layout options are preserved when in layouting step; when navigating back to editing and layouting again, they are no longer preserved. We can see how much of an issue this is, and refine in a further iteration 👍
