### ISSUE TITLE
Shared Filters: Global filters should be visible in the viewport of smaller screens when activate

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1712]
**Problem:**
Users don't understand the connection between the input fields and the time slider. Also the toggle with the label "shared" is hard to understand. Users do not see that the time filter is activated because the time slider is not in the viewport.

**Improvement:**
When activating the shared filter, the viewport should scroll to the interactive filter element so that it is in the viewport and users can see the connection between the inout fields in the sidebar and the element in the dashboard.

![Image](https://github.com/user-attachments/assets/b1c165a1-2e67-4242-a783-d8b5d96c85bf)

**Comment by bprusinowski** [comment]
Ready on TEST ✔️
