### ISSUE TITLE
Option to change the tab-label or delete it entirely & make more the horizontal scroll of many tabs more visible

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1714]
**Problem:**
Users had difficulty switching between tabs when they had many chart tabs open. They did not realize that they could scroll horizontally.
Tab label names have been super long since they were the same as the chart title. 

**Improvement:**
- Clearly indicate that tabs can be scrolled horizontally. Little arrows left and right when many tabs.
- The user should have the option to change the label of the tab or delete it entirely.

**Design:**
[Figma Design](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5240-95644&t=clRv0lDQb7CoJia4-4)

![Image](https://github.com/user-attachments/assets/34a1552c-7c12-4156-b80a-0d31b49b84ff)

**Comment by bprusinowski** [comment]
Ready on TEST 🧑‍💻

**Comment by KerstinFaye** [comment]
@bprusinowski I added the link in the chevron when clicking on the tab and also the field underneath the "title & description" in the editing mode.

**Comment by bprusinowski** [comment]
Hi @sosiology, thanks for testing 🙇‍♂️ Maybe we could combine the two first things in a new issue? The behavior of having an empty space is there by default in MUI (https://mui.com/material-ui/react-tabs/#scrollable-tabs), but we could try to change this 👍

**Comment by sosiology** [comment]
Thanks for the explanation @bprusinowski i created a new issue here #1776

**Comment by KerstinFaye** [comment]
Thanks @sosiology for the observations. 
1. I agree this would be very nice to align and only on scroll the space would be used for the arrow.
2. @bprusinowski If I remember correctly we discussed about this before? But for sure it would make a lot of sense to limit the characters.

**Comment by sosiology** [comment]
@KerstinFaye thanks for your feedback. If you have any other ideas or improvements on the topic of tab labels please adde them to the new issue here #1776
