### ISSUE TITLE
Adding dataset in the legend again

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1717]
**Problem:**
All participants first search for the datasets in the legend before they go to data sources or the Metadata Panel. They don't realize that "Details" links to the metadata panel, where the information about the dataset can be found.

**Improvement:**
- Show dataset in the legend. We will only show the dataset name and last updated. The rest of the information can be found in the metadata panel.
- Emphasize the "Details" button and possibly rename it

[Figma Design Section](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=4851-203884&t=0BpnGk1RIh4KF9os-4)

![Image](https://github.com/user-attachments/assets/7021f37b-9149-48cf-ae2b-7723c4c98018)

**Comment by bprusinowski** [comment]
@KerstinFaye should be ready on TEST 👍

**Comment by KerstinFaye** [comment]
Great. Thanks @bprusinowski. Looks good.

**Comment by sosiology** [comment]
LGTM Too. Thanks for this @bprusinowski
