### ISSUE TITLE
Merging of cubes: Taking out the dropdown in the dataset preview - modal

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1718]
**Problem:**
Data preview after a second data set has been selected: Users think that they have to select and deselect dimensions in the dropdown and by that affect which dimensions they have available later for the chart.

**Improvements:**
Remove dropdown for comparing dimensions. Improve the UX writing of the description (shorten). But still keep the preview of the datasets.

**Design**
[Figma Design](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=3834-230792&t=0BpnGk1RIh4KF9os-4)
![Image](https://github.com/user-attachments/assets/277a0b5d-5c80-48ed-8bcc-f09171c8f462)

**Comment by bprusinowski** [comment]
Ready on TEST 👌

**Comment by KerstinFaye** [comment]
Thank you. Looks good to me.
