### ISSUE TITLE
Add timestamp to drafts

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1719]
**Problem:**
It is difficult for users to distinguish between drafts of the same date. This is especially true if several drafts have similar names, as they are not displayed in full.

**Improvement:**
A timestamp in addition to the date for the saved drafts.
A tooltip that displays the full title of the chart on hover.

**Design:**
[Figma Design Link](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=3168-337965&t=0BpnGk1RIh4KF9os-4)
![Image](https://github.com/user-attachments/assets/9e35a185-e8e4-4a95-8829-536588283f6a)

**Comment by bprusinowski** [comment]
Ready on TEST 👍 @KerstinFaye I used the built-in JavaScript function to format the timestamp, so it looks a bit different than in the design. Let me know if I should replace the comma with whitespace and also remove seconds. I think I missed that we only stop at minutes in the Figma file 🫣

**Comment by KerstinFaye** [comment]
@bprusinowski Looks good to me, thanks!
