### ISSUE TITLE
Dropdown with links when clicking on username in the header

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1720]
**Problem:**
Users do not realize that they have to click on their profile name to get to their saved visualizations.

**Improvement:**
Dropdown with links when clicking on profilename: My visualisations, eIAM account, Logout

**Design:**
[Figma Design Link](https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5295-144375&t=0BpnGk1RIh4KF9os-4)

![Image](https://github.com/user-attachments/assets/59777f56-ebb0-4608-a630-283c7f6cc8ed)

**Comment by sosiology** [comment]
Looks Good @bprusinowski but i noticed the translations are missing - we should probably add those. Maybe @KerstinFaye can support? 
![image](https://github.com/user-attachments/assets/faad0637-70a8-4dad-9477-1075d899b6ef)

**Comment by KerstinFaye** [comment]
Also one more thing. Not super important, just a detail...Could we delete the pointer of the dropdown? I realized that it's overlapping with the name and it's not helpful. For smaller screens it would point at the edge of the name. Maybe it's easier to just delete the little triangle. Thanks

![Image](https://github.com/user-attachments/assets/375ac585-8434-4be9-b131-b29a6fcfe71f)

**Comment by bprusinowski** [comment]
@KerstinFaye sure, I missed this one 😱 It should be testable in ~10 mins via https://github.com/visualize-admin/visualization-tool/pull/1729 👍

**Comment by sosiology** [comment]
@bprusinowski i noticed while testing that the translations are missing for IT and FR

ChatGPT translation FR
My visualizations: Mes visualisations
eIAM Myaccount: Mon compte eIAM
Sign out: Se déconnecter

ChatGPT translation IT
Le mie visualizzazioni
Il mio account eIAM
Disconnetti

Probably need a better translation at some point, but i figure having something is better than nothing..

**Comment by sosiology** [comment]
LGTM

**Comment by KerstinFaye** [comment]
@bprusinowski I tried to add the translations, but I could not even find the English Version in Accent? 🤔
![Screenshot 2024-10-01 at 11 45 13](https://github.com/user-attachments/assets/9a983185-f135-4acd-af3d-c459e090a39c)

**Comment by bprusinowski** [comment]
@KerstinFaye as this is a name of a service (same in every language), it's not available in the translation strings. Let me know if this should be changed 👍

**Comment by KerstinFaye** [comment]
@bprusinowski Thanks. I didn't realized you added them already. 🫣 I think case no need to change anything.

**Comment by bprusinowski** [comment]
Aaa, yes, I added them already 😅 Right, thanks 🙇‍♂️
