### ISSUE TITLE
Shared Filters: Global filters should be visible in the viewport of smaller screens when activated

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1721]
**Problem:**
Users do not understand the connection between the input fields and the interactive filter element in the dashboard. Users do not see that the time filter is activated because the time slider is not in the viewport.

**Improvement:**
When activating the shared filter, the viewport should scroll to the time slider so that it is in the viewport.

**Comment by bprusinowski** [comment]
Ready on TEST 👍

**Comment by sosiology** [comment]
Works as described. (I think this was duplicated in the public repo)

**Comment by KerstinFaye** [comment]
yes, works perfectly fine. But I also think I tested this already before.
