### ISSUE TITLE
Adjusting the size of the 'Add Chart'-overlay

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1731]
Please center-align the content in the overlay when clicking 'Add chart'. The overlay is also wider than before. 

![Image](https://github.com/user-attachments/assets/2aec36b1-9214-4072-9d13-333d03c0c72d)

**Comment by bprusinowski** [comment]
@KerstinFaye could you provide a bit more information on how to reproduce the bug? It's not that wide on my side both in Safari and Chrome 🤔

**Comment by bprusinowski** [comment]
Closed by https://github.com/visualize-admin/visualization-tool/pull/1729

**Comment by sosiology** [comment]
LGTM this is what i see in chrome 
![Image](https://github.com/user-attachments/assets/7302934a-247a-4564-b574-abddd84e8fb9)

**Comment by KerstinFaye** [comment]
✅  Same on INT. Looks perfect now.
