### ISSUE TITLE
Axis title wrapping for every axis type

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#1735]
The wrapping of long or overlapping axis titles was implemented for dual-axis charts in https://github.com/visualize-admin/visualization-tool/pull/1698. We should extend this behavior to make sure every axis title wraps and extends chart height correctly.

**Comment by bprusinowski** [comment]
Looks like we still need to adjust chart height if titles are overlapping @noahonyejese? See the comment [here](https://github.com/visualize-admin/visualization-tool/pull/1745/commits/facb3bcc6c885f8b28561535247f1d91db422653#r1770523759), let me know if I missed something 👍

**Comment by sosiology** [comment]
Tested with https://test.visualize.admin.ch/v/byIM6i81aVeb?dataSource=Test-uncached LGTM. Thanks @bprusinowski
