### ISSUE TITLE
interactive filters in published mode show impossible filter options

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1736]
**Describe the bug**
interactive filters in published mode show impossible filter options.

**To Reproduce**
1. Go to https://visualize.admin.ch/v/x4a27Ep3GXXK?dataSource=Prod
2. Click on 'show filters'
3. Choose any other Municipality
4. See the chosen municipality was an impossible filter option and shouldn't be available at all

yet another way to run into impossible options is the municipality dropdown shown at https://visualize.admin.ch/de/v/tyzKKd4eZb8o

**Expected behavior** 
Interactive Filters in published mode only show possible filters.

**Environment (please complete the following information):**
- Visualize environment and version: PROD 4.7.4

cc @bprusinowski

**Comment by bprusinowski** [comment]
@Rdataflow thanks for providing another example, I take another look to see if we can also fix these cases 👍

**Comment by sosiology** [comment]
Reviewed on TEST and works as expected only filter options that yield results are shown. 
Test Chart See: https://test.visualize.admin.ch/v/Z_PSpKdNBlzN?dataSource=Test

**Comment by sosiology** [comment]
Works on INT with 4.9 as expected: https://int.visualize.admin.ch/v/JbEBkE_HYpF6?dataSource=Prod
