### ISSUE TITLE
Allow editing free canvas dashboard layout in preview mode

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#1739]
Currently, we are able to preview free canvas dashboard layout in different screen sizes, but the changes applied to it in a preview mode are not persisted on exiting it – we should change this behavior to save such changes.

**Comment by sosiology** [comment]
Looks good to me.
- i can select between 4 layout options
- If i edit the dashboard in different preview modes the changes persist, I can also order the charts differently per option (mobile, tablet, laptop etc.) 
- In XL preview mode with a reduced browser window, i can see the columns and scroll horizontally
