### ISSUE TITLE
error bars in segmented lines use misleading colors

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#1743]
**Describe the bug**
error bars in segmented lines use misleading colors

**To Reproduce** Steps to reproduce the behavior:

1. Go to https://test.visualize.admin.ch/v/yK9n8dvm0Lya?dataSource=Test-uncached
2. Zoom in
3. See all the error bars are in blue color - even those for the yellow line

**Expected behavior**
reuse colors consistent with the data line

**Screenshots or video**
![image](https://github.com/user-attachments/assets/c27bd09b-05c6-4c36-a941-2e09e24f5611)

**Environment (please complete the following information):**
Visualize environment and version: TEST 4.8.0

cc @bprusinowski @kronmar-bafu

**Comment by sosiology** [comment]
@Rdataflow the fix is ready for review and approval on INT
