### ISSUE TITLE
Embed mode improvement for iframe

### ISSUE THREAD

**Issue by KerstinFaye** [visualize-admin/visualization-tool#1747]
As a user I would like the option to embed my visualization in an iframe that behaves responsive. The JavaScript part of the embed code ensures that the iframe always maintains the correct size.

Radio buttons to select between responsive iframe and regular iframe above the embed link.

Figma Design Section:
https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5615-74527&t=yunKLfeL5dnjOYu5-4

![Image](https://github.com/user-attachments/assets/722f4a7b-2856-47c4-ab42-f60991c4e43d)
![Image](https://github.com/user-attachments/assets/b7bbecdf-1a06-4439-b7a9-d5d40919e0d1)

Further we would like to optimize the embed option for external Application. (E.g. AEM). Therefore we change the UI text into more generic version, so it is not only applicable for AEM.

Design: 
https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5623-44100&t=yunKLfeL5dnjOYu5-4

DoD
- Iframes behave responsive
- Iframe borders can be removed by using a specifc URL query parameter (e.g. ?noborder)

**Comment by noahonyejese** [comment]
I'm on this.

**Comment by KerstinFaye** [comment]
LGTM. Thanks! I did some little adjustments with the German translation in Accent.
