### ISSUE TITLE
Linked Column Not Recognized

### ISSUE THREAD

**Issue by mwannier30** [visualize-admin/visualization-tool#1749]
**Describe the bug** 
I've linked two tables in CubeCreator using the property `schema:name`. One table serves as the main table, while the other contains translations of species found in the main table. The link appears to work correctly, as I can retrieve the expected values in the Cube Design section. However, when I attempt to create a visualization in visualize and use the linked column as an Axis, Segmentation, or Filter, it fails to recognize the distinct species. As a result, it only displays a single color and no text in the legend.
I first did the same Cube in Int and it worked as expected, but now on Prod it doesn't work.

**To Reproduce** Steps to reproduce the behavior:

1. Start a visualization using this [dataset](https://visualize.admin.ch/en/browse?dataset=https%3A%2F%2Fhealth.ld.admin.ch%2Ffsvo%2FBT%2F11&dataSource=Prod)
2. Create a column Chart
3. Choose `Canton` as Horizontal Axis and `Species` as Segmentation

**Expected behavior** 
I expect to have different colors between the species, and the translations as legend.
I expect it to look how it looks on [int](https://int.visualize.admin.ch/en/v/wLtoDUsRpLMG?dataSource=Int)

**Screenshots or video** 
![Capture d’écran (22)](https://github.com/user-attachments/assets/c15f6878-fe9f-49ec-bfa8-738b0ec67e3d)

**Environment (please complete the following information):**

- Visualize environment and version: PROD v4.7.4
- Browser and version: Microsoft Edge V128.0.2739.67

**Comment by bprusinowski** [comment]
Hi @mwannier30, looks like the problem was fixed already (I was able to make this chart: https://visualize.admin.ch/en/v/sp_EnbKskLqW?dataSource=Prod)? Let me know in case something is still unclear :)
