### ISSUE TITLE
User Profile: Change Text from `Copy` to `Duplicate`

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1751]
Change the UI Text in the "Actions" Menu from `Copy` to `Duplicate` to align the text with the rest of the UI

![Image](https://github.com/user-attachments/assets/e65c9119-06d3-48e9-949d-baa7f76d64ba)

**Comment by bprusinowski** [comment]
Closed by #1760

**Comment by sosiology** [comment]
Tested on TEST - LGTM thanks @bprusinowski
