### ISSUE TITLE
`Cannot access 'h' before initialization` by Table Compact view

### ISSUE THREAD

**Issue by mwannier30** [visualize-admin/visualization-tool#1752]
**Describe the bug** 
When creating a table as chart type with a column displayed as an heatmap, clicking the 'compact view' button triggers an `Unexpected error: Cannot access 'h' before initialization`.

**To Reproduce** Steps to reproduce the behavior:

1. Create a table 
2. Change a measure column's style to `heat map`
3. Click on `compact view` above the table

**Expected behavior** 
I'm not sure what the compact view is supposed to do, but I don't expect to encounter an error.

**Screenshots or video** 
<img width="639" alt="image" src="https://github.com/user-attachments/assets/a3ccc3fb-43cc-45eb-b74b-5a1259ab9c96">

**Environment (please complete the following information):**

- Visualize environment and version: PROD v4.7.4
- Browser and version: Microsoft Edge v128.0.2739.67

**Comment by sosiology** [comment]
@mwannier30 this issue is now resolved on TEST and will be on PROD with the next release. 

Test chart with heatmap and compact view https://test.visualize.admin.ch/en/v/YuPhRu0hIKQS?dataSource=Prod
