### ISSUE TITLE
Change color of "My Visualizations" link when saving draft

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1756]
**Is your enhancement related to a problem? Please describe.**
Change the link "Meine Visualisierungen" to the regular Blue (that is used in buttons and links) instead of the violette? 
![Image](https://github.com/user-attachments/assets/3ba3abae-7707-406b-895f-a96bd97b340e)

**Describe the solution you'd like**
After the link is clicked once, it should remain blue like the other links in the UI instead of changing to purple (clicked state)

**Usecases and impact**
Alignment across the UI with other links

 _Originally posted by @KerstinFaye in [#105](https://github.com/visualize-admin/visualization-tool-private/issues/105#issuecomment-2337310705)_

**Comment by sosiology** [comment]
Nice one! Thanks for this fix @bprusinowski LGTM on TEST
FYI: @KerstinFaye

**Comment by KerstinFaye** [comment]
Thanks for the fast fix @bprusinowski!

**Comment by KerstinFaye** [comment]
Thanks for the fast fix @bprusinowski 🎉
