### ISSUE TITLE
Shared Filter Slider not in Viewport

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1757]
The Slider Labels for global filters are not shown in the viewport in layout mode

![Image](https://github.com/user-attachments/assets/0381889e-8847-48e3-8119-66b935e37d93)

In published mode they are shown as expected
![Image](https://github.com/user-attachments/assets/74edd8b1-b0ac-42e8-90e3-22d0573e3d9e)

To Reproduce: 
1. Go to https://test.visualize.admin.ch/en/v/0lLYk-4O7QEX
2. Click copy and edit this visualization
3. Click on "proceed to layout options" 
4. See that the labels on the slider are outside of the viewport

**Comment by sosiology** [comment]
Looks great @bprusinowski thanks! The tooltips are now fully shown in the editing view, also in a minimized browser window 💪 

![Image](https://github.com/user-attachments/assets/a75d9c02-d182-4b2e-947d-69b6be7bda32)

**Comment by KerstinFaye** [comment]
Same for me. Thanks @bprusinowski
