### ISSUE TITLE
Allow User to Copy Share Link from User Profile

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1758]
At the moment, if the user selects "share" on a published chart in the user profile, they are taken to the published view where they can then click the "share" button, and copy the URL. 
I think this behaviour could be confusing for someone who is using visualize for the first time, as they then have to find the share button in UI of the published view to copy the URL. I think it would be a nice enhancement to allow the user to copy the published chart link,  and possibly even the embedd code directly from the user profile, as oppose to having them first open the published view. 

https://github.com/user-attachments/assets/53e9b63d-59fb-41aa-b4dc-99d5acb0aa85

**Comment by sosiology** [comment]
@KerstinFaye @bprusinowski this is an idea/proposal to enhance the sharing behaviour in the user profile - would be interested to know what you think.

**Comment by bprusinowski** [comment]
I like the idea @sosiology 💯 Maybe we could then keep the current behavior under a "Preview" button, as we have for drafts?

**Comment by sosiology** [comment]
sorry for the delayed reply @bprusinowski yes, having the current behaviour under a "Preview" as for drafts would make sense to me. 

Just cc'ing @KerstinFaye here so she is in the loop :)

**Comment by KerstinFaye** [comment]
Thanks @sosiology and @bprusinowski for these suggestions. I really like the idea of having the share "published preview" link in the preview and the direct share button in the table. This would be very handy for the users. We can do this for the next iteration.

**Comment by sosiology** [comment]
Thanks @KerstinFaye 
Here is the new issue for the share link from the profile: https://github.com/visualize-admin/visualization-tool/issues/1758

**Comment by sosiology** [comment]
Cool, thanks for your feedback @KerstinFaye. Maybe we can tackle this in the next sprint, pending other priorities 🤞

**Comment by noahonyejese** [comment]
@KerstinFaye I have restructured the code to allow to use the same UI we use on the Editor side but on the Profile page, let me know if implementing a button in the actions like in the video above called for "Share" and "Embed" and on click it opens the Share or Embed UI just like on the Editor page. 

Let me know if this is optional from a design perspective. - Thanks

**Comment by KerstinFaye** [comment]
@noahonyejese @sosiology 
Here is what happens if you click "embed" in the more options button on a published chart listed the User Profile:
https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5896-37493&t=uybrHwBMTujLYK8N-4
![Image](https://github.com/user-attachments/assets/5131fbe1-5e7e-4851-9482-fde64e7963b2)

Here is what happens if you click "share" in the more options button on a published chart listed the User Profile:
https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5917-75765&t=uybrHwBMTujLYK8N-4
![Image](https://github.com/user-attachments/assets/cd497462-147b-45ec-b5fc-f2b1d125545e)

**Comment by sosiology** [comment]
Thanks @KerstinFaye these proposals work for me 💯

**Comment by KerstinFaye** [comment]
@noahonyejese Thanks for implementing this. I realized when I went to my User Profile List of charts, then clicked on more options of a published Dashboard and then clicked on "embed",  I saw the option to remove the border, which should not be possible for dashboards. But this seams to be not only from the list the case, but also from the published view. 
![Image](https://github.com/user-attachments/assets/74781b2c-0fd9-47ed-95c4-6d23da59dce0)

**Comment by noahonyejese** [comment]
> [@noahonyejese](https://github.com/noahonyejese) Thanks for implementing this. I realized when I went to my User Profile List of charts, then clicked on more options of a published Dashboard and then clicked on "embed", I saw the option to remove the border, which should not be possible for dashboards. But this seams to be not only from the list the case, but also from the published view. ![Image](https://github.com/user-attachments/assets/74781b2c-0fd9-47ed-95c4-6d23da59dce0)

I was told by @bprusinowski that it should only be disabled for tab layout Charts? Let me know if something changed or if that was a misalignment.  CC: @sosiology

**Comment by bprusinowski** [comment]
@sosiology I think that was the recommendation and the code change that was implemented (technically single charts have a tab layout, but we hide the icon and tab title in case we only have one chart). Maybe it's some different thing that sneaked in 👍
