### ISSUE TITLE
User Profile: Missing Translation for "Rename" option

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1765]
In the user profile in the edit button, the translation is missing for "Rename"

French: Renommer
Italian: Rinomina
German: Umbenennen
![Image](https://github.com/user-attachments/assets/4508fb92-9d16-4720-85dd-3806109d3264)

**Comment by sosiology** [comment]
@bprusinowski if this is something @KerstinFaye could do in accent, please assign to her. Thanks!

**Comment by KerstinFaye** [comment]
@bprusinowski @sosiology  I added the translations in Accent.
