### ISSUE TITLE
Dashboard Not Rendered Correctly in Published Mode

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1766]
I created a dashboard with three charts: 
The third chart is not shown correctly in the published dashboard.
If i try to copy and edit the dashboard, I get to the editor mode but upon clikcing "proceed to layout options" an application error is shown. 

There are 2 issues that need to be looked into. 
- Dashboard Layout not correct
![Image](https://github.com/user-attachments/assets/a530071f-c3a5-4364-8c39-70578d2d40b3)

- Application error when proceeding to the layout options
![Image](https://github.com/user-attachments/assets/4a787528-a006-4560-aed4-271aa6013a54)
https://github.com/user-attachments/assets/c0c75eeb-83d4-466c-81b0-b48b2982e060

**Comment by bprusinowski** [comment]
@sosiology this should be fixed by #1762. I'll merged the PR, should be one TEST in ~20 mins 👍

**Comment by sosiology** [comment]
Thanks @bprusinowski

**Comment by KerstinFaye** [comment]
Tried to recreate it. Seams fixed.
