### ISSUE TITLE
Visualize cannot load cube published on lindas int

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1767]
I published Cube UBD003001 Red List on Lindas IINT with Cube creator, but Visualize cannot load the cube.
According to Cube Validator the cube is conformed to the basic profile.
The cube does not even appear in Visualize search.

**Comment by sosiology** [comment]
Thank you for reporting the issue @ortnever. @bprusinowski could you take a look?

**Comment by bprusinowski** [comment]
Hi @ortnever, could you share more information about the cube, such as its IRI? Or maybe a link to LINDAS query to show `DESCRIBE` the cube?

This would be very helpful if the cube doesn't even appear in the search. Thanks in advance!

**Comment by ortnever** [comment]
Hi @bprusinowski 
https://environment.ld.admin.ch/foen/ubd003001
https://int.visualize.admin.ch/en/browse?dataSource=Int&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd003001
https://int.lindas.admin.ch/sparql#query=PREFIX+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E%0A%0ADESCRIBE+%3Fcube%0A%0AFROM+%3Chttps%3A%2F%2Flindas.admin.ch%2Ffoen%2Fcube%3E%0AWHERE+%7B%0A%0A++++++%3Chttps%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd003001%3E+schema%3AhasPart+%3Fcube+.%0A++++++%3Fcube+schema%3Aversion+14+.%0A++++%0A%7D%0A%0A&endpoint=https%3A%2F%2Fint.lindas.admin.ch%2Fquery

**Comment by ortnever** [comment]
Does it help?

**Comment by bprusinowski** [comment]
Yes, thanks @ortnever! I am taking a look 👍

**Comment by bprusinowski** [comment]
It looks like the cube with version 14 has a `schema:expires` predicate, which excludes the cube from being usable in Visualize. For "valid" cubes, we can't have this property, as it's used to filter out depreciated cubes.

<img width="1061" alt="Screenshot 2024-09-27 at 15 32 17" src="https://github.com/user-attachments/assets/538dc692-66d2-457e-9ec5-e2ef1ba41de4">

@ortnever let me know if this makes sense and if removing the property fixes the error 👀

**Comment by ortnever** [comment]
Thanks Bartosz for the explanation. I don't understand how this cube got the ‘expires’ property. 
I created and published this cube via the Creator cube and did not use the ‘unlist cube’ function, which is intended to depreciate the cube.
Could you please delete the property "expires".
Thank you.

**Comment by bprusinowski** [comment]
No problem! Unfortunately I cannot remove the "expires" property, I believe it requires some kind of "admin" rights to be able to remove triples from LINDAS – I'd suggest to reach out to Zazuko to support, as it also looks like a Cube Creator issue.

Let me know in case there's anything else I can support with 😊

**Comment by ortnever** [comment]
Thank you Bartosz ! In this case you can close the issue. Have a nioce week-end !

**Comment by bprusinowski** [comment]
Thanks @ortnever, you too!
