### ISSUE TITLE
Bar Charts Overlapping

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#177]
- The bar charts overlap into the next column
- Forstwirtschaftliches Testbetriebsnetz (TBN): Ergebnisse des Gesamtbetriebes - Betriebswirtschaftliche Kennzahlen nach Kennzahl, Forstzone, Hauptproduktbereich und Jahr

![Screenshot_2020-11-30_at_16 31 01](https://user-images.githubusercontent.com/59613691/139865414-3de482ed-ad1b-4dce-97b0-8b476301e520.png)

![Screenshot_2020-12-01_at_16 03 43](https://user-images.githubusercontent.com/59613691/139865423-83c73234-e35a-43eb-acdc-4adbaf65528e.png)

![Screenshot_2020-12-02_at_09 23 21](https://user-images.githubusercontent.com/59613691/139865424-dc053188-5fa6-4f32-b23b-1f2bb5ffe559.png)

**Comment by ptbrowne** [comment]
May be fixed by @bprusinowski in 251d8a37fecc5f838773517ec2fb5e26094158a9. The dataset does not exist anymore unfortunately.
