### ISSUE TITLE
Color Changes Lag for Error Bars

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1771]
This is a follow up issue for #1743 with a further improvement. 

**Description of Issue**
When the colors of the lines in the chart are changed the error bars to not react right away and remain in their previous color  until the chart is published.

**Steps to Reproduce**
1. Go to https://test.visualize.admin.ch/v/yK9n8dvm0Lya?dataSource=Test-uncached
2. Copy and edit the visualization
3. Open the segmentation filter
4. Change the color of the selected filter from orange to purple
5. See that the line changes to purple but the error bar remains orange 
![Image](https://github.com/user-attachments/assets/067c66c4-ed8e-4d06-8632-76845e4d7a42)
6. See when chart is published, error bars are correctly shown in purple 
![Image](https://github.com/user-attachments/assets/484b3f08-ad04-4656-ab7f-b71a2bb0aef0)

**Comment by bprusinowski** [comment]
Should be fixed on TEST in ~20 mins 🤞

**Comment by sosiology** [comment]
LGTM 🎉 . Thanks @bprusinowski for the quick fix
