### ISSUE TITLE
✅ Only one Dataset shown in legend when 2 cubes are merged

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1772]
**Describe the bug** 
When merging 2 cubes into a comparison chart, only one dataset is shown as the source in the legend under the chart.

**To Reproduce** Steps to reproduce the behavior:

1. Go to 'https://test.visualize.admin.ch/en/v/cwiHCcmWVyTi?dataSource=Test'
2. Open Details
3. See that 2 datasets are used in the visualization (Einmalvergütung für Photovoltaikanlagen and Electricity tariff per provider)
4. See that only one dataset is shown in the legend

**Expected behavior** 
Both datasets should be shown in the legend

**Screenshots or video** 
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/afab89b1-af99-44fb-8f80-e2c15d7a66da">

**Environment (please complete the following information):**

- Visualize environment and version: TEST v4.8.0 ([d6a6ad5](https://github.com/visualize-admin/visualization-tool/commit/d6a6ad5c625da81c164fed1e37aaf15fceb9cee8))
- Browser: Chrome

**Comment by sosiology** [comment]
Thanks for clarifying @bprusinowski makes total sense to me to only show 2 data sources when in fact 2 data sources are actually used in the chart 💯

**Comment by KerstinFaye** [comment]
@sosiology @bprusinowski Thanks for this observation. To me this leads back to the discussions of disabling regular chart types when two datasets are merged. My opinion is that it confuses the user if they only see one measure or one dataset even though they added another dataset. We should bring back this discussion when we revise the project again and focus again on the flow for merging cubes.

**Comment by sosiology** [comment]
@KerstinFaye thanks for the feedback. I added an issue #1778 so that we don't forget in the next sprint
