### ISSUE TITLE
Table fails at automatic generated sparql-queries

### ISSUE THREAD

**Issue by CDiGallo** [visualize-admin/visualization-tool#1775]
**Describe the bug**  

The automatic generated sparql-query for tables seems to be  broken or not updated. (does not work).

**To Reproduce** Steps to reproduce the behavior:

1. Go to '.[.](https://visualize.admin.ch/create/iesQqyggKQZD?dataSource=Prod). '
2. Click on 'choose table view' The table loads.
3. Click on generate sparql query'
4. table does not load -> timeout.

**Expected behavior** I would expect the table to load. probably also a #pragma off and a "select distinct" at the beginning.

**Environment (please complete the following information):** PROD

@Rdataflow  @l00mi

**Comment by CDiGallo** [comment]
federal chancellery wants to use this feature more extensively.
Also relevant for distribution of Schwermetalbelastung.

**Comment by sosiology** [comment]
Thanks for reporting @CDiGallo I was able to reproduce the bug with the dataset: "Bodenbelastung durch Schwermetalle
" 

Screenshot of the timeout on LINDAS to support with investigating 
![image](https://github.com/user-attachments/assets/0168cfda-0fae-4b9e-a9f7-07bf2d4d3390)

**Comment by sosiology** [comment]
@CDiGallo the fix is ready for review on INT. 

I tested with the following charts and in all cases the SPARQL query loaded in the editing mode. 
- https://int.visualize.admin.ch/v/9gnYPJJwFugh?dataSource=Prod
- https://int.visualize.admin.ch/v/rcI7YTuBKDPT?dataSource=Prod

**Comment by CDiGallo** [comment]
@sosiology  Thank you very muc!

@https://github.com/l00mi
@l00mi

Does this fix your problem in general?
