### ISSUE TITLE
Discuss -  disabling regular chart types when 2 data sets are merged

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1778]
@sosiology @bprusinowski Thanks for this observation. To me this leads back to the discussions of disabling regular chart types when two datasets are merged. My opinion is that it confuses the user if they only see one measure or one dataset even though they added another dataset. We should bring back this discussion when we revise the project again and focus again on the flow for merging cubes.

_Originally posted by @KerstinFaye in https://github.com/visualize-admin/visualization-tool/issues/1772#issuecomment-2385165068_

Related to: https://gitlab.ldbar.ch/bafu/visualize/-/issues/697

**Comment by KerstinFaye** [comment]
Based on our discussion with @bprusinowski we decided to not disable regular line and bar chart when more than one dataset is added. 
If we disabled regular chart types, there would be a confusion of why the user can’t show a  regular chart-type after adding a new dataset. The user could be frustrated to have less options than more.

To help the user, we will improve the default chart-type that is shown as soon as another dataset is added.
