### ISSUE TITLE
Table Chart - Column Bar charts - Backgrounds seems off

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#178]
- Shouldn't the grey background bar, have the max width of the column? There should be no spacing between the grey bar, and the actual bars
- Datensatz: Forstwirtschaftliches Testbetriebsnetz (TBN): Ergebnisse des Nebenbetriebes - Betriebswirtschaftliche Kennzahlen des Hauptproduktbereichs Dienstleistungen nach Kennzahl, Forstzone, Produkt und Jahr
- 
![Screenshot_2020-11-30_at_16 28 05](https://user-images.githubusercontent.com/59613691/139866144-0cbcf7d0-d8b2-4f1f-89bd-a6139a0ec10b.png)

![Screenshot_2020-11-30_at_16 28 47](https://user-images.githubusercontent.com/59613691/139866150-25acab77-2eff-4d1b-bb23-324a4a0b5107.png)

![Screenshot_2020-11-30_at_16 29 06](https://user-images.githubusercontent.com/59613691/139866153-8f15f86c-c5bc-45ab-a7c7-3b899e32db2c.png)

**Comment by ptbrowne** [comment]
Just to be sure, this is a table chart right ?

**Comment by AnninaWalker** [comment]
Yes, this is a table chart. In the right side bar you have the possibility to change the visualization type of numerical values into bar charts

**Comment by ptbrowne** [comment]
I think @bprusinowski tackled this some time ago, I am closing, please re open if you see again the issue.
