### ISSUE TITLE
Inconsistent Font-Style Across Visualizations and Languages

### ISSUE THREAD

**Issue by mwannier30** [visualize-admin/visualization-tool#1784]
**Describe the bug** 
The font style (and possibly the font size) is inconsistent across different visualizations and languages. For example, in one project, the title appears bold in French, but only in the first visualization, and it is not bold in German.

**To Reproduce** Steps to reproduce the behavior:

1. Go to [visualize.admin.ch](https://visualize.admin.ch/v/2DEBQ4bvfWsb?dataSource=Prod)
2. Change to french
3. See error (The first title is bold, but the second one is not, and it is not bold in German)

**Expected behavior**
The font-size and font-style should be consistent across all visualizations and languages. Titles should maintain the same formatting regardless of the language or project.

**Screenshots or video**
(easier to see by reproducing)
![Image](https://github.com/user-attachments/assets/43b5dc95-4215-41f2-812f-cc2d0d6ce0c8)
![Image](https://github.com/user-attachments/assets/3cd74a7c-19df-4981-b1b6-c8825b9ebc34)
![Image](https://github.com/user-attachments/assets/dd1aa7e9-39d1-438f-be57-1abea3028611)

**Environment (please complete the following information):**

- Visualize environment and version: PROD v4.7.4
- Browser and version: Microsoft Edge v129.0.2792.52

**Additional context**
/

**Comment by sosiology** [comment]
@mwannier30 thank you very much for reporting the bug. We will look into and let you know once it is resolved.

**Comment by sosiology** [comment]
Additional Context: I can reproduce this issue by adding a `symbol to the title - I assume this is what is formatting the text to bold. Tested on INT with: https://int.visualize.admin.ch/en/v/7maGAWlP2R2t?dataSource=Prod

See that when ' is added at the end of the title it appears bold
![Image](https://github.com/user-attachments/assets/990cdf5f-1207-4361-8062-15bcb77f7071)

See that when there are no symbols in the title, it appears as expected
![Image](https://github.com/user-attachments/assets/e78a86a8-abc0-4401-8789-16e535764d2a)

**Comment by sosiology** [comment]
@mwannier30 I am happy to inform you that the issue has been fixed on the INT environment, and will be published to PROD with the next Release. 
Here is an example of the chart on INT with the fix: https://int.visualize.admin.ch/fr/v/jbmgbP_G_OLE?dataSource=Prod

**Comment by mwannier30** [comment]
Thanks for the quick fix!
