### ISSUE TITLE
Firefox: Weird dropdown behaviour

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#179]
Firefox 83.0

- Weird dropdown behaviour. On click dropdown sometimes only opens for a few seconds and then disappears again

https://user-images.githubusercontent.com/59613691/139866560-ccbf4382-fb4a-43db-b7be-6e7490a6fc5c.mov

https://user-images.githubusercontent.com/59613691/139866589-6486afca-8e20-4530-9931-1d11f19ebc85.mov

**Comment by ptbrowne** [comment]
Mmh, maybe something is fetched and then the right panel is re-rendered which may cause the dropdown to close.

**Comment by AnninaWalker** [comment]
Tried to recreate it, but couldn't, which means it seems to work in the meantime ;-)

**Comment by sosiology** [comment]
I was able to reproduce the issue in Firefox 94.0.1 (64-bit) and 94.0.2 (64-bit)

https://user-images.githubusercontent.com/29289679/143220591-b0714d94-f8e9-464a-8551-12c8276b6b1c.mov

**Comment by sosiology** [comment]
retested with FF Version 99.0.1 (64-bit) and the inconsistent behaviour could not be reproduced.
