### ISSUE TITLE
Wrong data in table Chart

### ISSUE THREAD

**Issue by mwannier30** [visualize-admin/visualization-tool#1790]
**Describe the bug** 
When doing a table chart type, the data is not up to date and does not match the data shown with other chart types.

**To Reproduce** Steps to reproduce the behavior:

1. Go to [visualize](https://visualize.admin.ch/en/browse?dataset=https%3A%2F%2Fhealth.ld.admin.ch%2Ffsvo%2FBT_table%2F9&dataSource=Prod)
2. Start a visualization
3. Create a table chart and observe the data.
4. Create a different chart type and observe the data.
5. Compare the two and notice that they do not match.

**Expected behavior** 
I expect to have the most up-to-date data.

**Environment (please complete the following information):**

- Visualize environment and version: PROD v4.9.2
- Browser and version Microsoft edge v 129.0.2792.65

**Comment by adintegra** [comment]
Additional notes:
 
- Not all rows in the dataset are displayed ("Sheep" observations appear to be missing)
- Inconsistent display of rows when sort order is switched

https://github.com/user-attachments/assets/c7f4cc97-d455-4d16-b785-b6d03a316326

**Comment by sosiology** [comment]
Thank you for the valuable hint @mwannier30

**Comment by sosiology** [comment]
Hi @mwannier30 

The fix is ready for your review on INT (int.visualize.admin.ch). Also see the example chart here: https://int.visualize.admin.ch/v/QGCXVC05n5uQ?dataSource=Prod  

We would appreciate if you could have a look and confirm that the fix works as expected. We are planning a deployment to Production with the fix next week.

**Comment by mwannier30** [comment]
Hi @sosiology 
It looks good to me, Thanks!

**Comment by sosiology** [comment]
Thank you for the prompt feedback @mwannier30

**Comment by sosiology** [comment]
@mwannier30 the fix was deployed to production (visualize.admin.ch) today.
