### ISSUE TITLE
Link to the GitHub repo from the footer

### ISSUE THREAD

**Issue by wereHamster** [visualize-admin/visualization-tool#18]
…to make discovery of this repo a bit easier.

**Comment by loleg** [comment]
Looks like the place to that [is here](https://github.com/visualize-admin/visualization-tool/blob/master/app/components/footer.tsx). Pull requests are open :smile_cat:

**Comment by wereHamster** [comment]
I was since told that the link is on the [Legal Framework](https://visualize.admin.ch/en/legal-framework) page. I would have never looked for it there…

**Comment by loleg** [comment]
Thanks folks!
