### ISSUE TITLE
Search in Step 1 doesn't really filter out the typed in word as least for the word "Anzahl"

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#180]
If I type in the word "Anzahl" it doesn't really filter the dataset according to that: It also highlights single letters 🤷🏻‍♀️. It seems to work with other words though ;-)

https://user-images.githubusercontent.com/59613691/139867306-1085d365-6edb-48fb-a577-ee1898c19a54.mov

**Comment by herrstucki** [comment]
Also reported in #105 and #96
