### ISSUE TITLE
Automated Bug Reporting for End Users

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1802]
**Is your feature request related to a problem? Please describe.**
Allow users to automatically report bugs from visualize.admin.ch

**Describe the solution you'd like**
Integrate a "Report a Bug" button in Visualize that allows users to report an issue. When the button is clicked and email is opened and  users can enter the information based on the type of issue the are reporting. 

-  The email should go to visualize@bafu.admin.ch and support@interactivethings.com in Cc

**Describe alternatives you've considered**
1. We link this page https://github.com/visualize-admin/visualization-tool/issues/new/choose in the footer or similar. 
      - Pros: Minimal dev/design effort. 
      - Cons: There is a barrier to entry, as users will need to sign up to Github to report a bug. 
2. We implement a solution similar to https://databrowser.uis.unesco.org/ (see feedback button in bottom right hand corner). 
      - Pros: Users can submit feedback without leaving the site or logging into another place (e.g. Github) 
      - Cons: Requires third party integrations which may/may not be approved for government projects (for UIS we use Tally and Notion as a DB to collect inputs). 

**Usecases and impact**

- The feature would be beneficial for users, as they have a way to quickly and efficiently report issues they experience. 
- The feature would be valuable to the product team to gain insights on Users needs and issues they experience. 

**Additional context**
- Gitlab Issue: https://gitlab.ldbar.ch/bafu/visualize/-/issues/522

**Visual Design in Figma**
Figma Design Section: https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5850-40986&t=uybrHwBMTujLYK8N-4

[Prototype Bug Report/Feature Request from landing page](https://www.figma.com/proto/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?page-id=8%3A145669&node-id=5850-44207&node-type=frame&viewport=3407%2C-3057%2C0.17&t=OVtdhOvq4E94C1dA-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5850%3A44207&show-proto-sidebar=1)

[Prototype Bug Report/Feature Request from User Profile](https://www.figma.com/proto/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?page-id=8%3A145669&node-id=5886-38681&node-type=frame&viewport=3407%2C-3057%2C0.17&t=OVtdhOvq4E94C1dA-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5886%3A38681&show-proto-sidebar=1)

**Comment by noahonyejese** [comment]
@sosiology Just an Idea but what about creating a github issue directly via some inputs over some generic reporter github account? 

I don't know if this still needs some sort of requirements from the government. 

Never the less some design will be required depending on the approach, I will do the solution described by you solange for now. 

CC: @bprusinowski @KerstinFaye

**Comment by sosiology** [comment]
@noahonyejese thanks for the suggestion. If we can create some automation so that when the email is sent to BAFU it creates a github issue in the repo - i am very much open to that. Otherwise we will have to define an email address to use so we are also notified.

**Comment by KerstinFaye** [comment]
@noahonyejese I added the Figma Design Section above and als the User Flow starting from the landing page and the one starting from the User Profile.

**Comment by sosiology** [comment]
@noahonyejese in the english locale - the subject is missing from the email. It shows as "undefined" (see screenshot). In all other languages (DE, FR, IT) it works as expected ✅ 
![Image](https://github.com/user-attachments/assets/f25f2a44-a30b-4d6d-9ee9-58f6428c36d3)

**Comment by noahonyejese** [comment]
@KerstinFaye alright thanks a lot for the feedback

**Comment by sosiology** [comment]
@KerstinFaye @noahonyejese i created a new issue for the outstanding feedback here: https://github.com/visualize-admin/visualization-tool/issues/1891
