### ISSUE TITLE
Add Cookie Banner

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1805]
Implement the cookie banner (official Federal CI/CD) on visualize (in all languages)

### German
     
**Banner Text:** 
     Damit wir unser Webangebot optimal auf Ihre Bedürfnisse ausrichten können, verwenden wir das Analysetool Matomo. Dabei wird Ihr Verhalten auf der Website in anonymisierter Form erfasst. Es werden also keine personenbezogenen Daten übermittelt oder gespeichert. Wenn Sie damit nicht einverstanden sind, können Sie die Datenerfassung durch Matomo unterbinden und diese Website trotzdem ohne Einschränkungen nutzen.
   
 **Button Text:**
        Einverstanden
        Weiter ohne Datenerfassung

### French

**Banner Text:**
Afin de pouvoir adapter notre offre web de manière optimale à vos besoins, nous utilisons l’outil d’analyse Matomo. Ainsi, votre comportement sur le site web est enregistré anonymement. Par conséquent, aucune donnée personnelle n’est transmise ou stockée. Si vous n’êtes pas d’accord avec cela, vous pouvez arrêter la collecte de données par Matomo et continuer à utiliser ce site web sans restrictions.

 **Button Text:**
        D'accord
        Poursuivre sans collecte de données
      
### Italian
**Banner Text:**
Per poter adattare la nostra offerta web in modo ottimale alle vostre esigenze, utilizziamo lo strumento di analisi Matomo. Ciò significa, che il vostro comportamento sul sito web viene registrato in forma anonima. Di conseguenza, non vengono trasmessi o memorizzati dati personali. Se non siete d'accordo, potete interrompere la raccolta dei dati da parte di Matomo e continuare ad utilizzare questo sito web senza restrizioni.

**Button Text:**
Accetto
Continuare senza raccolta dei dati

### English
**Banner Text:** 
In order to be able to adjust our web offer optimally to your needs, we use the analysis tool Matomo. With it, your activities on the website are recorded in an anonymous form. Therefore, no personal data are transmitted or stored. If you do not agree to this, you can stop the data collection by Matomo and still use this website without restrictions. You will find further information on the page Tems and conditions.

**Button Text:**
Agree
Continue without data collection

**Comment by cype** [comment]
How will this work for embedded Visualize elements? For example, on www.dashboard.blv.admin.ch

It cannot be that the cookie banner then appears in every embedded element.

**Comment by sosiology** [comment]
Closing this issue as we strive for a solution that doesn't require a cookie banner
