### ISSUE TITLE
Newsletter Signup Button

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1808]
**Is your feature request related to a problem? Please describe.**
Add a button to the homepage to allow users to sign up for a newsletter which will inform them of new releases and changes.

**Describe the solution you'd like**
When the "sign up" button is clicked, an email window is opened with the subject "Visualize Newsletter Registration". The recipient of this email should be visualize@bafu.admin.ch.

**Describe alternatives you've considered**

**Usecases and impact**
- As a user of the website [www.visualize.admin.ch](http://www.visualize.admin.ch/), I want to be able to subscribe to a newsletter to be informed about new versions, including a link to the page with the updates.
- As an administrator, I want to have the ability to add subscribers and receive a notification for each new subscription.

**Additional context**
There is a concept in the landing page redesign for a newsletter signup. 
For now, the goal is to just open a mailto link, in future there could be a fully integrated newsletter tool and form. The client will collect and manage the registrations independently. 

Gitlab: https://gitlab.ldbar.ch/bafu/visualize/-/issues/141

Visual Design in Figma:
https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5850-44207&t=d6V59BZbW11RUbKH-4

**Comment by sosiology** [comment]
@noahonyejese here is some additional information for the Newsletter email that we could use for a first version. 

Email Subject: Visualize Newsletter Abonnieren
Email Body: Ich möchte mich für den Visualize Newsletter anmelden. Bitte fügen Sie meine E-Mail-Adresse zur Verteilerliste hinzu.

**Comment by sosiology** [comment]
@noahonyejese on TEST the subject line and body are missing https://test.visualize.admin.ch/en?dataSource=Prod, I also do not see the sign up button in the dropdown for the user login.

**Comment by noahonyejese** [comment]
Thanks @sosiology for the insights, sorry I haven't seen the subject and body for the newsletter, I'm adding them right away

**Comment by noahonyejese** [comment]
> [@noahonyejese](https://github.com/noahonyejese) on TEST the subject line and body are missing https://test.visualize.admin.ch/en?dataSource=Prod, I also do not see the sign up button in the dropdown for the user login.

Please not that was not implemented in this [PR](https://github.com/visualize-admin/visualization-tool/pull/1854) I moved it to keep the PR's less cluttered, I forgot to mention you here as well.

**Comment by KerstinFaye** [comment]
@noahonyejese Thanks for implementing all this. Only thing I realized is that if I click on my User Profile name and then click on feedback and I don't want to proceed this action and click outside the dropdown, I cant exit this action. The dropdown stays. The behaviour should allow the user to click outside the dropdown so it closes. 
https://github.com/user-attachments/assets/a6bb3b62-2918-4d6d-a4cb-a4f341ad7152

**Comment by KerstinFaye** [comment]
> [@noahonyejese](https://github.com/noahonyejese) on TEST the subject line and body are missing https://test.visualize.admin.ch/en?dataSource=Prod, I also do not see the sign up button in the dropdown for the user login.

@sosiology I was not aware that the Newsletter sign up button should also be in the dropdown of the User Profile? Did you meant this or did I misunderstood your comment? 
My understanding was only that the Bug Report and Feature request button should be there in a level under Feedback. I would also not recommend taking the Newsletter sign up button in this dropdown since this is not a crucial information that should be in this dropdown. (Cognitive overload, the actions should be reduced to the essentials)

**Comment by sosiology** [comment]
@KerstinFaye yes, i agree that **we do not need the Newsletter Signup in the Dropdown**. Sorry for the confusion here.
