### ISSUE TITLE
Time axis in published chart

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#181]
- I can't see from which year to which year the chart is filtered exactly in the published chart. Especially on mobile it looks a bit odd. I think the starting and the endpoint should always be be labeled
- 
![IMG_4537](https://user-images.githubusercontent.com/59613691/139868414-c1d5307a-b78b-49a5-a7dd-e8298e1297d8.png)

![Screenshot_2020-12-03_at_10 26 18](https://user-images.githubusercontent.com/59613691/139868423-f8235c24-b38d-4506-8c65-eab7dfd6833e.png)

**Comment by ptbrowne** [comment]
Should be possible to do with `axis.tickValues( scale.ticks( 5 ).concat( scale.domain() ) );`

**Comment by ptbrowne** [comment]
@AnninaWalker If you remember how you made this chart, could you post a link to the visualisation 🙇‍♂️ ? I tried to make it but could not find the proper dataset I think...

<img width="314" alt="image" src="https://user-images.githubusercontent.com/465582/140030072-bc28ae8c-7d1b-4007-ba3a-134e1669d8bb.png">

**Comment by AnninaWalker** [comment]
Yes, unfortunately the dataset is not available anymore ;-(
