### ISSUE TITLE
✅ "Created with visualize.admin.ch" missing from dashboards

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1813]
**Description**
The note that a chart was created with visualize.admin.ch is missing when multiple charts are published using the layout options: Tab layout, dashboard)

**Steps to Reproduce**
1. Go to: https://visualize.admin.ch/v/TVNwmsKWrtx5?dataSource=Prod
2. See that at the bottom of the chart, the hint "Erstellt mit: visualize.admin.ch" is missing 
3. Copy and Edit the Chart 
4. Select a dashboard layout (any)
5. See that in editing mode, but also in the published chart the note "Erstellt mit visualize.admin.ch" is missing. 

**Screenshots and Examples**
Tab Layout | https://visualize.admin.ch/v/TVNwmsKWrtx5?dataSource=Prod
![Image](https://github.com/user-attachments/assets/beb49b32-99c4-48d8-b822-ff065b83e4af)

Dashboard Layout | https://visualize.admin.ch/v/4yHJ0msuFuY2?dataSource=Prod 
![Image](https://github.com/user-attachments/assets/0d1ad2cd-c939-4d57-901e-d97d5a740763)

**Expected Result**
The note is shown below each chart in the tab layout, or at least once at the bottom of a dashboard. 
See example here (single chart): https://visualize.admin.ch/v/7PyLLMXyF4PW?dataSource=Prod

![Image](https://github.com/user-attachments/assets/ff5b59d5-7f89-4194-8596-a85eeed3e87d)

**Comment by noahonyejese** [comment]
@bprusinowski and @sosiology this is an issue I've worked on the past the idea was to move the "Created with" part onto the bottom when creating Dashboards with multiple Charts. (I now fixed the missing "Created with" on the single Chart). However how should it be on the Dashboard Charts with multiple Charts during Edit mode should it be for every Chart or just once like it is in published mode?

**Comment by bprusinowski** [comment]
Hi @noahonyejese, I am not sure if this is a behavior we all have in mind, but I think the labels should be there in single charts and tab layout, and in case of dashboards, we should only have one entry at the bottom and not include the labels in individual charts. @KerstinFaye maybe we have a design for this? 🤔

**Comment by sosiology** [comment]
@noahonyejese the goal is to have a solution for dashboards - where, as @bprusinowski said, it is shown in one place (not per chart). The single chart types should already have the "Created with" ....so i am not 100% sure what you fixed?

**Comment by noahonyejese** [comment]
> Hi [@noahonyejese](https://github.com/noahonyejese), I am not sure if this is a behavior we all have in mind, but I think the labels should be there in single charts and tab layout, and in case of dashboards, we should only have one entry at the bottom and not include the labels in individual charts. [@KerstinFaye](https://github.com/KerstinFaye) maybe we have a design for this? 🤔

Is this also during the preview for dashboard layout charts only at the bottom or is it there for each one

**Comment by noahonyejese** [comment]
> [@noahonyejese](https://github.com/noahonyejese) the goal is to have a solution for dashboards - where, as [@bprusinowski](https://github.com/bprusinowski) said, it is shown in one place (not per chart). The single chart types should already have the "Created with" ....so i am not 100% sure what you fixed?

No I noticed it was missing everywhere because I forgot to add a variable that I introduced to disabled it on Charts if needed. However therefore the only thing missing now is the dashboard having a link at the bottom of the page correct? If so should this be always the cased or only when published?

**Comment by noahonyejese** [comment]
Also the turnary here https://github.com/visualize-admin/visualization-tool/pull/1745/files#diff-34eba95302f579aaec7d8e6d0efc9dc2eab6b955bc8d96ea395c7273743e73ec isn't quite right we have to do 

```javascript
 state.layout.type !== "dashboard" ||
                (state.layout.type === "dashboard" &&
                  state.chartConfigs.length === 1)
```

instead of 

```javascript
                state.layout.type !== "dashboard" &&
                  state.chartConfigs.length === 1
```

To make sure that dashboards with only 1 Chart still have the Link like the other versions

**Comment by noahonyejese** [comment]
@bprusinowski it was only meant for the embed mode I made it now also for the published mode

**Comment by sosiology** [comment]
LGTM thank you @noahonyejese
