### ISSUE TITLE
Switch Button and Y-Axis Title Overlap in Interactive Chart Mode

### ISSUE THREAD

**Issue by mwannier30** [visualize-admin/visualization-tool#1818]
**Describe the bug** 
Wenn making the Chart mode (normal or 100%) interactive, the switch button and the title of the y-axis overlap.

**To Reproduce** Steps to reproduce the behavior:

1. Go to any project (e.g.: [visualize](https://visualize.admin.ch/en/browse?previous=%7B%22type%22%3A%22organization%22%2C%22iri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-lebensmittelsicherheit-und-veterinaerwesen-blv%22%2C%22topic%22%3A%22%22%7D&dataset=https%3A%2F%2Fhealth.ld.admin.ch%2Ffsvo%2FBT_entwicklung%2F13&dataSource=Prod))
2. Start a new visualisation
3. Select "Columns" or "Areas" as the chart type.
4. Add a segmentation column in the Chart options.
5. Change the Chart mode to interactive
6. Observe the overlapping elements.

**Expected behavior** 
The switch button and the y-axis title should appear one below the other without overlapping.

**Screenshots or video** 
![Image](https://github.com/user-attachments/assets/c0f56497-ad7b-4e83-8e8a-e1aeb8b30fad)

**Environment (please complete the following information):**

- Visualize environment and version: PROD v4.9.3
- Browser and version: Microsoft Edge v130.0.2849.56

**Comment by sosiology** [comment]
@noahonyejese i tested again on TEST and the label still overlaps. See here: https://test.visualize.admin.ch/en/v/KDLsGHe4GrX3?dataSource=Prod

If this is completed in a PR - please share the link for the PR or merge the PR to TEST so it can be reviewed. Thank you.

**Comment by noahonyejese** [comment]
> [@noahonyejese](https://github.com/noahonyejese) i tested again on TEST and the label still overlaps. See here: https://test.visualize.admin.ch/en/v/KDLsGHe4GrX3?dataSource=Prod
> 
> If this is completed in a PR - please share the link for the PR or merge the PR to TEST so it can be reviewed. Thank you.

@sosiology Not sure why it didn't work I already merged is this working for you --->>> https://visualization-tool-cvh4s3xls-ixt1.vercel.app/?dataSource=Prod 

- sorry for the inconvenience this may have caused

**Comment by sosiology** [comment]
LGTM, thanks!
