### ISSUE TITLE
Time axis/range broken for single point in time

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#182]
![Untitled](https://user-images.githubusercontent.com/59613691/139869252-c98f64d9-51dd-4750-8627-9fdda7fa923c.png)

**Comment by ptbrowne** [comment]
What do you think should be the expected behavior here ? It seems an acceptable edge case to me.

**Comment by AnninaWalker** [comment]
As we only have a single point in time it doesn't make sense to display the time slider at all, as you can't interact with it

**Comment by herrstucki** [comment]
What probably is more concerning is that you're able to choose a preset for the interactive filter that doesn't make any sense:

<img width="858" alt="Bildschirmfoto 2021-11-02 um 18 00 41" src="https://user-images.githubusercontent.com/70969/139911401-a0d33bbc-8038-4300-8c8e-e9bb91712a74.png">

**Comment by AnninaWalker** [comment]
@herrstucki Absolutely, I thought that the problem is problem already in the Editor itself.

**Comment by bprusinowski** [comment]
I can take care of this! I guess the slider in both editor and interactive filters just should not appear when there is a single point in time?

**Comment by AnninaWalker** [comment]
Yes exactly! Thank you!

**Comment by herrstucki** [comment]
Also, the preset slider should be limited to the range that is defined in the data filters from step 2. It may be that this is already the case but if you could double-check that would be great!
