### ISSUE TITLE
Migrate GitHub Actions from v3 to v4

### ISSUE THREAD

**Issue by adintegra** [visualize-admin/visualization-tool#1820]
Artifact actions v3 will be deprecated by December 5, 2024. We currently have GitHub Actions workflows using v3 of actions/upload-artifact or actions/download-artifact. After this date using v3 of these actions will result in a workflow failure (Artifacts within their retention period will remain accessible from the UI or REST API regardless of the version used to upload).

**Comment by Rdataflow** [comment]
@adintegra you may want to automate such version upgrades using Github dependabot i.e. https://github.com/dependabot/demo/blob/main/.github/dependabot.yml

**Comment by Rdataflow** [comment]
@adintegra well done - enjoy automation 😎
