### ISSUE TITLE
Design: Request New Funtionality Button

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1827]
**Description**
Add a new button on the Visualize start page “Request new functionality” with which every user can report a functionality request. This should trigger a mail to [visualize@bafu.admin.ch](mailto:visualize@bafu.admin.ch). with the “request for a new functionality” and Cc to Interactive Things (support@interactivethings.com), who will add the request to Gitlab and github as an issue manually..

**DoD**

- [ ] the button is implemented as designed
- [ ] New button exists on the Visualize start page; the button is called “Request new functionality” or similar.
- [ ] When you press the button, a new mail opens in which you can describe the request. A contact (name, organization, telephone, e-mail) is mandatory. 
- [ ] The subject of the mail is “new functionality requested in Visualize” (this allows the inbox in the mail account to be filtered. When you press “Send”, the mail is sent to [visualize@bafu.admin.ch](mailto:visualize@bafu.admin.ch).
- [ ] The mail is also sent in visible Cc to Interactive Things, who enter the request in Gitlab as issue(s).

**Comment by KerstinFaye** [comment]
Design can be found here:
**Visual Design in Figma**
Figma Design Section: https://www.figma.com/design/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?node-id=5850-40986&t=uybrHwBMTujLYK8N-4

[Prototype Bug Report/Feature Request from landing page](https://www.figma.com/proto/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?page-id=8%3A145669&node-id=5850-44207&node-type=frame&viewport=3407%2C-3057%2C0.17&t=OVtdhOvq4E94C1dA-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5850%3A44207&show-proto-sidebar=1)

[Prototype Bug Report/Feature Request from User Profile](https://www.figma.com/proto/Hn9wvuEYLUmdJtg4KwZYUx/visualize.admin.ch---design?page-id=8%3A145669&node-id=5886-38681&node-type=frame&viewport=3407%2C-3057%2C0.17&t=OVtdhOvq4E94C1dA-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=5886%3A38681&show-proto-sidebar=1)

**Comment by sosiology** [comment]
@noahonyejese in the english locale, the subject line shows up as "undefined". In all other languages it LGTM. 
![Image](https://github.com/user-attachments/assets/a2b1f457-bc40-4d3b-a3d7-ea5bc0bf0be6)
