### ISSUE TITLE
Timeslider: Mobile – Slider disappears

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#183]
If I double click several times on the slider, the slider suddenly disappears on mobile

https://user-images.githubusercontent.com/59613691/139869528-cf91b63b-dd8e-43ff-bdc9-bed9f8ef374e.mp4

**Comment by sosiology** [comment]
Reproducable with this chart https://test.visualize.admin.ch/v/RXbybrdOfCO9
