### ISSUE TITLE
Combining Datasets: Implement Improvements (Usability Testing)

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1830]
https://gitlab.ldbar.ch/bafu/visualize/-/issues/697

List of tasks for the improvements of the merging of cubes feature: 
https://www.notion.so/interactivethings/Merging-of-cubes-Iteration-3-13530da54302802b9073f45e58169c6d?pvs=4

- [x] Dimension dropdown grouped:
![Image](https://github.com/user-attachments/assets/d523aca7-de93-436d-a08c-1d05ea9a425f)
- [x] Filter grouped per dataset:
![Image](https://github.com/user-attachments/assets/dc1d145a-e8f3-4827-9902-3049a8f86a1a)
- [x] Delete “Contains values from Cantons” and termset value from the dropdown dimensions list to reduce complexity for the user:
![Image](https://github.com/user-attachments/assets/d050a47e-14f2-43a0-9239-85a6799dbcaf)

- [x] Dataset Section on top of the sidebar and rename to Dataset: 
![Image](https://github.com/user-attachments/assets/96f16e89-63d8-4620-95c1-b6112fc614dc)

- [x] Explanation of “Concepts” Filter on the Search page: ”Concepts represent values that can be shared across different dimensions and datasets”.:
![Image](https://github.com/user-attachments/assets/8e56dc1c-1faa-4f28-b7ca-b60ce3958dc1)

- [x] Improve default settings of charts as soon as a second dataset is added. [Based on the discussion underneath](https://github.com/13530da54302802b9073f45e58169c6d?pvs=25#13530da54302803ebdc5fb1ef75f7808). 
→ If possible show dual axis as a default chart type as soon as a second dataset is selected?

@bprusinowski @sosiology I took the tasks in here.

**Comment by sosiology** [comment]
- Dimension dropdown grouped ✅ 
- Filter grouped per dataset ✅ 
- Delete “Contains values from Cantons” and termset value from the dropdown dimensions list to reduce complexity for the user ✅ 
- Dataset Section on top of the sidebar and rename to Dataset ✅ 
- Explanation of “Concepts” Filter on the Search page: ”Concepts represent values that can be shared across different dimensions and datasets” ✅

**Comment by sosiology** [comment]
@bprusinowski i noticed in the modal to select a second data set, the user cannot select draft data sets and there is no sorting (newest, most relevant etc.) - is this intentional?
cc: @KerstinFaye

**Comment by bprusinowski** [comment]
@sosiology by checking the design it looks like indeed we should have a way to sort the datasets, but the draft toggle is not there. I think we should add the sorting and align with the design?

**Comment by sosiology** [comment]
@bprusinowski yes, at minimum we should have the sorting.

**Comment by bprusinowski** [comment]
@sosiology you can check https://github.com/visualize-admin/visualization-tool/pull/1917 👍

**Comment by sosiology** [comment]
LGTM @bprusinowski thank you!
