### ISSUE TITLE
Color Palettes overlap

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#184]
- If I use the Focus Tab to navigate through the website (Keyboard Nav) I can open several colorpalettes at once
- I also can't exit the colorpalette via Enter
- 
![Screenshot_2020-11-26_at_15 27 23](https://user-images.githubusercontent.com/59613691/139870017-16b05b10-118d-4edb-a0b6-5a5ad8ff3dd5.png)

**Comment by ptbrowne** [comment]
The color picker that is shown in the screenshot uses reach, for the color-palette, we use downshift and the escape key works properly.

**Comment by AnninaWalker** [comment]
Tried to recreate this as well, but in the current version on dev I don't even manage to get into the colorpalettes via focus tab? It jumps up itnwo the url field after Sorting.


https://user-images.githubusercontent.com/59613691/140039378-021494dd-77fd-477c-b4d7-929be4f82020.mov

**Comment by sosiology** [comment]
Closing the issue as it cannot be reproduced with the new UI (sidebar on left only)
