### ISSUE TITLE
Interactive Filter Overlaps with Meta Data Details

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#1887]
When activating interactive filters (for example here the "show in %" filter) it overlaps with the Meta Data Details of the cube and is not toggleable in edit and also publish mode.

![Image](https://github.com/user-attachments/assets/057e6171-34ec-4f62-b52e-23ddc9ca66cb)
¨

https://int.visualize.admin.ch/de/v/UOtn0J4gn7kY 

**To Reproduce** Steps to reproduce the behavior:

1. Go to add a segmentation and choose "Treibhausgas" for example
2. Click on the interactive filter options for %
4. See error.

**Expected behavior** A clear and concise description of what you expected to
happen.

They should not overlap

Tested on Edge web browser

**Comment by sosiology** [comment]
Hi @tboeni 
Thank you for reporting the issue. We already have this on our radar and are tackling it in this issue: https://github.com/visualize-admin/visualization-tool/issues/1818

**Comment by sosiology** [comment]
@tboeni this is fixed on INT and ready for review
