### ISSUE TITLE
PROD : Visualize dispay Value = "0"  instead of ‘no value’.

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#1888]
When I export the Visualize csv file for following Visualization https://www.visualize.admin.ch/de/v/-u-BR-bpgybi, 
I notice that Visualize exports a Zero value for the LF1 time reference, whereas there is no value for the LFI1 period.
This is correct in Lindas.

1. Open https://www.visualize.admin.ch/de/v/-u-BR-bpgybi
2. Export csv of the Chart
3. Open SPARQL-Query
4. See error : Value 0 is not the same as "No value". It must be fixed in Visualize (for download chart AND dataset) as soon as possible.

- Visualize environment and version: PROD : v4.9.3 ([4f0db71]
- Browser and version : edge

**Comment by ortnever** [comment]
@Rdataflow : fyi

**Comment by sosiology** [comment]
Thank you for reporting the issue @ortnever we will look into it as soon as possible. 

cc: @bprusinowski @adintegra
