### ISSUE TITLE
X-Axis labels are cut off

### ISSUE THREAD

**Issue by herrstucki** [visualize-admin/visualization-tool#190]
Not sure when this happened but currently, some of the vertical x-axis labels are cut off, at least in column charts:

![image](https://user-images.githubusercontent.com/70969/139911674-6ec0991d-1f0c-4062-b7cc-d71a4000aa4a.png)

**Comment by herrstucki** [comment]
Looks like this was fixed in #172?

**Comment by bprusinowski** [comment]
Not sure, I will take a look!

**Comment by bprusinowski** [comment]
Yes, it seems that it's been fixed in #172. Does that PR look good to you @herrstucki?
