### ISSUE TITLE
v5.0.1 on INT: Area-Chart: Segmentation doesn't work as expected

### ISSUE THREAD

**Issue by cype** [visualize-admin/visualization-tool#1918]
Since v5.0.1 was deployed on INT, the area chart no longer works as expected. Although I only selected three out of five categories during segmentation, the area chart shows all five categories.

![Image](https://github.com/user-attachments/assets/455ed7fc-d39f-4b5d-824f-04a786e42541)

https://int.visualize.admin.ch/create/_dGpBaksL8sK?dataSource=Int

**Comment by cype** [comment]
https://int.visualize.admin.ch/en/browse?dataSource=Int&dataset=https%3A%2F%2Fhealth.ld.admin.ch%2Ffsvo%2FMH_%2F4

**Comment by sosiology** [comment]
@cype the issue has been resolved on the TEST environment (test.visualize.admin.ch) one the change is deployed to INT I will inform you.

**Comment by sosiology** [comment]
@cpye The fix was deployed to INT v5.0.2 today
