### ISSUE TITLE
Include git commit info in version number

### ISSUE THREAD

**Issue by herrstucki** [visualize-admin/visualization-tool#192]
To indicate that the deployed versions can differ between different environments, even if the version _number_ can be the same, we should include the git hash in the version number, and even link to the commit in this repo.

To bake it into the app, we need to update the Dockerfile to use an argument like so:

```
docker build --build-arg COMMIT=$(git rev-parse HEAD)
```

In the Dockerfile, we expose it to the app with `NEXT_PUBLIC_COMMIT`, so it gets [inlined during build](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser)

Then we can display it in the app like so:

> v3.1.1 (https://github.com/visualize-admin/visualization-tool/commit/8e64d532cdac3992d8dd927d3ca0d77805a5d20f)

**Comment by ptbrowne** [comment]
And we can link to github directly from the commit sha1 :)

**Comment by herrstucki** [comment]
@ptbrowne yes, that's what I suggested ;) The only question to me is if we should do this regardless of env (dev/int/prod) but I'd say yes, to reduce complexity

**Comment by ptbrowne** [comment]
Yes, I do not think it causes a problem right now.
