### ISSUE TITLE
Data Set Source not Consistently Showing in Left Sidebar on INT

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1924]
The data set source sometimes does not appear in the left sidebar. This issue was reported by BAFU during testing. 

https://gitlab.ldbar.ch/bafu/visualize/-/issues/697#note_17941

**Comment by sosiology** [comment]
@bprusinowski i did some tests and documented them below. 


#### Test 1
Browser: Chrome, incognito Mode
Data Set: Heavy Metal Soil Contamination (PROD)
Logged in User: No
Result: ❌
![Image](https://github.com/user-attachments/assets/371f5d68-ae03-4e44-b35f-f946a9491623)

#### Test 2
Browser: Chrome, incognito Mode
Data Set: Heavy Metal Soil Contamination (PROD)
Logged in User: Yes
Result: ❌
![Image](https://github.com/user-attachments/assets/cb28b2f6-d833-4f67-890d-d948df583629)


#### Test 3
Browser: Chrome (normal browser window)
Data Set: Heavy Metal Soil Contamination (PROD)
Logged in User: Yes
Result: ✅
![Image](https://github.com/user-attachments/assets/21fccbb3-9dd7-466c-9f52-7e6b10559524)

#### Test 4
Browser: Chrome (normal browser window) - after deleting cache and cookies
Data Set: Heavy Metal Soil Contamination (PROD)
Logged in User: No
Result: ❌
![Image](https://github.com/user-attachments/assets/a799dab0-e00e-4988-bd6d-63975c8ed068)

#### Test 5
Browser: Chrome (normal browser window) - after deleting cache and cookies
Data Set: Heavy Metal Soil Contamination (PROD)
Logged in User: Yes
Result: ❌
![Image](https://github.com/user-attachments/assets/0d49207b-359f-4837-a9ba-a261970dab49)

After clearing my cache and browsing history - i can reliably reproduce the issue.

**Comment by bprusinowski** [comment]
Thanks @sosiology 🙇‍♂ I managed to fix it in #1925 (we didn't remove one additional feature flag when making merging of cubes widely available). Should be fine now 👍

**Comment by sosiology** [comment]
Thanks @bprusinowski 
I had a look on the PR can we merge to TEST so i can double check it there, and publish to INT asap?

**Comment by bprusinowski** [comment]
@sosiology the new version should be on INT soon 👍
