### ISSUE TITLE
Check Gitlab Visualize Storage

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1926]
From Claudio Di Gallo, BAR on 29.11.2024 per email 

> We’re running low on storage on gitlab. It seems the culprit is visualize. Do you have some old tags in there? I think we’ve had this before – but last time with trifid.
>  
> Do you have vhsn-access?
>  
> [SBAR-1282: Disk space on gitlab1.sbar.cust.vshn.net](https://control.vshn.net/tickets/SBAR-1282)

**Comment by ptbrowne** [comment]
I was hoping that @bprusinowski would take the task as I am not planned in for visualize right now.

**Comment by sosiology** [comment]
Resolution (copied from reply in VSHN ticket)

> I've set up a policy that should help keep space usage low (and manually removed some older containers, as the action will run on a two-week basis).
