### ISSUE TITLE
✓ Development: Image Download Single Chart

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#1928]
Implement the image download for a single chart 

Design Task: #1927

**Comment by bprusinowski** [comment]
@sosiology @KerstinFaye the feature can be reviewed here: https://github.com/visualize-admin/visualization-tool/pull/1931

**Comment by sosiology** [comment]
@bprusinowski Thanks for this! While testing on TEST i noticed that if the chart image is downloaded from the published page  "Created with visualize.admin.ch" appears 2x on the exported image. If the image is downloaded from the editor mode, it only shows up 1x.

**Examples**
1. Bar Chart: https://test.visualize.admin.ch/en/v/Md9KZ3H4AipE?dataSource=Prod
![Image](https://github.com/user-attachments/assets/8bc21e26-4ac0-4037-b7dc-de2d0b4a2a8d)

2. Bar Chart with Standard Error: https://test.visualize.admin.ch/v/KDrVsrnKFJlR?dataSource=Prod
![Image](https://github.com/user-attachments/assets/2db3d4d1-4165-4c62-aee3-f310d672e50c)

**Comment by bprusinowski** [comment]
@sosiology thanks for noticing this, I'll take a look! A small note: to make a screenshot we actually have to "see" the chart rendered on a page, which would make it a bit tricky to enable the button here, as we'd need to open the chart preview, make a screenshot and close it (more or less 😅).

**Comment by sosiology** [comment]
@bprusinowski thanks for the explanation - makes sense that the chart needs to be visible to download the image. Due to the technical complexity - I would not include the chat image download in the user profile for now - but maybe something to think about in future.

**Comment by KerstinFaye** [comment]
Tested on Safari, Brave, Chrome. Looks good. 
Only Bug I discovered: Dual Axis charts: the label color does not change according to the background color in the download. 
https://int.visualize.admin.ch/en/v/wVfk4PSYRdYk?dataSource=Prod

![Image](https://github.com/user-attachments/assets/712ec818-7e06-45f5-b25c-fff1db33703b)
Published view: 
<img width="424" alt="Image" src="https://github.com/user-attachments/assets/e85c325d-c8f2-4de6-bd0f-7a272b06735a" />
Image download: 
![Image](https://github.com/user-attachments/assets/14aa251e-4380-4b05-a043-9d2391aef7e6)

**Comment by bprusinowski** [comment]
Good catch @KerstinFaye, thank you for testing 🙇‍♂ I'll take a look 👍
