### ISSUE TITLE
Display bug in the cube list and pop-up column in test.visualize.admin.ch

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#193]
There is twice the same cube "State accounts - Domain" in the cube list, version 1 and 4.
I think I have to change the title because of a typing error.
![image](https://user-images.githubusercontent.com/35593772/140325684-c40c8735-a1d0-4bfd-9785-00162f1aa820.png)

Second problem, but certainly linked to the first one.
When I select alternatively one of the 2 versions of this cube, Visualize add a new column "Amount" with the same values each time, except for the last column where the values seem the same in another order.

![image](https://user-images.githubusercontent.com/35593772/140326381-2d23cd5c-d202-48fe-9ed2-5bb49514b981.png)

**Comment by herrstucki** [comment]
From looking at the metadata on https://cube-viewer.zazuko.com/?endpointUrl=https%3A%2F%2Flindas.admin.ch%2Fquery&user=&password=&sourceGraph=&cube=https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2FStateAccounts_Domain%2F1%2F

1. The cube with version 1 was not unlisted properly (has no `schema:expires`)
2. I'm not sure why the "Amount" column shows up that many times but at least in the v1 cube it's actually present more than once

**Comment by PDumasBAR** [comment]
OK, I will inform Zazuko there is a potential problem in the cube-creator.
Now I only see one version of this cube in visualize. You can close this issue.
