### ISSUE TITLE
Color Palettes for Ordinal Categories

### ISSUE THREAD

**Issue by jstcki** [visualize-admin/visualization-tool#217]
As described in https://github.com/visualize-admin/visualization-tool/issues/101#issuecomment-973001152, we should offer sequential color palettes for ordinal dimensions.

Not sure if the selection has to be strictly limited to ordinal dimensions, as they may also work for dimensions that are sorted manually.

For reference, d3 offers these single- and multi-hue palettes out of the box: https://observablehq.com/@d3/color-schemes?collection=@d3/d3-scale-chromatic

**Comment by sosiology** [comment]
Closing this as it is being tackled in https://github.com/visualize-admin/visualization-tool/issues/1722
