### ISSUE TITLE
Example on hompage flickering

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#220]
The example on the homepage "evolution of state account by office" flickers, see attachment
Browser: Chrome and Firefox

https://user-images.githubusercontent.com/29289679/143218683-d9ac8072-58e7-411a-940a-1710325987d5.mov

**Comment by ptbrowne** [comment]
I can reproduce

**Comment by ptbrowne** [comment]
@bprusinowski It seems to have been introduced by the imputation feature (I bisected to see the first failing commits and it is the merge of the imputation feature : cbdf3dd31702f336d18e33200e2f1365565db39e). Would you mind taking a look ?

**Comment by bprusinowski** [comment]
Yes, I will take a look, thanks for investigating!
