### ISSUE TITLE
Unexpected error when selecting scatter plot

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#236]
In this [sample](https://test.visualize.admin.ch/en/create/PPFAMVpweC3x) on test, selecting a scatter plot in the second step produces the error "Unexpected error".

Maybe the problem is in the dataset that contains a lot of missing values.

**Comment by sosiology** [comment]
Thank you for your note @PDumasBAR. Could you please specify which data set you are referring to so we can further investigate the issue? (The shared link leads to the data set overview in Visualize). Thank you in advance for your input.

**Comment by PDumasBAR** [comment]
Sorry, it was Staperfenquête. 
The link https://test.visualize.admin.ch/en/create/PPFAMVpweC3x initially pointed to a chart. But now to an "Unexpected error" :(

I've made a new version of this cube. Very different. I think that's the reason why the link doesn't work anymore.
I will try again this issue and tell you if it's ok or not.
