### ISSUE TITLE
Tooltip hidden behind the interface

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#239]
I'm working on the cube Stapferenquête where I've found repetition of the same measures.
I don't know if there is an error in the cube definition or in visualize.
But I can't read some values in the tooltip because it is hidden behind the interface :

![image](https://user-images.githubusercontent.com/35593772/144048252-1c795925-6ba6-4bdd-ab71-3e55479d5034.png)

**Comment by ptbrowne** [comment]
Ah it seems to happen if there is only one group of bars in the chart.

**Comment by ptbrowne** [comment]
Closed in favor of https://github.com/visualize-admin/visualization-tool/issues/315
