### ISSUE TITLE
Browse datasets by topic - Adding a descriptive text

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#247]
In order to give the user a bit more guidance, of what he can do, on the dataset page, a descriptive text should be added below the title.

<img width="1946" alt="Screenshot 2021-12-02 at 13 43 14" src="https://user-images.githubusercontent.com/59613691/144424379-52b19880-8386-49e6-8aaa-dac09174530b.png">

**Comment by ortnever** [comment]
I agree with this proposition.
