### ISSUE TITLE
Browse datasets by topics – Increase visibility of "Back to Datasets" Button

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#248]
Back to Dataset-Button should be more prominent

<img width="1949" alt="Screenshot 2021-12-02 at 13 50 25" src="https://user-images.githubusercontent.com/59613691/144425367-63432825-52c6-432e-bb0a-5c66e469b541.png">

**Comment by ptbrowne** [comment]
Are you sure about this ? I find it weird to have two primary buttons there, maybe the background-color of the back button could be a bit muted ?

**Comment by AnninaWalker** [comment]
![1 2 2_l_layout](https://user-images.githubusercontent.com/59613691/150148999-4e9702a2-b287-4e1e-bac7-aec716b76e0e.png)

Yes your right, we have to introduce secondary buttons. We didn't have them so far in the design components

**Comment by AnninaWalker** [comment]
Change button to grey #757575 according to CI Guidelines.
![1 2 2_l_layout](https://user-images.githubusercontent.com/59613691/150992324-7cd56593-94a9-403a-a085-541d919fae9f.png)
