### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#253]
- [x] Create pristine charts that will be screenshotted (create them on production) **bafu**. ⚠️ Those charts should be based on datacubes that will not change (otherwise the screenshots will fail because the data has changed)
- [x] Implement screenshotting of those charts through puppeteer fake browser
- [x] Upload to argos and add argos checks to GitHub PR checks
~~- [ ] List searches that should return results  **bafu**~~
~~- [ ] Implement jest/puppeteer e2e tests for those searches and add them to CI tests~~
- [x] Cleanup old testing strategy

**Comment by ptbrowne** [comment]
Search results testing is done via unit testing.

**Comment by sosiology** [comment]
Closing the issue as all tasks are marked as completed
