### ISSUE TITLE
Maps: Symbol Layer - Color Concept

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#274]
@bprusinowski  In the initial concept it was forseen, that in the Symbol Layer the Symbols are either colored in one color according to the selected Dimension or that an additional Dimension can be added allowing to color the Symbols either according to numerical or categorical data.
It looks like this hasn’t been implemented or not sure if I just can’t test it as the data is not available . To be discussed if this makes sense or not.

In any case there the Original Description and Link to the Design Concept.

Original Description:
The visualization of the symbol map basically takes place on the "Symbol Layer".

In a first step, a numerical dimension can be selected in the dropdown in the right side column, which will be "mapped" to the map accordingly. If no further dimension is selected for the coloring, the symbols receive a basic color, which can be adjusted as desired.

However, the publisher also has the option to select a second dimension (numeric or categorical) for the coloring. If a corresponding 2nd dimension is selected, the symbols will be colored analogously.  
If numerical data was selected as 2nd dimension, the publisher has the possibility to select a corresponding palette from a predefined color palette and can determine whether it should be displayed continuously or stepwise, as well as its interpolation (Linear, Quartiles, Quintiles, Natural etc). 
If categorical data has been selected as the 2nd dimension, these are made available as filters, as in the other chart types, and can be colored individually.

Link to Design in Notion

https://www.notion.so/interactivethings/Step-3-Symbol-Layer-8d210d78f6724d5599b528a352da7cea

<img width="1659" alt="Screenshot 2022-01-24 at 16 25 15" src="https://user-images.githubusercontent.com/59613691/150811940-c06e2333-57de-4823-be22-589cd090a238.png">

**Comment by bprusinowski** [comment]
I am not convinced that it makes sense to map both measures to one bubble (size & color). One case where it makes sense to me is for categorical dimensions mapped as colors; but I think it would be quite hard to make sense of 2 numerical variables at once.

What do you think @AnninaWalker @ptbrowne?

**Comment by ptbrowne** [comment]
I agree. The second usecase with categorical values mapped as color makes sense to me also.

**Comment by bprusinowski** [comment]
Closed by #778.
