### ISSUE TITLE
Maps: Area Layer - Design of Color Selection

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#275]
@bprusinowski Please adapt the design of the Color Selection according to the Design Mockups.

- First the user can select if the Color Palette should be Continuous or in Steps. 
- Then he selects the type of Interpolation. The selection should be in a dropdown instead of checkboxes. 
- Colors should be displayed as Color Palettes and not in text (oranges, purples etc.

Current implementation:
<img width="1652" alt="Screenshot 2022-01-24 at 16 32 57" src="https://user-images.githubusercontent.com/59613691/150813853-b1cb6591-e130-4ab9-a102-450cc77f6ae0.png">

Design Screens:
![3 1 3_l_map_chart-maker_step-3](https://user-images.githubusercontent.com/59613691/150813968-33c917f6-ad7e-4e4e-a45f-4fd263becb61.png)![3 1 2_l_map_chart-maker_step-3](https://user-images.githubusercontent.com/59613691/150813963-2b8f81ea-6cf8-4eaa-8e98-b26b3daa6569.png)
t-maker_step-3.png…]()
![3 1 4_l_map_chart-maker_step-3](https://user-images.githubusercontent.com/59613691/150813970-3bcfac55-f724-4a42-9e7a-b7a52afca344.png)
![3 1 5_l_map_chart-maker_step-3](https://user-images.githubusercontent.com/59613691/150813972-06dfc9b7-5bf5-42a6-996f-516e643d2395.png)

**Comment by ptbrowne** [comment]
I wonder if we should not add a bit of help to the user here, for example description text under continuous and divergent.

> use divergent color scales when there is a value of importance around which the data are to be compared

Found this in https://webcache.googleusercontent.com/search?q=cache:u639rZK-5kIJ:https://everydayanalytics.ca/2017/03/when-to-use-sequential-and-diverging-palettes.html+&cd=2&hl=fr&ct=clnk&gl=ch and it makes sense to me

It is a bit complicated though, maybe we could find a better way to express it, maybe visually in a tooltip. At least I think it would be helpful.

**Comment by bprusinowski** [comment]
Yeah, honestly I think we should decide if it's worth to include diverging color scales in the current format at all. They make sense with a clear "midpoint", such as 0 for a dimension with negative and positive values or some other measure (average, median?).

Maybe we could enable them if we detect that the dimension indeed has both negative and positive values / allow the user to select the midpoint on their own?

**Comment by ptbrowne** [comment]
Yep, since we do not a have a midpoint diverging color scales do not make much sense to me right now. It would be good to ask Zazuko if there is a plan to add this kind of information in the dimension metadata.

**Comment by ptbrowne** [comment]
I like the "midpoint" term, but we have to keep in mind that in more generic form, there could be several "step" values, and in those cases we should only present diverging scales with (number of colors) = (step values + 1).

**Comment by AnninaWalker** [comment]
@bprusinowski Just noticed that the legend gets a bit scrumbled up ;-) See the screenshot for the color settings.

<img width="1580" alt="Screenshot 2022-02-01 at 10 16 16" src="https://user-images.githubusercontent.com/59613691/151941844-06017272-adf3-471b-a1b7-acefba33585f.png">
