### ISSUE TITLE
Maps: Base Layer - Concept

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#276]
To be defined:
Concept for the Base Layer.

Initially the idea was that the overall mapping of the data is set in the Base Layer (if the data should be mapped to cantons, municipalities, forest zones etc. and applies to both: the Area and the Symbol Layer.

In the current implementation the color mapping can be done individually directly for the Area and for the Symbol Layer. Which allows to mix if the choropleth should be mapped to cantons and the symbols should be mapped to municipalities.
This leaves the current base layer a bit empty.

A few things we need to think of:

- Currently the Base Layer looks inactive per default. But two checkboxes are actually selected. So Base Layer should be activated but we need to think of the wording. Should there be instead of Add.. Relief, lakes. Or should we only write Base Layer?
- If a Choropleth is added then the Relief of the Map is still selected and sometimes still slightly visible as it overlaps a bit with the shapes (see screenshot). Should the Relief be deactivated as soon as the Choropleth is applied?
- Is it only possible to show the relief in the background if we have only a Symbol Layer activated, or could outlines of the Swiss Map be drawn? (see 2nd screenshot)

Overlappin
<img width="1661" alt="Screenshot 2022-01-24 at 16 41 06" src="https://user-images.githubusercontent.com/59613691/150816484-92d4eb17-902b-4106-b606-2c9bf8e3cd88.png">
g of Relief

Symbol Map with only Outlines in the Background instead of Relief

![6 1 3_l_map-chart-maker_step-5](https://user-images.githubusercontent.com/59613691/150816684-ad04a63a-896e-4c69-a0a0-ddf3f48dabfd.png)

**Comment by AnninaWalker** [comment]
Here an example what we once did for hackdays to draw just the outlines and not having a relief in the background. Would be nice if the user could choose between the two: https://swiss-maps.interactivethings.io

**Comment by bprusinowski** [comment]
I like the idea! I also see a question if a relief should even be an option? I don't really like that it flickers a lot when zooming / unzooming and I don't see it in design mockups :)

**Comment by AnninaWalker** [comment]
I think the relief was a request by the client, so I guess it would be great if the user could choose between both options. But maybe we can clarify that again with the client
