### ISSUE TITLE
Maps: Hierarchy Levels

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#280]
This is just a mental note;-) To be clarified when according data is available.

Double check how hierarchy levels are dealt with within the maps and if we can adapt the design we use for the cascading filters in the left side panel? What options do we have exactly in the hierarchy level here? Do they belong in the right side panel or left side panel? (To be defined, once data is available)
<img width="1649" alt="Screenshot 2022-01-24 at 17 14 48" src="https://user-images.githubusercontent.com/59613691/150821004-b1662c25-7ef5-4b0a-a31f-d0fbcf293f3a.png">

**Comment by bprusinowski** [comment]
`MultiFilter` has been implemented here, hierarchy level is not there anymore.
