### ISSUE TITLE
Maps: Covid Dataset - No shapes

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#285]
In the draft Covid Dataset: Covid19 Vaccinated Persons when I change the Measure in the Area layer to "Rolling 7 day average" I'm not sure what is happening exactly. It doesn't draw any shapes. Not sure if this is a bug, or if there is no data? 

<img width="1639" alt="Screenshot 2022-01-25 at 09 36 39" src="https://user-images.githubusercontent.com/59613691/150941592-e9f072db-9392-49cf-8758-6d37ec50691e.png">

**Comment by bprusinowski** [comment]
It means there is no data, I have just checked this case. I think we should handle this in some way to be sure - maybe "no data" displayed on hover, below a Canton name (and no legend, as it does not make any sense right now)?

**Comment by AnninaWalker** [comment]
Or maybe it shouldn't be available at all in the dropdown menu to avoid no result?

**Comment by bprusinowski** [comment]
I think it would be tricky to implement right now, I think it would need to be based on Patrick's work related to getting filters basing on other filters. Still there could be e.g. one shape with data and others without - so still there would be "gray" shapes without data.

**Comment by AnninaWalker** [comment]
Ok, that makes sense. We don't need to implement anything right now.

**Comment by ptbrowne** [comment]
Let's check this on Monday @bprusinowski :)

**Comment by ptbrowne** [comment]
Right now I have <img width="317" alt="image" src="https://user-images.githubusercontent.com/465582/155116791-e3d27c5f-6b4b-48e1-9389-6de787fa2f5e.png">

It seems like we should only put a No value inside the tooltip ?

I am testing with : https://test.visualize.admin.ch/fr/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FCOVID19VaccPersons_v2%2F2%2F?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22covid%22%7D (please provide a link to the browsing page of the dataset when there are two datasets with the same name :))

**Comment by bprusinowski** [comment]
I think it would be enough, @AnninaWalker what do you think?

**Comment by AnninaWalker** [comment]
I agree. Just put a "-" then we don't need to translate ;-)
