### ISSUE TITLE
Link to unversioned entry of Cube in Visualize does not work anymore.

### ISSUE THREAD

**Issue by l00mi** [visualize-admin/visualization-tool#288]
**Describe the bug**
At some point in time we had the agreement that we can link to a unversioned cube like here https://opendata.swiss/de/dataset/staatsrechnungen-funktion

e.g. https://visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2FStateAccounts_Function

This worked at some point, currently it seems to needs the additiona `/3/` in the link above.

**To Reproduce**
Click 2nd link above.

**Environment (please complete the following information):**
 - Visualize environment and version: PROD

**Comment by l00mi** [comment]
Any updates on this. That is a bug in production. The opendata.swiss entries do currently not work.

**Comment by ptbrowne** [comment]
I will work on this this afternoon. Can you provide more context on the opendata.swiss entries ? I thought it was only a bug between cube view and visualisation.admin ?

**Comment by ptbrowne** [comment]
OK I saw the link on opendata.swiss, I did not know at all that there was this contract between opendata.swiss and visualize.admin, thanks for the report.

**Comment by Rdataflow** [comment]
@ptbrowne could you investigate:
- https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ftest_ordinal_507 doesn't work 
- https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ftest_ordinal_507%2F5 OTOH does.

Expected would be a similar behaviour like like https://visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2FStateAccounts_Function where URL is forwarded to the versioned cube, right?

**Comment by Rdataflow** [comment]
@ptbrowne could you find the reason alreday? vero is also concerned by this issue...

cc @ortnever

**Comment by Rdataflow** [comment]
here the case for vero https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd000501

**Comment by Rdataflow** [comment]
@ptbrowne LGTM perfect 👍
