### ISSUE TITLE
Maps: Loader needed?

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#290]
Sometimes, when changing filters, it might take some time in order to load the new shapes (see video) I was wondering if we should add a loader in order for the user to see, that the filter is about to get applied. What do you think @bprusinowski ?

https://user-images.githubusercontent.com/59613691/150950222-800d9d28-a95c-4f0d-b909-2b350062679e.mov

**Comment by bprusinowski** [comment]
Cascading filters introduced a small loader next to the filters title

![filters loader](https://user-images.githubusercontent.com/52032047/155108095-9ff8a2e2-081d-4d15-97f8-cd6b74d1505e.jpg)

I think this solves this issue @AnninaWalker? Or would you like to also have another kind of an indication?

**Comment by bprusinowski** [comment]
Cool, I am closing the issue then :)
