### ISSUE TITLE
Remove Test Banner and Icons in the background on the landing page

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#295]
- Remove the red banner and the little symbols on the home page. (Do not remove the red banner for drafts).
(source: Email from Véronique on 26.01.2022) 
- Replace the "no data" message when the filter combination does not give any results with a message making clear that the user has to select another Filter Combination. But I think this will be solved anyway (or in most of cases?) with the new functionality on filter selection; the message should not be "no data", but rather "for this filter no data available" or similar:
(source: Email from Véronique on 26.01.2022 + Email from Sabine on 26.01.2022)

**Comment by sosiology** [comment]
![image002](https://user-images.githubusercontent.com/29289679/151182772-e7524bfc-a031-4b4d-b6f1-961c58fa5c6f.jpg)
![image004](https://user-images.githubusercontent.com/29289679/151182769-9184c48a-bfc6-4f4c-a7b9-78d2fe49e233.jpg)

**Comment by bprusinowski** [comment]
@sosiology I am not really sure how should we change the "No data" message, as the information on selecting other filters is already there just below a title?

Should it be:
title: "No data available for current filters"
description: "Select another combination of filters"?

I think that in general it should be solved in most cases by cascading filters (@ptbrowne correct me if I'm wrong :)).

**Comment by ptbrowne** [comment]
I think your proposition is good @bprusinowski , "Please try with another combination of filters".

I think in most cases it would be solved yes, but still I think improving the title/description just a bit like you did is a good step forward.
