### ISSUE TITLE
Ordinal Dimensions: Status are alphabetically ordered, and not according to their schema:position

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#298]
**Describe the bug**
I opened the Red List dataset and created this visualization: https://test.visualize.admin.ch/fr/v/Xs3DEBS67IGw But the status are alphabetically ordered, and not according to their schema:position. Or do I have a mistake in the data ?

**To Reproduce**
1. Go to '. https://test.visualize.admin.ch/fr/v/Xs3DEBS67IGw'
The name of the dataset in visualize is: "Listes Rouges (from INT) tst"

For information, here is the "ORDERING" for the status (second column):  
CODE_ID;Order;Description_DE;Description_FR  
EX;7;weltweit ausgestorben;éteint à l'échelle mondiale  
RE;6;ausgestorben in der Schweiz;éteint en Suisse  
CR;5;vom Aussterben bedroht;au bord de l’extinction  
EN;4;stark gefährdet;en danger;fortemente minacciato  
VU;3;verletztlich;vulnérable;vulnerabile;vulnerable  
NT;2;potenziell gefährdet;potentiellement menacé  
LC;1;nicht gefährdet;non menacé;non minacciato  
DD;0;ungenügende Datengrundlage;données insuffisantes

**Expected behavior**
The ordering should be according to the schema:position above and not alphabetical

**Screenshots**
![image](https://user-images.githubusercontent.com/29289679/151345093-6c902f9c-347a-47c4-a821-56dff82b747f.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST

**Additional context**
https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/317

**Comment by AnninaWalker** [comment]
@sosiology I assume thats because the order is selected here:
![Screenshot 2022-01-27 at 12 28 33](https://user-images.githubusercontent.com/59613691/151350522-a86b89c7-6699-4b2d-b1b4-204e4e0b88b3.png)

**Comment by ptbrowne** [comment]
I've forced the sorting to consider the position attribute if the dimension is nominal. I did not see your previous comment @AnninaWalker , I guess the most obvious thing here so that the user can either sort by name or by position in case of nominal dimension, would be to add a new option to this select "Position", and have it automatically chosen for Nominal dimensions. Does it make sense to you ?

**Comment by AnninaWalker** [comment]
Yes I thinks that makes total sense ;-)

**Comment by ptbrowne** [comment]
In fact, the ordinal dimensions do not have the Sorting options enabled as they already have defined order.
