### ISSUE TITLE
Search left panels counts do not consider the search text field

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#310]
**Describe the bug**

When searching for something, the counts and list of datasets in the left bar does not change.

**To Reproduce**

Go to browsing datasets
See the counts on the left bar
Search something
The counts do not change

**Expected behavior**

The counts should reflect the number of results considering the search

**Comment by AnninaWalker** [comment]
@ptbrowne It still doesn't change the count on the left.

**Comment by AnninaWalker** [comment]
@ptbrowne Good to go from my side

**Comment by MichelaBurzio** [comment]
Tested on Safari, Chrome, and Edge! All good
