### ISSUE TITLE
Sorting for nominal elements i.e. cantons or regions

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#312]
**Is your feature request related to a problem? Please describe.**
While ordering works for ordinal dimensions it doesn't for nominal dimensions i.e. 
*Cantons*
1. ZH
2. BE
...

*Production regions*
1. Jura
2. Plateau
...

**Describe the solution you'd like**
Have a way to order nominal dimensions by *default order*

@l00mi your opinion on which concepts to use for @ptbrowne ? you mentioned you prefer schema:identifier for nominal cases...

**Comment by l00mi** [comment]
I propose to allow the end-user to select out of specific set of attached predicates on the concept for a dimension, e.g.:

schema:name -> Beschriftung / étiquette / Label
schema:identifier -> Identifkation / identifient / Identifier
schema:alternateName -> Abkürzung / abréviation / Abbreviation
... ?

and/or manually order by e.g. dragging and dropping the legend labels in a specific order.

**Comment by ptbrowne** [comment]
>  Have a way to order nominal dimensions by default order

If there is a default order, isn't it an ordinal dimension ?

Anyway, we could have the schema:position retrieved also for nominal dimensions values and display "Position" it in the sorting options. Is there a way on the dimension to know if there is a schema:position available on the values ?
More generally, is there a way to annotate the dimension with the possible ordering methods ?

I think the schema:identifier is too much of an technical thing to be connected to order, don't you think ?

**Comment by l00mi** [comment]
> If there is a default order, isn't it an ordinal dimension ?

One is the order of the concept itself, like small, medium, big. Where the other is a pure visual order which is customary, but does not say anything about the order of the actual concept. A simple way to understand the difference:
* Ordinal -> schema:position, there is no opinion about the order.
* Nominal -> different use cases can have different ideas (is Zürich before Bern on a graphic.)

@bergos can we query with the query library which predicates are on concepts easily?
Currently I think we should have a minimal basic set.. like propose above.

I think its quite natural to say the order is by either the Label, or the Identifier, no?

**Comment by ptbrowne** [comment]
Thanks for the explanation @l00mi, I understand better. Yes, order by id or label seems natural.

**Comment by ptbrowne** [comment]
Currently, for a shared dimensions like the cantons, is the schema.org/identifier used to store the id of the canton ?

**Comment by l00mi** [comment]
@ptbrowne yes exactly, another one which I would consider is the schema.org/alternateName which are the Abbreviations of the things. With the cantons "BE", "ZH", "FR" ...

These predicates will be reused for the same use case. Be aware that you might also have multiple http://schema.org/identifier .. e.g. https://register.ld.admin.ch/zefix/company/1198554 has one directly attached literal, but then multiple other identifiers which are using the https://schema.org/PropertyValue construct. For a first step I would ignore these, in a next step we might need to add these to the list of possible "sortings".

**Comment by l00mi** [comment]
- [ ] Document the predicates to sort with the "labels" for the application to https://github.com/zazuko/cube-creator/wiki/LINDAS-Specifics
- [ ] Implement the feature to be picked up by Visualize
- [ ] Add Documentation for the End-User how the feature can be used.

**Comment by Rdataflow** [comment]
where to implement 
1. prio: default sorting order based on schema:identifier
  - for selection - i.e.
![image](https://user-images.githubusercontent.com/26090254/162704551-1b559efb-cc3e-457a-b6de-7addd7c66808.png)
  - for filtering - i.e.
![image](https://user-images.githubusercontent.com/26090254/162708348-724d92d6-81f3-43fe-b133-92f35c57d19d.png)
  - for sorted table view - i.e. 
![image](https://user-images.githubusercontent.com/26090254/162709718-4b8cc983-6105-478f-8cdf-221cf5b731b3.png)
  - for bar charts order - i.e.
![image](https://user-images.githubusercontent.com/26090254/162705873-1a9b7fd4-3d2e-462e-9ab7-30575d7dfcca.png) and 
![image](https://user-images.githubusercontent.com/26090254/162707865-90b6b2a1-091f-44d9-9d8f-3b7ab13c34aa.png)
and 
![image](https://user-images.githubusercontent.com/26090254/162708038-1a7e5eed-eeb8-40f3-8f04-735b9dbd91f6.png)

... and of course keep this on the fly in sync with whatever chart ordering applied:
  - hints order (mouse over)
![image](https://user-images.githubusercontent.com/26090254/162707349-f2142ead-bb7e-46e3-ba3f-f18e2e1c0417.png)
  - legend order
![image](https://user-images.githubusercontent.com/26090254/162708548-0b01b44a-67dd-4e0e-aae6-603428d6b220.png)

2. prio: whereever you already implemente user choice:
  - let the user choose order by identifier (new default), name (already implemented), altname (if provided)
    - for sorted table view
    - for bar charts order
    nb: more inspiration for icons explaining sort order 
![image](https://user-images.githubusercontent.com/26090254/162713595-53167353-4356-4c70-8220-4807c29fd9c3.png)
![image](https://user-images.githubusercontent.com/26090254/162713664-b8821fb7-4dc7-4949-8a3b-f95dd9956bf5.png)
as above but 1..9

**Comment by l00mi** [comment]
@Rdataflow Just to clarify, the "Produktionsregion" will become "Switzerland" in the final cubes and are not part of this sorting anymore as they will be organized hierarchically. For the rest of the concepts, the remarks are valid.

**Comment by Rdataflow** [comment]
@ptbrowne when can you tackle this issue?

**Comment by ptbrowne** [comment]
Closed by #821
