### ISSUE TITLE
selecting lfi data cubes jumps back to home page

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#313]
**Describe the bug**
Selecting one of the lfi datasets jumps back to https://test.visualize.admin.ch/

**To Reproduce**
1. Go to https://test.visualize.admin.ch/browse?includeDrafts=true&order=SCORE&search=lfi
2. Click on a LFI dataset

**Expected behavior**
Jump to visualize this chose dataset

**Environment (please complete the following information):**
Visualize environment and version: TEST v3.2.7 (ba4b7c5)

**Comment by ptbrowne** [comment]
Sorry for this issue, this is fixed now.
