### ISSUE TITLE
Color segmentation: search field

### ISSUE THREAD

**Issue by MichelaBurzio** [visualize-admin/visualization-tool#317]
**Describe the bug**
There is a mismatch between design and development. A search bar is needed to quickly search for an item within a long list of items.

**To Reproduce**
1. Create a visualization starting from 'Bathing water quality' dataset
2. Select bar chart
3. Click Next button
4. Click on 'Color' segmentation and select 'Bathing site'
5. See the missing search field on the filter section

![Group 2](https://user-images.githubusercontent.com/98882778/152195217-2afa5f60-c167-4587-b6a0-a553792ceab6.png)

**Environment (please complete the following information):**
 - Visualize environment and version: INT & TEST v3.2.7
 - Browser and version Chrome 97

**Additional context**
As a reference, Sketch file is available [here](https://sketch.com/s/d49152a2-8991-4868-8e8d-9ea63266c55c)
Look at _4 Navigation-Layout Optimization_ Layout _2.3.3_l_layout_
![2 3 3_l_layout](https://user-images.githubusercontent.com/98882778/152195903-c693ad97-f4d6-410c-8cd0-67bd47cc1833.png)

**Comment by ptbrowne** [comment]
@MichelaBurzio This has not been developed yet, so I changed the label from bug to enhancement. Thanks for the report though.
