### ISSUE TITLE
Several versions of the same cube in the result list

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#318]
test.visualize shows several versions of the cubes MFM-U Luftdaten Jahresmittel NO2, NO and MFM-U Luftdaten Jahresmittel Partikelanzahl.

**To Reproduce**
1. open test.visualize, navigation in German
2. search MFM-U, include draft
3. Different versions of the cubes appear.

![image](https://user-images.githubusercontent.com/79834090/152298837-d60386cb-e54f-4521-99f2-0ba1742aee3b.png)

**Environment (please complete the following information):**
 - Visualize environment : v3.2.7 [ce02c26]
 - Browser and version : Edge 97.0.1072.55 (64 bits)

**Comment by ptbrowne** [comment]
Thanks for the report Veronique. You're right that for the MFM-U datasets, there are duplicates presented in the search results:

https://environment.ld.admin.ch/foen/UBD010701/1
https://environment.ld.admin.ch/foen/UBD010701/2

are both there for the "MFM-U Luftdaten Jahresmittel NO2 NO" dataset for example.

On the front-end side, we rely on the old versions to have an "expire" property. It is not there for `https://environment.ld.admin.ch/foen/UBD010701/1` which prevents us from properly filter it out of the search results. I will see with @l00mi why some cubes do not have the `expires` property.

**Comment by l00mi** [comment]
@tpluscode can you please have a look?

**Comment by tpluscode** [comment]
Found the problem in publishing pipeline. Fix is on the way

**Comment by tpluscode** [comment]
We deployed a fix and I filled in the missing cube metadata in the affected cubes.

**Comment by ptbrowne** [comment]
Thanks @tpluscode for the update, looks good on my end, closing.
