### ISSUE TITLE
Wrong initial filter selection

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#327]
**Description**
For at least one dataset, there is a "No data available for this current filter selection" displayed during a chart type selection step; however when going to a next step, the data is correctly fetched.

**To Reproduce**
1. Go to https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd56_energieperspektiven2050%2F4?previous=%7B%22includeDrafts%22%3Afalse%7D.
2. Click on "Create visualization".
3. Wait for the error to appear.
4. Click "Next".
5. See the data being loaded.

**Expected Behavior**
The data should be loaded in a first step in way it does in the second step.

**Environment**
 - Visualize: TEST v3.2.7 (d1d94f5)
 - Browser: Safari 14.1.1 (16611.2.7.1.4)

**Comment by ptbrowne** [comment]
I think that would be a nice improvement to include in the sprint. It is related to #328

**Comment by sosiology** [comment]
@ptbrowne  the data is shown as expected during chart type selection but selecting the pie chart or scatter plot leads to an application error
![image](https://user-images.githubusercontent.com/29289679/154524909-909c733e-47ef-4fc1-8609-e3a668837d36.png)

**Comment by AnninaWalker** [comment]
Yes, same issue here!

**Comment by ptbrowne** [comment]
Should be OK now :)

**Comment by AnninaWalker** [comment]
👍

**Comment by MichelaBurzio** [comment]
👍 ok from me
