### ISSUE TITLE
Cascading Filter does not work with "Swiss PRTR (Test03)"

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#328]
@ptbrowne : il s'agit du bug communiqué par Email le 28.01.

Filtre en cascade ne fonctionne pas pour PRTR (Test03)"

1.	Rechercher PRTR via test.visualize, y compris Draft
2.	Ouvrir « Registre suisse des rejets et transferts de polluants Swiss PRTR (Test03) »
3.	Choisir Bar chart (pas de données, pour l’ordre des filtres affichés par défaut)
4.	Choisir Etablissement comme segmentation (couleurs) et Modifier l’ordre des filtres comme printscreen ci-dessous
5.	Un graphique s’affiche par défaut
6.	Modifier le polluant et choisir "Chloride"
7.	Pas de données, alors qu’il en existe si on choisit comme activité « nicht aufgeschlüsselt ».

Expected behavior
la valeur "nicht aufgeschlüsselt" devrait être sélectionnée automatiquement dans le filtre "Activité principale" et des données seraient ainsi disponibles

![image](https://user-images.githubusercontent.com/79834090/152493676-aff3c7d5-a6be-4828-8490-769c96494ab3.png)

![image](https://user-images.githubusercontent.com/79834090/152494180-4e11e23d-f33c-4a7a-b8e8-d1458dfce65b.png)

![image](https://user-images.githubusercontent.com/79834090/152494333-45487882-4085-40ed-a4a2-e10859f33d34.png)

**Comment by ptbrowne** [comment]
Thanks for the report Véronique, I was not able to work on it before. I can reproduce correctly. I think I can improve the filter selection, and will work on this today. At the same time I think we can see that the current cascading filters do improve the existing product and that the functional bug that you describe would have been even harder to solve with the current production filters. In this sense, I think this bug should not block a production deploy as it its criticity is not high.

- The state before was worse
- The user can work around the problem

**Comment by sosiology** [comment]
- A chart is now shown when the Pollutant is changed to Chloride. 
- The main activity shown is "Abfall- und Abwasserbewirtschaftung" (as oppose to "nicht aufgeschlüsselt" when the pollutant is changed but no error is shown.
