### ISSUE TITLE
General Layout improvements

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#334]
Implement the Layout improvements that have been approved by the client: See also on [GitLab](https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/319)

- [x] Remove the stepper (Process-Navigation) and add Call to actions. See invision doc [here](https://projects.invisionapp.com/share/9811YXLK6VU5#/screens/463668701)
- [x] Add process bar on top (Turn the red bar CI element into a process bar. See Invision doc [here](https://projects.invisionapp.com/share/9811YXLK6VU5#/screens/463668701)
- [x] Turn Back and Next Button into text links and put them on the outer left and right See Invision doc [[here](https://projects.invisionapp.com/share/9811YXLK6VU5#/screens/463668701)]
- [x] Keep “Publish” Button as Button but change the label to "Publish this visualization". See invision doc [here](https://projects.invisionapp.com/share/9811YXLK6VU5#/screens/463668853)
- [x] Change color  of "Back to the data list" to grey #757575. See Invision doc [here](https://projects.invisionapp.com/share/9811YXLK6VU5#/screens/463668700)
- [x] Published chart: Change Share and Embed buttons from links to buttons. See invision doc [here](https://projects.invisionapp.com/share/9811YXLK6VU5#/screens/463668703) 
 - [x] Change Color of “Create new visualisation” and "Copy and edit this visualization" to grey #757575. 
 - [x] Change label of Copy visualization to "Copy and edit this visualization

**Comment by MichelaBurzio** [comment]
I tested on Safari, Chrome, and Edge! all good
