### ISSUE TITLE
Design refinements

### ISSUE THREAD

**Issue by MichelaBurzio** [visualize-admin/visualization-tool#336]
Implement the design refinements that have been approved by the team after Michela's review: See also on [Notion](https://www.notion.so/interactivethings/Design-refinements-2ce86dd2ba564012865bc695a4b7e8ef)

### Search

- [x] Definition of default items order: remove relevance sorting option from the main page. Order the items by the newest and allow the user to switch to title sorting. See [invision](https://invis.io/9811YXLK6VU5#/463997811_03-12) doc.
- [x] Definition of default items ordered **during the searching**: order the items by relevance and allow the user to switch to title and newest sorting. See [invision](https://invis.io/9811YXLK6VU5#/463998535_03-13) doc. 

### Data download

- [x] Data download button: add a button to download the full dataset in the table view. See [invision](https://invis.io/9811YXLK6VU5#/464001535_03-14) doc.
- [x] Data download tooltip: add a tooltip to download both datasets in chart creation flow. See [invision](https://invis.io/9811YXLK6VU5#/464001538_03-15) doc.
- [x] Data download tooltip: add more download options in the published step. See [invision](https://invis.io/9811YXLK6VU5#/464001560_03-16) doc. 

### Legend

- [x] Interaction to collapse a long legend: add **Show all** and **Show less** buttons on the legend. Change legend font color to #757575. See invision [Show all](https://invis.io/9811YXLK6VU5#/463996614_03-10) and [Show less](https://invis.io/9811YXLK6VU5#/463996644_03-11) docs.

### Date filter

- [x] Date picker + Slider: Add a date picker before the slider to select the date range. See [invision](https://invis.io/9811YXLK6VU5#/464002323_03-17) doc.

The date picker component is reported here [Issue 357](https://github.com/visualize-admin/visualization-tool/issues/357)

**Comment by AnninaWalker** [comment]
Quick question: We will tackle these refinements in this sprint, right? We haven't discussed those yesterday. @sosiology @ptbrowne @bprusinowski
