### ISSUE TITLE
Provide tool-tips to show the `schema:description` on selected filters and/or legends in the graphics

### ISSUE THREAD

**Issue by l00mi** [visualize-admin/visualization-tool#341]
**Is your feature request related to a problem? Please describe.**

Data providers do make sure that the dimensions are nicely described with `schema:description`. For now visualize does not make use anywhere about this context information. 

**Describe the solution you'd like**

A simple first step would be to provide a tooltip with this information is available on the dimension:

![Screenshot 2022-02-10 at 12 55 01](https://user-images.githubusercontent.com/502518/153404449-ece08fe1-d61f-41ae-aeff-166cd4e18544.png)

Or on the datapoints itself:

![Screenshot 2022-02-10 at 13 00 22](https://user-images.githubusercontent.com/502518/153404813-6cd373c6-d55b-4d4e-8ed1-b0e8735c1b38.png)

**Additional context**

There are not much information ready yet in `schema:description`, I guess mostly because it has no impact on visualize.admin.ch. We should early encourage the data providers to make use of this. Because the data in context is the most important feature of our overall solution.

**Comment by bequrios** [comment]
This really would be a very important feature. I just tried to convince a work colleauge to use Linked Data exactly because of the further info you can get for the dimensions just to discover that they are not available in visualize.admin.ch

**Comment by AnninaWalker** [comment]
@bequrios We are planning to tackle this very soon. It is on our priority list.

**Comment by bprusinowski** [comment]
Completed in #716. We also now have a concept for handling this in a more scalable form – a metadata panel (#801).
