### ISSUE TITLE
Maps: Choose which cantons can be displayed

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#342]
**Is your feature request related to a problem? **
Input from Michael. Just by chance I discovered one missing feature which I would expect based on the other types of visualzation:
For the Areas Layer and also Symbols Layer (e.g. Canton) I would expect that we can choose which of the cantons are shown. As it is possible in all other visualization types. This will be very usefull once we have more datasets on municipality level, combined with the zoom feature.

**Describe the solution you'd like**
Being able to choose which cantons should be displayed by adding a filter section (as we have it in all other charts) to the Area and the Symbol Layer.

**Comment by AnninaWalker** [comment]
@bprusinowski Let's discuss as soon as you are back what this would mean to the map. Would we just highlight the selected cantons in the map and have all other cantons greyed out or could we even hide the unselected cantons?

**Comment by AnninaWalker** [comment]
I don't see any filters on test:
https://test.visualize.admin.ch/en/v/jJzFiZoMCADv

**Comment by bprusinowski** [comment]
They should be available on test now, maybe the change was still being deployed – just checked using Bathing water quality dataset

**Comment by bprusinowski** [comment]
For Covid19 or LFI datasets, the filters take some time to load, but this is also the case when selecting color in e.g. bar chart - maybe we'll have to investigate this @ptbrowne? But once they load, it should work (also tested this on Covid19 dataset)

**Comment by ptbrowne** [comment]
It also worked for me for the covid dataset

<img width="758" alt="image" src="https://user-images.githubusercontent.com/465582/154533819-bac187b3-6750-4690-af52-f06c58b4c976.png">

Yep Bartosz, it also took a long time I will investigate why tomorrow.

**Comment by ptbrowne** [comment]
Filters should normally load much faster.
