### ISSUE TITLE
strange duplication of elements observed in map creation

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#345]
@ptbrowne 
**Describe the bug**
Elements in data are oddly duplicated (tripple). Thus filters show duplicate options and the creation process offers duplicate filters.

**To Reproduce**
1. Go to https://test.visualize.admin.ch/v/nQaGJqqGV4hT
2. Click on Filters +
3. See error

**Expected behavior**
Non duplicate filters as previously
According to the cube viewer there are no dups
![image](https://user-images.githubusercontent.com/26090254/154018741-7f215eed-94c8-47fe-bef3-c4c1e6315d83.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/26090254/154017791-9e1320e3-c6d0-4234-a939-732e0de250f7.png)
![image](https://user-images.githubusercontent.com/26090254/154017526-3cc83123-3982-48e7-96d2-fe51c88f09c2.png)
![image](https://user-images.githubusercontent.com/26090254/154017553-dd48bf4c-b018-443f-a037-580b8f01ffba.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.3.0 ([7b9e175](https://github.com/visualize-admin/visualization-tool/commit/7b9e175cfbcd931ded3cba8c9524fa43bb2ef32b))

**Comment by bprusinowski** [comment]
Hi @Rdataflow, this is not related to the maps, duplicated columns are already visible on the chart preview page and in other chart types. It seems that these columns are present in the cube creator (see http://cube-viewer.zazuko.com/?cube=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-19-None-None%2Fcube%2F1&endpointUrl=https%3A%2F%2Fint.lindas.admin.ch%2Fquery&user=&password=&sourceGraph=). Maybe @l00mi could help there? I would start investigation with the cube creator.

**Comment by l00mi** [comment]
@bprusinowski this cubes are not create by the cube-creator. That is why they might have some details different. 

https://s.zazuko.com/zjdXP on the "shapes" of the cube everything is duplicated. As the WSL was doing updates recently, I have the feeling that they might have forgot to delete the old triples before publishing the new once. Which would have this effect, as the "shapes" are added by blank-nodes. 

@Rdataflow you would need to ask the to properly publish again.

**Comment by Rdataflow** [comment]
@bprusinowski of course it's not only the maps. it everywhere faulty...
we should not confuse TEST with INT. I observerd the data correctly on TEST
1. https://s.zazuko.com/M6Kr9
2. http://cube-viewer.zazuko.com/?cube=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-19-None-None%2Fcube%2F1&endpointUrl=https%3A%2F%2Ftest.lindas.admin.ch%2Fquery&user=&password=&sourceGraph= then add those four filters and you get 1 remaining entry... nothing duplicate
 
![image](https://user-images.githubusercontent.com/26090254/154077149-8ff1a467-a8ad-4a0c-864d-b810887c2921.png)

@bprusinowski let's discuss tomorrow in case ...

**Comment by Rdataflow** [comment]
@sandrobischof can you verify the datasets on LINDAS INT?
https://s.zazuko.com/zjdXP on the "shapes" of the cube everything is duplicated. As the WSL was doing updates recently, I have the feeling that they might have forgot to delete the old triples before publishing the new once. Which would have this effect, as the "shapes" are added by blank-nodes.

**Comment by IsabelMeraner** [comment]
@Rdataflow 

I just cleared our graph on INT/TEST and uploaded the cubes again. The duplicated values in the shapes should be gone. (sorry, we were indeed doing some uploads for testing purposes, which explains the redundant triples...)

**Comment by Rdataflow** [comment]
@IsabelMeraner thanks a lot. It works now fine again 👍

**Comment by AnninaWalker** [comment]
If I try to click the link above or even select that dataset manually and try to visualize a map I get an unexpected error @bprusinowski 

![Screenshot 2022-02-17 at 17 31 13](https://user-images.githubusercontent.com/59613691/154526597-f67c671c-9c06-452b-927a-03ea5e092cc1.png)

Go to https://test.visualize.admin.ch/v/nQaGJqqGV4hT


![Screenshot 2022-02-17 at 17 30 57](https://user-images.githubusercontent.com/59613691/154526656-7e62930d-47e1-4464-89b8-60f930f28fe9.png)
https://test.visualize.admin.ch/create/xEC-7QcRLLWJ

**Comment by bprusinowski** [comment]
@AnninaWalker thanks for raising this, we already have a fix there #364 - it should be merged and fixed on test soon :)

**Comment by AnninaWalker** [comment]
If I click on the link now: https://test.visualize.admin.ch/v/nQaGJqqGV4hT the map is loaded but I still see the duplicates.
Also if I try to click on copy and edit this visualization it jumps to the dataset selection

**Comment by AnninaWalker** [comment]
LGTM! 👍
