### ISSUE TITLE
Standard errors support 1 (column, grouped, tooltip, checkbox)

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#353]
The RDF cube schema defines related dimensions concept. The first related dimension type is the standard error. 

- [x] Add "related" field to each dimensions / measures with the information from meta/dimensionRelation
- [x] Draw error whiskers if the standard error related dimension is available
- [x] Support percentage unit
- [x] Simple column chart
- [x] Grouped column chart
- [x] Ability to activate / deactivate via checkbox (default would be checked)

EDIT: Add testing preview link : https://test.visualize.admin.ch/en/create/new?from=8sxAJrDh0tjd

**Comment by AnninaWalker** [comment]
The link above doesn't work. Where can I preview?

**Comment by AnninaWalker** [comment]
The standard error itself looks good to me, but the filters in the right side panel are not loaded. Not sure if this has anything to do with each other or if this is another bug.
![Screenshot 2022-02-17 at 17 53 00](https://user-images.githubusercontent.com/59613691/154530843-af586902-5fbc-47bb-ac66-6d13adde1af5.png)

**Comment by Rdataflow** [comment]
@ptbrowne cc @AnninaWalker what about 
- [ ] stacked bar chart

**Comment by ptbrowne** [comment]
We have mockups for this, I added it to the list in the description.

**Comment by ptbrowne** [comment]
I am creating another issue for this @AnninaWalker, it's not the same thing, it's a perf issue when loading the filters.

https://github.com/visualize-admin/visualization-tool/issues/374

**Comment by ptbrowne** [comment]
Fixed in #352 #356 #366, stacked chart, line and scatterplot will done in a future PR.

**Comment by AnninaWalker** [comment]
LGTM!
