### ISSUE TITLE
Weird behaviour when using filters in the right panel

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#355]
**Describe the bug**
Something weird is happening when trying to use "Select none" in filtering options in the right panel. A lot of data is showing on the chart (probably with some duplicates) and options are being "re-selected", so it's not actually possible to select none options. Also, checkboxes are not being "checked" when trying to select a single value.

**To Reproduce**
1. Load Bathing water quality dataset.
2. Select a bar chart.
3. Add coloring by Parameter.
4. Click on "Select none" down below in the Filter panel.
5. Click on "E.coli".

**Expected behavior**
I think it should be possible to select none and not display anything; selecting particular, single options should also work.

**Screenshots**

In the below screenshot, I firstly clicked on "Select none" (then checkboxes were re-selected) and then on "E.coli" – both checkboxes were de-selected, but the data filtered by "Enterokokken". It also seems that the data gets duplicated (see tooltip).

<img width="1920" alt="Screenshot 2022-02-16 at 13 12 44" src="https://user-images.githubusercontent.com/52032047/154262312-0fbd60c5-ad2a-4ead-979b-838030b16c4c.png">

**Environment (please complete the following information):**
 - Visualize environment and version: INT v3.3.0
 - Browser and version: Safari 14.1.1 (16611.2.7.1.4)

**Comment by ptbrowne** [comment]
Thanks @bprusinowski I've also noticed something weird, I am assigning myself as I know more this part of the app. I will look at it tomorrow.

**Comment by AnninaWalker** [comment]
@ptbrowne Probably related to this issue, I just discovered, when switching to the table chart type, that in the Column Bathing sites, the Filters are missing. In the Parameter section they are available.
<img width="1596" alt="Screenshot 2022-02-17 at 12 06 54" src="https://user-images.githubusercontent.com/59613691/154469058-6ffd8e10-5556-4d8e-81b0-2584ff8e3638.png">
<img width="1601" alt="Screenshot 2022-02-17 at 12 07 12" src="https://user-images.githubusercontent.com/59613691/154469075-b571132d-90d3-4d44-806b-98956c4778d5.png">

**Comment by ptbrowne** [comment]
Thanks for the issue, it was actually not the same (this is related to the fact that bathing site are geo dimensions now, and previously geo dimensions could not be filtered on the right). I fixed it in #359 .

**Comment by AnninaWalker** [comment]
Perfect! Just saw that it works now!

**Comment by AnninaWalker** [comment]
Looks good to me @ptbrowne
