### ISSUE TITLE
Date picker component

### ISSUE THREAD

**Issue by MichelaBurzio** [visualize-admin/visualization-tool#357]
**Date picker**
To facilitate the UX in selecting dates, the development of a new calendar component is necessary. 

Please look at the [notion document](https://www.notion.so/interactivethings/Calendar-component-cd1dfd1c5ec54d56976cb79f4480aa55) to read all specifications and expected behavior. 

![5 1 3_layout](https://user-images.githubusercontent.com/98882778/154309287-f1754a89-e930-434e-bfef-ffd524f92806.png)

**Comment by bprusinowski** [comment]
@sosiology as we improved the date picker in the current sprint, I wonder if we could close this issue?

**Comment by sosiology** [comment]
@bprusinowski lets close it for now. It will come up again if it is an issue :)
