### ISSUE TITLE
Remove (i) Icon that appears when editing / creating map visualizations

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#360]
**Describe the bug**
When creating visualizations with the chart type: maps,  an unexpected (i) icon appears in the bottom right-hand corner below the zoom toggles.

**To Reproduce**
1. Go to test.visualize.admin.ch
2. Select "Bathing Water Quality Dataset"
3. Select Chart Type: Map
4. While editing the map an unexpected (i) icon appears in the bottom right-hand corner below the zoom toggles
![Screenshot 2022-02-17 at 10 44 56](https://user-images.githubusercontent.com/29289679/154457342-78299f56-a367-45fe-86a2-14b9f77942c7.png)

**Expected behavior**
The (i) should be removed if no additional information is provided to the user. Alternatively, "Swisstopo" should be shown, analog the published chart. See "Additional Context" below.

**Links**
Example of a published chart: https://test.visualize.admin.ch/en/v/VWCtv10OBxBz

**Environment (please complete the following information):**
 - Visualize environment and version: Test v3.3.0
 - Chrome

**Additional context**
On the published chart the (i) is not there, but rather "Swisstopo" is shown - which I believe is correct as they are the source of the information / data. However, I find the black arrow to be confusing. Maybe we can remove it?
![Screenshot 2022-02-17 at 11 24 16](https://user-images.githubusercontent.com/29289679/154457306-192ee9ed-9121-4530-a353-499bd02dc62e.png)

**Comment by AnninaWalker** [comment]
I still see the weird black arrow on top of the swisstopo logo

**Comment by bprusinowski** [comment]
I am just waiting for the pipelines go finish 😅 It will be available on TEST in ~ 15 mins.

**Comment by AnninaWalker** [comment]
No everything disappeared, the arrow and the ©swisstopo. I don't know if the swisstopo copywright needs to be shown? If not it is ok for me as it is now

**Comment by bprusinowski** [comment]
It was disabled temporarily, we have #369 to deal with this properly. It turned out to be challenging to make it display correctly, without this weird black arrow on top and with actual interactions (so you could click on swisstopo – it's actually a link – and hover over the info icon when on mobile).
