### ISSUE TITLE
error: map cannot be displayed

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#363]
@ptbrowne 
**Describe the bug**
Unexpected error
An unexpected error occurred while displaying this chart.

**To Reproduce**
1. Go to https://test.visualize.admin.ch/v/I2WxBXeQt2JY

**Expected behavior**
display map

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.3.0 ([a3dcdaf](https://github.com/visualize-admin/visualization-tool/commit/a3dcdafab218e9bdee34ae3d7d3b7babb0e2e9ea))

**Comment by AnninaWalker** [comment]
Should this work now on test? It doesn't on my side yet

**Comment by sosiology** [comment]
Same here. I just clicked the link above and got the unexpected error. If I "Copy and edit" the visualization I also get an error
![image](https://user-images.githubusercontent.com/29289679/154528657-34959440-7474-4365-bab6-024a0e2a7a46.png)

**Comment by t0b3** [comment]
@bprusinowski true doesn't work on TEST. Can you reopen?
What could be the reason?

**Comment by t0b3** [comment]
@bprusinowski works now on TEST - well done :+1:

**Comment by bprusinowski** [comment]
Thanks! :)

**Comment by AnninaWalker** [comment]
Yes it works now on my side 👍

**Comment by sosiology** [comment]
Works on Test 👍 
Dataset not available on INT
