### ISSUE TITLE
Selecting Pie Chart leads to application error

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#365]
**Describe the bug**
When the chart type "Pie Chart" is selected there is an application error. The error can be reproduced with the following data sets
- Palmer Penguins
- Trafic Noise Pollution
- Peaks Bundesratsgeschäfte

The data set "Bathing Water Quality" seems to work

**To Reproduce**
1. Go to 'test.visualize.admin.ch'
2. Select the data set `Trafic Noise Pollution" 
3. Select "Pie Chart"
4. Application error is shown

**Expected behavior**
The user should be able to continue through the steps to create a visualization

**Screenshots**
![image](https://user-images.githubusercontent.com/29289679/154499755-99f3cce0-8d49-41bb-af0a-24b168ef4540.png)
![image](https://user-images.githubusercontent.com/29289679/154499988-26e46435-f0a1-4190-90be-5b1a7f5f672d.png)

**Environment (please complete the following information):**
 - Visualize environment and version: Test v3.3.0 [a3dcdaf]
 - Browser and version Chrome

**Additional context**

**Comment by ptbrowne** [comment]
Fixed in [6175627](https://github.com/visualize-admin/visualization-tool/commit/6175627075f34fae4942275fed32408556f15f20)

**Comment by AnninaWalker** [comment]
👍

**Comment by sosiology** [comment]
LGTM, thanks!
