### ISSUE TITLE
Timeout for preview observations for Energypespektiven 2050 or LFI dataset

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#368]
~~Can we adapt the size of the card to the content?~~

~~With the following dataset, the dataset is not really visible as it has a lot of text information.~~

No rows are available in the preview table.

https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd56_energieperspektiven2050%2F4?previous=%7B%22includeDrafts%22%3Afalse%7D.

![Screenshot 2022-02-17 at 17 22 11](https://user-images.githubusercontent.com/59613691/154525041-fb706ddf-f40e-4917-9b59-6c8b6c7cc416.png)

**Comment by AnninaWalker** [comment]
Ah no, there seems to be a bug @ptbrowne 

![Screenshot 2022-02-17 at 17 29 40](https://user-images.githubusercontent.com/59613691/154526210-f8658b63-5974-43f3-8858-8fea912ec178.png)

**Comment by ptbrowne** [comment]
For large datasets the query to get the preview rows can take a long time. When it timeouts, no data is available, so no rows are shown. I have edited the title of the issue for clarity.

**Comment by ptbrowne** [comment]
It seems to work now, I am closing, please re-open if you experience the issue.
