### ISSUE TITLE
Show attribution on map

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#369]
We should find a way to add attribution on the map. Right now it is disabled because we have not yet found the correct way to do it.

> Terms of use: the map combines different data sets with different terms of use. The map and the geoservice that provides it may be used in accordance with the [General Terms of Use and Operating Conditions of the Federal Spatial Data Infrastructure FSDI](http://www.geo.admin.ch/terms-of-use). In the case of digital or analog representations and publications by the administrative units of the Federal Administration, the following source reference **must be provided in all cases**: (with appropriate links) [© swisstopo](https://www.swisstopo.ch/),[© MapTiler](https://www.maptiler.com/copyright/) [© OpenStreetMap contributors](https://www.openstreetmap.org/copyright)

https://www.geo.admin.ch/en/geo-services/geo-services/portrayal-services-web-mapping/vector_tiles_service.html

I think here the problem is that the attribution control is not displayed properly. I think we are lacking CSS classes for attribution elements like `.mapboxgl-ctrl mapboxgl-ctrl-attrib .mapboxgl-compact` as I see that in the above documentation, the "i" is displayed properly (and on hover it shows swisstopo). I think we may have to copy some CSS classes into our global CSS.

_Originally posted by @ptbrowne in https://github.com/visualize-admin/visualization-tool/pull/361#discussion_r808971804_

**Comment by bprusinowski** [comment]
I think we can close it, we handled this by adding a separate element and placing it on top of the map.

**Comment by sosiology** [comment]
tested on TEST with the bathing water data set and it looks good to me! 
Now on hover, the information is shown behind the (i) as expected, and on the publish chart the information is shown (without hover).
