### ISSUE TITLE
Interactive Filters do not work on the home page

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#373]
**Describe the bug**
The interactive Filters (Time axis and legend) do not seem to work on the homepage example. The other filter (selection of office) works.

**To Reproduce**
1. Go to test.visualize.com
2. Scroll down to the second example on the homepage
3. De-Select the legend filter for expenditure

**Expected behavior**
When the filter for expenditure is not selected, the area should not show up on the visualization

**Screenshots**
https://user-images.githubusercontent.com/29289679/154649775-81ee3e33-8792-42a3-85bc-b16f838371f4.mov

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.3.0 (68a646c)
 - Browser and version: Chrome 98.0.4758.102, Safari 15.1, Firefox 97.0.1

**Additional context**

**Comment by MichelaBurzio** [comment]
👍
