### ISSUE TITLE
Visualisation layer under labels / lakes

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#380]
We have disabled labels on the map as they were under the viz layer. We should find a way to insert the viz layer just under the viz layer, see https://deck.gl/docs/api-reference/mapbox/overview#inserting-a-2d-deck-layer-before-an-existing-mapbox-layer.

- Labels over viz layer
- Lakes over viz layer

This could be done via different layer styles.

**Comment by sosiology** [comment]
Notes from Weekly Call (06.04.2022)
- The shapes are stacked and you cannot see everything (e.g. in Tessin the shapes are over the lakes, whereas int he West of CH it is ok) - this is due to the lake layer being under the shapes.

**Comment by ptbrowne** [comment]
Let's also check https://github.com/visualize-admin/visualization-tool/issues/479

**Comment by ptbrowne** [comment]
Fixed by #514
