### ISSUE TITLE
Tooltip not in Viewport

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#381]
**Describe the bug**
Tooltip not in viewport/not next to line in chart (pending screen size)

**To Reproduce**
1. Go to https://int.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fculture.ld.admin.ch%2Fsfa%2FStateAccounts_Category%2F5%2F?previous=%7B%22includeDrafts%22%3Afalse%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22peaks%22%7D
2. Select Area chart
3. Change `Category`from Allgemeine Verwaltung to Ertrag der Liegenschaften und Kaptialien
4. See error: Tooltips for the years from ca. 1991 go beyond the view port. 

**Expected behavior**
The tooltips should be shown in the viewport / close to the chart so the user has a visual reference and read the values.

**Screenshots**
![image](https://user-images.githubusercontent.com/29289679/154705226-a37c9675-e2e1-463d-8d6a-9cd98bac066a.png)
![image](https://user-images.githubusercontent.com/29289679/154705419-de5ad9ac-f38a-40fd-99de-5b3215e301dc.png)

**Environment (please complete the following information):**
 - Visualize environment and version: INT 3.4
 - Browser and version: Edge + Firefox

**Additional context**

**Comment by ptbrowne** [comment]
The "no filter" case is patological here, hence the "wood saw" pattern that you see. When #385 is removed this would be fixed I think.

**Comment by sosiology** [comment]
Cannot be reproduced with the link above - will close the issue.
