### ISSUE TITLE
Mobile UI alinements 

### ISSUE THREAD

**Issue by MichelaBurzio** [visualize-admin/visualization-tool#382]
**Describe the bug**
On the mobile device, the share and embed buttons are too close together. Spread them 16 px apart. 
The link [Created with visualize.admin.ch](https://int.visualize.admin.ch/en/v/Fz1D2p8CtLlj) should be on one line if possible.

**To Reproduce**
1. Go to [link](https://int.visualize.admin.ch/en/v/Fz1D2p8CtLlj ) on mobile

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/98882778/154706626-c5017eb4-060a-4764-9187-36ea90f94b58.png)

**Comment by bprusinowski** [comment]
@MichelaBurzio I wonder if the gap should be 16px; we are using 8px in this case, the same spacing as between "Create New Visualization" and "Copy and edit this visualization". Maybe we should be consistent and also use 8px?

**Comment by MichelaBurzio** [comment]
Perfect! It is a good idea. Let's use 8 px ;) Thanks

**Comment by AnninaWalker** [comment]
@bprusinowski Would it also be possible to put the Created with visualize.admin.ch on a new line as suggested above? The rest looks good to me

**Comment by bprusinowski** [comment]
@AnninaWalker but only when the text overflows, right? Or should it be below in all cases?

**Comment by AnninaWalker** [comment]
No, only when the text overflows. 👍
