### ISSUE TITLE
Filter Option appears but cannot be selected

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#383]
**Describe the bug**
On the map the filter option for Standard error appears when the user clicks on "add filter" but it cannot be selected

**To Reproduce**
1. Go to https://test.visualize.admin.ch/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-20-None-None%2Fcube%2F1?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22LFI1%22%7D)
2. Click on 'Create Visualization'
3. Select map chart type
4. on the left side bar click "add filter"
5. Standard error appears as an option but cannot be added

**Expected behavior**
A filter that cannot be added should not appear for selection

**Screenshots**
![image](https://user-images.githubusercontent.com/29289679/154709116-18d2beff-f370-40b4-b186-fa481538cfdb.png)

https://user-images.githubusercontent.com/29289679/154709621-82398168-c38c-4d94-9670-da7a4a2214e8.mov

**Environment (please complete the following information):**
 - Visualize environment and version: v3.4.0 (831c5d2) TEST
 - Browser and version Firefox

**Additional context**
Not sure if this is a standard error issue or a general issue with the filters.

**Comment by ptbrowne** [comment]
Here I think this is a problem with the data as the dimension containing standard error is not marked as a measure dimension. If it was marked it could be removed from the possible filter dimension. Am I correct @l00mi ?

**Comment by Rdataflow** [comment]
@ptbrowne hmm, **standardError** is an *auxiliary* dimension, not *measure*, neither *key* cc @l00mi

**Comment by l00mi** [comment]
Yes that is a good point. That is underspecified, in general I think you are right and that could be a solution @ptbrowne. But I am not sure what are the effects if we create define it as measureDimension, it will also show as a possible Axis then, no?

So I think the solution might be that we introduce a "filterDimension" which is the only one which is shown in the "optional Filter", and all other dimensions are simply ignored. WDY?

**Comment by Rdataflow** [comment]
from a generic perspective filtering on arbitrary dimensions (basically any dimensions) keeps the approach simple, doesn't it? once we begin to add more logic (bool filterDim) this adds complexity...

in this very case there filtering by standardError overall doesn't make much sense, though there are be some edge cases it would be helpful to filter out values with standardError > x%

@ptbrowne so it definitely won't hurt to enable the filter on this dimension, i.e. like cube viewer
cc @l00mi

**Comment by ptbrowne** [comment]
The thing here is that if it is a measure, you should be able to filter it with an interval slider to filter against min / max. This is not supported yet by visualize so for the time being this dimension should be removed as it does not make sense to filter against a single value of the standard error column.

**Comment by Rdataflow** [comment]
@ptbrowne basically every dimension with 
`qudt:scaleType qudt:IntervalScale`
or 
`qudt:scaleType qudt:RatioScale`
would fit this exeception, as the UI is not ready to handle such cases, right?

@l00mi agree on the concept?
