### ISSUE TITLE
Dataset upload error on TEST + temporary URL

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#386]
**Describe the bug**
After choosing  a dataset in the search, the next page displays the basic information and the "start a visualization" button.  
But the data never shows up - see "loading data" in the printscreen.

This might not happen for all datasets, but does happen for:
- Heavy Metal Soil Contamination
- Traffic noise pollution
- Listes rouges (dernier relevé)

Then, when moving to the chart selection:
- all charts seem to work and display something
- except the Table chart -> same problem

**To Reproduce**
1. Go to 'https://test.visualize.admin.ch/de'
or https://visualize-ad-testingv3--dl6d2r.herokuapp.com/en
2. Choose a dataset:
- Heavy Metal Soil Contamination
- Traffic noise pollution
- Listes rouges (dernier relevé)

**Screenshots**
![image](https://user-images.githubusercontent.com/6167669/154911536-78f44b26-dcb8-4c5f-946c-b807e79da16e.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.4.1 + https://visualize-ad-testingv3--dl6d2r.herokuapp.com/en
 - Browser and version: Firefox 97.0.1

**Additional context**

**Comment by ptbrowne** [comment]
Thanks @FabianCretton , it seems like an upstream issue with the database, we had a timeout this morning.

**Comment by ptbrowne** [comment]
I am closing right now since I checked all the examples that you gave and could see data.
