### ISSUE TITLE
Table doesn't load for LFI dataset

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#388]
**Describe the bug**
Table view doesn't load for LFI data cube but gives unexpected error as of now.

**To Reproduce**
1. Go to https://test.visualize.admin.ch/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-20-None-None%2Fcube%2F1?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22lfi%22%7D
2. Click on `Start a visualization`
3. Select chart type 'Table'
4. Click 'next'
5. see error 'No data available for current filter selection - Please try with another combination of filters.'

**Expected behavior**
The default table view has all categories enabled. (colum 1-7 every filter enabled) 
Thus the data shall be shown in a table view as it was the case last week.

**Screenshots**
![image](https://user-images.githubusercontent.com/26090254/154918830-8db618d0-e46b-46a8-9e3f-a031b603582e.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.4.1 ([040ed03](https://github.com/visualize-admin/visualization-tool/commit/040ed03a0445f0cc90e06d87d33336a3f31ee014)[](https://test.visualize.admin.ch/en/legal-framework))

**Additional context**
Oddly enough the table view starts to work after in column 2 (stage of stand development) clicking on 'Select none' and after selecting one of those filters again... 

cc @sandrobischof

**Comment by Rdataflow** [comment]
maybe related to #386

**Comment by ptbrowne** [comment]
I am having timeouts on the observations query. We did not make change to it, so I am asking Zazuko if the timeouts can be solved, maybe this is something that we'll only see on the int environment. @l00mi

**Comment by l00mi** [comment]
It is just at the limit of a size which can be handled. (This query does with the DISTINCT look at the whole cube, only to show the first 10 lines.) You could add the optimization as once communicated https://github.com/zazuko/rdf-cube-view-query/pull/69

**Comment by ptbrowne** [comment]
I tried without distinct directly in lindas query editor and still had a timeout.

**Comment by l00mi** [comment]
Its pretty quick here: http://cube-viewer.zazuko.com/?cube=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-19-None-None%2Fcube%2F1&endpointUrl=https%3A%2F%2Fint.lindas.admin.ch%2Fquery&user=&password=&sourceGraph=

**Comment by ptbrowne** [comment]
I guess it's quick because the labels are not considered in the cube viewer and related to the optional that are added to the query to pull the labels.

**Comment by ptbrowne** [comment]
The data now loads with no problem (with no changes on our part), it might have been a fluck from the database, I am closing right now, we'll reopen if necessary.
