### ISSUE TITLE
Search options combinations seems buggy

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#391]
**Describe the bug**
I report here a few things regarding the dataset search feature, the combination of the search options between theme/organisations and keywords:
1/ the number of dataset is updated under theme/organisations when a keyword is entered -> this seems to work
But this number should also be updated when just clicking on the "Include draft datasets" checkbox.
Clarification: when just clicking on the "include draft" checkbox, then the number of datasets is not updated, but it should

2/ when a keyword is entered, and then a theme/organisations is selected -> what is happening ?
Because the keyword seems automatically deleted, but it seems that it is still used to filter the search results.
The correct behavior should be: keep the keyword in the field, show only the datasets that correspond to the keyword+selected theme/organisation.
Complement: when doing it the other way round it seems to work properly (first select a theme/organisation, and then enter a keyword)

3/ Another special case where I do not understand what is happening:
1. Go to 'https://test.visualize.admin.ch/en'
2. Enter "list" in the search field, and select "include drafts"
3. The categories show "1" for "National Economy"
4. Click on "National economy" and then, the results are empty:
![image](https://user-images.githubusercontent.com/6167669/154942456-3ee17528-b51a-40bf-a9a2-a9b7b51b3e36.png)

**Environment (please complete the following information):**
- Visualize environment and version: TEST v3.4.1 + https://visualize-ad-testingv3--dl6d2r.herokuapp.com/en
- Browser and version: Firefox 97.0.1

**Comment by AnninaWalker** [comment]
LGTM! 👍
