### ISSUE TITLE
Missing selectable chart types

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#392]
**Describe the bug**
On [Visualize tmp](https://visualize-ad-testingv3--dl6d2r.herokuapp.com/) v3.4.1 (), Visualize allows only table as chart type for the dataset "State accounts - Function"

![image](https://user-images.githubusercontent.com/35593772/154932221-95c03775-6481-4547-968d-d481058e76d4.png)

Same thing on [Visualize test](https://test.visualize.admin.ch/) v3.4.1 (040ed03), but works on [Visualize int](https://test.visualize.admin.ch/) v3.4.1 (040ed03)

![image](https://user-images.githubusercontent.com/35593772/154932382-a9bbf958-37ef-46aa-9e5e-c13b984a8592.png)

**Environment:**
 - Edge Version 98.0.1108.43 (Official build) (64-bit)
 - Firefox 78.12.0esr (64-bit)

**Summary per dataset of the same collection "State accounts"**
| Dataset | tmp | test | int | prod |
|---|---|---|---|---|
|Category| ok (v15) | ok (v15) | ok (v5) | ok (v5) |
|Domain| bad (v15) | bad (v15)  | ok (v8) | ok (v8) |
|Function| bad (v8)  | bad (v8) | ok (v3)|  ok (v3) |
|Office| ok (v10) | ok (v10) | ok (v4) | ok (v4) |

Problem is probably in the datasets (old versions in Lindas INT) rather than in Visualise.

**Comment by ptbrowne** [comment]
Thanks Pierre. I think this is a problem with the cube : there is no column marked as measure in the provided dataset. See https://visualize.admin.ch/en/docs#/charts/types for which charts are allowed for which chart type.
