### ISSUE TITLE
Table chart: Remove style option once "use as group" and "hide column" are selected

### ISSUE THREAD

**Issue by MichelaBurzio** [visualize-admin/visualization-tool#399]
**Describe the bug**
Once the user selects the table option, a series of filters are available depending on the column. 
Some style options are available even though they are not required. In addition, the drop-downs are too close together and it would be better to space them out. 

**To Reproduce**
1. Create a visualisation from **State accounts - Office** dataset
2. Click on **Table** option/chart
3. Select the column **year**
4. Select on the right panel **use as group** and **hide column**
5. Column style section is available. Options to change the text style are not working accordingly.

**Expected behavior**

- [ ]  No Text style options should be displayed once **use as group** and **hide column** are selected.
- [x] The space between the panel elements is not respected, please add 16 px between the elements. 
- [x] Add a grey border to the **column color** box, otherwise, it is not visible. (by default it is white as the background). 

**Screenshots**
<img width="1728" alt="Screenshot 2022-02-21 at 17 43 02" src="https://user-images.githubusercontent.com/98882778/154996605-c9fb989e-17ff-45d1-8ef7-12f508fe87a3.png">

<img width="1728" alt="Screenshot 2022-02-21 at 17 45 14" src="https://user-images.githubusercontent.com/98882778/154997025-49518a8f-d9be-4ca6-9a35-332ba3f042f1.png">

**Environment:**
 - Visualize environment and version: [e.g. INT v3.4.1]
 - Browser and version [e.g. Chrome 97]

**Comment by sosiology** [comment]
Closing this issue, as the open task has been resolved. 

1. The text style option is not shown when the user selects "hide column" ✔ 
2. The bold styling works when "use as group" is activated (the change can however only be seen when the group / accordion is opened) ✔
