### ISSUE TITLE
Graph does not reflect auto-selected filters on the left

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#400]
When the value of filter 1 is changed, the content of filter 2 is automatically adjusted according to the availability of data, but not the graph on the right. The graph on the right-hand side retains the last value of filter 2. A refresh does not refresh the graph either, you have to select another value in filter 2 to refresh the graph. If there is only one value in filter 2, it cannot be displayed.

**To Reproduce**
1. open Bathing Stites in INT
2. choose bar chart
3. add color : parameter
4. add Filter Monitoring programm
5. Deplace the filter monitoring programm in position 1
6. Select BAQUA_SO in Filter Monitoring Programm
-> Impossible to display the graph for the bathing site "Solothurn"

**Screenshots**
![image](https://user-images.githubusercontent.com/79834090/155003488-0e79056b-fd3a-4c67-b2b8-405d7a900666.png)

**Environment (please complete the following information):**
INT v3.4.2 ([3e72a7d]
 - Edge

**Comment by ptbrowne** [comment]
Reopening until deployed to int

**Comment by ptbrowne** [comment]
Fixed on int. It was a silly mistake on my part. Thanks @ortnever for the feedback.

**Comment by AnninaWalker** [comment]
LGTM! 👍

**Comment by ortnever** [comment]
Yes, it's perfect. Thank you very much!
