### ISSUE TITLE
Maps chart - wrong icon

### ISSUE THREAD

**Issue by MichelaBurzio** [visualize-admin/visualization-tool#403]
**Describe the bug**
The filter icon should change according to the design.

**To Reproduce**
1. Select a **map** chart
2. Click on Next
3. Click on symbols in the chart options panel
4. See on the right panel the wrong icon for the filter section.

**Expected behavior**
Please change the filter icon accordingly to the design below.
<img width="398" alt="Screenshot 2022-02-22 at 10 35 46" src="https://user-images.githubusercontent.com/98882778/155104289-15c0e06b-8bca-488a-b259-011c1ff82e7f.png">

**Screenshots**
<img width="1728" alt="Screenshot 2022-02-22 at 10 33 29" src="https://user-images.githubusercontent.com/98882778/155103960-5f79fc74-0091-4cae-a120-e77ea17b9137.png">

**Environment (please complete the following information):**
 - Visualize environment and version: [e.g. INT v3.2.6]
 - Browser and version [e.g. Chrome 97]

**Comment by sosiology** [comment]
Reviewed on TEST - LGTM 👍 
Great catch @MichelaBurzio
