### ISSUE TITLE
New Color Icon

### ISSUE THREAD

**Issue by MichelaBurzio** [visualize-admin/visualization-tool#405]
The color icon is not descriptive of the section. We would like to change it to a brush icon.

**Describe the solution you'd like**
Instead of showing the segment icon, replace it with the color icon. See the image below.
The new icon is available in SVG on Sketch. In alternative ask to a designer to share the file. 

![Group 3](https://user-images.githubusercontent.com/98882778/155110605-4641fcc3-06f1-4006-bf4b-64bec76aea1f.png)

**Comment by AnninaWalker** [comment]
New icon will follow by @MichelaBurzio

**Comment by bprusinowski** [comment]
Cool, waiting for it! 😎

**Comment by AnninaWalker** [comment]
@bprusinowski please find here the new icon

![ic_color](https://user-images.githubusercontent.com/59613691/155544228-4ba3657f-55c7-464b-b455-13d5de86a5e9.svg)
