### ISSUE TITLE
+

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#410]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Visualize environment and version: [e.g. INT v3.2.6]
 - Browser and version [e.g. Chrome 95]

**Additional context**

**Comment by ptbrowne** [comment]
I guess this is a mistake @ortnever ? I am closing, please reopen if applicable :)
