### ISSUE TITLE
Pie chart and areas Chart not color-coded

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#411]
Maybe a problem bound to the big amount of possible colors?
The data legend under the pie chart contains the needed elements and the tooltip on the chart correctly identifies the various components, but every pie segment is blue. In the “filter” list on the right side it is possible to manually change the color of a single value, which is actually not part of the pie

**To Reproduce**
1. open following Visualization
https://int.visualize.admin.ch/it/v/Sm2aulFahho-
https://int.visualize.admin.ch/it/v/CzLwRaMHotcb

**Expected behavior**
Each element in the legend gets its own color

**Environment (please complete the following information):**
 - INT v3.4.2 ([3e72a7d]
- Browser : ?

**Additional context**
It is possible to build a pie chart with the very same data but other settings and get a correctly colored one. See https://int.visualize.admin.ch/fr/v/nA6OHSEEZJ3d
Maybe a problem bound to the big amount of possible colors?

@AFoletti

**Comment by ptbrowne** [comment]
Mmh weird. When I clone the chart and change the color palette, then change it again to the first one, I have a good looking result.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/465582/155141405-aa8c797f-0a2b-43b4-affc-74713d175afc.png">

**Comment by sosiology** [comment]
Can this issue be reproduced or can it be closed?

**Comment by ortnever** [comment]
You can close it.
