### ISSUE TITLE
Areas Chart : not contiguous but no missing value?

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#412]
The graph below appears to contain missing values as the visualization of the surfaces is not contiguous.
It's strange because the values of Energieverbrauch_PJ and ThgEmissionen_MtCO2eq (the two measures of the cube) are mandatory for all rows and there is an automatic check that verifies this in the original data. If values are missing in LINDAS this means that there is potentially an error in the creation of the triples.
Or can this visualisation problem be due to something other than missing values?

see : [this chart](https://int.visualize.admin.ch/it/v/Sm2aulFahho-)

**Environment (please complete the following information):**
 - Visualize environment : INT v3.4.2 ([3e72a7d]
 - Browser and version : ?

@AFoletti

**Comment by AFoletti** [comment]
I checked on [LINDAS ](https://lindas.admin.ch/sparql/)with the following SPARQL query to check an observation with values == 0.0.
It looks like they are correctly stored in LINDAS, so I guess there is an issue somewhere in the interpretation of those data

`SELECT * FROM <https://lindas.admin.ch/sfoe/cube> WHERE {<https://energy.ld.admin.ch/sfoe/bfe_ogd56_energieperspektiven2050/3/observation/ZERO_VarC_eeplus_50_2026_sektor_crf2_entr_16> ?p ?obs .}`

**Comment by ptbrowne** [comment]
The problem here is are the negative values in the Energy consumption column. It does not play well with area charts.

- Is this normal that in the data there is negative values in the "energy consumption" column ? What does it mean for an energy consumption to be negative ?

**Comment by AFoletti** [comment]
I have to admit that I am myself not the best specialist for the actual _meaning_ of this data.
However, I asked the same question to the specialists some months ago when I was preparing the dataset. A negative consumption is actually a production.

Not the best solution of course. A more clean data model would have 2 additional columns like "energyproduction" and "CO2absorbtion" or similar. That way, the numbers will always be positive.

This is however out of the scope of this ticket.
Is there a solution app-wise, or should we simply avoid area charts with this data?

**Comment by bprusinowski** [comment]
The main problem is that we can't really plot a stacked area chart with series that contain both positive and negative values. In this case, we could display an error with a call to action to de-select such series from a chart – we didn't have such dataset before, but I guess additional cases like that could appear in the future, we will consider this together with @ptbrowne.

I think in this case it would be good to split this column into two as suggested if possible or to switch to another chart type (for example stacked bar chart should work).

**Comment by AFoletti** [comment]
Thanks for the input. I will test the stacked bar chart.

Anyways I agree with you that with the growing usage similar cases may very well appear, and at least a warning is needed somehow.
