### ISSUE TITLE
Show standard error in maps tooltip

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#416]
**Describe the bug**
LFI maps show values but don't show unit and standard error

**To Reproduce**
1. Go to https://test.visualize.admin.ch/de/v/OvgisUTHnmJ6
2. Hovering shows value with unit and +/- StandardError
3. Compare to https://test.visualize.admin.ch/de/v/EqkKIN-tq4kc
4. See missing Unit and missing StandardError

**Expected behavior**
On maps the StandardError shall be displayed if available in the cube

**Screenshots**
* good label
![image](https://user-images.githubusercontent.com/26090254/155222190-6368aeb7-e932-4baf-b94e-dde353790bb9.png)

* missing StandardError in label
![image](https://user-images.githubusercontent.com/26090254/155222112-cdc93ed5-6f7b-48ca-af58-3f1973722c3e.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.4.3 ([7ca070f](https://github.com/visualize-admin/visualization-tool/commit/7ca070f4e535ab6602e73003ec7d1f5d85ed68ac))

**Comment by ptbrowne** [comment]
Thanks for the feedback @Rdataflow, I removed the "bug" label as this is something that has not been implemented. We will take a look.

**Comment by ptbrowne** [comment]
fixed by #420 , also added the unit there.
