### ISSUE TITLE
Tooltip not completely visible

### ISSUE THREAD

**Issue by AFoletti** [visualize-admin/visualization-tool#422]
**Describe the bug**
When a visualization has a lot of classes (I'd say >15) is it possible that the tooltip you get by hovering over the chart is partially outside the viewport and is missing its upper part.

**To Reproduce**
1. Go to t[his visualization](https://int.[visualize.admin.ch](https://int.visualize.admin.ch/fr/v/VmYA1y5nelED)/fr/v/VmYA1y5nelED)
2. Hover over the chart to obtain the tooltip
3. The tooltip is missing its upper part and does not show some of the available classes

**Expected behavior**
The tooltip is always fully drawn in the viewport and is not missing any part even when there are many classes to show.
_As an alternative_: the tooltip only shows the value of the class you are actually hovering instead of each class. This may solve this issue and help the user when some classes have very similar colors, but on the other hand could make it hard to get a tooltip if a class is too small compared to others

**Screenshots**
![image](https://user-images.githubusercontent.com/691243/155472505-f36b54f0-5dce-41fb-bbf4-93cdc3812d17.png)

**Environment (please complete the following information):**
 - Visualize environment and version: INT v3.4.4 1019df3
 - Browser and version: Edge

**Comment by sosiology** [comment]
Thank you for reporting the issue @AFoletti. We already have this on our radar (see: https://github.com/visualize-admin/visualization-tool/issues/315) so I will close this issue to avoid duplication.
