### ISSUE TITLE
Modification Cube "Trafic noise pollution" -> link on home page

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#423]
The dataset "Traffic noise pollution" has currently an unnecessary key dimension: the year. As the data owner explained to me, there will never be a time series because the methodology is not comparable from one survey to another. There is simply a reference year (currently 2015). 
So I would like to remove the year dimension in my cube before any graphs are published. However, if I make this correction, the structure will change, so the link used on the home page will be broken.

Can you tell me how to proceed? I make the change and you change the example link on the home page directly after?

**Comment by ptbrowne** [comment]
The best here for me would be to create a new cube since you are modifying the structure of the cube, then deprecate the older cube. This way, the example of the homepage would work until we change it. If it is simpler for you, you can change the structure of the cube directly but until we deploy in production, the example will not work on the homepage. If it's OK for you, let's do it but I think we should keep to the process of creating a new cube when we change the structure.

**Comment by ortnever** [comment]
with "deprecate" do you mean "unlist" in the cube Creator?

**Comment by ptbrowne** [comment]
Thanks  for the question, I am re-reading https://github.com/zazuko/cube-creator/wiki/4.-Publication#clarification-about-flags-expired-and-actions-unlist-delete and it seems both "expiration" and "unlisting" would make the cube inaccessible to the application, and thus there would be a failing example on the homepage until our next deployment.

To ensure no failing example on the homepage at all time, I would advise to do as follow:

1. Publish the new cube
2. I change in the homepage the cube URL and information
3. I deploy to int
4. We check that everything is OK
5. After deployment to prod, you can unlist the first cube

**Comment by ortnever** [comment]
just to be sure...
Step 1 : Publish the new cube -> in Lindas PROD?
It means we will have 2 cubes "Traffic noise pollution" in PROD until deployment to prod on next monday and unlisting cube 1 ?

**Comment by ptbrowne** [comment]
Yes, I think it is preferrable to have a broken example on homepage until deployment.

**Comment by ortnever** [comment]
@ptbrowne : 
as long as I cannot publish the cube, I cannot send you the new url for the graphic on the home page. 

I had to open a new issue in github cube creator. The other one have been closed.

https://github.com/zazuko/cube-creator/issues/1116

**Comment by ortnever** [comment]
Here the new URL for the exemple on the home Page. Just tell me when deployed to INT. I will have a check.

https://www.visualize.admin.ch/de/v/n15PkjjQQIrU

**Comment by ptbrowne** [comment]
It's deployed on int.

**Comment by ortnever** [comment]
Perfect. It's ready for prod ! Thank you.
