### ISSUE TITLE
Problem with changing left panel filters when using color segments

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#425]
**Describe the bug**
An unexpected error (Error: Can't find color for '128794') appears when trying to switch filters using the left panel.

**To Reproduce**
1. Go to the [Covid dataset](https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2FCOVID19VaccPersons_v2%2F2%2F?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22covid%22%7D).
2. Select a bar chart type.
3. Select color segmentation by Population.
4. Change Canton filter from Zurich to Zug.
5. See the error.

**Expected behavior**
It should be possible to change filters in such case.

**Screenshots**
<img width="1920" alt="Screenshot 2022-02-24 at 13 20 45" src="https://user-images.githubusercontent.com/52032047/155522934-1f077a6b-6cc1-4e5d-b940-1c72a5c2d64e.png">

**Environment (please complete the following information):**
 - Visualize environment and version: TEST 3.4.4
 - Browser: Safari 14

**Additional context**
I think it's related to #299.

**Comment by bprusinowski** [comment]
The problem here seems to be that the Population dimension is not a Measure, but a standard dimension. If we encounter `minInclusive` and `maxInclusive` on a dimension, we only fetch min & max values – so in this case, we only have two colors for min and max, when we should fetch all values.

 @l00mi I wonder if it makes sense to have a numeric variable that is not a measure. I think that in this case (Covid19 dataset) it's just a wrong mapping done in Cube Creator, but do we really have use cases for numeric regular dimensions (except for standard error, maybe?)?

I can imagine that e.g. we **maybe** would like to filter by some ID or similar variable that is numeric, but I am not really sure if it makes sense.

Should we introduce some changes on our side to either:
- treat non-measure, numeric variables as measures (which probably can be dangerous),
- treat non-measure, numeric variables as nominal dimensions (and fetch all values for them, just like for regular, non-numeric dimensions),
or maybe there should be some restriction on the cube creator side?

What's your view on that?

**Comment by Rdataflow** [comment]
@bprusinowski it's important keep those two concepts apart

1. `qudt:scaleType` which indicate the `{nominal,ordinal,interval,ratio}` scaleType. the latter who indicate what call numerical.
2. `rdf:type` which flag `{Key,Measure}Dimension`s **or can be absent** *i.e. to indicate "none of them"*

based upon these concepts it becomes clear that i.e. a non-measure (rdf:type not set to MeasureDimension) with ratio scaleType shall not be treated as a Key nor a MeasureDimension.

NB: As you noticed this generic logic equally applies to the LFI cubes for the standardError Dimension and more cases to come... you can think of any *meta information loosely indicating*

* precision, validity or usefulness of a measurement (i.e. `cloud cover` on satellite images, `dirt in a probe`, )
* reference values (i.e. `reference area`, `reference population`) which could be used as (a) a criteria to filter bigger or smaller entities or even (b) a divisor to resolve to `measure per area`, `measure per population`, etc.
* ... more cases to join


So it definitely makes a lot of sense to have such dimensions with whatever kind of non-measure meta information available. Apart from the standardError the filter case is the most obvious.

cc @l00mi @ptbrowne

**Comment by l00mi** [comment]
I agree we are at the point to consolidate the interpretation of this metadata per Dimension.

I am not sure if there is a common understanding on this, and honestly I do not know exactly how these are interpreted, except the rather simplistic https://visualize.admin.ch/docs#/charts/types.

So I would be very happy if there is an exacter overview how the metadata on Dimensions is interpreted by Visualize right now. Then we can align on the expectations and document it.

**Comment by l00mi** [comment]
@bprusinowski in general you are right numerical data will be mostly Measurement Dimensions, but it can also be a KeyDimension, 

e.g. "Level of Happiness": (1,2,3) although in this cases I push data providers to better create concepts with "ordinal".
or
"Age Group (Above)": (20, 30, 40) etc.

So we need a distinction on this level.

Concretely on the Covid Dataset you are absolutely right, that was a lastly build example and is wrong here. Although again, it is aways possible that Dataprovider will do the same, and this can neither syntactically nor semantically catched by a machine, so Visualize needs to be a bit robust on this cases.

**Comment by bprusinowski** [comment]
I am closing this for now, we disabled nominal, numerical dimensions in the chart options & interactive filters, so this error is no longer there.

@l00mi, we are also preparing a document on how Visualize interprets dimensions metadata, I'll let you know once it's ready.
