### ISSUE TITLE
Add NumericalDimension

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#430]
**Is your feature request related to a problem? Please describe.**
We should have a `NumericalDimension`, which is identical to a `Measure`, but can be differentiated in encoding specs. This would allow us to properly filter out numerical dimensions that are not measures in particular fields and enable us to potentially create new fields to improve new app (e.g. numeric range filter).

**Additional context**
See [this thread](https://github.com/visualize-admin/visualization-tool/pull/426#discussion_r814052756).

**Comment by Rdataflow** [comment]
isNumerical is already available trough: 
`scaleType is in {IntervalScale,RatioScale} `

@bprusinowski it's important keep those two concepts apart

1. qudt:scaleType which indicate the {nominal,ordinal,interval,ratio} scaleType. the latter who indicate what call numerical.
2. rdf:type which flag {Key,Measure}Dimensions or can be absent i.e. to indicate "none of them"

based upon these concepts it becomes clear that i.e. a non-measure (rdf:type not set to MeasureDimension) with ratio scaleType shall not be treated as a Key nor a MeasureDimension.

NB: As you noticed this generic logic equally applies to the LFI cubes for the standardError Dimension and more cases to come... you can think of any meta information loosely 

* precision, validity or usefulness of a measurement (i.e. cloud cover on satellite images, dirt in a probe, )
* reference values (i.e. reference area, reference population) which could be used as (a) a criteria to filter bigger or smaller entities or even (b) a divisor to resolve to measure per area, measure per population, etc.
* ... more cases to join

So it definitely makes a lot of sense to have such dimensions with whatever kind of non-measure meta information available. Apart from the standardError the filter case is the most obvious.

cc @l00mi @ptbrowne

**Comment by bprusinowski** [comment]
Hi @Rdataflow,

thank you for clarifying the differences! This issue was meant as a purely technical improvement, which won't affect the mappings done in the cuber creator. We treat some concepts as "dimension types" to make it easier to use within the application; so there is e.g. a TemporalDimension, which is created based on the "Time description" data kind set on a dimension in the cube creator.

Right now we have to retrieve "isNumerical" property for each dimension: even GeoCoordinates or GeoShapes dimensions, which can't be numerical, as they contain sets of coordinates and names of the regions.

If we introduced a NumericalDimension (which is not a MeasureDimension and may or may not be a KeyDimension) it would be more efficient and easier to maintain some of the option fields that could only be used with such dimensions (potentially, as we don't have any of such at the moment).

I hope that our intentions are clearer now :)
