### ISSUE TITLE
New dataset "Unexpected Error"

### ISSUE THREAD

**Issue by AFoletti** [visualize-admin/visualization-tool#434]
**Describe the bug**
When I try to visualize my new dataset on TEST, I get either an empty chart or an "Unexpected error" window, no matter which chart type I pick.

(When trying to use the Map chart type, I get a warning that cantons geometries are currently not available with a suggestion to try later. This part is thus more a heads-up than a bug report)

**To Reproduce**
1. Go to ['https://test.visualize.admin.ch/'](https://test.visualize.admin.ch/)
2. Create a new visualization with the BFE dataset "Einmalvergütung für Photovoltaikanlagen"
3. Try to create a chart for a single canton
4. No data appears (**note that every canton DO have data. Some cantons DO NOT have data for the first year in the Timeseries**)
5. Now try to use "Kanton" as color
6. You get the "Unexpected error" window

**Expected behavior**
Chart show data and can be correctly created
(cantons geometries are correctly fetched and used when selecting a Map chart)

**Screenshots**
![image](https://user-images.githubusercontent.com/691243/155968457-f4849d42-4be5-48cf-a166-9f60d2dc6614.png)
Empty chart

![image](https://user-images.githubusercontent.com/691243/155968534-02864a41-b6d8-46c8-bed8-6ba26fd11e2b.png)
Unexpected error

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.4.7 ([0d01260](https://github.com/visualize-admin/visualization-tool/commit/0d01260252595c56bf62bea51461fb84212891f1))
 - Browser and version: Edge

**Additional context**
See https://github.com/visualize-admin/visualization-tool/discussions/433
I guess this is once again bound to the interaction of the tool with "strange" data?

**Comment by AFoletti** [comment]
Side-note: the Map chart now loads the cantons correctly. However, this chart type suffers from the same 2 issues described above

**Comment by bprusinowski** [comment]
Hi @AFoletti, I did some investigation and it seems that the Kanton variable has a "string" type assigned in the first step in the cube creator; however I think it should not have any type selected at this point. Could you try to remove the type and republish the cube to see if it helps, at least with showing chart types other than map?

I am not sure if we should change something on our side, what's you view on that @l00mi? Does it make sense to have a `dataType` on a variable that has a `dataKind` of GeoShape? In the case of a working example, Covid19 dataset, the `dataType` is empty.

**Comment by bprusinowski** [comment]
The exact problem is that when a variable has some `dataType`, then we use it a literal when we build the filters; when it's not, then we use `namedNode`, as it should be in case of Cantons `SharedDimension`.

**Comment by AFoletti** [comment]
Helly @bprusinowski 
Removing the "string" type to the Kanton attribute in the Cube Creator did the trick. Now it works flawlessly with every chart type.
Thanks for your help! I will jot down a note-to-self somewhere for the future :)

**Comment by bprusinowski** [comment]
Great, I'm glad I could help! :)

**Comment by AFoletti** [comment]
A tangent question: is there a way to activate the measure filter in the map chart if my cube has more than one available measurement? I can find how to activate the year filter, but not the measure

**Comment by bprusinowski** [comment]
Just to make sure – you'd like to use a Measure (e.g. Anzahl Anlagen) as a filter on the left panel, below a Jahr filter?

**Comment by AFoletti** [comment]
I... guess?
I would like to have the option to pick which measure to show in my chart. Kind of a published-status equivalent of this
![image](https://user-images.githubusercontent.com/691243/155983327-5b58859d-8c33-469e-8313-8686b4dc3420.png)
so that my users can visualize more than one measure if available.

But it seems to me that's not possible in any kind of chart. Should I post it as feaute request?

**Comment by AFoletti** [comment]
Hey @l00mi , thanks for your input!
Actually your idea and mine are complementary but not the same.
I would like the option to switch the _single_ measure shown in the chart to other measures available in the same cube. This of course may require a redraw of the axis because of changing Unit and/or scale.

I would of course support your idea and the option to show two measures at the same time, but this is in my opinion a little more specific since works well with only a subset of the available chart types while a "_show me Anzahl Anlagen or Leistung_" dropdown could be useful for any.

And yes, GoLive for this dataset is planned soon

**Comment by ptbrowne** [comment]
@AFoletti Indeed I think the idea is interesting, could you open an issue describing it with an example and your particular context ? I am also interested in where you publish the charts and whether this problem could not be dealt with at the CMS layer.

**Comment by l00mi** [comment]
@ptbrowne What do you mean with CMS layer? Simply creating two graphs and put them aside?

**Comment by ptbrowne** [comment]
I meant that to me visualize.admin was to be paired up with a CMS (here maybe have a toggle to switch between two chart types) for more advanced usecases.

But the more I think about it, the more switching dimension on a single axis inside the same chart makes sense. What is difficult then is to know when to stop, if you can switch dimensions on 1 axis, can you change dimension on the other axis, then as a publisher, do you get to decide which combination are possible ?

**Comment by l00mi** [comment]
It is not about switching the axis, it is about allowing two measurements on the vertical axis, which would need to allow an axis left one right to work.

**Comment by ptbrowne** [comment]
>  I would like the option to switch the single measure shown in the chart to other measures available in the same cube. This of course may require a redraw of the axis because of changing Unit and/or scale.

@l00mi This is not what I understand from @AFoletti message.

**Comment by AFoletti** [comment]
As I already said, @l00mi 's idea looks complementary to mine, if probably more difficult to implement. However, @ptbrowne 's interpretation of my still inofficial feature request is correct

And yes, we actually plan to solve our need at the HTML level for the moment being. I will prepare 3 different charts, each for the 3 available measures in the cube, and implement a simple drop-down in the HTML that will show the iFrame correcponding to the selection made.
I guess this places my FR in the "nice to have" pile since I can solve it easily outside of Visualize. But you can't obtain if you don't ask 😉 
I will open a proper FR ticket soon.
