### ISSUE TITLE
Plot more than a single measure

### ISSUE THREAD

**Issue by AFoletti** [visualize-admin/visualization-tool#439]
**Is your feature request related to a problem? Please describe.**
It is often interesting to show two separate measures in the same chart. Today, this is in Visualize not possible.

**Describe the solution you'd like**
I would like the option to add other measures available in the cube to be plotted in the same chart as the first.
If the measure's Unit is the same, it should be possible to add as many measures as there are in the cube, and the vertical axis should adapt accordingly.
Alternatively, or if the second measure has a different Unit than the first one, the user should be able to activate a second vertical axis.

**Describe alternatives you've considered**
None really.

**Additional context**
Related to [this FR](https://github.com/visualize-admin/visualization-tool/issues/438)
See discussion (and a screenshot) [here](https://github.com/visualize-admin/visualization-tool/issues/434)

**Comment by AFoletti** [comment]
Pinging @l00mi since this was mostly his idea (I allowed myself to make it a little more generic)

**Comment by sosiology** [comment]
@AFoletti we have begun to tackle this issue and some questions came up about how to best approach certain aspects. Would you have time next week for a short alignment call to answer some of our questions?
cc: @bprusinowski

**Comment by AFoletti** [comment]
@sosiology certainly, just say the time!
You should have my full conctact information (if not, you can ask someone in BAFU). Next week afternoons are pretty busy for me, so a morning would be better.

**Comment by sosiology** [comment]
Thank you for the prompt feedback @AFoletti 
I sent you an invitation and call link for October 03 at 11:00 Let me know if that works for you, otherwise I am happy to propose some alternative dates and time slots

Cc: @bprusinowski

**Comment by sosiology** [comment]
Ready for Internal Review via PR
