### ISSUE TITLE
Bar chart race

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#443]
**Is your feature request related to a problem? Please describe.**

The bar chart race is a bar chart with a time slider that plays through the time and the bars in the chart update their position according to their value.
The result is an animated bar chart that allows the user to see the evolution of a values along the time.

**Describe the solution you'd like**

In visualize, we could add to a "bar chart race" chart that would have an encoding field "time" that would be displayed if a time dimension is present in the dataset. If a time filter is added to a chart, the publisher could decide to display a play / pause button and configure whether the animation autoplays.
This would not be the same thing as the "time filter" which only filters whereas here the "time" discussed here is an encoding (we encode time through multiple charts that can be scrolled through with a time slider).
Animation would be of the essence here so that bars animates smoothly as the time slider is scrubbed.

**Usecases and impact**

I find these charts very informative and they would be useful in context where we want to see the evolution of values through time. they could benefit from this type of chart.
We have multiple datasets with time encodings, I see this type of chart being very useful for environment / energy / finance / agriculture datasets.
Additionally, these type of charts are informative as well as being engaging, and they often are shared on social media. This could be a lever for increased user engagement. 

**Additional context**

Example in d3 observable: https://observablehq.com/@d3/bar-chart-race-explained
Example in flourish: https://flourish.studio/visualisations/bar-chart-race/?utm_source=showcase&utm_campaign=visualisation/3498987
Article that demonstrates an example of this chart "Animated chart of the day" in the context of automotive production: https://www.aei.org/carpe-diem/animated-chart-of-the-day-worlds-top-ten-countries-for-motor-vehicle-production-1950-to-2019/

https://user-images.githubusercontent.com/465582/156765373-355465cb-5c45-47c0-9db8-dccee749b8ac.mp4

**Comment by sosiology** [comment]
an additional reference of how something similar could also be applied to maps: https://www.covid19.admin.ch/de/epidemiologic/case/d/geo-regions?geoDate=2020-02-24

**Comment by bprusinowski** [comment]
Should be closed when we implement time slider feature (starting with #834).

**Comment by bprusinowski** [comment]
Closed by the latest work on animations (#1101, #1103, #1105).
