### ISSUE TITLE
Harmonize UI for time handling

### ISSUE THREAD

**Issue by AFoletti** [visualize-admin/visualization-tool#444]
**Is your feature request related to a problem? Please describe.**
When creating a map using data with a time element (see [this example](https://test.visualize.admin.ch/de/v/F3ftcamV7S_Y)) you have the option to allow the user to pick the year. However, this option is hidden behind a not-very-prominent "show filters" button.
On the contrary, for other chart types (bar, lines, area) the time selector is shown in a very clear and prominent way under the chart itself.

**Describe the solution you'd like**
I would like to have the time selector for the map charts to behave and be presented to the user in the same slick, neat and user-friendly way as in the line and bar chart types.
**Good**:
![image](https://user-images.githubusercontent.com/691243/156996502-1ee716fd-beed-4a4e-b173-c6da07a66b13.png)
**Bad**:
![image](https://user-images.githubusercontent.com/691243/156996592-d17599c5-bf67-4cdd-9719-d784f96ea90b.png)

Of course for the map chart type the time selection will allow the user to pick only one year to show (instead of a time period for the other chart types)

**Describe alternatives you've considered**
None really

**Usecases and impact**
I agree that most filters can be hidden behind the "show filter" button in order to keep the visualization tidy. However, time is a central element of a visualization, even more so for a map where you can only show one year at a time. Moreover, it is confusing to have the very simple and neat time selector for some chart types and not for the map o.ne.

**Additional context**
See the issue in action [here ](https://www.uvek-gis.admin.ch/BFE/testumgebung/EE_Einmalverguetung/)(page still in dev). It would be very nice for the user to be able to easily pick the year to show on the map. It may very well miss out on the "show filter" button, which even if noticed is prone to be considered as an advanced feature.

**Comment by Rdataflow** [comment]
very interesting 
@Rdataflow subscribes

**Comment by sosiology** [comment]
Achieved with the introduction of the animated charts / maps
