### ISSUE TITLE
Tables do not render for big cubes

### ISSUE THREAD

**Issue by dabo505** [visualize-admin/visualization-tool#457]
**Describe the bug**
If the cube is too big the data does not show in the tables view. 

**To Reproduce**
Choose any of the BLW cubes: https://test.visualize.admin.ch/browse/organization/https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-landwirtschaft-blw?includeDrafts=true

**Expected behavior**
For bigger cubes there should be a limit, so that only a part of the data is shown.
That also means there needs to be a "Show another 100 (?) rows" or something similar.

**Comment by ptbrowne** [comment]
Thanks for reporting, I'll have a look into it this week.
