### ISSUE TITLE
Contact Point is not shown in visualize

### ISSUE THREAD

**Issue by dabo505** [visualize-admin/visualization-tool#462]
**Describe the bug**
I added a contact point for all BLW-cubes. It's there in LINDAS but doesn't show in visualize:

https://s.zazuko.com/4NJGNA

https://test.visualize.admin.ch/browse/dataset/https%3A%2F%2Fagriculture.ld.admin.ch%2Ffoag%2Fagricultural-market-data%2Farable-crops-collection-points%2F1?previous=%7B%22type%22%3A%22organization%22%2C%22iri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-landwirtschaft-blw%22%2C%22includeDrafts%22%3Atrue%7D

**Comment by bprusinowski** [comment]
Hi @dabo505,

I did some investigation and it seems it should be structured differently – this is [how we parse](https://github.com/visualize-admin/visualization-tool/blob/e94ae9e228ccf2a2ef5ec232369c385fc5026db5/app/rdf/parse.ts#L71-L74) contactPoint information (using dCat + vCard namespaces).

You can also see a correct formatting e.g. in Bathing water quality dataset in [this query](https://s.zazuko.com/fLTyD8).

Let me know it that helps!

**Comment by dabo505** [comment]
Hi @bprusinowski 
Awesome! Thanks for the hint. I will update the data accordingly.

**Comment by bprusinowski** [comment]
I am closing the ticket as the issue seems resolved, please re-open if you have a question or if it does not work :)

**Comment by dabo505** [comment]
Thank you, working fine by now...
