### ISSUE TITLE
New WASTA dataset only loads in table view

### ISSUE THREAD

**Issue by AFoletti** [visualize-admin/visualization-tool#464]
**Describe the bug**
The new WASTA dataset is published on LINDAS TEST and visible in the list of available datasets.
However, when trying to create a viz with it, I either becomes an error message, or the UI goes on indefinitely with the loading wheel. This is true for all chart types **except** the table one, which works fine.

**To Reproduce**
1. Go to ['visualize TEST'](https://test.visualize.admin.ch/en/browse)
2. Scroll down and look for "Statistics on hydropower plants (WASTA)" (**please note** that at the time of writing the filters on the left do not work either, so you have to scroll. I did not post a bug because it could maybe be temporary?)
3. Select "Statistics on hydropower plants (WASTA)" as dataset to visualize
4. Play around with the chart types and enjoy the error messages

**Expected behavior**
Data loads and each chart type actually works

**Screenshots**
Error message:
![image](https://user-images.githubusercontent.com/691243/159893002-661a8355-ba44-43a9-bc23-44fc7d042505.png)

Neverending loading:
![image](https://user-images.githubusercontent.com/691243/159893146-c25c2dc6-dd54-4965-a90a-1881e35b0e18.png)

Table is fine:
![image](https://user-images.githubusercontent.com/691243/159893210-af604424-75a7-417f-9ecf-0fc4b034c35e.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.4.8 ([e94ae9e](https://github.com/visualize-admin/visualization-tool/commit/e94ae9e228ccf2a2ef5ec232369c385fc5026db5))

**Additional context**
I just noticed that the same problem seems to be visible for all, or at least many of them datasets.

**Comment by AFoletti** [comment]
>  (**please note** that at the time of writing the filters on the left do not work either, so you have to scroll. I did not post a bug because it could maybe be temporary?)

I just noticed that this problem does not appear anymore in v3.4.8 ([77eb65e](https://github.com/visualize-admin/visualization-tool/commit/77eb65e46333083a5fd168a6aad6809bc2dcbf95))
However, mais data loading issue is still there. 

Examples of other affected datasets:
- Traffic noise pollution
- Heavy Metal Soil Contamination
- Bathing water quality

**Comment by AFoletti** [comment]
Seems to be fixed in v3.4.8 ([53200c2](https://github.com/visualize-admin/visualization-tool/commit/53200c20b68c1a26406d74853ace69f4f9678159))

Thanks!

**Comment by sosiology** [comment]
Thanks for the input and feedback @AFoletti !
