### ISSUE TITLE
Outline around chart type selection in sidebar

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#471]
**Describe the bug**
Remove the outline around the chart type selection

**To Reproduce**
1. Go to 'test.visualize.admin.ch
2. Select a data set and continue to the chart type selection
3. See error

**Expected behavior**
In the chart type selection menu in the left sidebar, there is a grey line around the options

**Screenshots**
![image](https://user-images.githubusercontent.com/29289679/160401748-c3a758f5-3ee6-4d53-81d8-5a1a19cb302e.png)

**Environment (please complete the following information):**
 - Visualize TEST v3.4.8
 - Browser and version [Chrome 99)

**Additional context**

**Comment by AnninaWalker** [comment]
LGTM
