### ISSUE TITLE
Map: Same behaviour in left side bar for symbol layer as for color segmentation in other charts

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#474]
**Is your feature request related to a problem? Please describe.**
When I select for ex. a Bar Chart, but have not yet selected a Color Segmentation yet, the component in the left side bar is disabled and the text is: Add... When I select a Map but have not yet selected a Symbol Layer yet, it looks like its already active

**Describe the solution you'd like**
The Symbol Layer component in the left side bar should be disabled as well, and it should say "Add.." as well, than having a dimension already selected.

**Usecases and impact**
Coherence throughout the tool
<img width="1494" alt="Screenshot 2022-03-29 at 11 50 41" src="https://user-images.githubusercontent.com/59613691/160585762-1d927d0d-bac1-46f7-a45d-eca5ed24cf29.png">
<img width="1488" alt="Screenshot 2022-03-29 at 11 51 20" src="https://user-images.githubusercontent.com/59613691/160585828-d256c29e-bc5e-4d0a-9f17-f0c42dee17f8.png">

**Comment by bprusinowski** [comment]
Good catch @AnninaWalker, thanks for reporting!

**Comment by AnninaWalker** [comment]
I've double checked and this would still need to be solved. The thing is that the Symbol level currently looks active, but you don't see any symbols because the checkbox in the right side bar is not yet checked. So either the checkbox needs to be checked per default, or it has to be done as described above @ptbrowne @bprusinowski @sosiology
