### ISSUE TITLE
Font styles

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#478]
I've noticed that on the landing page the definition of H2 and H3 are not correct

- [x] H2 should be 24px and H3 should be 18px.

- [x] In the Catalog Documentation the Definition of H1 is also incorrect. It should be 32px instead of 40px. And the wrong Font (apple system) is still displayed:

Landingpage 
<img width="2104" alt="Screenshot 2022-03-30 at 11 05 58" src="https://user-images.githubusercontent.com/59613691/160795766-95b6cfbf-19bc-4529-bb0a-04bca7b92fe4.png">
<img width="2115" alt="Screenshot 2022-03-30 at 11 06 19" src="https://user-images.githubusercontent.com/59613691/160795782-0142083f-b4dd-4b59-a873-7660b5c2d9a4.png">

Catalog Documentation
<img width="1871" alt="Screenshot 2022-03-30 at 11 00 15" src="https://user-images.githubusercontent.com/59613691/160795827-61b15912-94d4-4538-8dee-d4f0dfeb8a8c.png">

These are the definitions in the styleguide (Please refer to those):
<img width="1826" alt="Screenshot 2022-03-30 at 10 59 07" src="https://user-images.githubusercontent.com/59613691/160795875-45e273b8-d0db-4c8f-8494-83645f6da437.png">

**Comment by AnninaWalker** [comment]
Also here, the font definition should be body2 (14px). Currently it is 13px.

![Screenshot 2022-04-05 at 09 40 17](https://user-images.githubusercontent.com/59613691/161704216-869a70f0-b3ab-4c9a-b45d-be02e2c49317.png)

And H1 should be 32px instead of 40px
![Screenshot 2022-04-05 at 09 40 26](https://user-images.githubusercontent.com/59613691/161704492-c907726a-6ecb-45a1-a879-f43209677136.png)

**Comment by AnninaWalker** [comment]
This should be h4 instead of body1

![Screenshot 2022-04-05 at 12 15 52](https://user-images.githubusercontent.com/59613691/161732581-9f37db6b-8baf-42ae-bd2e-78cfbc1ad9fa.png)

**Comment by AnninaWalker** [comment]
And these labels should be #757575
![Screenshot 2022-04-05 at 12 18 45](https://user-images.githubusercontent.com/59613691/161733075-33f760b3-d807-483c-b4c9-136641d5b265.png)

**Comment by ptbrowne** [comment]
Thanks for your thorough reviewing @AnninaWalker, I am implementing the changes and adding checkboxes in your message where I've implemented the changes.
In the last screenshot, "Title" / "Description" are indicated but in the design, their color is "#333" (in the code we use the design token "grey.800") so for me it's OK no ?

----

Additionally, would it be possible in Sketch to use named colors like "grey.800" ?

**Comment by AnninaWalker** [comment]
Oh I'm so sorry. I've added the last screenshot to the wrong comment. The Title Description font should be h4 as well in the left side bar. The color is right with #333.

Regarding the renaming of colors:  I would prefer to not rename the colors as the colors in the Sketch File are named according to the colors in the Styleguide of the Federal Governement along with the hex code. Instead I was wondering whre the grey.800 is coming from? Should it be renamed on your side?

**Comment by AnninaWalker** [comment]
Ah now I see, in the Catalog documentation you have the 100 to 900 definition for the Greyscale. If it helps, yes I can add this naming to the colors in the Sketch File as well

**Comment by ptbrowne** [comment]
Ah OK no problem. As for the colors, yes maybe it's on my side.

I can't see proper names in Sketch though ? 

<img width="211" alt="image" src="https://user-images.githubusercontent.com/465582/161749387-fe241907-3c7e-4c22-8bce-5dd43cb5632b.png">

**Comment by ptbrowne** [comment]
The linked PR is not merged so no : https://github.com/visualize-admin/visualization-tool/pull/490, I will tell you when it's merged.

**Comment by AnninaWalker** [comment]
Thank you! LGTM! 👍
