### ISSUE TITLE
Search: No search results - Left side bar dissapears

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#485]
**Describe the bug**
Currently, when I search for a keyword and it doesn't provide a searchresults, I don't get a subline "No matching results foudn" and the left hand navigation dissapears.

**To Reproduce**
1. Go to '.test.visualize.admin.ch.'
2. Search for LFI (without including draft datasets)
3. See error

**Expected behavior**
As in the mockup, add a subline "No matching records found" and the keep the left hand navigation, so the user has the opportunity to click on a category or organization directly without having to clear the search first.

**Screenshots**
Status quo
![Screenshot 2022-04-05 at 11 05 22](https://user-images.githubusercontent.com/59613691/161720188-d8568833-0f3d-401a-9c11-4b901fb23636.png)

Original design
![Screenshot 2022-04-05 at 11 05 09](https://user-images.githubusercontent.com/59613691/161720214-8144bf14-ad94-4c83-aaf6-bd42da59259d.png)

**Environment (please complete the following information):**
 - Visualize environment and version: [e.g. INT v3.2.6]
 - Google Chrome

**Comment by ptbrowne** [comment]
Fixed in https://github.com/visualize-admin/visualization-tool/commit/7f3266b65e3e033022d79878a420454074006624

**Comment by AnninaWalker** [comment]
The "No results" line and keeping the left side bar is fine now, but if I click now for ex. directly on Administration, I would expect, that either the LFI in the search field is cleared automatically and I see all the results for Administration. Or the LFI keyword is kept, and I still don't see any results (But that doesn't really make sense). Currently the LFI gets cleared in the searchfield, but the results are still related to LFI. So I need on the x-icon first to clear the results.

https://user-images.githubusercontent.com/59613691/162156670-2902aa0f-7b5d-4290-ac6d-ac352bb44cb2.mov

**Comment by sosiology** [comment]
Testing Result: Keyword LFI remains in the search field when the user clicks on a category or organization in the left side bar

**Comment by ptbrowne** [comment]
We had a chat with Annina about this, and this is the behavior we want to keep. The problem was that when the input was not correctly showing the current search, and now it has been fixed. Concerning clearing the search input when jumping to another category, we decided it was best not to have this since you can want to narrow your search in a particular category .
