### ISSUE TITLE
Date filter missing

### ISSUE THREAD

**Issue by AFoletti** [visualize-admin/visualization-tool#493]
**Describe the bug**
After setting up a map chart, I can't find the "Date" field in the filters.

**To Reproduce**
1. Go to [TEST](https://test.visualize.admin.ch/)
2. Look for the "Statistics on hydropower plants (WASTA)" dataset and create a map chart with it
3. Get the "Date" and "OpStatus" filters option on the left
![image](https://user-images.githubusercontent.com/691243/161957539-dcd350d8-6b5d-4365-a665-f2d319e5c24f.png)
5. Go on to finalization. Activate data filters
![image](https://user-images.githubusercontent.com/691243/161957641-b363a9d7-aaa4-4c41-96bc-95dcbfe5f5b0.png)
6. "Date" is missing from the available filters (right panel)
![image](https://user-images.githubusercontent.com/691243/161957799-c87d6aac-7895-4fa3-b0ed-02d12141e01b.png)

**Expected behavior**
"Date" is available as filter (and actually as a proper time dimension, with timeselection and all that)

**Screenshots**
See above

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.4.8 ([d824e99](https://github.com/visualize-admin/visualization-tool/commit/d824e995e0ba67552cacff210feae60f0e05611d))

**Additional context**

**Comment by ptbrowne** [comment]
The interactive date filter is not supported by the map (yet). Right now, the date is used as a filter and it is not encoded in the chart.

**Comment by ptbrowne** [comment]
It is very similar to this issue : https://github.com/visualize-admin/visualization-tool/issues/451

**Comment by AFoletti** [comment]
You mean you can use a _year_ as a filter in the map, but not a _date_?

**Comment by ptbrowne** [comment]
Normally you should not be able yet to use a year as a filter. It works right now on your dataset "Einmalvergütung für Photovoltaikanlagen" since the year dimension is not properly understood as a Temporal Dimension, but as a Nominal Dimension.
I see right now that temporal dimesions are not supported as Interactive Filters dimensions. They should be but they are not.

**Comment by bprusinowski** [comment]
Closing as we now support interactive data filters with maps 🗺
