### ISSUE TITLE
Selecting Organization "Swiss Federal Archives" leads to error message in FR, IT and EN locales

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#494]
**Describe the bug**
When selecting "Swiss Federal Archives SFA" from the "Organizations" on the data selection page an error message is shown in all locales except German. 

**To Reproduce**
1. Go to 'visualize.admin.ch" (make sure language is set to EN, FR, or IT the bug cannot be reproduced in the DE locale)
2. Click on 'Swiss Federal Archives" from the list of Organizations
3. See error

**Expected behavior**
The data sets under the organization Swiss Federal Archives should be shown so the user can select a data set to visualize. 

**Screenshots**
![image](https://user-images.githubusercontent.com/29289679/162231610-6603737a-e695-4bf9-bced-67e78d197c4b.png)

**Environment (please complete the following information):**
 - Visualize environment and version: PROD v 3.4.7
 - Browser and version: Chrome: Version 100.0.4896.75 (Official Build) (arm64) / Safari Version 15.1 (17612.2.9.1.20)

**Additional context**
Reported on 07.04.2022 via email

**Comment by ptbrowne** [comment]
Fixed, was a firewall issue.
