### ISSUE TITLE
Search dataset with accents, does it work ?

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#495]
**Describe the bug**
I did publish a cube called "Öffentliche Ausgaben TEST 1"
But searching for "Öffentliche" gives no result, searching for "Ausgaben" does work.

![image](https://user-images.githubusercontent.com/6167669/162456434-4523183a-580e-4d13-8089-6c196eb5e6a6.png)

version: v3.4.8 ([d824e99)

**Comment by ptbrowne** [comment]
I think we should keep an eye on this bug after we switch to database searching. Otherwise here our work will be thrown away when we use database search.

**Comment by ptbrowne** [comment]
I've added this tests to our search tests, so that we cannot forget when we switch to database searching.

**Comment by ptbrowne** [comment]
It should work correctly now, with the database search. Please re-open if you see again the issue.
