### ISSUE TITLE
Datasets currently down - graphql service rejects

### ISSUE THREAD

**Issue by t0b3** [visualize-admin/visualization-tool#496]
**Describe the bug**
Visualize Browse: No datasets found - turning forever

**To Reproduce**
1. Go to 
- https://visualize.admin.ch/browse
- https://int.visualize.admin.ch/browse
- https://test.visualize.admin.ch/browse
2. Wait forever

**Expected behavior**
Show list of datasets

**Screenshots**
![image](https://user-images.githubusercontent.com/5751047/162562792-6d6b80d3-0e6b-448c-b9d8-7af4c2b77abd.png)
![image](https://user-images.githubusercontent.com/5751047/162562765-e82d66d0-e301-4871-ade4-98a404a16704.png)

**Environment (please complete the following information):**
- TEST and INT and PROD

**Additional context**
*request*
```curl 'https://visualize.admin.ch/api/graphql' -X POST --data-raw '{"query":"query DataCubes($locale: String!, $query: String, $order: DataCubeResultOrder, $includeDrafts: Boolean, $filters: [DataCubeSearchFilter!]) {\n  dataCubes(\n    locale: $locale\n    query: $query\n    order: $order\n    includeDrafts: $includeDrafts\n    filters: $filters\n  ) {\n    highlightedTitle\n    highlightedDescription\n    dataCube {\n      iri\n      title\n      creator {\n        iri\n        label\n        __typename\n      }\n      description\n      publicationStatus\n      datePublished\n      themes {\n        iri\n        label\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n","operationName":"DataCubes","variables":{"locale":"de","includeDrafts":false,"filters":[]}}'```
*response*
`<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 749007228021991049<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>`

@ptbrowne @bprusinowski

**Comment by t0b3** [comment]
**Lessons learnt** (draft)
- implement some API monitoring? (i.e. pingdom on graphql etc.) similar to https://status.geo.admin.ch/
- have alerts to trigger intervention by the responsible providers?

**Comment by ptbrowne** [comment]
Thanks Thomas for the report. We have https://visualization-tool.status.interactivethings.io/ to monitor status (you can subscribe to get updates). 

e've started having problems on Friday afternoon, and we think it's a firewall problem, as locally the site works perfectly. We have contacted the hosting provider to have more information and to tell them to insert firewall exceptions for our requests. Unfortunately at our level, there is not much we can do. I'll keep you posted here.

**Comment by ptbrowne** [comment]
Fixed, it was a firewall problem.

**Comment by Rdataflow** [comment]
Thanks for your intervention and for escalating this to the firewall operator.
Wouldn't it be useful to monitor for `Request Rejected` hence automatically escalating to the operator for 24x7 intervention?
cc @zellersabine @retostoll

**Comment by Rdataflow** [comment]
@ptbrowne Thanks for your intervention and for escalating this to the firewall operator.
Wouldn't it be useful to monitor for Request Rejected hence automatically escalating to the operator for 24x7 intervention?
cc @ZellerSabine @RetoStoll

**Comment by ptbrowne** [comment]
We are currently monitoring the firewall rejection, since you have subscribed to the status page, you should have received a notification when the situation was solved (this notification was automated). We could escalate automatically to Jan from Abraxas if needed, but I do not know the contract you have with them for this. Since whitelist rules were added, I do not think the firewall situation will repeat.

**Comment by Rdataflow** [comment]
👍 Hopefully it will not reoccur too often.
IMHO a direct alert to the ops makes sense (at least for ops related issues like firewall blocking and the like)... but first Vero will clarify the SLA questions on uptime warranties and intervention. 
cc @zellersabine
