### ISSUE TITLE
UI Refinement: Default state

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#506]
As we have now the call to actions on top, explaining what the user can do on the current screen, we should change the default state of the left side bar and already preselect the first section. Currently nothing is selected, and we have a call to action in the right sidebar as well, which seems a bit redundant.

**Status quo: Editing**
![Screenshot 2022-04-14 at 10 25 06](https://user-images.githubusercontent.com/59613691/163351516-b3ef7c02-c46a-44ff-b4ca-887b9ab44a1b.png)

**New default:**
![Screenshot 2022-04-14 at 10 25 13](https://user-images.githubusercontent.com/59613691/163351524-e8f699a6-8850-4597-b1a0-0dc978d5d945.png)

**Status quo: Annotating**
![Screenshot 2022-04-14 at 10 25 19](https://user-images.githubusercontent.com/59613691/163351533-b1e15d70-d62e-4bf4-a422-c9bb571ec5f5.png)

**New default:**
![Screenshot 2022-04-14 at 10 25 28](https://user-images.githubusercontent.com/59613691/163351547-3e94c08f-6abe-467a-94dc-f9408f5ba0f2.png)

**Additionally change the Call to Action on top for step 2 to the following:**
Status quo:
Customize your visualization by using the filters and color segmentation options in the sidebars

New Call to action:
Customize your visualization by using the Chart Options and Filters in the sidebar

**Comment by bprusinowski** [comment]
Closing as we do not have this type of call to actions anymore.
