### ISSUE TITLE
Scatterplot issues

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#511]
**Describe the bug**

When doing a scatterplot from the COVID data, the segment is automatically chosen as "Population" and the coloring is discrete.  It does not make sense to encode the population as discrete as it is a continuous value.

**To Reproduce**
1. Go to test.admin.ch
2. Search for the "COVID19 Vaccinated Persons" dataset
3. Select scatterplot chart
4. Population is shown as segment but when you click on it, on the right panel it is shown "None"

**Comment by ptbrowne** [comment]
This is related to #430 as Population is a numerical dimension but for now I guess it is detected as NominalDimension.

**Comment by bprusinowski** [comment]
Closing, as this seems like a data issue (wrong data type / dimension type), and it seems that now Population is not selectable as a Segment anymore (see [here](https://int.visualize.admin.ch/en/create/new?cube=https://health.ld.admin.ch/foph/covid19/affected)).
