### ISSUE TITLE
Interactive Filters: Time range slider

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#513]
**Is your feature request related to a problem? Please describe.**
To address all the issues mentioned in #493 , #451 , #443 , #444 the handling of the time range filter should be aligned across all visualization types (charts & maps).

**Describe the solution you'd like**
The handling of the time range filter should be aligned across all visualization types. No matter if a time range has been applied in the X or Y Axis, the Time / Date should appear as a separate option /section in the Interactive Filters section on the left side bar if a time dimension is available in the data. We could even consider to add a play button below the slider to autoplay the development over time. (Autoplay could be an additional checkbox in the Time slider options in the right side bar). This should be available in all visualization types including maps (which is currently not the case)

**Describe alternatives you've considered**
None

**Usecases and impact**
Time plays an important role in visualizations, so it is important to make it very visible to the user. Alignment across all charts helps to avoid confusion

**Additional context**
<img width="1491" alt="date-filter-01" src="https://user-images.githubusercontent.com/59613691/164023973-f3d0794c-d479-4313-9fc9-f14f89c51660.png">

<img width="1489" alt="date-filter-02" src="https://user-images.githubusercontent.com/59613691/164026299-f0f035b0-3346-41f1-9755-0cfb87b809f0.png">

<img width="1504" alt="date-filter-03" src="https://user-images.githubusercontent.com/59613691/164023716-bf7a50cd-77ae-4f7a-b492-1cc12689fcfb.png">

**Comment by sosiology** [comment]
yep, agreed and closed
