### ISSUE TITLE
Interactive Filters: Confusing behaviour regarding timeline

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#520]
**Is your feature request related to a problem? Please describe.**
The timeslider in the right sidebar, when Interactive Filters are selected, is referring to the overall dataset, and not to the current filter selection, which leads to confusion as the timeslider in the rightsidebar is displaying different dates, than the timeslider below the chart.

**Describe the solution you'd like**
Make it clear to the user, what dates are actually selected. Currently not sure, what is the best solution here.

**Describe alternatives you've considered**
None

**Usecases and impact**
Understandable UI for the user

**Additional context**
![Screenshot 2022-04-26 at 10 38 30](https://user-images.githubusercontent.com/59613691/165259417-ad746d35-252c-4f5e-871c-9ea2f776202e.png)

https://user-images.githubusercontent.com/59613691/165259811-b460d5a4-94a9-4967-b0a5-db776d540b40.mov

**Comment by sosiology** [comment]
maybe we can also tackle this issue https://github.com/visualize-admin/visualization-tool/issues/182 when we investigate this?

**Comment by AnninaWalker** [comment]
See also #547
