### ISSUE TITLE
Align `Download Data` Button across all Screens in the Application

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#521]
**Description**
On the data set selection screen the `Download data`is on the bottom right hand side of the table, whereas on all other screens in the chart creation workflow, including the published chart, the `Download data` button appears on the bottom left of the chart.

**Describe the solution you'd like**
To ensure continuity across the application, I would recommend aligning the position of the button across all screens.

**Screenshots**
![image](https://user-images.githubusercontent.com/29289679/165332315-08f77b50-7be8-4316-b004-897d86d525b6.png)
![image](https://user-images.githubus
![Screenshot 2022-04-26 at 17 08 39](https://user-images.githubusercontent.com/29289679/165332543-7e50f117-2fec-42a4-81fb-09a025b9ec29.png)
ercontent.com/29289679/165332347-107b3355-d8af-4eec-9d9c-29ff97a2f671.png)

**Comment by bprusinowski** [comment]
@AnninaWalker so the "Showing first 10 labels" text should be aligned to the right then? Or should the download data button be placed below this label?

**Comment by AnninaWalker** [comment]
@bprusinowski I would put the label to the right
