### ISSUE TITLE
Published Charts not Responsive/Rendered Correctly on Mobile

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#524]
**Describe the bug**
On mobile, the published chart is not centered in the view port (responsive)

**Actual behavior**
https://test.visualize.admin.ch/v/RXbybrdOfCO9
<img width="430" alt="image" src="https://user-images.githubusercontent.com/29289679/165527276-a44d7999-24ae-4f04-a091-058aedb8cb3c.png">

**Expected behavior**
https://visualize.admin.ch/en/v/2LOL8lbaWP_V
<img width="436" alt="image" src="https://user-images.githubusercontent.com/29289679/165527957-07eaf1ff-cd40-4803-ba90-e1655d90ec4b.png">

**Screenshots**

**Environment (please complete the following information):**
 - Visualize environment and version: Works as expected on PROD but not on TEST
 Tested in Browserstack with iOS, v15.4, Browser: Safari

**Additional context**

**Comment by ptbrowne** [comment]
Fixed in https://github.com/visualize-admin/visualization-tool/pull/530
