### ISSUE TITLE
choropleth color palette begin (white) misses contrast to background / basemap

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#538]
**Is your feature request related to a problem? Please describe.**
choropleth color palette begin (white) misses contrast to background / basemap

**Describe the solution you'd like**
A color palette not beginning in white but with a color contrasting the light basemap.

**Describe alternatives you've considered**
appearingly none

**Usecases and impact**
lowest values of maps don't have contrast to appear as a measurement

**Additional context**
![image](https://user-images.githubusercontent.com/26090254/166484452-0bdf1b0b-fbab-4bbc-85ba-46c60183b258.png)
https://test.visualize.admin.ch/de/v/uAhcqNB7it-d

@zellersabine @afoletti

**Comment by Rdataflow** [comment]
@ptbrowne cc @AnninaWalker

**Comment by AFoletti** [comment]
I am open to any solution, but it is true that this is an issue.
Today, I often pick the color ramp not because of the color itself, but looking for hte better contrast possible with the basemap. Which is kind of a pity :)

**Comment by ptbrowne** [comment]
@AFoletti Please tell us if the artificial clamping of the sequential color palette solves your problem. It is deployed on test.admin.ch.

**Comment by AFoletti** [comment]
Hello @ptbrowne 
Looks way better, many thanks!
