### ISSUE TITLE
No more Filter Information 

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#539]
**Describe the bug**
The information on the values selected in the filters has disappeared since we have the possibility to switch from one type of graph to another via the tab.

**To Reproduce**
1. Go to 'int.visualize.admin.ch'
2. Choose for exemple Dataset "State accounts - Office"
3. No information on filter selection above the graph. See Screenshot.
Is this intended? Perhaps I missed this decision.

**Expected behavior**
This information is essential for understanding the graph. In theory, it could be indicated in the description, but it is preferable that it be included automatically. 

**Screenshots**
INT :
![image](https://user-images.githubusercontent.com/79834090/166937013-4e2402da-61c7-4f37-a754-f88384b0550f.png)

PROD = Expected behavior 
![image](https://user-images.githubusercontent.com/79834090/166936783-78baa002-1331-4d8b-812a-f1a5f8b1fa08.png)

**Environment (please complete the following information):**
 - Visualize environment and version: v3.6.3 ([7957aad]
 - Browser and version [Edge]

**Comment by AnninaWalker** [comment]
Dear @ortnever Thanks for reporting. No this is not intended. The information should still be available below the title. @ptbrowne Can we add this information again, please.
