### ISSUE TITLE
Data download : Unit not exported

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#544]
**Describe the bug**
This is not really a bug but by Data Download, the unit is not included in the column title. I think it's important that this information is included in the exported file.

**Expected behavior**
Add unit in paranthesis next to the column title in the downloaded File.

**Screenshots**

![image](https://user-images.githubusercontent.com/79834090/167617399-129b188e-b8e1-433c-a908-f0dc4fe31d9d.png)

![image](https://user-images.githubusercontent.com/79834090/167617333-b5191172-4d85-4cab-a0cc-66d74d452a5e.png)

**Environment (please complete the following information):**
 - Visualize environment and version: 
 - Browser : Edge

**Comment by ptbrowne** [comment]
I put this as enhancement @ortnever as I do not think it was ever discussed. I am taking a look.
