### ISSUE TITLE
The horizontal axis is not correctly filtered when the data source is already restricted

### ISSUE THREAD

**Issue by PDumasBAR** [visualize-admin/visualization-tool#547]
**Describe the bug**
If, in step 1 of the visualization, the values (years) on the X-axis is limited :

![image](https://user-images.githubusercontent.com/35593772/167633532-70a86657-c99c-454d-8e7b-a1a746ed4513.png)

In step 2, the X-axis default setting displays inconsistent values :

![image](https://user-images.githubusercontent.com/35593772/167636085-f35f3151-a789-4a39-b993-4e9a6bf87642.png)

**To Reproduce**
1. Select a dataset with a time dimension and start a visualization
2. Choose a chart type and select the time dimension as the X-Axis
3. Apply a limitation on the time dimension (on the right) and go to the next step
4. Enable the interactive filter on the time dimension and try to change the default setting on the X axis (on the right). It displays incorrect values.

**Expected behavior**
There is no confusion between the default setting or the X-Axis filter. Maybe it's better to have the default setting only in step 1 and interactiv filter only in step 2.

**Environment (please complete the following information):**
 - Visualize INT v3.6.4 [dc5a883]
 - Microsoft Edge Version 100.0.1185.44 (Official build) (64-bit)

**Comment by AnninaWalker** [comment]
Same issue reported here at #520
