### ISSUE TITLE
UX: chart -> show table -> show chart: jumps to page top

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#549]
**Describe the bug**
unexpected jump to page top ocurring on change back to `show chart`
occurs in editor as well as for published charts

**To Reproduce**
1. Go to https://test.visualize.admin.ch/en/v/lr5jcv-VTGIB
2. scroll down a bit to still see the chart
3. Click on 'switch to table view'
4. Click on 'switch to chart view'
5. See page jumping back to top

**Expected behavior**
stay at the current page position - same behaviour as when switching to `table view`

**Environment (please complete the following information):**
 - Visualize environment and version: [e.g. TEST & INT v3.6.4]

**Comment by Rdataflow** [comment]
LGTM in published view. still jumpy in editing view.

**Comment by ptbrowne** [comment]
Should be solved in published view now :) Please reopen if you see again the issue.
