### ISSUE TITLE
Feedback on new default Map style

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#553]
**Is your feature request related to a problem? Please describe.**
To continue the discussion on #537 . A new default Map style should be added, that is less disrupting. An initial style with greyscale has been created on MapTiler. We need to clarify how this can be used in terms of licensing @ptbrowne

**Comment by ptbrowne** [comment]
Thanks Annina, I've deployed the new grey style.

@RDataflow, we would pleased to have your feedback. Let's use this issue for this.

**Comment by bprusinowski** [comment]
Closing, as we now render data layers on top of base layer (which was also updated in the meantime).
