### ISSUE TITLE
Problems with the filter on a "yyyy-mm" time reference

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#564]
I have on test.visualize a new cube with a time reference of type yyyy-mm. In the creator cube I defined the scale of measure Intervall and the Data kind Time description + Time Precison : month. It seems to me that this is correct?
However the filter on the time reference does not work correctly in Visualize. I do not see all the dates.

**To Reproduce**
1. Go to 'test.visualize.admin.ch
2. Select German navigation (DE)
3. Search "Luftbelastung" 
4. Open dataset "Luftbelastung entlang der A2 und der A13 - Monatliche Mittelwerte - NO und NO2"
5. If you let "zeitliche Referenz" on the horizontal axis, the filter on the right side is displayed correctly. The only small thing is that the beginning of the scale is 2011 instead of 01.2011, but this is a detail.
![image](https://user-images.githubusercontent.com/79834090/169503157-793b3bfe-74e0-4c09-ba63-4a788f681693.png)
6. Now choose another dimension on the horizontal axis, for example "Schadstoffe".
The dimension "time reference" is displayed in the filters on the left, but you can only choose 2 values: 01.2011 and 02.2011
![image](https://user-images.githubusercontent.com/79834090/169500490-a5078f76-fe49-4c42-a76c-20dd7228eb68.png)

8. Change the type graphic on map
9. Same problem occures

**Expected behavior**
all available values of the dimension "zeitliche referenz" should be displayed in the drop down list.

**Screenshots**

**Environment (please complete the following information):**
 - test.visualize.admin.ch, v3.7.0 [d8c018a]
 - edge

**Additional context**

**Comment by ptbrowne** [comment]
It seems like the dataset need to be republished @ortnever, I cannot find it.

The problem seems similar to https://github.com/visualize-admin/visualization-tool/issues/498, I will take a look when the dataset is republished.

**Comment by ortnever** [comment]
Sorry @ptbrowne . It's published as Draft.
![image](https://user-images.githubusercontent.com/79834090/169773078-55ebbe95-480e-44a5-bc7d-548f9b6cfe4f.png)

**Comment by ptbrowne** [comment]
@ortnever Please tell us if it's working for you. If not I will re-open.

**Comment by ptbrowne** [comment]
It's still deploying.

**Comment by ortnever** [comment]
@ptbrowne Yes, it works. Thank you very much ! 
There is just a little detail in the Time-scala on the right side, but not really important (2011 instead 01.2011)

![image](https://user-images.githubusercontent.com/79834090/170021182-8e27f30a-af6d-4d99-bf8d-fe8092366577.png)

**Comment by ptbrowne** [comment]
Thank you Veronique, I've created a new issue to tackle the slider label detail, as I think the current implementation will work for the course and we will tackle this minor thing in the next sprint.

**Comment by ptbrowne** [comment]
It's deployed in production now.

**Comment by ortnever** [comment]
@ptbrowne : Oh thank you! I am very glad and hope we will publish the cube very soon in PROD. .
