### ISSUE TITLE
[No title] datasets

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#565]
I see 3 datasets on int with title "NO TITLE", what is the reason behind that ? cc @ortnever @fabiancretton ?

**Comment by FabianCretton** [comment]
@ptbrowne I do not know what are those 3 cubes. When clicking on them, in visualize, the GUI comes back to home.
Maybe from Michael ?

**Comment by ortnever** [comment]
I do not know what it is.

**Comment by ptbrowne** [comment]
I no longer see them on int.visualize.admin.ch, so closing.
