### ISSUE TITLE
Cascading filters in publishing mode

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#566]
This is probably an improvement and not a bug.
Currently cascading filters only work in edit mode.  Cascading filters should also work in publish mode if possible. To be discussed depending on the investment needed.

see Gitlab https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/511

**Comment by PDumasBAR** [comment]
If they are cascading, interactive filters must be sortable.
