### ISSUE TITLE
Home page test.visualize, new URLs for examples

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#567]
the urls of the examples of the home pages on test.visualize are broken since we had to republish the cubes.
Here is the new URL of the noise example:
https://test.visualize.admin.ch/fr/v/pLtlQN4Pe-OU (I prefer to publish only Draft Version on Lindas Int and Test)

@PDumasBAR, could you please add the URL of the other example here. THANK YOU!

**Comment by PDumasBAR** [comment]
Here the new URL of the Distribution of expenses and income by office: https://test.visualize.admin.ch/fr/v/nXl3EyjZY7qY
