### ISSUE TITLE
Format currency as .2f

### ISSUE THREAD

**Issue by AFoletti** [visualize-admin/visualization-tool#569]
**Is your feature request related to a problem? Please describe.**
When storing a number in the triple store, trailing zeroes in the decimals are truncated (ex: 10.50 becomes 10.5).
While this makes very much sense in general, there are situations where you want to show a very specific number of decimals (specifically when using currencies).
[Example](https://test.visualize.admin.ch/de/v/I9X2w6D2NdaK)

**Describe the solution you'd like**
When displaying a currency, it would be nice to have trailing zeroes added to show cents. Example, 10.5 CHF should show as 10.50.
I would like for visualize to check if the number is a currency and display it in a **.2f** format

**Describe alternatives you've considered**
This may look like a minor change, but we truly are not used to see currencies truncated and it really looks strange in visualize. It may stay as it is without impacting functionality or correctness in any way, but it remains a nice visual improvement nevertheless.

**Comment by sosiology** [comment]
Gitlab Issue: 
- https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/361

**Comment by ptbrowne** [comment]
@l00mi What would be the way to detect a currency dimension ? I searched for "currency" inside the cube.link documentation but could not see anything.

**Comment by l00mi** [comment]
That would be if [qudt:unit](https://cube.link/#qudt-unit) uses a currency e.g. https://qudt.org/vocab/unit/SwissFranc, which has the property qudt:hasQuantityKind which is https://qudt.org/vocab/quantitykind/Currency.

**Comment by ptbrowne** [comment]
Fixed in https://github.com/visualize-admin/visualization-tool/pull/653
