### ISSUE TITLE
Hierarchies - Bathing water quality : no label or no entrie for some stations

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#584]
Some station labels are not displayed in the preview table. Example: CH11005 Solothurn (BAQUA SO), CH19006 Badi Tennwil (BAQUA_AG) etc.
The same stations do not appear in the left filter either. They appear with label  in the hierarchical tree but without color.
Notice that all observation sites appear correctly in the shared dimension and are mapped in the Cube Creator, except 5 stations which could not be mapped in the Cube Creator: CH21098 to CH211002.

**To Reproduce**

1. Open test.visualize.admin.ch
2. Search  "Bathing water quality" (Include draft datasets)
3. No label in the preview table for some stations, e.g. CH11005 (Solothurn), CH19006 (Badi Tenwil, CH17028 (Strandabd Stampf, Zürichsee)
4. Start a visualization
5. The station does not appear in the drop list of the filter of the dimension "Observation location" on the left.
6. Choose "Observation Location" as "color".
7. The station 11005 Solothurn appears correctly under BAQUA_SO in the hierarchical tree but has no color (value)
**Screenshots**
![image](https://user-images.githubusercontent.com/79834090/173355107-2dba1acd-fad8-405f-a639-0586178737b7.png)
![image](https://user-images.githubusercontent.com/79834090/173355675-35ae7e48-2b65-4c05-9113-3c0b460f6046.png)
![image](https://user-images.githubusercontent.com/79834090/173359736-d3f8284d-09c5-4bc2-b5d6-33f10b3739b0.png)

**Environment (please complete the following information):**
 - Visualize environment : TEST v3.7.5 ([3b8fc7e]

**Comment by ptbrowne** [comment]
@l00mi When I look at the unique values inside the cube, it seems to me that some of the stations are not mapped to a hierarchical concept, leading to some stations not having a correct label.

See https://s.zazuko.com/8xiAoX , I think there might be something to fix there.

In the meantime, I will make it so that hierarchical values that are being showed are only the ones that are in the data.

**Comment by ortnever** [comment]
...and some observation sites do not appear in the hierarchical tree at all. For example, all sites of the monitoring programmes Baqua AG and Baqua BE.

**Comment by l00mi** [comment]
## Missing BE AG
@ortnever this were not in the initial dataset which i used to build the hierarchies. Would you mind to add these manually?

## Missing entries (not linked once)
I just fixed the before missing stations in the Shared Dimension. But that said it might always also have strings (Not concepts) of missing data. Ideally in this case they would be still shown, but with the strings.

Finally the overall approach I would imagine is, collect all stations (in this example), which can be found in the hierarchy get added to the hierarchy tree in the widget. All other, not in the hierarchy present concepts get added to the end as a simple list of the widget. Potentially with a small divider in-between. (We will almost never have perfect data, so we will need to show also special cases.) I understand that this might be out-of-scope for this project phase.

**Comment by ortnever** [comment]
No, I could not add BAQUA AG and BAQUA BE. I do not really know how I have to proceed. I cannot open the Dynamic propierties. 
Concerning the mapping with Swisstopo Layer:
- 3 weeks ago  the data provider sent an updated of the Geo layer incuded the data 2021.
- the station names are all correct in this new layer and it contains the 5 missing stations.
- I imported the new data in PROD. You can use them to replace the csv of the cube with Hierarchies in INT if you need.

![image](https://user-images.githubusercontent.com/79834090/177803000-98ba8e5b-63a8-4870-a321-f995412f7a18.png)
