### ISSUE TITLE
Standard Error visualization for missing errors

### ISSUE THREAD

**Issue by kronmar** [visualize-admin/visualization-tool#589]
Currently in the bar plots, if the standard error for some observation/measurement is given as as "null" (i.e. no standard error is given), the error bar is displayed as a thick line width height zero.

This should not happen as it implies that an error was provided (hovering over the observation clears this by providing the real error, meaning "x [unit] +/- null [unit]"). Instead, no visualization of this error should be plotted.

![image](https://user-images.githubusercontent.com/95312586/177784930-8b5c61cc-16a6-41ef-a2b1-ced6f2d424b5.png)

**Comment by lloydrichards** [comment]
An example of a dataset would be [NFI: Topics by forest type and stage of development](https://opendata.swiss/en/perma/nfi_C-501%40bundesamt-fur-umwelt-bafu)

**Comment by kronmar** [comment]
Oh this is a bit of an older issue, I no longer had on my radar... 

But maybe to help with it, here is a concrete case where such a thing would happen: [https://visualize.admin.ch/en/v/lKB-Vc3eRFwg](https://visualize.admin.ch/en/v/lKB-Vc3eRFwg)
