### ISSUE TITLE
Maps hierarchy implementation doesn't rely on actual hierarchies from the data

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#596]
**Describe the bug**
The hierarchy implementation doesn't rely on the hierarchies according to the data (as fetchable with cube-hierarchy-query)

**To Reproduce**
1. Go to https://test.visualize.admin.ch/create/new?cube=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-19-None-None%2Fcube%2F1
2. Select *map*
3. Select *areas*
4. Open *hierarchy level* drop down (right)
5. See error: missing values

**Expected behavior**
for this dataset two levels are expected.
1. Switzerland [parent]
2. Production region [children]

**Screenshots**
![image](https://user-images.githubusercontent.com/26090254/179955580-ddaabef8-7db1-4eb3-8095-794ee5aa61f8.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.7.5

cc @kronmar

**Comment by ptbrowne** [comment]
Fixed, now we do not show the "Hierarchie-Ebene" dropdown, as we only use the filters. I still have to see how to properly select only the bottomest layers.

**Comment by AnninaWalker** [comment]
@ptbrowne What I find a bit irritating here is that the "Schweiz is listed separately above the summary "Schweiz", Its now shown twice. Any way to avoid this? In this case it's a bit unfortunate



![Image](https://user-images.githubusercontent.com/59613691/186107204-24568c52-fcaf-4bfb-b1e6-1944a314ea63.png)



![Image](https://user-images.githubusercontent.com/59613691/186107270-f43b4e44-314d-4cb8-bdf6-08152feab440.png)

**Comment by ptbrowne** [comment]
@AnninaWalker Since we agreed this was not blocking, could you move your comment to a [new discussion](https://github.com/visualize-admin/visualization-tool/discussions) ? This way, we will not forget about this.

**Comment by AnninaWalker** [comment]
@ptbrowne Created a new issue here: https://github.com/visualize-admin/visualization-tool/issues/659
