### ISSUE TITLE
Show link to further information "dcat:landingpage" on final graphic

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#599]
https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/351

**Comment by ptbrowne** [comment]
Closed with https://github.com/visualize-admin/visualization-tool/pull/607

**Comment by AnninaWalker** [comment]
According to the feedback in GitHub this link should only be shown in the published graphic, but I guess it is ok, to show it all the time. Please change style and size according to general component with link and Icon (see screenshot).
I'd also change the naming. Something like "more information about the data" I'm sure @sosiology has a better suggestion.

![Image](https://user-images.githubusercontent.com/59613691/186104687-904e9106-a24c-4309-bcc7-e9df2ce6cf84.png)

**Comment by ptbrowne** [comment]
> According to the feedback in GitHub this link should only be shown in the published graphic, but I guess it is ok, to show it all the time.

For now, this is the same component that is used in the editor and in the published view. As I understood, the initial rationale was to show the user in the editor always what was going to be published.

Concerning the styling, something like this :

<img width="629" alt="image" src="https://user-images.githubusercontent.com/465582/186105981-2fb5635c-73ae-408b-8920-0e14c27a88e2.png">

**Comment by AnninaWalker** [comment]
Yes, I would only change the order and have probably: Download, Switch to Table view, Learn more.. and then the RUN SPARQL. Or the learn more about the dataset at the very end

**Comment by sosiology** [comment]
Wording LGTM! thanks @AnninaWalker and @ptbrowne

**Comment by ptbrowne** [comment]
Fixed in #662
