### ISSUE TITLE
Hierarchies: Enhancements incl. nested levels

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#604]
Gitlab Issue: 
- https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/367

- [x] Show hierarchies inside left filters  
- [x] Show hierarchies inside legend
- [x] Select only leaves as the default when segmenting to avoid 200% problem (see Gitlab issue)
- [x] Fix hierarchies in maps #596

**Comment by ptbrowne** [comment]
For me the majority of this issues has been done.

**Comment by ptbrowne** [comment]
Yes you're right, this task was already big and I think it would be better to split those improvements out of the main improvements of the hierarchies. I had kept it in my head though but thanks for reminding me, I am creating a new issue to track this.

**Comment by ptbrowne** [comment]
I created this https://github.com/visualize-admin/visualization-tool/issues/643

**Comment by AnninaWalker** [comment]
OK
