### ISSUE TITLE
Basemap on INT & PROD not displayed

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#621]
**Describe the bug**
on INT and PROD the basemap is not displayed.

**To Reproduce**
1. Go to https://visualize.admin.ch/v/RHM-yJOzXvrM
2. See missing basemap

**Expected behavior**
basemap shown

**Screenshots**
![image](https://user-images.githubusercontent.com/26090254/184836041-33449da5-5cfe-49f1-8a18-55eb5661c6e2.png)

**Environment (please complete the following information):**
 - Visualize environment and version: PROD v3.7.5 [85588c6]

does visualize use the swisstopo vector tiles endpoint? if that's no longer the case, why?

cc @afoletti

**Comment by ptbrowne** [comment]
For the basemap we use maptiler and the configuration was not correct in int / prod (we had no data with maps previously). It should be OK now in int. We will deploy next week in production and this will fix the problem, is that OK for you ?

**Comment by sosiology** [comment]
Basemap shows on Test, but will need to be retested once deployed to INT

**Comment by Rdataflow** [comment]
@ptbrowne LGTM on INT now https://int.visualize.admin.ch/v/W53kaLGl1kgT - thus ready to deploy this configuration on PROD...
