### ISSUE TITLE
Map + Hierarchy: By default, select the bottom layers if there is a hierarchy

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#629]
By default we want only the bottomest layers of a hierarchy to be selected. Right now, the selection of those values is done in the reducer, at a place where we do not have information on the hierarchy. We need to find a way to first pass the hierarchy infromation to the reducer, then to select only the bottomest leaves.

>  As a user, I'd like to have an initial map view presented with all the bottommost children of a geographic hierarchy to get a good first overview without any additional interaction.
> 
> reason: for areas overlapping parents would block the view to the children while for points it would not make much sense.

https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/367

**Comment by ptbrowne** [comment]
CC @rdataflow, I track this issue separately from the general hierarchy improvements as this is bit trickier to handle with the current status of the code.

**Comment by ptbrowne** [comment]
Fixed in https://github.com/visualize-admin/visualization-tool/pull/650

**Comment by ptbrowne** [comment]
Ah it seems that if we select map too fast, all the regions are selected.

**Comment by ptbrowne** [comment]
Fixed in #663

**Comment by sosiology** [comment]
@ptbrowne thanks for looking into the reported issue. LGTM
