### ISSUE TITLE
"Öffentliche Ausgaben TEST 3" dataset do not appear in the dataset search

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#639]
**Describe the bug**
One dataset from lindas INT seems invisible in the dataset search.
The name: Öffentliche Ausgaben TEST 3
The cube: https://int.cube-creator.lindas.admin.ch/app/cube-projects/cube-project!!fab-offentliche-ausgaben-test3-05mgyvomygx/publication/jobs/cube-project!!fab-offentliche-ausgaben-test3-05mgyvomygx!!jobs!!eotGMON0JSN_95DwJ9k6o

One existing visualization based on that cube: https://test.visualize.admin.ch/en/v/TuaEE4zT6rQT?dataSource=Int

**To Reproduce**
1. Go to 'https://test.visualize.admin.ch/browse?dataSource=Int'
2. Select the Drafts as well
3. Enter "Ausgaben" for the german search
4. There are some results, but no "Öffentliche Ausgaben TEST 3"

Remark: without doing a search by keywords, and selecting all datasets from BAFU, the cube is also invisible

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.7.7, with Datenquelle INT

**Comment by FabianCretton** [comment]
@ptbrowne I did re-publish the cube (from Cube Creator), and it appears now.
So you were certainly right that something was missing, I do not know the details, but we can close this issue

**Comment by FabianCretton** [comment]
Hello @ptbrowne, I add a new comment to this closed issue, as I do not know if it is related.
Today, my cube "Öffentliche Ausgaben TEST 3" no more appears in Visualize.
It was there before, and was not re-published lately (last publication 22.08)
Testing the cube here says it is correct:
https://test.visualize.admin.ch/fr/_cube-checker?cubeIri=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_Offentliche_Ausgaben_test3%2F8&dataSource=Int

Do you have any idea of what is happening ?

**Comment by FabianCretton** [comment]
@ptbrowne That cube is back today, maybe you did correct something (i see the last commit yesterday afternoon), otherwise I do not know what happened.

**Comment by ptbrowne** [comment]
I did commit something ;) Thanks for your feedback, sorry for the bug :)
