### ISSUE TITLE
Implement latest improvements to side panel

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#643]
Implement the latest changes regarding the re-arrangement of the Color Palette and a different design for the Color Refresh.

![Image](https://user-images.githubusercontent.com/59613691/185962562-31ade080-a20b-4f7b-be41-20256ccf2fd8.png)

_Originally posted by @AnninaWalker in https://github.com/visualize-admin/visualization-tool/issues/604#issuecomment-1222538624_

**Comment by bprusinowski** [comment]
Closing, as we updated the panel (as design of the color refresh) in the meantime.
