### ISSUE TITLE
Dash instead Label for one category in Dataset "Greehouse gas emission by sector"

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#664]
A Label of the hierarchical dimension "Greenhouse gas emission sectors"is not displayed correctly in the "Edit view" (dash instead label, see Printscreen). In the "Published view" the label is displayed correctly.
https://test.visualize.admin.ch/en/v/_T5UYw7b-ZYX

The label is longer than the others. It is maybe the reason.

1. Open test.visualize.admin.ch with Int as datasource
2. search for "Emission" + "Include draft Datasets"
3. select "Greenhouse Gas Emissions by Sector"
4. start the visualization
5. Select the "Colors" axis
6. Select the "Sector" dimension
7. Select all categories
8. The label of the first category in the list is not displayed.

The label "International aviation (not included in total)" should be displayed instead of the dash.

test.visualize.admin.ch, v3.7.10 ([65188b5]. 
Browser : Edge

![image](https://user-images.githubusercontent.com/79834090/187203570-592e6b61-05e1-43cd-8a98-3de40e978c82.png)

**Comment by ptbrowne** [comment]
@tpluscode Seems like we have a minor issue with cube-hierarchy-query that ultimately leads to this : https://github.com/zazuko/cube-hierarchy-query/issues/11

**Comment by ptbrowne** [comment]
We still have a problem with this dataset

**Comment by tpluscode** [comment]
The fixed query does not work?

**Comment by ptbrowne** [comment]
This has been fixed in #689 , see https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fubd000501%2F10?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22greenhouse%22%7D&dataSource=Int
