### ISSUE TITLE
button <reset map> doesn't work on published maps

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#665]
**Describe the bug**

**To Reproduce**
1. go to published map on https://test.visualize.admin.ch/v/2q3Ny4iW-9Rm
2. rotate / tilt the map view
3. click on *reset map* button
4. ... oddly nothing happens

**Expected behavior**
reset to initial view

**Screenshots**
![image](https://user-images.githubusercontent.com/26090254/187408714-3d87a313-a638-4abf-9268-443dc55c9051.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.7.10 [e0c4c24]

cc @afoletti

**Comment by bprusinowski** [comment]
Thanks for raising this @Rdataflow, indeed we only reset the map to its initial position (x & y), not taking rotations into consideration. I will try to fix this in this sprint.

**Comment by ptbrowne** [comment]
@Rdataflow Is rotation+tilting a function that should be activated / deactivated completely on the maps ? Do you need rotation + tilting ?

**Comment by Rdataflow** [comment]
you may deactivate it, as currently there is no need for it 👍

**Comment by Rdataflow** [comment]
@bprusinowski tillt and rotate is still possible. RMB still allows to rotate and tilt.
observed today on https://test.visualize.admin.ch/v/bOkX-KXoEgsp?dataSource=Int
![image](https://user-images.githubusercontent.com/26090254/189870344-ee75900e-7271-4088-bcf1-7e2415e3dd07.png)

**Comment by bprusinowski** [comment]
Hi @Rdataflow, that's true, thanks for noticing! We did a bigger refactor of the map chart (code-wise) and I think it got lost along the way. I am disabling this feature right now.

**Comment by Rdataflow** [comment]
@bprusinowski well done 👍
