### ISSUE TITLE
very slow search if several keywords are entered

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#683]
The search takes more than one minute  if several keywords are entered. However, the result is good.
I had once an "error message" but I cannot reproduce it.

**To Reproduce**
1. Go to 'test.visualize.admin.ch', source:INT
2. Search "Emissions de gaz à effet de serre".
3. Result are displayed after 1 minute 20 sec.

Just for information, the print screen of the failed search. But it happened only once:
![image](https://user-images.githubusercontent.com/79834090/188919249-385fecb6-b851-403f-8336-8353b5335f10.png)

**Environment (please complete the following information):**
 - Visualize environment and version: v3.7.10 ([bfb9035]
 - Browser and version : Edge

**Comment by adintegra** [comment]
@ptbrowne what do you think about trying a pure SPARQL approach to the search, similar to what they have done [here](https://environment.ld.admin.ch/datasets/)? Something along [these lines](https://s.zazuko.com/4dc43F) maybe. 

It's a slightly blunter instrument and probably has some tradeoffs I'm missing right now, but curious to hear your thoughts.

**Comment by ptbrowne** [comment]
This is fixed via #726 .
