### ISSUE TITLE
Categories not displayed in the filters

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#687]
The left and right filters do not display all categories. 

1. open test.visualize.admin.ch, source: int
2. Search "Ausgaben" including drafts
3. Select "Öffentliche Ausgaben TEST 3".
4a. Select "Categories" on the colour axis
5a. Display all filters on the right side
or
4b. Leave the colour axis empty
5b. Select the category filter on the left side

Only the root Total and its children are displayed. Level 2 is missing.

**Expected behavior**
All categories and all levels should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/79834090/189052630-1f6ed892-10d8-426a-a1ef-e793a0c935ba.png)

![image](https://user-images.githubusercontent.com/79834090/189052786-532cf23d-94ad-4ce7-a439-ed327fcff099.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.7.10 ([bfb9035]
 - Browser and version : Edge

**Comment by ortnever** [comment]
For dataset "Greenhouse gas emissions" there are also problems with the filters but they are different: all categories appear but without labels and items cannot be selected.

![image](https://user-images.githubusercontent.com/79834090/189055675-6817481c-acdb-40e8-9837-6d7454a0a813.png)

**Comment by ptbrowne** [comment]
@ortnever Can you tell me if the problem persists I am not able to reproduce anymore those two bugs ? I think the 2nd was fixed through #689 but cannot reproduce the other problem. It may have been solve also by #689 .

**Comment by ortnever** [comment]
hi @ptbrowne , everything is fine now **on int.visualize.admin.ch.**

fyi : Now that we can choose the environment from int.visualize.admin.ch I will test from that environment using Lindas PROD data or Lindas INT data when there is no PROD dataset to test the feature in question, for example hierarchies.
