### ISSUE TITLE
Full precision must be dispayed with Decimal Datatype

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#690]
## Context
We would like to see the full precision of decimal/float datapoints within visualize expressed in scientific notation – either within the charts directly or when hovering over a datapoint.

## Current Behavior
Currently, the behaviour of the application is such that the full precision of the data coming from LINDAS is not displayed. Small values, in particular, are problematic, as they can be truncated to 0.

## Expected Behavior
The application should provide a means for the user to see the full precision of a datapoint – either in the chart display or, at least, in the tooltip for the datapoint.

Full precision must be dispayed for decimal numbers. It concerns table chart, mouse over, axis labels, other places? For export, already ok.

## Datasets
The dataset "Greenhouse gas emissions by sector and by gas (hierarchie Gas)" can be used as an example/ for testing. Select the Gas "Synthetic gas" and the sector "Sectors CO2 Ordinance". . - - 
- https://int.visualize.admin.ch/en/v/mDYTVQkRhvvU
- https://int.visualize.admin.ch/en/v/_vkg3ZVUnAZU

### References

- See also https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/361#note_8490 
- Corresponding GitLab Isssue: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/408

**Comment by sosiology** [comment]
Decision: Show full percision expressed as scientific notation. 
Example: https://www.covid19.admin.ch/en/epidemiologic/waste-water/d/development?wasteWaterFacility=427100&rel=abs
Also see comment in Gitlab. https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/408#note_8894
