### ISSUE TITLE
Search : Keyword + include Draft datasets

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#699]
When a keyword is entered in the search filed (without "return") and, in a second step, the "Include draft dataset" box is checked, the display is update but the result considers only the criterion "include draft datasets". 

Is it possible to consider the keyword when the chex box "incude draft" is activated without having to make the return?

**Comment by sosiology** [comment]
@ptbrowne tested on INT with INT data source - LGTM, thanks!
