### ISSUE TITLE
No data for the filter selection because of selected categories (7 by default)

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#700]
As only 7 categories are selected by default on the color axis, the risk is high of not having any data for the current filter selection. This is a pity, especially now that we have solved this problem with the cascading filters.

**To Reproduce**
1. int.visualize.admin.ch, source : PROD
2. Search and open "Soil pollution"
3. Choose "sampling period" on the x-axis
4. Choose "Site" on the color axis
5. Try several Filter combination for dimension "Heavy metal" and "Land use" 

![image](https://user-images.githubusercontent.com/79834090/189388028-aa8efbe7-f9df-4ce5-a513-8f5455a53dec.png)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Visualize environment and version: INT, source PROD, v3.7.11 ([ba2e668]
 - Browser : edge

**Comment by ptbrowne** [comment]
Fixed on dev, through #697
