### ISSUE TITLE
Scatter Plot: Same colour for different categories

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#71]
Scatter Plot : The colours for Male and Female are not differentiated on the graph. Ex. Example: Palmer Penguins
https://test.visualize.admin.ch/fr/create/Pz6yBMKXQMGO
Same colour on the graph for Male and Female categories.
![image](https://user-images.githubusercontent.com/79834090/116086247-e5c78080-a69f-11eb-9423-7551d972404c.png)

**Comment by herrstucki** [comment]
@ortnever This is fixed in the next deployment that goes live on dev.visualize.admin.ch (these take 15 – 20 minutes).
