### ISSUE TITLE
Implement currency formatting in chart elements

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#712]
Special handling of currencies is currently only used in table. It should be used in tooltips as well as in legend of other charts.

## To test

* [Öffentliche Ausgaben](https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_Offentliche_Ausgaben_test3%2F8?dataSource=Int)

The Mio CHF values should have no numbers after comma inside chart tooltips.

* [Foreign exchange rates](https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_foreign_exchange_rates_more_decimals_tests%2F3?previous=%7B%22type%22%3A%22theme%22%2C%22iri%22%3A%22https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Fcategory%2Ffinances%22%2C%22includeDrafts%22%3Atrue%2C%22order%22%3A%22TITLE_ASC%22%2C%22search%22%3A%22%22%7D&dataSource=Int)

The value CHF should be displayed with as many numbers after the comma as possible.

* [Einmalvergütung für Photovoltaikanlagen](https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd84_einmalverguetung_fuer_photovoltaikanlagen%2F13?previous=%7B%22includeDrafts%22%3Afalse%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22photovoltaik%22%7D&dataSource=Int)

The EIV Gesamtvergütung values should be displayed with 2 numbers after the comma.

## Related

Gitlab issue: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/361

**Comment by ptbrowne** [comment]
Closed in https://github.com/visualize-admin/visualization-tool/pull/704

**Comment by ptbrowne** [comment]
cc @afoletti @rdataflow, it is deployed on int.visualize.admin.ch.

**Comment by AFoletti** [comment]
Hey @ptbrowne 

Many tanks! Here my feedback:

- I did not find any problem with tests 1 and 2 so they looks OK to me
- for EIV (and Iguess for every map?) there is an issue with the legend, where it is not shown in .2f (see picture)
![image](https://user-images.githubusercontent.com/691243/190397142-a9f79b18-7480-44dd-a128-95b2fd24413b.png)

Side note: I get an error when I try to visualize the EIV data as _scatterplot_ or _pie chart_. I guess the data is not adapted to such plots, but the I should not get stuck with an inresponsive app.
![image](https://user-images.githubusercontent.com/691243/190397503-940460ba-6aec-4c32-8669-f98ab6c484df.png)

**Comment by sosiology** [comment]
@AFoletti Thank you for sharing your feedback. I created a [new issue](https://github.com/visualize-admin/visualization-tool/issues/719) for the error you mentioned in the side note. 
cc: @ptbrowne

**Comment by Rdataflow** [comment]
@ptbrowne I took a quick look at it: the 3 data sets behave exactly as expected 🎉

cc @sosiology
