### ISSUE TITLE
map containing hierarchies: by default parents are selected where they shouldn't

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#714]
**Describe the bug**

**To Reproduce**
1. Go to https://test.visualize.admin.ch/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2F49-19-None-None-44%2Fcube%2F1
2. Click on 'map'
3. See error: all regions are selected, where only the bottommost children should be...

**Expected behavior**
only the bottommost children should be selected by default

**Screenshots**
see screenshot: 
- the lake is cantonal territory - however by default only municipalities should be selected.
![image](https://user-images.githubusercontent.com/26090254/190395490-7a83d3ab-d9ef-48f7-8733-a1edd6b9bbef.png)

**Environment (please complete the following information):**
 - Visualize environment and version: v3.8.0 ([9b6863c](https://github.com/visualize-admin/visualization-tool/commit/9b6863cc990903bd81c2348d79484f78c1551915))
 - Browser and version [e.g. Chrome 95]

**Additional context**

**Comment by ptbrowne** [comment]
Mmh, it's weird I cannot reproduce your problem : I click on map and I have 5 / 6 values selected, Switzerland is not selected. Do you still have the problem.

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/465582/190627787-00bbb867-8640-48ee-aacf-68b0c7fdea17.png">

**Comment by Rdataflow** [comment]
true, I think it's related to the missing hierachy in dataset on #718
