### ISSUE TITLE
default filter setting: by topmost parent element (for hierarchies)

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#718]
**Describe the bug**
a data cube shall be filtered by the topmost parent element initially by default (in case hierarchy exists)

**To Reproduce**
1. Go to https://test.visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/fab_hierarchy_test12_switzerland_canton_municipality/3
2. See left filter at 'Zurich'

**Expected behavior**
the topmost parent 'Schweiz' (Switzerland) shall be selected as an initial default

**Screenshots**
![image](https://user-images.githubusercontent.com/26090254/190450927-7c41654e-d1b0-421d-ae28-433f78a142c4.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST 3.8.0
 - Browser and version [e.g. Chrome 95]

**Comment by ptbrowne** [comment]
Does this dimension have a hierarchy ? I could not see Switzerland when using this dimension as a color and when I check here : https://s.zazuko.com/aFuJs, I cannot see a hasHierarchy or inHierarchy predicate.

**Comment by Rdataflow** [comment]
@ptbrowne 💯 hierarchy was missing...
works as expected with hierarchy in: https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_hierarchy_test13_switzerland_canton_municipality
