### ISSUE TITLE
Display Year on x-Axis

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#72]
Lines Diagram : The x-axis "year" is displayed strangely (months between the years).
Example : 
![image](https://user-images.githubusercontent.com/79834090/116086877-93d32a80-a6a0-11eb-9e7c-74aac12f830b.png)

**Comment by herrstucki** [comment]
Although technically not wrong (time is continuous), I agree that this is confusing.

Implemenation note: we need to make use of the dimension's specified time interval. Alternatively, we can fall back on the datatype (if it's xsd:gYear or similar).

**Comment by l00mi** [comment]
Btw. with dataKind we have a way to hint what we expect the granularity to be in the data, if set I propose to use it as an override.

<img width="587" alt="Screenshot 2021-04-28 at 23 25 13" src="https://user-images.githubusercontent.com/502518/116474665-14e51a00-a879-11eb-8140-22812d3c9c87.png">
