### ISSUE TITLE
map doesn't load

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#722]
**Describe the bug**
map doesn't load

**To Reproduce**
1. Go to https://test.visualize.admin.ch/v/SUlonFeYMavu?dataSource=Int
2. See map doesn't load

**Expected behavior**
Show map as for same dataset w/o hierarchy (https://test.visualize.admin.ch/v/oUxguf5fe1z5?dataSource=Int)

**Screenshots**
![image](https://user-images.githubusercontent.com/26090254/190626049-69e4b384-7ba7-4968-b950-dd17f683b15c.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.8.0
 - Browser and version [e.g. Chrome 95]

**Comment by sosiology** [comment]
@ptbrowne the map now loads as expected in both the editor and published view. However I noticed that if I add the symbol layer an application error is shown. Below the screenshot from the browser console


![Image](https://user-images.githubusercontent.com/29289679/196195717-4f58f3c4-85df-403f-bed3-3d890d780b96.png)
