### ISSUE TITLE
map: geographical offset

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#723]
**Describe the bug**
the regions on the map show a clear offset from the background layer

**To Reproduce**
1. Go to a map view
  - https://test.visualize.admin.ch/v/OxhY2quLz_sR?dataSource=Int
  - https://test.visualize.admin.ch/v/oUxguf5fe1z5?dataSource=Int
2. See map with offset

**Expected behavior**
all elements on the map to be aligned according to the WGS coordinates contained in the data

**Screenshots**
![image](https://user-images.githubusercontent.com/26090254/190627192-79749188-26d7-43b0-8062-dc2b514adb3c.png)
![image](https://user-images.githubusercontent.com/26090254/190627246-f9fb64c5-1c16-4a10-9a42-eaea324ad4ca.png)

**Environment (please complete the following information):**
 - Visualize environment and version: TEST v3.8.0 ([fe0b493](https://github.com/visualize-admin/visualization-tool/commit/fe0b493f0056276bf18f004f96b7132f5fc200b6))
 - Browser and version: Chromium Edge Version 105.0.1343.27 on Windows

**Additional context**

**Comment by ptbrowne** [comment]
Mmh this is unfortunate, I can only reproduce this bug in Edge on Windows, is this something that is new for you ? Do you usually test with this browser ?

**Comment by Rdataflow** [comment]
@ptbrowne yup, I always test with Edge. 
Interestingly it happens only on TEST while on AFAICT INT currently seems not affected for whatever reason...

**Comment by Rdataflow** [comment]
@ptbrowne still present in TEST 3.9.0 and also observed on INT 3.9.0 now.
needs to be bisected and fixed before releasing to PROD.

cc @sosiology

**Comment by Rdataflow** [comment]
@ptbrowne also happens with Edge 92.0 and even FF 91.8.0esr on other windows machines

cc @zellersabine @ortnever looks like a pretty nasty bug

**Comment by adintegra** [comment]
Not reproducible on Edge for Mac (v105.0.1343.42).

**Comment by Rdataflow** [comment]
@adintegra I assume Mac for some unknown reason behaves differently even after hard reload (Ctrl+F5) - right?

**Comment by sosiology** [comment]
Thanks for adding the feedback @Rdataflow !
