### ISSUE TITLE
search doesn't find datasets on 'Treibhausgasemissionen'

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#729]
**Describe the bug**

**To Reproduce**
1. Go to https://int.visualize.admin.ch/browse/organization/https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-umwelt-bafu?topic=https%3A%2F%2Fregister.ld.admin.ch%2Ffoen%2Ftheme%2F8&includeDrafts=true&search=Treibhausgasemissionen&order=SCORE&dataSource=Int
2. observe no data found

**Expected behavior**
find 2 datasets on 'Treibhausgasemissionen' as in https://int.visualize.admin.ch/browse/organization/https%3A%2F%2Fregister.ld.admin.ch%2Fopendataswiss%2Forg%2Fbundesamt-fur-umwelt-bafu?includeDrafts=true&topic=https%3A%2F%2Fregister.ld.admin.ch%2Ffoen%2Ftheme%2F8&dataSource=Int

cc @sosiology

**Comment by ptbrowne** [comment]
Fixed on int. Due to cubes not having description.
