### ISSUE TITLE
Inconsistencies in the number of results displayed by category

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#730]
The number of "draft" datasets shown per category in the left panel does not match the number of results displayed in the center panel. 

**To Reproduce**
1. open int.visualize.admin.ch
2. check the box "include draft datasets".
3. Click on a category in the left panel
4. Compare the number of results.

![image](https://user-images.githubusercontent.com/79834090/191467702-34635aa1-f2a8-4040-88da-8ca44535ff06.png)

![image](https://user-images.githubusercontent.com/79834090/191467844-41213b7a-f2db-44e9-9280-a77c789b6352.png)

 - Visualize environment and version: v3.9.2 ([3fc980f]
 - Browser and version : Edge 105.0.1343.27

**Comment by sosiology** [comment]
@ortnever we will try to tackle this issue this week, so it can be tested before we deploy to production next week.

**Comment by ptbrowne** [comment]
Fixed by https://github.com/visualize-admin/visualization-tool/pull/745

**Comment by sosiology** [comment]
@ortnever the bug has been resolved and can be reviewed and tested on int.visualize.admin.ch

**Comment by ortnever** [comment]
@sosiology @ptbrowne 
yes, everything is ok now. I think the search works very well now. Thank you very much for all enhancements.
