### ISSUE TITLE
map: geo offset in edit mode

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#731]
unfortunately the first map-offset fix only helped for published maps. the error ist still present in edit mode :-(
see also https://github.com/visualize-admin/visualization-tool/issues/723#issuecomment-1252302801

steps to reproduce: (in edit mode)
1. open url https://test.visualize.admin.ch/v/OxhY2quLz_sR?dataSource=Int
2. click copy & edit
3. (if necessary) hard reload (Ctrl+F5)
4. see offset

cc @ortnever

**Comment by ptbrowne** [comment]
This has been tackled in #743
