### ISSUE TITLE
Colored Map with Ordinal Scale Measure

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#734]
### User Story
As a user I would like to show a colored map from my ordinal scale measure (e.g. low, medium, high).\

### Definition of Done
Ordinal measures can be used as color mapping for map chart layers – with `schema:name` and `schema:description` appearing in the tooltip and colors that are pre-defined based on potential `schema:color`.

### Additional Info
* [Example dataset](https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ftest_ordinal_507%2F7)
* Take the following into account:
  * Sort order (i.e. severity) according to `schema:position`
  * Typical attributes shall be displayed on hovering (currently, NaNs see [example](https://test.visualize.admin.ch/en/v/AP2HkMGFzw8w))
    * `schema:name @lang`
    * `schema:description @lang`
  * For the corresponding table view `schema:name` will be enough (same as implemented already for nominal key dimensions in table view)
* Color of levels can differ case-by-case, i.e. danger case here [green, yellow and red](https://www.naturgefahren.ch) while non danger may select other colors

![image](https://user-images.githubusercontent.com/29289679/191741522-64d4e648-7c9a-4072-8513-ed223ea254c9.png)
![image](https://user-images.githubusercontent.com/29289679/191741557-537e7794-9472-4360-967f-6a67f59ed7e4.png)

**Comment by adintegra** [comment]
I couldn't pinpoint the problem exactly (yet), but somewhere when switching from ord1 to ord2 and back to ord1, it seems the filter states get out of sync with what is displayed on the map – at the latest, this is the case at about 0:50 in the video.



https://user-images.githubusercontent.com/6533245/197601655-db66cbe8-071b-4f1f-b64e-9580eab56a70.mp4

**Comment by bprusinowski** [comment]
Thanks again @adintegra for testing and catching this! I moved the issue to #803 and created a PR (#804) which should fix this.
