### ISSUE TITLE
Add hierarchies in interactive filters in publication mode

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#739]
Hierarchies are not identifiable in the interactive filters in publication mode.
See example : https://int.visualize.admin.ch/fr/v/Bmbh2c5f-T4F

The same layout should be applied in publication mode as in editing mode (left panel).

![image](https://user-images.githubusercontent.com/79834090/192292743-5374e35a-5fa4-4b79-a79a-f2c486c587fd.png)

![image](https://user-images.githubusercontent.com/79834090/192293008-c6a25571-d526-422f-9e88-7c858010d879.png)

**Environment (please complete the following information):**
 - Visualize environment and version: v3.9.2 ([3fc980f]
 - Browser and version : edge

**Comment by sosiology** [comment]
@ortnever after discussing this with the development team we estimate that it will take ca. 2-3 days of work to implement the hierarchies in the interactive filters of the published charts, and would propose tackling this enhancement in the next sprint. Would that work for you?
