### ISSUE TITLE
Search : different problems

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#740]
I published a dataset with Title "untitre" and   following "Categorie" and "Organisation", as Draft. 

![image](https://user-images.githubusercontent.com/79834090/192305554-67915050-6bdd-4d0a-bbe3-a3bbf301d8bc.png)

According to the documentation the search functionality includes these cube fields in its scope:

✅ Title: schema:name : ok
✅ Description: schema:description : ok
✅ Publisher: dcterms:publisher : ok
✅ Organisation label: dcterms:creator/schema:name : ok

⚠️ Theme label: dcat:theme/schema:name (tested with "Crime, criminal justice" and "Trade") 

- [ ] No result with "Trade"
-  1 result with "Crime" or "criminal justice" : ok

- [ ] If I search all drafts I do not find the dataset and the categories "Crime, criminal justice" and "Trade", as well as the Organisation "Swiss post" are not displayed in the left panel.

![image](https://user-images.githubusercontent.com/79834090/192307230-c8473ee5-f936-4ae1-b72b-92efe89ad920.png)

If I search "crime", I find the dataset and the categories "Crime, criminal justice" and "Trade" are displayed in the left panel.
![image](https://user-images.githubusercontent.com/79834090/192308252-36c9be46-4f5a-4b04-92e1-afdd2e38245f.png)

**Environment (please complete the following information):**
 - Visualize environment and version: v3.9.2 ([3fc980f]
 - Browser and version: Edge

**Comment by sosiology** [comment]
@ortnever we will try to tackle this issue this week, so it can be tested before we deploy to production next week.

**Comment by sosiology** [comment]
@ortnever the bug has been resolved and can be reviewed and tested on int.visualize.admin.ch
