### ISSUE TITLE
Bar/Pie Chart Missing Aggregation

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#758]
**Describe the enhancement**
Reported by Claudio also see: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/419:

As I was working with the EFK-Data-Toyset (EFK = Die Eidgenössische Finanzkontrolle, Federal Finance control), I found, that some diagrams are not properly displayed. If you look at the picture below, you see, that the first bar has 6 entries in the infographic pop-up. One as 16k for "Campaign X", one as 1k for "Campaign X", two times 1k for "Testpartei A" and two times 1k for "Testpartei B". The cursor is on the first bar on the left on "Firma A":
![image](https://user-images.githubusercontent.com/29289679/193789409-234ac961-ebdc-4bcb-b0c5-8e6f9878be02.png)
![image](https://user-images.githubusercontent.com/29289679/193789429-48006a12-dc06-45ee-b8fd-f6f08e796eee.png)
The information I try to convey with this Bar is: Company A ("Firma A") Has paid 17k to "Campaign X", 2k to "Testpartei A" and "Testpartei B". Now we have three problems:

1. The Amounts are not aggregated in the infobox.
1. The graphics are wrong. It seems to me, as if the last entry overwrites all other of the same group. That means, the Entry with 16k is graphically overwritten by the entry of 1k.
1. In the Pie chart problem 1 also occurs, but problem 2 on the other hand does not:
![image](https://user-images.githubusercontent.com/29289679/193789490-4f2ffc52-8fb2-4f5b-97ea-98d571f5d626.png)

Of these 3, number two is the most problematic. With this bug you could create misleading charts, which is not great if you want to publish official party transparancy data (:

link to the Visualize-Chart: https://test.visualize.admin.ch/en/create/DKER-mMyM4R6?dataSource=Int

**To Reproduce**
1. Go to 'https://test.visualize.admin.ch/en/create/VlP6n-UR5JdP?dataSource=Int`
2. Hover cursor on the first colum, Firma A
4. See error(s)

**Expected behavior**
From my point of view, which scratches only the surface, I see two path to possible solutions. 1) Graphically, stack the same groups on top of each other, same as data of two different groups would. 2) Create a kind of aggregate function like "groupy_by(horizontal Axis) %>% summarise(sum(money))" I feel, as if Visualize probably can't calculate complex functions like these. And 1) is probably not a very sustainable solution.

**Screenshots**

**Environment (please complete the following information):**
 - Visualize environment and version: [e.g. TEST v3.9.5 ([6063484](https://github.com/visualize-admin/visualization-tool/commit/60634847219602df66d80c0ad4045cb5d1673ff3)), Data Source: INT
 - Browser and version Chrome

**Additional context**

**Comment by Rdataflow** [comment]
seems like claudio got non-aggregated data. It might help to aggregate the data by the each of the `key dimensions` in order to get **uniquely defined observations** and thus useful charts :thumbsup: 

there is more information at https://github.com/zazuko/cube-creator/wiki/Context#key-dimension

@adintegra beware to stay in sync with zazuko on the cube concept and the **uniquely defined observations**

**Comment by bprusinowski** [comment]
Closing this issue, as the data was not prepared correctly in the Cube Creator in this example (and we do not want to support aggregations).
