### ISSUE TITLE
Show the date of the latest data update on chart

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#759]
- Design: See if it makes sense to have an info panel, with this information + values & dimension description
- Development: 1st add the information in the footnotes, then see if we need to make an info panel

**Comment by AnninaWalker** [comment]
I'd simply add the Status line next to the dataset with: Latest update (date & time)

Additionally we can put this information then also in the Meta Data Side Panel that we will tackle next.
![8 2 1_l_metadata](https://user-images.githubusercontent.com/59613691/195589306-3e96bc86-19f8-4282-889c-dfa7aff81fa3.png)

**Comment by ptbrowne** [comment]
What do you think of an additional line ? I think it would be easier to find the information.

Here the 06.08h is the time right ?

**Comment by ptbrowne** [comment]
What about the publication date ? Should it be there or only the modification date ?

**Comment by ptbrowne** [comment]
Should we also modify the chart preview, we only put the date published there ? I think it would be good to be coherent between the preview and the footnotes. Maybe we will tackle that with the metadata panel ?



![Image](https://user-images.githubusercontent.com/465582/195814668-f2a12c9e-c106-4bd4-9971-5ae60ec1e472.png)

**Comment by AnninaWalker** [comment]
Yes I agree. It makes sense to be coherent and then also add the Latest update to the Metadata Panel.

Regarding the lines. I agree that readability might be better if everything is on a separate line, but as we have more and more information added I decided to group the the dataset and Publication date on one line and the Source and Creator of the visualization on one line to avoid a big block of text.

**Comment by AnninaWalker** [comment]
And yes06.08h is the time stamp

**Comment by AnninaWalker** [comment]
@ptbrowne To better distinguish the information we could make the labels bold (see screenshot)

![Image](https://user-images.githubusercontent.com/59613691/196130244-09f0fded-5b76-4d0e-ab04-17435b5f76fe.png)

**Comment by ptbrowne** [comment]
I see this is the same "technique" as we use for the filters. I can implement this. My only comment would be if we could maybe swap the bold to the values instead of the labels (both for filters and metadata).
