### ISSUE TITLE
Enable Automatic Upgrading of Cube Versions

### ISSUE THREAD

**Issue by jstcki** [visualize-admin/visualization-tool#76]
Currently, a cube's version is locked to the one selected when the visualization was created.

The logic is already implemented in https://github.com/visualize-admin/visualization-tool/blob/6d72bb37deb55fcbe3f6da4ce246a1bb71284366/app/rdf/queries.ts#L96-L162

It is disabled because this functionality depends on #75 to work (otherwise versioned dimension values are used as filters which will break newer cubes). See https://github.com/zazuko/cube-creator/issues/658

**Comment by herrstucki** [comment]
Also concerns list of cubes, see https://github.com/zazuko/cube-creator/wiki/3.-Publication#different-publication-statuses-published--draft

**Comment by herrstucki** [comment]
Consider showing the used cube version in the published graphic (where?)
