### ISSUE TITLE
Use shacl:order as hint for the order in the Table preview.

### ISSUE THREAD

**Issue by l00mi** [visualize-admin/visualization-tool#78]
From a Use Case of WSL (which creates cubes manually) we have added a field to specify the Order of dimensions for visualisation purposes, see https://github.com/zazuko/rdf-cube-schema#shapes (at the end).

At the time of writing the label can not yet be added in the cube-creator, and the feature is in the backlog https://github.com/zazuko/cube-creator/issues/700.

### Example

For the cube "forest area by production region and stand structure", the order of column should be as follow:

The order of column should be as follows :

1. Inventory
2. production region
3. stand structure
4. unit of evaluation
5. forest area (ha)
6. Standard error (SE) of estimate (%)
7. grid
8 evaluation type

- [x] Dataset preview
- [x] Table chart (left "Columns" and middle table)

**Comment by Rdataflow** [comment]
see https://zazuko.github.io/rdf-cube-schema/#sh-order
> The sh:order can be used to indicate the relative order of the dimension, for use in visualizations. It should be used according to [the specification](https://www.w3.org/TR/shacl/#order) by using ascending order, for example, so that properties with smaller order are placed above (or to the left) of properties with a larger order.

**Comment by sosiology** [comment]
Issue in Gitlab: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/384

Related to: https://github.com/visualize-admin/visualization-tool/issues/312
