### ISSUE TITLE
"automatic" color modification when editing a visualization

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#781]
**Describe the bug**
When editing an existing visualization (button "Copier et éditer cette visualisation"), and then when clicking on the "Couleur" parameter, once the filters are uploaded the colors change

**To Reproduce**
1. Open one of those 2 visualizations:
https://test.visualize.admin.ch/fr/v/3cbX1vtyQtQQ?dataSource=Test
https://test.visualize.admin.ch/fr/v/CutNfGjCNnpq?dataSource=Test
2. Click on "Copier et éditer cette visualisation"
3. Click on the left on "Couleur"
4. The colors change once the filters are uploaded

**Environment (please complete the following information):**
 - Visualize TEST v3.9.6
 - Browser Firefox 105.0.3

**Comment by bprusinowski** [comment]
Hi @FabianCretton, thanks for reporting! This should be fixed once we merge #778.
