### ISSUE TITLE
Crash of the map when activating symbol layer

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#788]
@ptbrowne the map now loads as expected in both the editor and published view. However I noticed that if I add the symbol layer an application error is shown. Below the screenshot from the browser console

![Image](https://user-images.githubusercontent.com/29289679/196195717-4f58f3c4-85df-403f-bed3-3d890d780b96.png)

_Originally posted by @sosiology in https://github.com/visualize-admin/visualization-tool/issues/722#issuecomment-1280900855_

**Comment by ptbrowne** [comment]
@bprusinowski I suspect this might be caused by the new enhancements on the ordinal handling for maps ? Can you take a look ?

**Comment by bprusinowski** [comment]
I'll take a look :)

**Comment by bprusinowski** [comment]
@sosiology do you remember how to reproduce this error? I copied the visualization, added a symbol layer (and changed color dimensions to see if all options work) and I can't reproduce the error.

**Comment by ptbrowne** [comment]
I could reproduce the error. I am taking a look.
