### ISSUE TITLE
Implement a 1st version of the metadata panel

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#801]
Improve metadata viewing and put the information inside a panel.

https://www.notion.so/interactivethings/Metadata-Design-iteration-02-New-Layout-18f7b50f05714dbeae7222e370c23ac4

## 1st step

- Implement a side panel
- Add all the dimension description with their icons
- Implement the "routing" inside the panel, with animation
- Implement the "jump to" inside dimension descriptions (currently shown as search in mockups)

## 2nd step

- Add fetching of dimension values' description
- Show dimension values description
- Implement highlighting inside search
- Use "routing" to make "metadata panel links" that open the metadata panel at the right place (maybe only with a Metadata context here, not saving things in configurator-state)
-  Should work in both publisher mode and edit mode (so no configurator state), so at this point MetadataPanelContext seems the way to go.

**Comment by bprusinowski** [comment]
Some of the points were transferred to #917.
