### ISSUE TITLE
New User Interface, search + preview

### ISSUE THREAD

**Issue by bprusinowski** [visualize-admin/visualization-tool#817]
Linked to [GitLab Issue 425](https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/425)

See mockup here https://www.notion.so/interactivethings/V02-Presented-to-client-3d7f120f4c56477f9a51fe66f5112bc4

## Search

- Cosmetics, banner

## Dataset preview

- Page is widened
- Metadata looks like a panel
- Table sides have transparency gradients

**Comment by sosiology** [comment]
@bprusinowski thanks for preparing! I added some of my observations below. 

cc: @AnninaWalker 

**1. The lines between the datasets should not go all the way to the edge (based on the design in notion)**


![Image](https://user-images.githubusercontent.com/29289679/200315430-3276a772-44b4-40ca-b8d9-b0c87528136e.png)

**2. The search bar is not aligned with the datasets when browser window is minimized as is currently the case (on PROD)**

New UI:
![Image](https://user-images.githubusercontent.com/29289679/200315543-0d45a875-70e3-4542-a4e2-c6bf8bbfece9.png)


Current UI:
![Image](https://user-images.githubusercontent.com/29289679/200315612-ea922133-5bf4-4e35-bf73-4ae7e7648730.png)

**3. Placeholder Text is different. In the new UI we have "Search" in the old UI we have "Name, description, organization, theme, keyword"**

New UI:


![Image](https://user-images.githubusercontent.com/29289679/200315976-2563246f-d704-4394-93dc-2606276e84ef.png)


Current UI:


![Image](https://user-images.githubusercontent.com/29289679/200315935-c39001c1-6316-492e-8181-ca666df5d2a9.png)


**4. "Sort by" Dropdown**
- The text "Sort by" appears to be a different font size than the font of the text in the dropdown
![Image](https://user-images.githubusercontent.com/29289679/200316722-1bed0cd1-7163-4ab0-a9c0-a70d9dfa3848.png)
- The distance between the "Sort by Newest" and the arrow for the dropdown seem a bit far apart. I would expect the distance to be the same as the distance between the check box and the text "include draft datasets"

![Image](https://user-images.githubusercontent.com/29289679/200317096-82a39f48-493b-45cc-97cd-18dc7239d68a.png)
Also see design file:


![Image](https://user-images.githubusercontent.com/29289679/200317236-4231dda9-792d-4014-a6fd-f0bf3c08fd0f.png)


**5. Adjust icons to match design**

![Image](https://user-images.githubusercontent.com/29289679/200318079-4c566447-f496-415a-b10c-2a64f777e733.png)

**Comment by bprusinowski** [comment]
Thanks @sosiology for reviewing 💯  🙇 

1. This was kind of a conscious decision, as otherwise we would end up with something like this when hovering over a dataset:

<img width="1148" alt="Screenshot 2022-11-07 at 14 46 10" src="https://user-images.githubusercontent.com/52032047/200325771-0dd43176-e768-47ad-8bbb-c019f0cf2d91.png">

2. I improved this in #828 🙇 
3. I relied on the design here, but the translations for old placeholder were not removed; I can bring them back quickly :)
4. I think the font appears differently because it has different weight (and Newest starts with a capital letter), but I've checked and they have the same font and size. For the arrow, it's there because "Relevance" option takes more space than the default "Newest" – arrow placement depends on the longest item inside the select. But I could try to make it dynamic 😄 
5. Also fixed in #828 👌

**Comment by AnninaWalker** [comment]
1. Hmm I'm not really a fan of having the lines to go through to the edge. I think it this case it might be better to change the style of the Hover effect. Maybe on hover we make the title bold and do not make use of change of the background color. I think that would look a lot smoother.

2. LGTM now 👍 

3. Yes sorry for the confusion. I just had search in my design, but we can take over the ones from the previous deployment 

4. Font LGTM but it would be nice if you could have the arrow dynamic. The distance should be always the same and the whole element should be right aligned

5. LGTM in the fixed version 👍

**Comment by bprusinowski** [comment]
Thanks @AnninaWalker for the review, I'll introduce the changes 🙇
