### ISSUE TITLE
Replace examples on home page

### ISSUE THREAD

**Issue by herrstucki** [visualize-admin/visualization-tool#82]
Currently, the home page example charts are not working. We need to replace them with new ones, ideally with static data, so they don't depend on live cubes.

**Comment by bprusinowski** [comment]
Hi @ortnever, unfortunately the first two examples don't work ("Keine Daten") – could you take a look at this?

Or should we create the examples ourselves based on the data from these cubes?

![Screenshot 2021-10-19 at 13 10 43](https://user-images.githubusercontent.com/52032047/137898776-899a1ba8-09db-471f-872f-ff4adb2484f1.png)

I came up with these examples (tried to match the data shown on the chart with descriptions provided in the examples), but I'm not sure if they are fine with you.

I would appreciate it if you could guide me into a correct direction. Thanks!

**Comment by ortnever** [comment]
Here the URLs for the examples on the homePage. 
I admit that the graphs are not really nice but they make sense. We will replace them with more attractive graphics when we have more cubes published.
If there is a problem, just tell me. 
https://test.visualize.admin.ch/en/v/CrTq9JmpiXt-
https://test.visualize.admin.ch/de/v/8MrC1M0sFrd1

**Comment by bprusinowski** [comment]
Hi @ortnever,

thank you for providing new examples! The second one works, but unfortunately this is what is being displayed when I open the first link:

<img width="1440" alt="Screenshot 2021-11-04 at 16 40 08" src="https://user-images.githubusercontent.com/52032047/140363247-d54a435b-c5f6-4ab3-942d-1c005600183e.png">

Could you take a look at this?

After creating a new chart based on this example and playing around with the filters, some data showed up, but I am not sure what was your vision for the chart there.

<img width="770" alt="Screenshot 2021-11-04 at 16 41 26" src="https://user-images.githubusercontent.com/52032047/140364306-8ec9bb00-bfaf-4b40-a950-89c4bd9db709.png">

**Comment by ortnever** [comment]
once again, the URLs for the first example.
https://test.visualize.admin.ch/en/v/fq-xjBXGpxgg
I don't know why the link created yesterday no longer shows the data today. Maybe it's because I created a new version? Strange. I'll try to do some tests about that.

**Comment by ortnever** [comment]
with "created a new Version" I mean I published a new Version of the cube 1 hour ago. But normaly, the "old" URLs should work and display the new Version of the Cube..

**Comment by ortnever** [comment]
Another example from Pierre for the homepage. Maybe instead of Bodenbelastung, so there are no two bar charts.
https://test.visualize.admin.ch/de/v/scBBn-4e4o3p
