### ISSUE TITLE
Some dataset don't work in the Table Chart Mode

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#838]
The following two example datasets don't work when I try to apply the Table Chart Type. 
I get an error message, that the data couldn't be loaded.

It works when I apply another Chart Type as for ex. Bar Charts.

        
      https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ftobias_holz_beschaffung_institutionell_test%2F2?dataSource=Int

        
      https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ftobias_holzernte_m3_version3%2F3?dataSource=Int

**Comment by ptbrowne** [comment]
What is the context of those datasets, do you know of anything that could be peculiar about them ?

**Comment by AnninaWalker** [comment]
Yes these two datasets where provided to me as example datasets for the pivot table. See https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/300

I wanted to see how they currently perform as tables and noticed that they don't work

**Comment by AnninaWalker** [comment]
It has therefore not a priority. I can work around it, but just thought we should look into it at one point

**Comment by bprusinowski** [comment]
Related to #457?

**Comment by sosiology** [comment]
In sprint 4.5 @bprusinowski will check in Cube Creator to see how large the data set is.
