### ISSUE TITLE
Show hierarchy as tree in Select (interactive filter and left filter)

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#840]
#Right now, hierarchies in selects are shown as "flat" hierarchies with list sub headers. It should be shown as a tree. The branch "feat/hierarchy-tree-select" is in draft and contains an implementation of the menu + tree (select-tree.tsx), it's in WIP right now.

Design: https://www.notion.so/interactivethings/V04-Indent-and-new-UI-844455727a2b421ca00e0309c3a25957#31e6722b846d4b4cb5eb6f0665648ee8
Behavior: https://codesandbox.io/s/filesystemnavigator-demo-material-ui-forked-r273pw?file=/demo.tsx

**Comment by AnninaWalker** [comment]
@ptbrowne Could we also implement the search box above the Hierarchy as we have it in the Menu Panel in the Editor? I think that would be very useful, especially if we have a large tree

**Comment by ptbrowne** [comment]
We could but this is not a task that I would do without approval.

**Comment by AnninaWalker** [comment]
This was more a conceptual input from my side. I forgot to add the search field in the Mockups, but I think it should be definitely there.
