### ISSUE TITLE
Filter Alignment

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#849]
Probably goes into the same issue like her: #847 

If there is no color box in front of the filter, the text should be leftaligned with the other elements:
Also the spacing between the elements (line height) should be optimized.

![Screenshot 2022-11-15 at 15 57 19](https://user-images.githubusercontent.com/59613691/201952164-84f9589b-8840-41a4-a7b1-0e0bec6f0cf9.png)

**Comment by AnninaWalker** [comment]
Still doesn't look aligned to me ;-) @bprusinowski 

<img width="1754" alt="Screenshot 2022-11-21 at 15 46 20" src="https://user-images.githubusercontent.com/59613691/203084186-68341e7c-1f73-4e2d-8a45-1767ec157a31.png">

**Comment by bprusinowski** [comment]
Should be fine on TEST now 🤞
