### ISSUE TITLE
revise UX to filter and choose dimension->element on map

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#85]
the "Messwert auswählen" terminology doesn't correspond to the "RDF cube schema" 
the "Holzernte.Total" dropdown list is just another filter which works the same way other filters on the left do.
therefore the UX for filters & "Messwert" (Segmentation) needs to be reconsidered based on the "RDF cube schema"
![image](https://user-images.githubusercontent.com/26090254/118976468-5434f100-b975-11eb-9b9b-fc5b0fdc55e3.png)

**Comment by herrstucki** [comment]
As this would be a "Measure Dimension" according to the cube schema, I think "Messwert" is appropriate? Also please consider that the UI language needs to be as non-technical as possible. The minority of users will know anything about cube schema terminology.
