### ISSUE TITLE
Browser "back" button not working after dataset selection

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#853]
**Describe the bug**
After selecting a dataset and showing the dataset's details, shouldn't the browser "back" button be similar to the "Back to the datasets" button ?

As there is this "Back to the datasets", maybe this is a known "problem" or a decision.

**To Reproduce**
1. Open Visualize https://int.visualize.admin.ch/en?dataSource=Int
2. Click on 'Create a visualization'
4. In the displayd list of dataset, choose a dataset
5. Once the dataset detail page is displayed, click on the browser's "back" button -> nothing happens

**Expected behavior**
The browser's "back" button should bring back to the former page

**Environment (please complete the following information):**
 - Visualize environment and version: INT v3.12.0
 - Browser and version: Firefox 106.0.5
Seems similar on Chrome

**Comment by AnninaWalker** [comment]
@ptbrowne  There still seems to be an odd behaviour for the Back Button. See video below. Clicking on the Back Button does not lead one step back, but it suddenly add Color Segmentation

https://user-images.githubusercontent.com/59613691/203078232-be43bd7a-7eaa-410e-9e3e-da6c634c1fa1.mov
