### ISSUE TITLE
Categories in the filter are not ordered by the IDs

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#857]
The categories in the filter are not ordered by the IDs

**To Reproduce**

1. Go to 'int.visualize.admin.ch' and search "Rétributions uniques pour installations photovoltaïques"
2. Open the filter "Standort der Anlage"
3. The list of cantons in the left-hand filter is displayed in alphabetical order. 
4. Select "Show Datafilter" for "Standort der Anlage", Publish the graph and show filters
5. The list of cantons in interactiv filter is displayed in alphabetical order. 
6. Copy and edit the visualization
7. Choose "Standort der Anlage" as color.
8. The list of cantons in the left-hand filter is also displayed by alphabetical order.

**Expected behavior**
Categories in filters should be sorted by default by ID (Gitlab Issue #405).  
- It must work in all filters
- It must work for all dimensions, including the shared dimension with hierarchy (at least for level 1). Try with : https://int.visualize.admin.ch/en/v/OM6rpkJ7K9bT
The order of "Emission sources" according to the id is : 1. Sectors Ordinance CO2 / 2. International aviation (not included in total) / 3. Balance of land use
- it must work in edit mode and in publish mode with interactive filters. 

**Screenshots**
![image](https://user-images.githubusercontent.com/79834090/202393315-5bf13260-4ef6-448b-a1e9-58032aeadd28.png)

![image](https://user-images.githubusercontent.com/79834090/202393104-b372a052-c810-4c59-8286-27b8fa87a99a.png)

![image](https://user-images.githubusercontent.com/79834090/202391913-474d314c-4461-45ea-8ad2-01e9597ee08b.png)

**Environment (please complete the following information):**
 - Visualize environment and version: v3.12.0 ([c7820ce]
- Browser : Edge
- 
**Additional context**

**Comment by AnninaWalker** [comment]
@bprusinowski the filters in the left and the legend below the visualization do not show the same order. Shouldn't that be the same (both on Automatic)?

<img width="1491" alt="Screenshot 2022-11-21 at 14 48 34" src="https://user-images.githubusercontent.com/59613691/203071474-1f71647a-d8b3-4360-8db6-7a75b12ada8d.png">

**Comment by AnninaWalker** [comment]
See also here, when I change the X-Axis to "Standort der Anlage" and then change the Sorting, it doesn't affect the Sorting of the filters below
https://user-images.githubusercontent.com/59613691/203071865-b79bfca7-56ae-4543-9896-d52eacd169c7.mov

**Comment by AnninaWalker** [comment]
And in the leftsidepanel the sorting seems to work within the datafilters, but once published, the order is alphabetical again. I wonder if we would need to add the sorting options to the published chart? As an enduser might be confused if it is not ordered from A-Z?
<img width="1836" alt="Screenshot 2022-11-21 at 14 52 34" src="https://user-images.githubusercontent.com/59613691/203072456-2b7a40ec-f82d-4a78-8408-fab152b887ba.png">
![Uploading Screenshot 2022-11-21 at 14.52.46.png…]()

**Comment by ortnever** [comment]
dear @AnninaWalker 
We had decided that the filter sorting should be done by default according to the ID and that it should not change. So as not to confuse the graph editor. See my comment here: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/405#note_9066

I understand your point about the end user. Especially as the end user does not have the possibility to search for a term within the filter like the editor.

However, I propose to do as we decided. We will have to think more generally about these different sorts. There are a lot...

**Comment by AnninaWalker** [comment]
Thank you for your feedback @ortnever . Yes I agree, it needs some further thinking. An option could be to add the Sorting options also in the Published Chart, so that the enduser could change the default sorting. And I think it would help to add a a search field on top to allow quicker access as a future enhancement.

**Comment by ptbrowne** [comment]
@ortnever We've added on test the search and ordering of hierarchies by order id. Please tell if it's correct for you and re-open if there's something unexpected.

**Comment by ortnever** [comment]
@ptbrowne I can't find my feedback that I wrote a few minutes ago...I've got the wrong issue?

Just one more remark : while consulting another dataset, I noticed that the search field was not available in the filter.
See here : 
![image](https://user-images.githubusercontent.com/79834090/204500293-ec75c11d-1387-4de2-b170-dd6664bb1ce6.png)

**Comment by ptbrowne** [comment]
Your last feedback was there : https://github.com/visualize-admin/visualization-tool/issues/858#issuecomment-1330362910

Can you give me a link to the chart you screenshotted ? The search input right now is only available for dimension with a hierarchy. We haven't had time to add it to dimensions without hierarchy.

**Comment by ortnever** [comment]
Here the link but you don't need it. It was to show that everything is good :-)

https://int.visualize.admin.ch/fr/v/PaEo-LY9rOWl

**Comment by ptbrowne** [comment]
Yes.
