### ISSUE TITLE
Order in Legend by dataset "Greenhouse Gas Emission"

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#858]
The order in the graph and the lengend are reversed in dataset "Greenhouse gas emission". In other datasets (with categories Production Regions or cantons) the order is ok.

**To Reproduce**
- Copy and edit this visualization : https://int.visualize.admin.ch/en/v/z3272nClUz2J
- The categories are ordered by ID in the graph (1. Sectors of emission 2. International aviation 3. Balance of land use) but the order in the legend is reversed

**Expected behavior**
graph and legend have to be ordered by schema:identifier by default (Auto)
See #199 https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/119

**Screenshots or video**
![image](https://user-images.githubusercontent.com/79834090/202405846-e142432f-d043-4d61-8e27-4c61506eabc8.png)

**Environment (please complete the following information):**

- Visualize environment and version: [e.g. INT v3.12.0]
- Browser : Edge

**Additional context**

**Comment by AnninaWalker** [comment]
Also here, the Tooltips and the Legends are inline with the Sorting, but the Filters in the Leftside Panel are not affected by the Sorting, which I think should be the case.


https://user-images.githubusercontent.com/59613691/203074539-b0dce85b-b2b2-4597-bd08-f2ac53f5b385.mov

**Comment by ortnever** [comment]
yes, it should be exactly like that !

**Comment by ptbrowne** [comment]
@ortnever We've added on test the search and ordering of hierarchies by order id. Please tell if it's correct for you and re-open if there's something unexpected.

**Comment by ortnever** [comment]
@ptbrowne Thanks Patrick.  It's really well done. You can find all the occurrences if they appear at different places in the hierarchy. Very good. 

Example: Waste

![image](https://user-images.githubusercontent.com/79834090/204496507-514f76c5-90d3-4d2d-92a1-c75ef3421464.png)
