### ISSUE TITLE
« An unexpected error has occurred » - Urgent to understand why if I want to go on with tests

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#86]
I have this problems with the Red Lists (Rote Liste), but it seems it happens for different dataset as well.

Just choosing the dataset and hitting the "Next" button will give that error without any further information -> the page is totally blank (no more menu or anything), with that error message.
![image](https://user-images.githubusercontent.com/6167669/119090860-7168ce80-ba0c-11eb-83eb-1c15790831d9.png)

I am pretty "new" to the visualization tool, I do not fully understand the meta-data to be set in the Cube Creator for visualization, so maybe this is a simple mistake - but any way, a clearer message should be displayed to the user.

**Comment by PDumasBAR** [comment]
Same behavior when trying to visualize my cube "Staatsrechnungen" (Comptes de l'Etat, State accounts).
Can view the data in the first step, but not more.
