### ISSUE TITLE
Vertical scale for values below 0.01

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#861]
The scale of the vertical axis does not adjust when the values are less than 0.01.

See exemple here : https://int.visualize.admin.ch/en/v/tu0BcZSVYN9y

**Expected behavior**
The scale should be adjusted according to the values that are displayed.

**Screenshots or video**

![image](https://user-images.githubusercontent.com/79834090/202421575-a034dc9b-3c8a-4a86-837b-1f0531e63a37.png)

**Environment (please complete the following information):**

- Visualize environment and version: [e.g. INT v3.12.0]
- Browser : Edge

**Additional context**

**Comment by AnninaWalker** [comment]
Nice!
