### ISSUE TITLE
Sort Ordinal Dimension by schema:position in table

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#871]
Ordinal dimensions should always be sorted according to schema:position. This is not yet the case for tables. The sort order of ordinal dimensions in the tables is currently alphabetical, which does not make much sense. 

Here a dataset with an ordinal Dimension "Status".
https://int.visualize.admin.ch/fr/v/uQV2R62hgGMD

**Environment (please complete the following information):**

- Visualize environment and version: INT v3.12.0
- Browser and version : edge

**Additional context**

**Comment by bprusinowski** [comment]
Hi @ortnever, thanks for reporting the issue. Do you think we also should take Identifier into account generally when sorting tables, as in filters order, or only position?

**Comment by Rdataflow** [comment]
@ortnever sort by position will do for ordinal measures. I don't see the need to add ID neither.

**Comment by Rdataflow** [comment]
@ortnever indeed the sorting of nominal dimensions in tables is an important thing which needs to be considered.

**Comment by ortnever** [comment]
@Rdataflow : It is currently possible to sort a table on a nominal dimension but this sorting is automatically done alphabetically (you can choose from A to Z, or from Z to A). If you think it should be possible to choose between Sorting by ID (e.g. for cantons) or sorting alphabetically, we need to open a new issue or re-open this one.

Currently in table Chart: 
![image](https://user-images.githubusercontent.com/79834090/206218376-34f7f86c-eecb-45f3-abfc-c89be809545e.png)

Currently in other Charts :
![image](https://user-images.githubusercontent.com/79834090/206218765-742aca7e-c8db-4782-b7da-b680d710b23d.png)

**Comment by Rdataflow** [comment]
@ortnever good point. can you open an issue to have this corrected for tables?
