### ISSUE TITLE
Attribution of colours by categories for a dimension "Year"

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#872]
The attribution of colours in the example below is strange. How does it work?

1. Copy and Edit  " https://int.visualize.admin.ch/en/v/Lnk_MB0Bx75c
2. Edit "Jahr der Vergütung"
3. Only 2 colors from the palette are used, while the values range from 2014 to 2021

**Expected behavior**
As many colours should be used as there are different years, as long as colours are still available in the palette. 

**Screenshots or video**
If applicable, add screenshots or a short video to help put your problem into a context.

**Environment (please complete the following information):**

- Visualize environment and version: INT v3.12.0
- Browser and version: Edge

**Additional context**

**Comment by AnninaWalker** [comment]
I also see that the user can't adjust the colors manually as in the other chart types. The color square is missing in front of the filters @bprusinowski 

![Screenshot 2022-11-22 at 11 16 51](https://user-images.githubusercontent.com/59613691/203288621-c03de944-bf06-439c-ace4-828e1d2a2e8f.png)
