### ISSUE TITLE
Stand structure hierarchy in cube seems incorrect.

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#875]
**Describe the bug**

Cube: NFI: Forest area by Production region and Stand structure 
The Stand structure dimension is not shown as a hierarchy.

**To Reproduce**

<img width="297" alt="image" src="https://user-images.githubusercontent.com/465582/203004508-d14e5400-2684-40e3-868c-c01baf6b413f.png">

1. Go to https://int.visualize.admin.ch/en/create/new?cube=https://environment.ld.admin.ch/foen/nfi/49-19-44/cube/1
2. Click on the filter "Stand structure"
4. See that the hierarchy is not represented

**Expected behavior**

The hierarchy should be represented.

---

Looking quickly into it, I expect the hierarchy inside the data to be broken.
When fetching the hierarchy from values, we prune the hierarchy to only have tree values that are present inside the data. Here the tree is incomplete from the start and I think it may come from case problems between the hierarchy ids and the value ids; I see for example that in the data the value for "Total" is "https://environment.ld.admin.ch/foen/nfi/ClassificationUnit/STRUK/Total" while inside the data, the value is "https://environment.ld.admin.ch/foen/nfi/ClassificationUnit/Struk/Total".

@l00mi How do you debug in this case, is this done via cube-viewer ?
@rdataflow If you have published the cube recently, could you check that everything is in order ?

**Comment by Rdataflow** [comment]
@ptbrowne I guess @kronmar fixed this - can you approve this?

**Comment by ptbrowne** [comment]
It looks good now, we have a hierarchy.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/465582/206208741-d585ec55-041e-4352-86be-f3f4151bf2bc.png">
