### ISSUE TITLE
Visualize zeigt keine Datensätze an

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#88]
Seit gestern Abend zeigt Visualize keine Datensätze an.
Kein datenauswahl.
![image](https://user-images.githubusercontent.com/79834090/119450736-a3dc3980-bd34-11eb-9acf-f388097d15b9.png)

**Comment by herrstucki** [comment]
It's a LINDAS issue. I get a "User does not have read permissions for the index" error.

Please report on https://control.vshn.net/

cc @PDumasBAR
