### ISSUE TITLE
Browse Datasets: Sorting by relevance suddenly disappears

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#885]
**Describe the bug**
After entering something in the searchfield, suddenly the Sorting By relevance dissappears in the dropdown.

**To Reproduce**

1. Go to 'test.visualize.ch'
2. Click on the Sorting Dropdown in the Browse Dataset view and see all 3 Sorting options
3. Search for a keyword in the Search field
4. Delete the keyword in the searchfield
5. Click on the Sorting Dropdown in the Browse Dataset view and see suddenly only 2 Sorting options

**Expected behavior**
Sorting by Relevance should always be visible

**Screenshots or video**

https://user-images.githubusercontent.com/59613691/203264074-6efbb276-eaab-429d-b828-a80dc38c353e.mp4

**Environment (please complete the following information):**

- Visualize environment and version: INT v3.13.0
- Browser and version Safari, 15.6.1

**Comment by ptbrowne** [comment]
So the bug is more that relevance is displayed when we have not searched anything right ?

**Comment by AnninaWalker** [comment]
I thought the "By relevance" is showing the datasets ordered according to the most search datasets in general and not only according to what I have searched as an individual? Or am I wrong? So if the first one is the case, I'd assumed that the By relevance is always visible. If the second one is the case, then yes, it shouldn't be displayed if I haven't searched for anything yet.

**Comment by ptbrowne** [comment]
There is no mechanism of popular searches, or popular datasets. The "relevance" keyword is only meaningful when there is a search term entered.

**Comment by AnninaWalker** [comment]
Ah ok, got it! Thanks for clarifying!
