### ISSUE TITLE
Browse Dataset: Sorting BG Color

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#886]
**Is your enhancement related to a problem? Please describe.**
Nothing urgent, but after changing the selection of the Sorting, a light grey background is visible around the button. This shouldn't be visible.

**Describe the solution you'd like**
Delete this grey background

**Describe alternatives you've considered**
None

**Additional context**

https://user-images.githubusercontent.com/59613691/203264860-a776a7d4-ec71-4468-b64c-17a54d38216d.mp4

**Comment by ptbrowne** [comment]
So the bug is more that relevance is displayed when we have not searched anything right ?
