### ISSUE TITLE
Scatterplot: Improve Scaling

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#888]
**Is your enhancement related to a problem? Please describe.**
The Scatterplot Chart Type, takes currently up a lot of space and is not visualized within the viewport, which makes it very hard to read.

**Describe the solution you'd like**
Optimize the scaling of the Scatterplot. Especially the height, so it fits better into the viewport

**Describe alternatives you've considered**
Not

**Usecases and impact**
Improves readibility of the chart.

**Additional context**
![Screenshot 2022-11-22 at 10 16 02](https://user-images.githubusercontent.com/59613691/203274817-ba6b2f2f-c21e-4fd0-9180-25ac8afb33e8.png)

**Comment by bprusinowski** [comment]
Closing, as recently we adjusted aspect ratios of charts in the edit mode to make sure they fit on the screen.
