### ISSUE TITLE
New UI: Chart Sizing

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#889]
**Is your enhancement related to a problem? Please describe.**
With the new UI the visualizations can be shown a lot bigger than before. As they are currently resizing according to the width of the browser window - in many cases- it leads to that the chart doesn't fully fit into the viewport of the browser window and that the bottom is cut off. (Especially the Scatterplot is out of proportion)

**Describe the solution you'd like**
Should the visualizations resize according to the height of the browser window instead of the width?

**Describe alternatives you've considered**
Or should we limit the height?

**Usecases and impact**
I guess in order to read the visualization at least the visualization and most of the legends should be within the viewport.

**Additional context**

https://user-images.githubusercontent.com/59613691/203276299-9ee2c27f-d416-400c-889c-fea9119c0dec.mp4

**Comment by bprusinowski** [comment]
As this is an issue mostly in the edit mode, where chart takes all available space, it shouldn't be a problem in published (or embed) mode. I think it's important that we keep the "correct" aspect ratios of charts in published mode, but we already adjusted them in the edit mode recently, so this shouldn't be a problem anymore.
