### ISSUE TITLE
Interactive Filters: Time filter in Leftside Panel and Visualization don't correspond

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#890]
**Describe the bug**
If I active the time filter in the Interactive Filter section, I see in the left sidepanel, the full range that is available in the dataset, but not the range I have actually filtered my visualization by. In this example the timeslider in the leftside panel should only show the span from 2002 to 2010 and not from 1995 to 2010. 

**To Reproduce**

1. Go to 'Öffentliche Ausgaben Test 3 Dataset'
2. Click on 'Horizontal Axis' and set year filter to 2002 to 2010
3. Scroll down to 'Interactive Filters'
4. Check show time filter
5. See error

**Expected behavior**
Left side panel and visualization should show the same timerange

**Screenshots or vide
![Screenshot 2022-11-22 at 10 48 53](https://user-images.githubusercontent.com/59613691/203283030-b1b0b2f3-25ee-4259-8cd7-5997838a3c1f.png)
o**

https://user-images.githubusercontent.com/59613691/203283404-1f2d8016-019d-42a1-820f-ca94e5015d93.mp4

**Environment (please complete the following information):**

- Visualize environment and version: INT v3.13.0
- Browser and version Safari
-

**Comment by bprusinowski** [comment]
Closing as we recently introduced syncing of both filters, and I can't find this dataset anymore. I believe the issue should be fixed now.
