### ISSUE TITLE
Time slider: Suddenly visible on test.visualize.ch

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#894]
**Describe the bug**
I suddenly see the time slider option in the "Öffentliche Ausgaben Dataset". If I select it, nothing happens except that I suddenly get a very funny tooltip.

**To Reproduce**

1. Go to 'Öffentliche Ausgaben Dataset'
2. Click on '.Interactive Filters - Time slider'
3. Choose year

**Expected behavior**
Deactivate Time slider

**Screenshots
![Screenshot 2022-11-22 at 11 23 08](https://user-images.githubusercontent.com/59613691/203290509-15bd83d6-8c6c-45cb-a598-6d88f5f5205a.png)
 or video**
![Screenshot 2022-11-22 at 11 23 39](https://user-images.githubusercontent.com/59613691/203290531-414d2338-3edf-4d56-afd8-e921313c982c.png)

**Environment (please complete the following information):**

- Visualize environment and version:  INT v3.13.0 ]
- Browser and version Safari 15.6.1

**Comment by bprusinowski** [comment]
Hi @AnninaWalker, thanks for reporting this. As time slider is only visible if you've set the flag (and the feature is still in alpha stage), I will further work on it during this sprint if time allows. I would not hide the time slider by default taking above reasons into consideration, as it's not visible by default – end users shouldn't have access to it (you could remove the flag from LocalStorage of the browser and then it wouldn't be available).

**Comment by AnninaWalker** [comment]
Perfect. Yes I assumed it must be something like that, but wasn't a 100% sure. But then its fine by me. Thanks for clarifying
