### ISSUE TITLE
Maps: Empty Dropdowns in "NFI: Volume by Production region and Stage of stand development "

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#896]
**Is your enhancement related to a problem? Please describe.**
When I select the "NFI: Volume by Production region and Stage of stand development " and try to set the Interactive Filters for Evaluation Type and Inventory, per default the Dropdown seems to be empty. Then when I click on one of them I see its content. 
I assume thats because nothing is in the data. 

**Describe the solution you'd like**
Would it be possible that, when there is nothing in the date to add either "None" or "-" or something equivalent, so it doesn't look like an error?

**Describe alternatives you've considered**
None

**Additi
![Screenshot 2022-11-22 at 13 42 58](https://user-images.githubusercontent.com/59613691/203317565-a9b6f3e3-18a0-439b-8d4e-6f82a84f5662.png)
onal context**
![Screenshot 2022-11-22 at 13 45 27](https://user-images.githubusercontent.com/59613691/203317583-fcc20b8e-a91d-4f58-9dbe-72a422ffe3e1.png)

**Comment by bprusinowski** [comment]
As we recently added cascading filters behavior to interactive filters, this should no longer be the case.
