### ISSUE TITLE
Reduce size of blue bar from 350px to 250px 

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#897]
**Is your enhancement related to a problem? Please describe.**
In the new UI the blue bar takes up a lot of space on smaller screens. As a result, users cannot see the data sets.

**Describe the solution you'd like**
 I would propose reducing it to 250px to ensure that the maximum amount of information can be seen on smaller screens without scrolling. 

**Describe alternatives you've considered**
Open to alternatives

**Usecases and impact**
The change will allow users with smaller laptop screens to see more of the UI without scrolling 

**Additional context**
This is a nice to have issue, and by no means a priority at the moment. 
![image](https://user-images.githubusercontent.com/29289679/203322416-f2c7ec26-d64c-415f-a890-b198704eb248.png)

**Comment by sosiology** [comment]
@ptbrowne @bprusinowski when checking the pr link (https://visualization-tool-j0jvzwry2-ixt1.vercel.app/en/browse?dataSource=Prod) i noticed that with this change, when the browser window is minimized the search bar is shown below the blue background and sometimes covers the text. If there is no easy fix for this, I would propose we keept the height of the blue background at 350px.  
![Screenshot 2022-11-29 at 09 23 28](https://user-images.githubusercontent.com/29289679/204476820-59cbc84e-999e-483f-8065-4bbbdb4a3f4a.png)

cc: @AnninaWalker

**Comment by ptbrowne** [comment]
Thanks, my bad, I changed to have a min height of 250, and if the content is shrunk down, the banner height will grow to accomodate it.

**Comment by sosiology** [comment]
Excellent! LGTM, thanks!
