### ISSUE TITLE
Add search field in long dropdown list

### ISSUE THREAD

**Issue by AnninaWalker** [visualize-admin/visualization-tool#899]
**Is your enhancement related to a problem? Please describe.**
As the filter dropdowns are now sorted by identifier (I guess) it might be a bit more difficult to find what you are looking for. I'd suggest that we Add a Search field on top of the dropdown list, so the user can easier narrow down what he is looking for

**Describe the solution you'd like**
Add a searchfield.

**Describe alternatives you've considered**
None

**Usecases and impact**
More user friendly

**Additional context**

https://user-images.githubusercontent.com/59613691/203327328-9bed4d3e-2033-47ce-92c8-0a7a373c822b.mp4

**Comment by ptbrowne** [comment]
For now, the search has been added to filters on dimensions with hierarchies.
