### ISSUE TITLE
Cant access diagram page

### ISSUE THREAD

**Issue by davidhanimann** [visualize-admin/visualization-tool#90]
The second page (showing diagrams) is no longer working: 'An unexpected error has occurred.'

![image](https://user-images.githubusercontent.com/19548402/119680277-51d50a00-be41-11eb-8a5d-35e91cd227fb.png)

Tested with several cubes.

**Comment by herrstucki** [comment]
Probably a duplicate of #86 .

I can't reproduce at the moment because all cubes are missing again 🙃
