### ISSUE TITLE
Add "Use abbreviations" checkbox

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#903]
Implement a checkbox to allow the user to show abbreviations if they are available in the data.
Also see design concept: [#424](https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/424)
And Comment from Véronique in Gitlab pasted below: https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/439#note_9215

> I now notice that the concept does not clearly say that the "use abbreviation" check box should also be available when choosing the dimension on the colour axis.
> As the Screenshot in [#424](https://github.com/bafu/umweltdatenkiosk-planning/-/issues/424) only shows the use case on the x-axis, I prefer to make this clear here.
> Please make sure that the check box is also available for the colours.

![Image](https://user-images.githubusercontent.com/29289679/203364139-c618bfbe-103b-4a84-8c82-dbeb527793e2.png)

**Comment by AnninaWalker** [comment]
@bprusinowski Shouldn't it be the other way round in this example. Here when I check the abbreviations box I get the long labels. But I guess has to do how it is handled in the cube?


https://user-images.githubusercontent.com/59613691/205866900-fe28db90-bb77-4ed6-8876-a20baa716ea7.mp4
