### ISSUE TITLE
Sort by ID (automatic) does not work by Horizontal Axis

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#907]
Sorting nominal dimensions by ID does not work for the vertical axis.
1) sorting by ID is not selected by default when the page is opened
2) sorting by ID is not done when selecting "Automatic" (even after a refresh)

**To Reproduce**
1) Search Dataset "Einmalvergütung für Photovoltaikanlagen" 
2) Start a visualization
3) Select "Standort der Anlage" on Vertical Axis.
4) Default Sort is by Name instead Automatic
5) Select Sort "Automatic"
6) Standortanlage are sorted by Name in the graph.
7) Publish
8) Standortanlage are sorted by Name in the graph.

**Expected behavior**
- Automatic must be seleczted by default and provid a Sort by ID, in Edit and publish View.

**Screenshots or video**
![image](https://user-images.githubusercontent.com/79834090/203602676-72e35cd7-358d-40f2-a424-c0a7d0824851.png)

![image](https://user-images.githubusercontent.com/79834090/203602940-f3dc9226-5270-4451-9d12-5066ba45840c.png)

**Environment (please complete the following information):**

- Visualize environment and version: INT v3.13.0 ([09c6e42]
- Edge

**Additional context**

**Comment by ptbrowne** [comment]
You can now sort the horizontal axis for this usecase.
