### ISSUE TITLE
Filter : Order by ID

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#909]
The order of the filters is not per ID in following examples.

**To Reproduce**
1. Open https://int.visualize.admin.ch/de/v/ziydEGND7eCt
2. Display the interactiv Filter
3. Look at "Gas" . Order is not by ID
4. Copy and edit
5. Look at Filter on the left, same Problem.

Other example 
1. https://int.visualize.admin.ch/de/v/GISkKFwUmzDZ
2. display fthe interactive filter 
3. Look at "Standort der Anlage" . Order is not by ID
4. Copy and edit
5. Look at Filter on the left, same Problem.

**Expected behavior**
All filters must be ordered by ID, everywhere.

**Screenshots or video**
![image](https://user-images.githubusercontent.com/79834090/203725646-70ac3161-5387-4bf4-8448-1c8a0a5ed9cb.png)

![image](https://user-images.githubusercontent.com/79834090/203743725-1521aaf8-bf12-46d0-88e7-47c8f583678f.png)

**Here below, the ID for dimension Gas and example where the order is correct :**

![image](https://user-images.githubusercontent.com/79834090/203733403-854ba38b-3409-417b-a8cb-8df69b6265a0.png)

![image](https://user-images.githubusercontent.com/79834090/203733334-c05ba84e-944a-40fc-8ade-46578358ae61.png)

**Environment (please complete the following information):**

- Visualize environment and version: INT  v3.13.0 ([09c6e42]
- Edge

**Additional context**

**Comment by FabianCretton** [comment]
As discussed this morning, here is another example from a project that is currently not accessible as TEST is down:
![image](https://user-images.githubusercontent.com/6167669/203747707-f44e2235-5cdf-4877-9e50-9ba0dec1b0f9.png)
The identifier is a string as:
4403.2010
4403.1290
                                              
Why does the .2010 come before the .1290, or do I have  mistake in my data ?

The link to visualize the project, once TEST is back on, could be:
https://test.visualize.admin.ch/en/browse/dataset/https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Ffab_foreign_trade_test_2%2F2?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22fab%22%7D&dataSource=Test

**Comment by ortnever** [comment]
@ptbrowne when looking at another dataset, I noticed that the search field was not available in the filter. 
See for example : https://test.visualize.admin.ch/de/v/ARznezP3g77s
