### ISSUE TITLE
Change "Interaktive" to "Interaktiv" 

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#916]
**Describe the bug**
The DE UI String for the interactive filter toggle should be "Interaktiv" instead of "Interactiv**e**".

**Expected behavior**
See above

**Screenshots or video**
![image](https://user-images.githubusercontent.com/29289679/204580151-c5a6c1bb-3f18-4463-bbf4-074c00fc4a86.png)
**Environment (please complete the following information):**

- Visualize environment and version: [e.g. INT v3.14.0 ([75fd5d8](https://github.com/visualize-admin/visualization-tool/commit/75fd5d8961efaf84236bfd3c6b6720a93395c692))

**Additional context**

**Comment by ptbrowne** [comment]
Fixed in https://github.com/visualize-admin/visualization-tool/commit/0c299c38ac2a2eb3b30a3a289be4843a1acf5ecc
