### ISSUE TITLE
Visualize PROD very slowly or data not available

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#930]
Since this morning Visualize is either very very slow or the data is not available at all.

https://visualization-tool.status.interactivethings.io/

![image](https://user-images.githubusercontent.com/79834090/212096350-0081fbe6-a57c-473c-88be-e74f03f93449.png)

**Comment by ptbrowne** [comment]
Are you still experiencing the problem @ortnever  ?

**Comment by ptbrowne** [comment]
Closing as this was solved.
