### ISSUE TITLE
"Cascading filter" behaviour by hierarchical dimensions

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#931]
The "Cascading filter" behaviour does not work correctly on filters containing hierarchical dimensions.

**To Reproduce**

1. Open the Draft dataset "Greenhouse gas emissions by sector and by gas" (include Draft) and start a visualization
2. Open the Filter "Emission sources" and select "Synthetic gases" (Sectors Ordinance CO2 -> Other)

![image](https://user-images.githubusercontent.com/79834090/212634960-f6b77f2b-e825-459a-9e7d-9ae812c127c9.png)

5. Open the second Filter "Greenhouse gas"

7. See error
-> all gases are displayed, while there are only values for synthetic gases
-> When I select a gas for which there are no values for the selected emission source, e.g. Methane, another gas is selected, in our example "Perfluorocarbons" without the user being warned.

![image](https://user-images.githubusercontent.com/79834090/212635810-49d34788-625d-4927-9844-eb45df4b4a7d.png)

**Expected behavior**

Only available values should be displayed in the filters (in our example: synthetic gases).

![image](https://user-images.githubusercontent.com/79834090/212634463-77c52480-09cb-44ac-a98a-8d6afe13759c.png)

**Environment (please complete the following information):**

- Visualize environment and version: PROD v3.16.0 ([5fccbf0]
- Browser and version: Edge

**Additional context**

**Comment by AnninaWalker** [comment]
An input that already mentioned but I guess would be some additional work is, if it really is necessary to show the top level "All greenhouse gas" or if we could just directly show the first level? But in case probably another discussion. This bug is fixed

**Comment by ptbrowne** [comment]
> if it really is necessary to show the top level "All greenhouse gas" 

I do not have an opinion here, this would have to be corrected in the data ;)
