### ISSUE TITLE
Handle multiple parallel hierarchies per dimension

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#936]
Forest regions can be grouped following two different taxonomies

```
Switzerland - Level 0 [root]
    split into [Protection forest regions](https://s.geo.admin.ch/994786067c) - with children at Level 1a:
        Jura + Plateau
        Northwestern Alps
        Northeastern Alps
        Southwestern Alps
        Southeastern Alps
        Southern Alps

    - or alternatively -

Switzerland - Level 0 [root]
    split into [Production regions](https://s.geo.admin.ch/994784e008) - with children at Level 1b:
        Jura 
        Plateau
        Pre-Alps
        Alps
        Southern Alps

    - or alternatively -

Switzerland - Level 0 [root]
    split into Cantons - with children at Level 1c:
        ZH
        BE
        ...

```

By default we should not show regions of different kind (hierarchy trees) as they potentially overlap with each other.

Input from Michael regarding the data side implementation for this issue

1 Additional Description for the Hierarchy (if needed)
The multiple different hierarchies, might have the same root (CH -> Forest Protection Regions / Forest Production Regions), or completely different roots (e.g. Europe -> NUTS Regions / CH -> Cantons). For the same root case, it is necessary, to also show the "type" of the root. (It should be shown together with the Root classification, as shown below.)
The additional description is only shown in case of multiple hierarchies. (To keep the interface clean, and also because most hierarchies do not have such a description.)

![Image](https://user-images.githubusercontent.com/29289679/213175614-4f0c654d-3429-45cb-9108-6f89fdd5db11.png)

The description can be taken from the schema:name inside the hierarchy description which looks something like the below. The same language fallback as in the rest of visualize.admin.ch shall be used:

```
[
  meta:inHierarchy [
    a meta:Hierarchy ;
    meta:hierarchyRoot <https://ld.admin.ch/country/CHE> ;
    schema:name "CH - Forest Prod" ;
    meta:nextInHierarchy [
      schema:name "Forest Production Regions"@en ;
      schema:name "Wald Produktionsregionen"@de ;
      sh:path <http://schema.org/containsPlace> ;
    ]
  ]
]
[
  meta:inHierarchy [
    a meta:Hierarchy ;
    meta:hierarchyRoot <https://ld.admin.ch/country/CHE> ;
    schema:name "CH - Forest Eco" ;
    meta:nextInHierarchy [
      schema:name "Forest Economic Regions" ;
      sh:path <http://schema.org/containsPlace> ;
    ]
  ]
]

```

Zazuko will need to document this properly.

        

        

* Related cube : https://test.visualize.admin.ch/en/browse?previous=%7B%22includeDrafts%22%3Atrue%2C%22order%22%3A%22SCORE%22%2C%22search%22%3A%22nfi%22%7D&dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2FC-96-r%2Fcube%2F1&dataSource=Int

* example data is provided online in this cube: https://test.visualize.admin.ch/en/browse?dataset=https%3A%2F%2Fenvironment.ld.admin.ch%2Ffoen%2Fnfi%2FC-96-r%2Fcube%2F1&dataSource=Int
* UI & spec as documented in michaels comment

**Comment by AnninaWalker** [comment]
LGTM
