### ISSUE TITLE
useRedirectToVersionedCube uses wrong dataSource on page load

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#939]
It seems like useRedirectToVersionedCube uses the default dataSource prod on int.lindas.admin.ch when reaching https://int.visualize.admin.ch/en/browse?dataset=https%3A%2F%2Fpolitics.ld.admin.ch%2Ffch%2Fpolitical-correspondence&dataSource=Int instead of picking the Int dataSource indicated in the URL.

It is visible from the network tab where we can see that the request to Lindas is made to lindas.admin.ch

It leads to the failure of loading the cube.

I cannot yet reproduce on localhost.

**Comment by bprusinowski** [comment]
To reproduce the issue locally:

- set `ENDPOINT` env variable to point at PROD LINDAS env
- restart the application
- go to http://localhost:3000/en/browse?dataset=https%3A%2F%2Fenergy.ld.admin.ch%2Fsfoe%2Fbfe_ogd102_fuellstand_gasspeicher&dataSource=Int
