### ISSUE TITLE
Problem when embedding: Legend not fully visible with the tooltip

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#941]
We are currently looking at how the graphics appear on the website. We found the following problem :

In the line charts, the legend via the tooltip is always aligned centrally above the current year. This means that the legend is cutted to the left or right if years are selected at the beginning or end of the axis.

With the bar chart, on the other hand, the legend is automatically placed correctly.
![image](https://user-images.githubusercontent.com/79834090/214002998-dd0fbc86-d3dc-46cc-b122-084451fcb072.png)

How it looks like in AEM :
![image](https://user-images.githubusercontent.com/79834090/214004560-9f69db4f-9302-490b-bba3-4f126434ea90.png)

Ok by Bar chart
![image](https://user-images.githubusercontent.com/79834090/214004928-8566e54f-7436-4ae5-9cd3-aa86a355d0de.png)

**Comment by bprusinowski** [comment]
Hi @ortnever, we recently changed the way we position tooltips in case of segmentation being active. This problem should no longer exist – please feel free to re-open the issue if that's not the case.
