### ISSUE TITLE
Choice of displaying the links below the embedded graph

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#943]
**User Story:** 
As an editor I would like to have the choice to embed my Visualization in a web page (iFrame or external application) without all the links below the chart and without links to the Metadata.
Information to be removed for the "Minimal View" (see also screen shot)

- Dataset
- Latest update
- Download data
- switch to table view
- Learn more about the dataset
- run SparQl query
- Metadata Button + all Links to Metadata

The link "created with Visualize" must be kept, but the label has to be replaced with "more Information" or something like that.
I do not have a concrete idee for the labels in the box “Embed Code”. Maybe you could have : “Embed full view” vs “Embed minimal view”.

The current Embed codes are of course still available for editors who wish to implement the full view.

![Image](https://user-images.githubusercontent.com/29289679/214597148-e57892fe-e332-47df-8093-13f84edda7ef.png)

![Image](https://user-images.githubusercontent.com/29289679/214597184-99490fa6-ed3f-4cc2-ae6e-cb63c29915a4.png)

![Image](https://user-images.githubusercontent.com/29289679/214597292-9840d456-af50-4388-a2fc-7280767f91d3.png)

**Comment by AnninaWalker** [comment]
Nice! I especially like that, when you switch between the Standard & Minimal View, that you immediately see what it changes in the chart, due to the new placement of the Share and Embed Button. Nice improvement!
