### ISSUE TITLE
Download data: replace label "Filtered dataset" with "Chart dataset”

### ISSUE THREAD

**Issue by sosiology** [visualize-admin/visualization-tool#944]
Under the link "Download data" the user has the choice between downloading the filtered dataset (only the data of the graph) or downloading the full dataset.
The label "Filtered dataset" is not clear, it should be replaced by "Chart dataset".

![Image](https://user-images.githubusercontent.com/29289679/214307617-48580c77-e75d-455e-a1c1-a4499939a071.png)

**Comment by ptbrowne** [comment]
Fixed in 0c8c86e4

**Comment by sosiology** [comment]
Reviewed in editor mode and in the published charts in all languages and it all LGTM! Thanks @ptbrowne
