### ISSUE TITLE
Labelling in hierarchies

### ISSUE THREAD

**Issue by ptbrowne** [visualize-admin/visualization-tool#956]
See if https://gitlab.ldbar.ch/bafu/umweltdatenkiosk-planning/-/issues/437 is possible.

**Comment by sosiology** [comment]
Closing this here, as the issue is closed in Gitlab.  The use case is resolved with the parallel hierarchies also see comment here: https://gitlab.ldbar.ch/bafu/visualize/-/issues/437#note_10226
