### ISSUE TITLE
applied colors vs color choice: out of sync

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#960]
**Describe the bug**
The colors applied in the chart and the legend are not in sync with the chosen colors according the the color choice.

**To Reproduce**

1. Go to https://int.visualize.admin.ch/create/new?from=IFisdlO-qn2J
2. Click on `color / region`
3. See orange color picked for `Alpensüdseite` (southern alps)
4. See blue color applied in chart & legend

**Expected behavior**
The picked color shall be applied in the chart

**Screenshots or video**
![image](https://user-images.githubusercontent.com/26090254/218675135-96862260-46cf-4bb3-bd34-a78152ed5630.png)

**Environment (please complete the following information):**
- Visualize environment and version: [e.g. INT v3.19.1 ] ([729209d](https://github.com/visualize-admin/visualization-tool/commit/729209d8be1d7112c0bf2a19117b8c5d397beada))

**Comment by ptbrowne** [comment]
Should be fixed via https://github.com/visualize-admin/visualization-tool/pull/970
