### ISSUE TITLE
poor performance on INT

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#961]
**Describe the bug**
For some unkown reason visualize INT suffers from poor performance compared to https://visualization-tool-git-main-ixt1.vercel.app/

**To Reproduce**

visualize INT
1. Go to https://int.visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/nfi/C-96/cube/1&debug=true&dataSource=Int and compare with https://visualization-tool-git-main-ixt1.vercel.app/create/new?cube=https://environment.ld.admin.ch/foen/nfi/C-96/cube/1&debug=true&dataSource=Int
2. wait > 30secs to load
3. Click on debug (buttom right)
4. compare timings

**Expected behavior**
INT as well as PROD shall have robust and roughly comparable timings instead of double and more i.e.
- DataCubeMetadataWithComponentValues: 33 vs 16 secs
- DataCubeMetadata: 12 vs 3 secs
- DataCubeObservations: 51 vs 23 secs
- DataCubeMetadataWithComponentValues: 51 vs 19 secs
- PossibleFilters: 14 vs 6 secs 
do some of the environments suffer from lack of hardware resources, configuration or network latency or the like which would need to be addressed?

**Screenshots or video**
Visualize INT
![image](https://user-images.githubusercontent.com/26090254/218704361-2fb1c735-463a-4869-bfd2-b3d55206161e.png)

git main
![image](https://user-images.githubusercontent.com/26090254/218704602-41ccf1ec-fc8a-443c-890b-7894fe486695.png)

**Environment (please complete the following information):**
- Visualize environment and version: [e.g. INT v3.19.1]
- git main: 3.19.1

**Comment by Rdataflow** [comment]
notice the very same queries on a fresh deployed instance (3.19.1 release) are even quicker
![image](https://user-images.githubusercontent.com/26090254/218962874-8e6c2f88-842b-47e4-a3bc-20277b529466.png)

@ptbrowne for which reason some of the deployments of the same image become slow as the poor timings mentioned above?

**Comment by ptbrowne** [comment]
Was fixed through the introduction of caches, further performance improvements will be tracked through https://github.com/visualize-admin/visualization-tool/issues/968
