### ISSUE TITLE
poor SPARQL query performance

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#968]
**Describe the bug**
First time loading this cube suffers from bad SPARQL query performance due to bad query. The user has to wait ~5000ms longer to have the chart fully loaded due to such kind of queries.

**To Reproduce**

0. Wait for the LRU cache to be empty
1. Go to https://int.visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/nfi/49-20-21/cube/1&debug=true
2. Click on the debug symbol
3. Open DataCubeMetadataWithComponentValues
4. See slowest / topmost SPARQL query (~5000ms)

**Expected behavior**
quick query

**Environment (please complete the following information):**
- Visualize environment and version: [e.g. INT v3.19.5]

**Additional context**
* reason: poor SPARQL query performance
* robust optimization is needed

**Comment by bprusinowski** [comment]
@Rdataflow as we improved a lot since adding this issue (it references 3.19.5 Visualize version), I will close the issue 👀
