### ISSUE TITLE
Cube Checker

### ISSUE THREAD

**Issue by tboeni** [visualize-admin/visualization-tool#972]
The Cube Checker seems to be not working correctly for me. When controlling the cube status via Cube Checker whether it is INT or PROD yields the same result. 

![TreibhausgasCubeChecker](https://user-images.githubusercontent.com/111350367/220584990-5ad432a7-a2ba-48c1-9a46-73158917c5bf.PNG)
This screenshot shows the status of the Cube Checker when applied to the Greenhouse Gas Emission cube which has been already published on PROD and is live and working, which is unexpected.

This error appears also if you follow from Cube Creator to Visualize via the direct link  after the publication process.

**To Reproduce**

It can be easily reproduced by entering the links from the respective cubes into the Cube Checker ([int](https://int.visualize.admin.ch/_cube-checker), [prod](https://visualize.admin.ch/_cube-checker))
For the links to the Cube themselves, follow the _Run SPARQL Query_ link below the graphics of either Visualize graphic

![TreibhausgasSPARQL](https://user-images.githubusercontent.com/111350367/220587592-88029068-1af9-478b-a337-baf5b9c58d5e.PNG)

**Environment:**
- Visualize environment and version: v3.19.5 0481cfa
- Browser and version Edge 109.0.1518.55

**Comment by ptbrowne** [comment]
Hi @tboeni, thanks for the feedback. It seems like you are entering an unversioned cube IRI in the cube checker. The cube checker supports only versioned iri at the moment. I agree that the error could be better. From the Run SPARQL Query link that you mentioned, you get the versioned IRI. I added this warning in the cube checker doc and added a link to the cube checker doc on the cube checker page.

```patch
- https://environment.ld.admin.ch/foen/ubd000502
+ https://environment.ld.admin.ch/foen/ubd000502/3
```

Please tell me if it's OK for you, I am closing this issue, do not hesitate to re-open if it's unclear.

**Comment by tboeni** [comment]
Hi @ptbrowne thanks for your answer, yes for this cube it has been solved. With this IRI it works fine. 
I have not experienced the error again since. However I will keep my eyes open if the issue would return
