### ISSUE TITLE
wrong sort order - schema:identifier of type^^xsd:integer

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#973]
**Describe the bug**
The sort order found in filter (a - filter list, b - drop down, c - metadata panel) is wrongly ordered by schema:identifier interpreted as `xsd:string` - while in LINDAS it has type `xsd:integer`. NB: Meanwhile the legend (preview & published) is fine 👍 

**To Reproduce**
a) Steps to reproduce the behavior:
1. Go to https://int.visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1
2. Click on Color > Canton
3. Scroll down to selected filters / or `edit filters`
4. See wrong sort order applied ("1":Zurich, "10":Fribourg, "11":Solothurn, ...)

b) Steps to reproduce the behavior:
1. Go to https://int.visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1
2. Click on add filter > Canton
3. Open DropDown List
4. See wrong sort order ("1":Zurich, "10":Fribourg, "11":Solothurn, ...)
![image](https://user-images.githubusercontent.com/26090254/220591204-9d6b2999-3174-4797-948b-cd4b15d750e8.png)

c) Steps to reproduce the behavior:
1. Go to https://int.visualize.admin.ch/create/new?cube=https://environment.ld.admin.ch/foen/gefahren-waldbrand-warnung/1
2. Click on Metadata > Data
3. Open Canton
4. See wrong sort order ("1":Zurich, "10":Fribourg, "11":Solothurn, ...)
![image](https://user-images.githubusercontent.com/26090254/220594984-416886ab-543b-4c37-a18f-734bed9ea169.png)

**Expected behavior**
Identifier parsed according to the data in lindas as `xsd:integer` and thus ordered (1:Zurich, 2:Berne, 3:Lucerne ...)
xref: https://github.com/visualize-admin/visualization-tool/pull/937#issuecomment-1404804789

**Environment (please complete the following information):**
- Visualize environment and version: [e.g. INT v3.19.5]

**Additional information**
required for the upcoming go live of forest fire warning.

**Comment by ptbrowne** [comment]
@Rdataflow  Has this dataset changed ? I remember solving the integer interpretation bug, but now I cannot re-check since I cannot use a column chart due to the lack of number measure.
