### ISSUE TITLE
wrong sort order along x-axis - schema:identifier of type^^xsd:integer bug

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#976]
**Describe the bug**
The sort order along x-axis is ORDER BY schema:identifier wich is great 👍 
However the values are wrongly interpreted while LINDAS provides type ^^xsd:integer

**To Reproduce**

1. Go to https://test.visualize.admin.ch/en/v/-Ivpxbqun9Bl?dataSource=Int
2. See wrong order in x-axis ("1", "10", "2", ...)

**Expected behavior**
Correct order in x-axis (1, 2, 3, ... 10, ...)

**Screenshots or video**
![image](https://user-images.githubusercontent.com/26090254/220697270-847a70be-594c-4017-ab8c-f27b1ca28d84.png)

**Environment (please complete the following information):**
- Visualize environment and version: [e.g. INT v3.19.5]

**Additional context**
see also #973 which seems loosely related considering the wrong interpretation of the datatype

**Comment by Rdataflow** [comment]
Note: the non-appearance of the labels might be an issue on the data side. https://s.zazuko.com/4THygX
@kronmar can you tackle this - **AFTER** this issue has been addressed

**Comment by kronmar** [comment]
That's a really interesting find @Rdataflow. However, the issue is not directly on the data-side as [this query](https://s.zazuko.com/VCn6Up) shows. The data is there, but somehow not callable with a DESCRIBE query.

**Comment by ptbrowne** [comment]
I guess here that since we cannot fetch the named nodes, we cannot know their identifier (even though it is part of the named node URLs). I think this problem would disappear if the diameter classes were correctly present on the data side.

**Comment by Rdataflow** [comment]
@Kronmar so ist tour turn...

**Comment by Rdataflow** [comment]
@Kronmar so its your turn...
