### ISSUE TITLE
Search: Difference between number of datasets listed by organization/category and number of results

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#979]
It's a small thing but strange. The number of datasets shown in the left frame does not correspond to the number of datasets in the result list for the category "Energy" or the organization "Federal Office of Energy".

- Open https://int.visualize.admin.ch/en/browse?includeDrafts=true&dataSource=Prod
- select Enregie (8) in the left panel, number of results = 7
- select Swiss Federal Office of Energy (5) in the left panel, number of results = 4.

![image](https://user-images.githubusercontent.com/79834090/221174396-ce0b7d7c-42f0-4861-a738-4993cd40a6dc.png)

![image](https://user-images.githubusercontent.com/79834090/221174423-18edd88c-d06c-41f3-98d7-486142ad1ac1.png)

![image](https://user-images.githubusercontent.com/79834090/221174758-50206731-cac2-4cea-9de1-9ce25eef8f22.png)

**Environment (please complete the following information):**

- Visualize environment and version: INT 
- Edge v3.19.5 [0481cfa]

**Comment by ptbrowne** [comment]
The cube with title ""Modellergebnisse EP2050+: Szenario ZERO Basis, KKW-Laufzeit 50 Jahre, ausgeglichene Jahresbilanz" is count twice for the count on the left. This particular cube is at version 5. The version 4 lacks an expire pattern (unlike versions 3, 2, 1). The version 4 of the cube should be fixed and have an `<http://schema.org/expires>` predicate so that it is considered expired.

**Comment by ortnever** [comment]
Salut @AFoletti , Peux-tu regarder le commentaire de Patrick ci-dessus. Merci. 
J'ai utilisé Lindas PROD pour tester, depuis visualize int.

**Comment by AFoletti** [comment]
Will check later today or tomorrow morning.

**Comment by AFoletti** [comment]
So: I have to say that the need of a `<http://schema.org/expires>` predicate is totally new to me. I guess it's automatically set by the CubeCreator to the former version when a new one is created.

Version 5 of this cube is only a draft, while 4 is not. In other words, Version 4 is still the officially valid one and thus not expired.

My guess is that Visualize should not only check for expiring date but if some of the still active versions are drafts to keep the lists consistent.
@ptbrowne what do you think?

**Comment by Rdataflow** [comment]
@AFoletti schema:expires is handled by CC yes.

@ptbrowne this case shows multiple versions can definitely occurs intentionally (one versoin published, a later one draft). Thus the counting logic needs to be corrected to reflect this kind of situation...

cc @ortnever
