### ISSUE TITLE
accessibility problems

### ISSUE THREAD

**Issue by mbch** [visualize-admin/visualization-tool#98]
Using Safari on macOS the "tab" key is not working as expected. 
URL: https://www.test.visualize.admin.ch/en/create/new
On Chrome you can use the Tab Key to visit every part of the page - on Safari only a few parts of the page are reachable. For example it's not possible to change the language or select a cube without mouse.

**Comment by herrstucki** [comment]
@mbch That's because in Safari the standard shortcut is different: it's Option-Tab to navigate to all elements. Nothing we can do about this.
