### ISSUE TITLE
Width of Graph by Embeding with Iframe

### ISSUE THREAD

**Issue by ortnever** [visualize-admin/visualization-tool#982]
When I embed a graphic by Iframe in AEM, and I simulate a display on Phone, the graphic is cut because the width is fixed on 600px. 
Should we set the width to 100% of the page width? See example below.
If we do that, the display on Phone is ok (I have only tested with the simulator in AEM), but the display on desktop is a little bit smaller as the display with width=600px.

![image](https://user-images.githubusercontent.com/79834090/221182334-7de4cdfc-afe0-4bb7-b297-a55714ccd591.png)

![image](https://user-images.githubusercontent.com/79834090/221181911-c59a9422-78b9-4bb5-9636-ad74513e60eb.png)

![image](https://user-images.githubusercontent.com/79834090/221181974-2c39dd03-cb68-4257-bf8f-18742b2f5f31.png)

**Environment (please complete the following information):**

- Visualize environment and version: INT v3.19.5 ([0481cfa]
- Browser : Edge

**Comment by ptbrowne** [comment]
@ortnever On test I am deploying a fix that makes the embed code of the iframe contain a max-width: 100% on the style of the iframe. It has the effect that the iframe will adjust to the size of the screen if the size of the screen is > 600px. This way we have both fixed size of 600px on desktop and 100% on mobile. I think this is the behavior you want, tell me if it is OK ;)

**Comment by ortnever** [comment]
hi @ptbrowne, exactly, you can deploy like you describe. Our Webmanager has confirmed it. Thank you.
