### ISSUE TITLE
schema:position not used to order chart legends

### ISSUE THREAD

**Issue by FabianCretton** [visualize-admin/visualization-tool#986]
**Describe the bug**
An ordinal dimension is used to display a map, the schema:position should be used to order the legend under the chart

**To Reproduce**
1. Visualize INT or TEST
2. Dataset "waldbrand" which is a draft
3. Choose the map view
4. The labels under the map are ordered alphabetically, and not according to schema:position
5. Seems the same for the table view

**Screenshots or video**
![image](https://user-images.githubusercontent.com/6167669/222086723-aadd9be4-d991-48e5-9be4-a4fc2d319ad9.png)

![image](https://user-images.githubusercontent.com/6167669/222087036-02499dd7-1764-4e8d-b0b4-80894a264cc9.png)

![image](https://user-images.githubusercontent.com/6167669/222087217-a63fdd4b-c5ae-4055-ad85-b7ef0f79c38b.png)

**Environment (please complete the following information):**

- Visualize environment and version: INT v3.19.7
- Browser and version: FireFox 110

**Comment by Rdataflow** [comment]
@ptbrowne table preview ordered by ordinal measure still behaves as screenshot nr 3

**Comment by ptbrowne** [comment]
I extracted in a new issue: https://github.com/visualize-admin/visualization-tool/issues/988
