### ISSUE TITLE
Wrong MouseOver Value

### ISSUE THREAD

**Issue by mbch** [visualize-admin/visualization-tool#99]
MouseOver a bar shows wrong value

Example:
Cube markusb008EN
(Next)
Columns
(Next)
Horizontal Axis: Category (keep as it is)
Vertical Axis: Switch from Id to Score
The graphics is fine: A has Score 50 and B has Score 55
but if you hoover over the bars with the mouse it reports “A 50” and “B 15”

**Comment by herrstucki** [comment]
The cube markusb008EN seems to be missing some of the newer metadata requirements (KeyDimension, MeasureDimension etc.). I tried to fix it but it doesn't exist in the Cube Creator anymore?

However, I can't reproduce this with another cube … e.g. when I use the draft Palmer Penguins cube, the tooltip correctly shows the values after I change the y-Axis.

Feel free to re-open this issue if you can reproduce the issue with another cube.
