### ISSUE TITLE
map focus on remaining elements

### ISSUE THREAD

**Issue by Rdataflow** [visualize-admin/visualization-tool#998]
**Describe the bug**
The map extent on https://int.visualize.admin.ch/v/slKaX2RK6q-r  is whole switzerland whereas the focus shall be only on the data shown.

**To Reproduce**

1. Go to https://int.visualize.admin.ch/v/slKaX2RK6q-r
2. See extent Switzerland

**Expected behavior**
Focus to extent of the data (3 regions in Ticino in this case)

**Screenshots or video**
![image](https://user-images.githubusercontent.com/26090254/223765647-0374d4a8-2e5a-4e06-ba7e-2833002c9a66.png)

**Environment (please complete the following information):**
- Visualize environment and version: [e.g. INT v3.19.9]

**Additional context**
needed soon for the fire fire warning dataset - will be great showcase 🚀

**Comment by Rdataflow** [comment]
Thank you for this quick suggestion. Unfortunately it doesn't fit, as it blocks the map view thereafter :-(

**Comment by sosiology** [comment]
@ptbrowne reviewed and approved by @Rdataflow via email on 14.03.2023 at 17:30 and can be deployed to INT this week when you are available again. Thanks in advance!

**Comment by ortnever** [comment]
This feature is very nice. Thank you Patrick and Thomas !
